### ISSUE TITLE
GC limit exceeded when running SourceRoot.tryToParse in Eclipse on a large codebase

### ISSUE THREAD

**Issue by jimshowalter** [javaparser/javaparser#1042]
We have 4M+ lines of code in 19593 Java files and 7114 Java test files.

Running latest Neon.

eclipse.ini:

--launcher.appendVmargs
-vmargs
-Dosgi.requiredJavaVersion=1.8
-Dosgi.instance.area.default=@user.home/eclipse-workspace
-XX:+UseG1GC
-XX:+UseStringDeduplication
-Xms1G
-Xmx14G

It failed on the  same file after changing the memory settings, which seems impossible.

Tried removing the file and rerunning it, and then it failed on a different file with the same error:

[error] Error while deleting dead code and obsolete class references by string:
GC overhead limit exceeded

java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.github.javaparser.GeneratedJavaParser$CustomToken.newToken(GeneratedJavaParser.java:110)
	at com.github.javaparser.GeneratedJavaParserTokenManager.jjFillToken(GeneratedJavaParserTokenManager.java:2474)
	at com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:2564)
	at com.github.javaparser.GeneratedJavaParser.jj_scan_token(GeneratedJavaParser.java:9964)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_59(GeneratedJavaParser.java:9686)
	at com.github.javaparser.GeneratedJavaParser.jj_3_3(GeneratedJavaParser.java:9694)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_107(GeneratedJavaParser.java:9748)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_127(GeneratedJavaParser.java:6258)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_84(GeneratedJavaParser.java:6273)
	at com.github.javaparser.GeneratedJavaParser.jj_3_14(GeneratedJavaParser.java:6931)
	at com.github.javaparser.GeneratedJavaParser.jj_2_14(GeneratedJavaParser.java:5661)
	at com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1707)
	at com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3887)
	at com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1322)
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1027)
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:918)
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:480)
	at com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:226)
	at com.github.javaparser.ParseStart$$Lambda$43/457233904.parse(Unknown Source)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:123)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:182)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:72)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:67)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:67)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:115)
	at com.intuit.qbo.deadCodeRemoverShared.DeadCodeRemoverUtils.remove(DeadCodeRemoverUtils.java:40)
	at com.intuit.qbo.deadCodeRemover.DeadCodeRemoverMojo.execute(DeadCodeRemoverMojo.java:83)
	at com.intuit.qbo.deadCodeRemoverTools.RunDeadCodeRemover.main(RunDeadCodeRemover.java:25)

Exception in thread "main" org.apache.maven.plugin.MojoExecutionException: Error while deleting dead code and obsolete class references by string:
GC overhead limit exceeded
	at com.intuit.qbo.deadCodeRemover.DeadCodeRemoverMojo.execute(DeadCodeRemoverMojo.java:89)
	at com.intuit.qbo.deadCodeRemoverTools.RunDeadCodeRemover.main(RunDeadCodeRemover.java:25)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at com.github.javaparser.GeneratedJavaParser$CustomToken.newToken(GeneratedJavaParser.java:110)
	at com.github.javaparser.GeneratedJavaParserTokenManager.jjFillToken(GeneratedJavaParserTokenManager.java:2474)
	at com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:2564)
	at com.github.javaparser.GeneratedJavaParser.jj_scan_token(GeneratedJavaParser.java:9964)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_59(GeneratedJavaParser.java:9686)
	at com.github.javaparser.GeneratedJavaParser.jj_3_3(GeneratedJavaParser.java:9694)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_107(GeneratedJavaParser.java:9748)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_127(GeneratedJavaParser.java:6258)
	at com.github.javaparser.GeneratedJavaParser.jj_3R_84(GeneratedJavaParser.java:6273)
	at com.github.javaparser.GeneratedJavaParser.jj_3_14(GeneratedJavaParser.java:6931)
	at com.github.javaparser.GeneratedJavaParser.jj_2_14(GeneratedJavaParser.java:5661)
	at com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:1707)
	at com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3887)
	at com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1322)
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1027)
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:918)
	at com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:480)
	at com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:226)
	at com.github.javaparser.ParseStart$$Lambda$43/457233904.parse(Unknown Source)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:123)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:182)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:72)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:67)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at java.nio.file.Files.walkFileTree(Unknown Source)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:67)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:115)
	at com.intuit.qbo.deadCodeRemoverShared.DeadCodeRemoverUtils.remove(DeadCodeRemoverUtils.java:40)
	at com.intuit.qbo.deadCodeRemover.DeadCodeRemoverMojo.execute(DeadCodeRemoverMojo.java:83)
	... 1 more

**Comment by jimshowalter** [comment]
The code looks like this:

public class DeadCodeRemoverUtils {

	public static void preamble(String rootSourceDir, Logger logger) {
		StringBuilder builder = new StringBuilder();
		builder.append(DeadCodeRemoverMojo.class.getSimpleName());
		builder.append(": removing dead code and class references by string with settings: rootSourceDir=");
		builder.append(rootSourceDir);
		builder.append(", buildTimestamp=");
		builder.append(BuildTimestampUtils.buildTimestamp(DeadCodeRemoverUtils.class));
		LoggingUtils.info(builder.toString(), logger);
	}

	public static void remove(String rootSourceDir, Logger logger) throws Exception {
		long start = System.currentTimeMillis();
		preamble(rootSourceDir, logger);
		SourceRoot sourceRoot = new SourceRoot(FileAndDirectoryUtils.fullCheckDir(new File(rootSourceDir)).toPath());
		List<ParseResult<CompilationUnit>> java = sourceRoot.tryToParse();
		long elapsed = (System.currentTimeMillis() - start) / 1000;
		LoggingUtils.info("DEAD-CODE REMOVER ELAPSED: " + elapsed + " (" + (java.size() / elapsed) + " files/second)", logger);
	}
}

**Comment by jimshowalter** [comment]
Switching to the SourceRoot.Callback fixed the problem.

**Comment by matozoid** [comment]
Cool :-) Can I close this then?

**Comment by jimshowalter** [comment]
Yes. You might want to add something in the documentation that says hey, dummy, if you have millions of lines of code, you should probably use the callback mechanism. In restrospect it's obvious: it's similar to DOM vs. SAX for large XML files.
