### ISSUE TITLE
Parse Error When multiple parameters added for Java Parser 

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#1124]
Hi,

We get this error when we run it against this source code ( which is an example here)

```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 67,col 22) Parse error. Found ",", expected one of  "!=" "%" "&" "&&" "(" ")" "*" "+" "-" "/" "<" "<=" "==" ">" ">=" "?" "^" "instanceof" "|" "||"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10202)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10058)
  com.github.javaparser.GeneratedJavaParser.Annotation(GeneratedJavaParser.java:5008)
  com.github.javaparser.GeneratedJavaParser.Modifiers(GeneratedJavaParser.java:418)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:988)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:924)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:486)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:232)
  com.github.javaparser.JavaParser.parse(JavaParser.java:133)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:333)
  com.github.javaparser.JavaParser.parse(JavaParser.java:167)
  com.github.javaparser.JavaParser.parse(JavaParser.java:180)
  com.att.tdtsonar.restapi.att_sonar_microservices_plugin.PathHelper.inspectJavaFile(PathHelper.java:29)
  com.att.tdtsonar.restapi.att_sonar_microservices_plugin.PathHelper.main(PathHelper.java:22)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:337)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:167)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:180)
	at com..restapi.plugin.PathHelper.inspectJavaFile(PathHelper.java:29)
	at com.att..restapi.att_sonar_microservices_plugin.PathHelper.main(PathHelper.java:22)
```

Class FILE:-
------------------
```java
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.text.ParseException;
import java.util.List;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.expr.AnnotationExpr;

public class PathHelper {
	public static void main(String[] args) throws Exception {
		File f = new File("C:\\software\\jersey-examples-2.26-b09-all\\jersey\\examples\\helloworld-spring-webapp\\src\\main\\java\\org\\glassfish\\jersey\\examples\\helloworld\\spring\\SpringRequestResource.java");
		inspectJavaFile(f);
	}

	public static void inspectJavaFile(File pFile) throws FileNotFoundException, ParseException, IOException {
		CompilationUnit cu;
		FileInputStream in = new FileInputStream(pFile);
		try {
			cu = JavaParser.parse(in);
		} finally {
			in.close();
		}

		List<AnnotationExpr> ael = cu.getChildNodesByType(AnnotationExpr.class);
		for (AnnotationExpr ae : ael) {
			System.out.println(ae.getNameAsString());
			
			if (ae.getChildNodes().size() != 0) {
				for (Node n : ae.getChildNodes()) {
					System.out.println("Args - " + n.toString() + " with Type = " + n.getMetaModel().getTypeName());
				}
			}
		}
		System.out.println("Using the AnnotationVisitor..");
	}

}
```

SAMPLE CODE AGAINST WHICH WE GET THIS ERROR:-
----------------------------------------------------------------
```java
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
 * Jersey Spring integration example.
 * Demonstrate how to use Spring managed JAX-RS resource class with request scope (+ Spring bean DI).
 *
 * @author Marko Asplund (marko.asplund at gmail.com)
 */
@Path("spring-hello")
@Component
@Inject
public class SpringRequestResource {

    @Autowired
    private GreetingService greetingService;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
	@Consumes(MediaType.TEXT_PLAIN,MediaType.APPLICATION_XML)
	public String getHello() {
        return greetingService.greet("world");
    }
	
	
	@ResponseBody
	@RequestMapping(value = "/ex/foos", method = POST)
	public String postFoos() {
		////RequestMapping(value = "/ex/foos", method = POST)
		return "Post some Foos";
	}

}
```
Can you please check why we get this error? What we are trying to do is to get a list of all the annotations ( method,class level, etc) and then find out the parameters for each annotation. Now it works for an annotation with a single parameter but it never works for an annotation with multiple parameters. We also looked at other threads like:-
https://stackoverflow.com/questions/37208935/javaparser-annotationexpr-get-parameters
https://stackoverflow.com/questions/5410193/get-class-annotations-from-java-source-file

But it does not work. The above code which we are using works fine but only for a single parameter based annotation. If we add one more parameter to an annotation, then the parsing fails. 

Can you please check why this happens and give us some sample code to read parameters for annotations in a Java class file. 

Thanks in advance,
Jitesh

**Comment by matozoid** [comment]
Hi! You're getting a parse error on your source code, which means you're passing invalid Java code to the parser.

Since this is not a JavaParser issue (the Java compiler would have given you an error too) I'll forward you to https://docs.oracle.com/cd/E19798-01/821-1841/gipzh/index.html with a tip to watch the { } in the annotations.

If this answer is sufficient, please close the issue. Feel free to ask more :-)

**Comment by ryan-beckett** [comment]
@jbdundas: You're supposed to have multiple strings encased inside braces for the `@Consumes` annotation.

`@Consumes({MediaType.TEXT_PLAIN, MediaType.APPLICATION_XML})`

That produces no parse errors.

**Comment by matozoid** [comment]
Assuming this is answered.
