### ISSUE TITLE
TokenMgrError

### ISSUE THREAD

**Issue by ElDzi** [javaparser/javaparser#1159]
`Exception in thread "main" com.github.javaparser.TokenMgrError: Lexical error at line 152, column 94.  Encountered: "" (0), after : ""
	at com.github.javaparser.ASTParserTokenManager.getNextToken(ASTParserTokenManager.java:2483)
	at com.github.javaparser.ASTParser.jj_scan_token(ASTParser.java:8950)
	at com.github.javaparser.ASTParser.jj_3R_213(ASTParser.java:8336)
	at com.github.javaparser.ASTParser.jj_3R_178(ASTParser.java:8375)
	at com.github.javaparser.ASTParser.jj_3R_123(ASTParser.java:8423)
	at com.github.javaparser.ASTParser.jj_3R_98(ASTParser.java:7556)
	at com.github.javaparser.ASTParser.jj_3_15(ASTParser.java:7667)
	at com.github.javaparser.ASTParser.jj_3R_198(ASTParser.java:7725)
	at com.github.javaparser.ASTParser.jj_3R_136(ASTParser.java:7790)
	at com.github.javaparser.ASTParser.jj_3R_94(ASTParser.java:7826)
	at com.github.javaparser.ASTParser.jj_3_11(ASTParser.java:7867)
	at com.github.javaparser.ASTParser.jj_3R_87(ASTParser.java:7887)
	at com.github.javaparser.ASTParser.jj_3R_170(ASTParser.java:7185)
	at com.github.javaparser.ASTParser.jj_3R_111(ASTParser.java:7214)
	at com.github.javaparser.ASTParser.jj_3R_195(ASTParser.java:8394)
	at com.github.javaparser.ASTParser.jj_3R_133(ASTParser.java:8755)
	at com.github.javaparser.ASTParser.jj_3R_294(ASTParser.java:5428)
	at com.github.javaparser.ASTParser.jj_3R_267(ASTParser.java:5548)
	at com.github.javaparser.ASTParser.jj_3R_236(ASTParser.java:5587)
	at com.github.javaparser.ASTParser.jj_3R_201(ASTParser.java:5672)
	at com.github.javaparser.ASTParser.jj_3R_211(ASTParser.java:5759)
	at com.github.javaparser.ASTParser.jj_3R_174(ASTParser.java:5892)
	at com.github.javaparser.ASTParser.jj_3R_376(ASTParser.java:6015)
	at com.github.javaparser.ASTParser.jj_3R_372(ASTParser.java:6071)
	at com.github.javaparser.ASTParser.jj_3R_370(ASTParser.java:6167)
	at com.github.javaparser.ASTParser.jj_3R_368(ASTParser.java:6255)
	at com.github.javaparser.ASTParser.jj_3R_364(ASTParser.java:6292)
	at com.github.javaparser.ASTParser.jj_3R_345(ASTParser.java:6360)
	at com.github.javaparser.ASTParser.jj_3R_315(ASTParser.java:6418)
	at com.github.javaparser.ASTParser.jj_3R_293(ASTParser.java:6440)
	at com.github.javaparser.ASTParser.jj_3R_264(ASTParser.java:6470)
	at com.github.javaparser.ASTParser.jj_3R_233(ASTParser.java:6512)
	at com.github.javaparser.ASTParser.jj_3R_200(ASTParser.java:6552)
	at com.github.javaparser.ASTParser.jj_3R_151(ASTParser.java:6627)
	at com.github.javaparser.ASTParser.jj_3R_100(ASTParser.java:7022)
	at com.github.javaparser.ASTParser.jj_3R_247(ASTParser.java:7731)
	at com.github.javaparser.ASTParser.jj_3R_219(ASTParser.java:7761)
	at com.github.javaparser.ASTParser.jj_3R_187(ASTParser.java:7779)
	at com.github.javaparser.ASTParser.jj_3R_292(ASTParser.java:7454)
	at com.github.javaparser.ASTParser.jj_3R_262(ASTParser.java:7498)
	at com.github.javaparser.ASTParser.jj_3R_225(ASTParser.java:7597)
	at com.github.javaparser.ASTParser.jj_3R_194(ASTParser.java:8411)
	at com.github.javaparser.ASTParser.jj_3R_133(ASTParser.java:8753)
	at com.github.javaparser.ASTParser.jj_3R_294(ASTParser.java:5428)
	at com.github.javaparser.ASTParser.jj_3R_267(ASTParser.java:5548)
	at com.github.javaparser.ASTParser.jj_3R_236(ASTParser.java:5587)
	at com.github.javaparser.ASTParser.jj_3R_201(ASTParser.java:5672)
	at com.github.javaparser.ASTParser.jj_3R_211(ASTParser.java:5759)
	at com.github.javaparser.ASTParser.jj_3R_174(ASTParser.java:5892)
	at com.github.javaparser.ASTParser.jj_3R_376(ASTParser.java:6015)
	at com.github.javaparser.ASTParser.jj_3R_372(ASTParser.java:6071)
	at com.github.javaparser.ASTParser.jj_3R_370(ASTParser.java:6167)
	at com.github.javaparser.ASTParser.jj_3R_368(ASTParser.java:6255)
	at com.github.javaparser.ASTParser.jj_3R_364(ASTParser.java:6292)
	at com.github.javaparser.ASTParser.jj_3R_345(ASTParser.java:6360)
	at com.github.javaparser.ASTParser.jj_3R_315(ASTParser.java:6418)
	at com.github.javaparser.ASTParser.jj_3R_293(ASTParser.java:6440)
	at com.github.javaparser.ASTParser.jj_3R_264(ASTParser.java:6470)
	at com.github.javaparser.ASTParser.jj_3R_233(ASTParser.java:6512)
	at com.github.javaparser.ASTParser.jj_3R_200(ASTParser.java:6552)
	at com.github.javaparser.ASTParser.jj_3R_151(ASTParser.java:6627)
	at com.github.javaparser.ASTParser.jj_3R_100(ASTParser.java:7022)
	at com.github.javaparser.ASTParser.jj_3R_130(ASTParser.java:5368)
	at com.github.javaparser.ASTParser.jj_3R_90(ASTParser.java:5422)
	at com.github.javaparser.ASTParser.jj_3R_207(ASTParser.java:5384)
	at com.github.javaparser.ASTParser.jj_3R_172(ASTParser.java:5499)
	at com.github.javaparser.ASTParser.jj_3R_117(ASTParser.java:6879)
	at com.github.javaparser.ASTParser.jj_3_38(ASTParser.java:6872)
	at com.github.javaparser.ASTParser.jj_2_38(ASTParser.java:5299)
	at com.github.javaparser.ASTParser.BlockStatement(ASTParser.java:3696)
	at com.github.javaparser.ASTParser.Statements(ASTParser.java:1531)
	at com.github.javaparser.ASTParser.Block(ASTParser.java:3677)
	at com.github.javaparser.ASTParser.MethodDeclaration(ASTParser.java:1195)
	at com.github.javaparser.ASTParser.ClassOrInterfaceBodyDeclaration(ASTParser.java:924)
	at com.github.javaparser.ASTParser.ClassOrInterfaceBody(ASTParser.java:830)
	at com.github.javaparser.ASTParser.ClassOrInterfaceDeclaration(ASTParser.java:420)
	at com.github.javaparser.ASTParser.TypeDeclaration(ASTParser.java:348)
	at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:161)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:113)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:160)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:179)`

**Comment by matozoid** [comment]
Do you have the source code that caused this so I can analyse it?

**Comment by matozoid** [comment]
One thing is for sure: this exception should have been caught.

**Comment by matozoid** [comment]
Hmmm, `ASTParser` and `TokenMgrError` haven't been in the code for a lot of versions now. @ElDzi - I recommend you upgrade to the latest version and try again. Please open a new issue if things still don't work.
