### ISSUE TITLE
Typecast of lambda expression causes NullPointerException

### ISSUE THREAD

**Issue by fanzhidongyzby** [javaparser/javaparser#1186]
The following testing code will cause `NullPointerException` on javaparser, please fix this bug if possible.
```
public class Demo {
    public void fun() {
        List<Integer> list = Stream.of(1, 2, 3, 4, 5).map((Function<Integer, Integer>) v -> v * v)
            .collect(Collectors.toList());
        System.out.println(list);
    }
}
```

The exception stack information is:
```
Caused by: java.lang.NullPointerException
	at com.github.javaparser.ast.Node.setAsParentNodeOf(Node.java:331)
	at com.github.javaparser.ast.expr.MethodCallExpr.setArgs(MethodCallExpr.java:96)
	at com.github.javaparser.ast.expr.MethodCallExpr.<init>(MethodCallExpr.java:63)
	at com.github.javaparser.ASTParser.PrimarySuffixWithoutSuper(ASTParser.java:3180)
	at com.github.javaparser.ASTParser.PrimarySuffix(ASTParser.java:3121)
	at com.github.javaparser.ASTParser.PrimaryExpression(ASTParser.java:2806)
	at com.github.javaparser.ASTParser.PostfixExpression(ASTParser.java:2718)
	at com.github.javaparser.ASTParser.UnaryExpressionNotPlusMinus(ASTParser.java:2702)
	at com.github.javaparser.ASTParser.UnaryExpression(ASTParser.java:2614)
	at com.github.javaparser.ASTParser.MultiplicativeExpression(ASTParser.java:2511)
	at com.github.javaparser.ASTParser.AdditiveExpression(ASTParser.java:2474)
	at com.github.javaparser.ASTParser.ShiftExpression(ASTParser.java:2437)
	at com.github.javaparser.ASTParser.RelationalExpression(ASTParser.java:2390)
	at com.github.javaparser.ASTParser.InstanceOfExpression(ASTParser.java:2371)
	at com.github.javaparser.ASTParser.EqualityExpression(ASTParser.java:2335)
	at com.github.javaparser.ASTParser.AndExpression(ASTParser.java:2312)
	at com.github.javaparser.ASTParser.ExclusiveOrExpression(ASTParser.java:2290)
	at com.github.javaparser.ASTParser.InclusiveOrExpression(ASTParser.java:2268)
	at com.github.javaparser.ASTParser.ConditionalAndExpression(ASTParser.java:2246)
	at com.github.javaparser.ASTParser.ConditionalOrExpression(ASTParser.java:2224)
	at com.github.javaparser.ASTParser.ConditionalExpression(ASTParser.java:2204)
	at com.github.javaparser.ASTParser.Expression(ASTParser.java:2044)
	at com.github.javaparser.ASTParser.VariableInitializer(ASTParser.java:1068)
	at com.github.javaparser.ASTParser.VariableDeclarator(ASTParser.java:999)
	at com.github.javaparser.ASTParser.VariableDeclarationExpression(ASTParser.java:3759)
	at com.github.javaparser.ASTParser.BlockStatement(ASTParser.java:3697)
	at com.github.javaparser.ASTParser.Statements(ASTParser.java:1531)
	at com.github.javaparser.ASTParser.Block(ASTParser.java:3677)
	at com.github.javaparser.ASTParser.MethodDeclaration(ASTParser.java:1195)
	at com.github.javaparser.ASTParser.ClassOrInterfaceBodyDeclaration(ASTParser.java:924)
	at com.github.javaparser.ASTParser.ClassOrInterfaceBody(ASTParser.java:830)
	at com.github.javaparser.ASTParser.ClassOrInterfaceDeclaration(ASTParser.java:420)
	at com.github.javaparser.ASTParser.TypeDeclaration(ASTParser.java:348)
	at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:161)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:113)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:160)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:179)
```

**Comment by fanzhidongyzby** [comment]
I switched to the latest version (3.4.3) of javaparser, and found this issue is fixed.
