### ISSUE TITLE
NPE on MethodDeclaration.getDeclarationAsString [v2.0.0]

### ISSUE THREAD

**Issue by raducoravu** [javaparser/javaparser#123]
I have a Java interface with a method like:

```
      /**
       * Get all the editor locations.
       * 
       * @param editingArea One of the constants in this class:
       * <br>
       * {@link #MAIN_EDITING_AREA} - for the editors in the main Oxygen workspace area.
       * <br>
       * {@link #DITA_MAPS_EDITING_AREA} - for the editors in the DITA Maps Manager view workspace area.
       * <br>
       * @return All the editor locations or empty array if no editor is opened
       */
      URL[] getAllEditorLocations(int editingArea);
```

When calling MethodDeclaration.getDeclarationAsString I get a NPE:

```
Caused by: java.lang.NullPointerException
    at com.github.javaparser.ast.body.MethodDeclaration.getDeclarationAsString(MethodDeclaration.java:258)
    at JP$1.visit(JP.java:62)
    at JP$1.visit(JP.java:1)
    at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:110)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:234)
    at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:84)
    at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:263)
    at JP.javaToXML(JP.java:70)
```

**Comment by ptitjes** [comment]
Hi @raducoravu 

First of all, thanks for the report and sorry for the inconvenience!

I'm quite sure this has been fixed in master (here https://github.com/javaparser/javaparser/commit/a4f1d6ad90bd0ad68d630ebde2dfe695b60c0685).

Would you mind trying to clone and build JavaParser and report us if it indeed solves your problem ?

We plan to do a release in the near weeks but in the mean time you might need to use a home build.
Again sorry for the inconvenience!

**Comment by raducoravu** [comment]
Hi,

I tried downloading the latest sources and running "mvn clean install" on my computer.
At some point it breaks with:

```
  [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.0:testCompile (default-testCompile) on project javaparser-testing: Fatal error compiling: invalid target release: 1.8 -> [Help 1]
```

**Comment by ptitjes** [comment]
Hi Radu,
We require Java 1.8 to build the project, even if the parser itself is compiled to target execution on Java 1.6.

**Comment by raducoravu** [comment]
I tested and indeed the NPE seems to be fixed on the trunk.
