### ISSUE TITLE
ModifierVisitor and LexicalPreservingPrinter

### ISSUE THREAD

**Issue by attiand** [javaparser/javaparser#1297]
Hi, I found another test case which throws java.lang.UnsupportedOperationException. It needs both calls to println and the comment to throw. I am using version `3.5.7`.

```java
static class CallModifierVisitor extends ModifierVisitor<Void> {
	@Override
	public Visitable visit(MethodCallExpr n, Void arg) {
		// Add a call to foo() on every found method call
		return new MethodCallExpr(n.clone(), "foo");
	}
}

@Test
public void invokeModifierVisitor() throws IOException {
	String code = "class A {" + EOL +
			      "   public void bar() {" + EOL + 
			      "     System.out.println(\"hello\");" + EOL + 		      
			      "     System.out.println(\"hello\");" + EOL + 
			      "     // comment" + EOL +
			      "   }" + EOL +
			      "}";

	CompilationUnit cu = JavaParser.parse(code);
	LexicalPreservingPrinter.setup(cu);
	cu.accept(new CallModifierVisitor(), null);
}
```

Throws
```
java.lang.UnsupportedOperationException: kept token(}) vs ChildTextElement{// comment
}
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:632)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$2.concreteListReplacement(LexicalPreservingPrinter.java:203)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listReplacement(PropagatingAstObserver.java:82)
```

**Comment by ftomassetti** [comment]
Thanks for reporting it!

**Comment by ftomassetti** [comment]
Thanks @attiand , it should be now fixed (available in next release)
