### ISSUE TITLE
LexicalPreservingPrinter does not play well with core-generators.

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1301]
If we enable it by uncommenting this: https://github.com/javaparser/javaparser/blob/master/javaparser-core-generators/src/main/java/com/github/javaparser/generator/core/CoreGenerator.java#L23

then code generation fails with a unhelpful message.

@ftomassetti I think this is a good use case for a nice debugging session :-)

**Comment by ftomassetti** [comment]
I uncommented those three lines and run `sh run_core_generators.sh`. The build succedeed, however I can see this error:
```
[INFO] --- exec-maven-plugin:1.6.0:java (generate-javaparser-core) @ javaparser-core-generators ---
New source root at "/Users/federico/repos/javaparser/javaparser-core/src/main/java"
New source root at "/Users/federico/repos/javaparser/javaparser-core/target/generated-sources/javacc"
Running TypeCastingGenerator
Parsing /Users/federico/repos/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/body/AnnotationDeclaration.java
Parsing /Users/federico/repos/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/body/BodyDeclaration.java
[WARNING]
java.lang.NoClassDefFoundError: javax/annotation/Generated
	at com.github.javaparser.generator.Generator.annotateGenerated(Generator.java:31)
	at com.github.javaparser.generator.Generator.addMethod(Generator.java:90)
	at com.github.javaparser.generator.Generator.addOrReplaceWhenSameSignature(Generator.java:61)
	at com.github.javaparser.generator.core.node.TypeCastingGenerator.generateIsType(TypeCastingGenerator.java:94)
	at com.github.javaparser.generator.core.node.TypeCastingGenerator.generateNode(TypeCastingGenerator.java:57)
	at com.github.javaparser.generator.NodeGenerator.generate(NodeGenerator.java:30)
	at com.github.javaparser.generator.core.CoreGenerator.run(CoreGenerator.java:46)
	at com.github.javaparser.generator.core.CoreGenerator.main(CoreGenerator.java:40)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Generated
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:563)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 14 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.728 s
[INFO] Finished at: 2018-01-13T16:15:32+01:00
[INFO] Final Memory: 16M/55M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.6.0:java (generate-javaparser-core) on project javaparser-core-generators: An exception occured while executing the Java class. javax/annotation/Generated: javax.annotation.Generated -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

Should I look into this or were you getting a different error?

**Comment by matozoid** [comment]
I'm getting a different error - this is my environment:
```
danny@werklaptop:~/workspace/javaparser$ mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /home/danny/.sdkman/candidates/maven/current
Java version: 1.8.0_151, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-104-generic", arch: "amd64", family: "unix"
```
```java
Retrieving cached com/github/javaparser/ast/expr/Expression.java
Parsing /home/danny/workspace/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/body/VariableDeclarator.java
Parsing /home/danny/workspace/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/type/VoidType.java
Retrieving cached com/github/javaparser/ast/type/Type.java
Parsing /home/danny/workspace/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/stmt/WhileStmt.java
Retrieving cached com/github/javaparser/ast/stmt/Statement.java
Parsing /home/danny/workspace/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/type/WildcardType.java
Retrieving cached com/github/javaparser/ast/type/Type.java
Running GenericListVisitorAdapterGenerator
Parsing /home/danny/workspace/javaparser/javaparser-core/src/main/java/com/github/javaparser/ast/visitor/GenericListVisitorAdapter.java
[WARNING] 
java.lang.UnsupportedOperationException: removed com.github.javaparser.printer.concretesyntaxmodel.CsmIndent@1 vs ChildTextElement{return result;}
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:689)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$2.concreteListChange(LexicalPreservingPrinter.java:192)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementRemoved$2(NodeList.java:461)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at com.github.javaparser.ast.NodeList.notifyElementRemoved(NodeList.java:461)
	at com.github.javaparser.ast.NodeList.remove(NodeList.java:146)
	at com.github.javaparser.ast.NodeList.clear(NodeList.java:380)
	at com.github.javaparser.generator.core.visitor.GenericListVisitorAdapterGenerator.generateVisitMethodBody(GenericListVisitorAdapterGenerator.java:30)
	at com.github.javaparser.generator.VisitorGenerator.generateVisitMethodForNode(VisitorGenerator.java:66)
	at com.github.javaparser.generator.VisitorGenerator.lambda$generate$1(VisitorGenerator.java:51)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.github.javaparser.generator.VisitorGenerator.generate(VisitorGenerator.java:51)
	at com.github.javaparser.generator.core.CoreGenerator.run(CoreGenerator.java:48)
	at com.github.javaparser.generator.core.CoreGenerator.main(CoreGenerator.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by ftomassetti** [comment]
I have to figure out how to get this error...

After uncommenting those three lines do you just run `run_core_generator.sh` or do you do something else?

**Comment by matozoid** [comment]
There are five comment lines, only uncomment the ones with "Lexical" in them. Does that work?

**Comment by matozoid** [comment]
I'm not sure why your build doesn't know the `@Generated` annotation. JDK 9 maybe?

**Comment by ftomassetti** [comment]
I have tried:
* uncommenting exactly those three lines referred to Lexical preservation (branch issue1301)
* switching to java 8 (still get the error about the Generated annotation)

Still same behavior when running run_core_generator.sh

**Comment by ftomassetti** [comment]
After running mvn clean and relaunch the script I notice this warning:

```
New source root at "/Users/federico/repos/javaparser/javaparser-core/src/main/java"
[WARNING]
java.lang.IllegalArgumentException: Only directories are allowed as root path!
	at com.github.javaparser.utils.SourceRoot.<init>(SourceRoot.java:64)
	at com.github.javaparser.utils.SourceRoot.<init>(SourceRoot.java:71)
	at com.github.javaparser.generator.core.CoreGenerator.main(CoreGenerator.java:37)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

**Comment by ftomassetti** [comment]
Ok, while `java -version` now indicates Java 8 Maven is still using Java 9:

```
➜  javaparser git:(issue1301) mvn -version
Apache Maven 3.3.9 (bb52d8502b132ec0a5a3f4c09453c07478323dc5; 2015-11-10T17:41:47+01:00)
Maven home: /usr/local/Cellar/maven/3.3.9/libexec
Java version: 9.0.1, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk-9.0.1.jdk/Contents/Home
Default locale: en_FR, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"
```

And I also realize I have a weird locale...

**Comment by ftomassetti** [comment]
Ok, when I managed to convince Maven to use Java8 I get the error

**Comment by matozoid** [comment]
I recognize this train of thought all too well ;-)
