### ISSUE TITLE
JsonPrinter throws MissingFormatArgumentException

### ISSUE THREAD

**Issue by fvarrebola** [javaparser/javaparser#1338]
If you set ```JsonPrinter``` to output code that contains format strings, you will get a ```MissingFormatArgumentException```.

To reproduce the problem, use the following test case:
```
public static void main(String[] args) {
    String code = "class Test {" +
            "  public void method() {" +
            "    String.format(\"I'm using %s\", \"JavaParser\");" +
            "  }" +
            "}";
    CompilationUnit unit = JavaParser.parse(code);
    JsonPrinter printer = new JsonPrinter(true);
    printer.output(unit);
}
```

You should see a stack trace like the following:
```
java.util.MissingFormatArgumentException: Format specifier '%s'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at com.github.javaparser.utils.SeparatedItemStringBuilder.append(SeparatedItemStringBuilder.java:28)
	at com.github.javaparser.printer.JsonPrinter.output(JsonPrinter.java:48)
	at com.github.javaparser.printer.JsonPrinter.output(JsonPrinter.java:63)
	at com.github.javaparser.printer.JsonPrinter.output(JsonPrinter.java:54)
	...
```

BTW I ran the test case against JavaParser 3.5.10 and JDK 1.8.0_112.

**Comment by matozoid** [comment]
Thanks for the report! Looks like we need to do some escaping there.
