### ISSUE TITLE
SourceRoot.tryToParse() doesn't ignore hidden directories

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1427]
In my project some template java files in the `/.idea` are present that get picked up by the SourceRoot's FileVisitor. For some reason the relative path is changed from `/.idea/fileTemplates/code/Catch Statement Body.java` to `/idea/fileTemplates/code/Catch Statement Body.java`, which throws a `NoSuchFileException`.

```
java.nio.file.NoSuchFileException: /idea/fileTemplates/code/Catch Statement Body.java
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.Files.newByteChannel(Files.java:361)
	at java.nio.file.Files.newByteChannel(Files.java:407)
	at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
	at java.nio.file.Files.newInputStream(Files.java:152)
	at com.github.javaparser.Providers.provider(Providers.java:70)
	at com.github.javaparser.Providers.provider(Providers.java:74)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:109)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:124)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:144)
	at com.github.javaparser.utils.SourceRoot$1.visitFile(SourceRoot.java:139)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:139)
	at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:159)
```

A solution would be to skip hidden directories upon visiting the files, add this function
```
@Override
  public FileVisitResult preVisitDirectory(Path dir, BasicFileAttributes attrs) throws IOException {
    if (Files.isHidden(dir) || roots.stream().anyMatch(dir::startsWith)) {
      return SKIP_SIBLINGS;
    }
    return CONTINUE;
}
```
to the FileVisitor

```
public List<ParseResult<CompilationUnit>> tryToParse(String startPackage) throws IOException {
    assertNotNull(startPackage);
    logPackage(startPackage);
    final Path path = packageAbsolutePath(root, startPackage);
    Files.walkFileTree(path, new SimpleFileVisitor<Path>() {
        @Override
        public FileVisitResult visitFile(Path file, BasicFileAttributes attrs) throws IOException {
            if (!attrs.isDirectory() && file.toString().endsWith(".java")) {
                Path relative = root.relativize(file.getParent());
                tryToParse(relative.toString(), file.getFileName().toString());
            }
            return FileVisitResult.CONTINUE;
        }
    });
    return getCache();
}
```

**Comment by matozoid** [comment]
Okay, that might be a good idea, considering people still use .svn directories.

**Comment by matozoid** [comment]
It's interesting to investigate why that "." disappears too. Maybe a bug in the JDK?

**Comment by matozoid** [comment]
Okay, it's SourceRoot, it just assumes that every directory inside of the root is a valid package "part" so it doesn't like dots. Anyway, I've generalized it a bit and now it skips every directory name that is not allowed in a package.
