### ISSUE TITLE
Parsing SourceRoot without startPackage doesn't parse

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1445]
I'm experiencing some strange behaviour with the parsing functions of `SourceRoot`. When defining a `startPackage` is behaves as expected, but when not defining a `startPackage` I get no result at all.

```
sourceRoot.tryToParse();
logger.debug("sourceRoot.getCompilationUnits().size() = " + sourceRoot.getCompilationUnits().size());
// returns 0
sourceRoot.tryToParse(startPackage);
logger.debug("sourceRoot.getCompilationUnits().size() = " + sourceRoot.getCompilationUnits().size());
// return 18
```

I unfortunately can't debug properly because the `ParrelParse` is an anonymous class and I don't have access to maven on this computer. I however suspect it because of 
```
if (!SourceRoot.isSensibleDirectoryToEnter(dir)) {
    return SKIP_SUBTREE;
}
```
which should be `SKIP_SIBLINGS`, skipping the whole sub tree skips too many folders

**Comment by matozoid** [comment]
This is going to be hard to debug without some hints about your directory structure :-)

But at least I noticed that `BulkParseTest.parseOwnSourceCode` stopped working because it starts at a too high directory!

**Comment by daanschipper** [comment]
I wrote a test that shows my problem, when adding this to `SourceRootTest` the size is of the list of cu's is 0. Here root is `javaparser/javaparser-testing/target/test-classes`. However, when I set `root = CodeGenerationUtils.classLoaderRoot(SourceRootTest.class).resolve("com");` to `javaparser/javaparser-testing/target/test-classes/com` it behaves correctly.
```
@Test
public void test() throws IOException {
    Path root = CodeGenerationUtils.classLoaderRoot(SourceRootTest.class).resolve("");
    SourceRoot sourceRoot = new SourceRoot(root);
    sourceRoot.tryToParse();
    List<CompilationUnit> compilationUnits = sourceRoot.getCompilationUnits();
    assertNotEquals(0, compilationUnits.size());
}
```

**Comment by daanschipper** [comment]
After some more investigation, `JAVA_IDENTIFIER.matcher(dirToEnter).matches()` is false, thus `isSensibleDirectoryToEnter()` returns false and the whole sub tree is skipped.

Again with the same paths `javaparser/javaparser-testing/target/test-classes` and `javaparser/javaparser-testing/target/test-classes/com`, the dirToEnter is `test-classes` and `com` respectively and the result of the match is false and true.

**Comment by matozoid** [comment]
Yes, I made it that way. SourceRoot must be pointed at the root of a source directory and will skip any directory that cannot be part of a package name (meaning: not a valid identifier.)

**Comment by daanschipper** [comment]
So what would you recommended for a multi-module project? Having multiple SourceRoots per module?

**Comment by daanschipper** [comment]
I'm preparing a pr where I'm additionally checking if the directory given to `isSensibleDirectoryToEnter()` is equal to the root of the SourceRoot, if so return true otherwise false. What do you think of that solution?

**Comment by matozoid** [comment]
In theory I'd say: read the project configuration file, but I can imagine that's way too much work right now (although someone was working on doing that for maven a while ago.)

Wasn't that class you made recently scanning for good source root directories? That would map to multiple SourceRoots then. Here's what I did to a test in JP to fix its source code scanning: https://github.com/javaparser/javaparser/pull/1447/files#diff-2eb268cce8749d4bbd719719ed2aeaf2

Comment 2: maybe I don't understand. `isSensibleDirectoryToEnter` gets every directory that is entered while scanning the directories inside the root, so almost all of the time it is not equal to the root, since it will be a (sub-)subdirectory of it.

Please correct me if I'm wrong, it turns out I often am if I'm talking outside my area of expertise, which is the symbol solver :-)

**Comment by daanschipper** [comment]
While you're solution is correct, creating new SourceRoots for each root, is does require some manual work. I hoped that providing one Path to SourceRoot would be sufficient enough that it would gather all java files within that directory and you could mess with the CompilationUnits within the folder. However this is apparently not the use of that class

I could extract the `JavaSymbolSolverWalker` from the utility class that I wrote earlier so it will collect the 'proper' roots of a directory which `SourceRoot` and `SymbolSolverQuickSetup` can then both utilise. I'm not sure where I should put this class, maybe `javaparser-core/utils/SourceRootsExtractor`?

**Comment by matozoid** [comment]
Okay, I had to think about this long and hard, but #1450 convinced me that we need something like this in core :-)

Here's some other things I was thinking about:

What are we doing here? Are we scanning a project directory? So should we call it `ProjectRoot`? Would people be confused with the symbol solver setup? `ProjectRoot` wouldn't include dependencies like jars, or would it? Should we call it `SourceRoots` if not? Can we connect it tightly to the symbol solver so we don't duplicate functionality? (That happens too often already...) What about we make a `TypeSolver` that accepts a `ProjectRoot`? Or `SourceRoots`? `ProjectRoot` is a clean, clear concept, `SourceRoots` is not.

What are your ideas on this?

**Comment by AwesomeLemon** [comment]
I don't feel that I understand current project architecture good enough, so I won't comment on many questions about that.

Instead I thought I should write what I was trying to achieve in #1450 in the first place. And that was to find and to compile all files in some project folder. So @matozoid, in your terminology what I would like to have is ``SourceRoots``.

**Comment by matozoid** [comment]
That adds something to think about: if it's `SourceRoots`, it can just as well be a single `static Set<SourceRoot> scanForSourceRoots(Path dir)` on `SourceRoot` itself.

**Comment by daanschipper** [comment]
I agree with AwesomeLemon that I needed to find and compile all files in a project folder. However, I also need to resolve the symbols in that project folder, the function `scanForSourceRoots(Path dir)` would not be sufficient enough for that since this should also scan all the jar files.

I'm thinking about a class `ProjectRoot` that handles all the functionality for javaparser-core, scanning the directory for `SourceRoot`s. Then I'd extend this class in `javaparser-symbol-solver-core` which is able to extract the jar files and add everything to a `TypeSolver`.

I'm currently achieving this with a sort of wrapper around `TypeSolver`. I'm first setting up TypeSolver with the SymbolSolverQuickSetup, and then I'm adding this to the `SourceRoot` with the aid of `ParserConfiguration`. I would love it if all this is within one class, it took me quite some time to figure this all out and set it up accordingly.

**Comment by matozoid** [comment]
Alright, just give it a shot then, and we'll see what comes out :-)

**Comment by daanschipper** [comment]
I think I have found the project that is reading the configuration file! You can find his dependency resolvers [here](https://github.com/hugofmelo/EHExtractor/tree/master/EHExtractor/src/ufrn/dimap/lets/ehmetrics/dependencyresolver)

**Comment by daanschipper** [comment]
I've written a solution for this problem, but upon testing it I'm stumbling over the following problem. I'm walking over the files of this project (javaparser-parent), adding all `.java` and `.jar` files to the `TypeSolver` and collecting the `SourceRoots`. I've now written a test that picks one `SourceRoot` from the `ProjectRoot` and tries to resolve every `MethodDeclaration`. However, this approach fails since some files are also added that are not valid java files.

When trying `methodDeclaration.resolve.getQualifiedName` for `com.github.javaparser.ast.nodeTypes.NodeWithConstructors.getDefaultConstructor()`, the `TypeSolver` iterates over the `foundTypes`, which also includes the invalid java files (in my case `javaparser/javaparser-testing/target/test-classes/com/github/javaparser/utils/module-info.java`) 

```
        try {
            return foundTypes.get(name, () -> {
                SymbolReference<ResolvedReferenceTypeDeclaration> result = tryToSolveTypeUncached(name);
                if (result.isSolved()) {
                    return SymbolReference.solved(result.getCorrespondingDeclaration());
                }
                return result;
            });
        } catch (ExecutionException e) {
            throw new RuntimeException(e);
        }
```

@matozoid Do you have any suggestions on how to tackle this? Manually adding which directories to skip defeats the whole purpose of the class.


This is the stacktrace that is thrown:

```
com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Issue while parsing /Users/daans/Documents/thesis/dev/javaparser/javaparser-testing/target/test-classes/com/github/javaparser/utils/module-info.java

	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5053)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveType(JavaParserTypeSolver.java:123)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:59)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:135)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.solveType(JavaParserInterfaceDeclaration.java:249)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.toReferenceType(JavaParserInterfaceDeclaration.java:319)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.getAncestors(JavaParserInterfaceDeclaration.java:257)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:71)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:436)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:496)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:492)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:78)
	at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:52)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:71)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
	at com.github.javaparser.symbolsolver.utils.ProjectRootTest.lambda$resolveExpressions$1(ProjectRootTest.java:35)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.symbolsolver.utils.ProjectRootTest.resolveExpressions(ProjectRootTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Issue while parsing /Users/daans/Documents/thesis/dev/javaparser/javaparser-testing/target/test-classes/com/github/javaparser/utils/module-info.java
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5053)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.parseDirectory(JavaParserTypeSolver.java:98)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:165)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$tryToSolveType$2(JavaParserTypeSolver.java:124)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5058)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 43 more
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.RuntimeException: Issue while parsing /Users/daans/Documents/thesis/dev/javaparser/javaparser-testing/target/test-classes/com/github/javaparser/utils/module-info.java
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
	at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5053)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.parse(JavaParserTypeSolver.java:80)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$parseDirectory$1(JavaParserTypeSolver.java:104)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5058)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 53 more
Caused by: java.lang.RuntimeException: Issue while parsing /Users/daans/Documents/thesis/dev/javaparser/javaparser-testing/target/test-classes/com/github/javaparser/utils/module-info.java
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$parse$0(JavaParserTypeSolver.java:87)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5058)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
	... 62 more
Caused by: com.github.javaparser.ParseProblemException: (line 1,col 1) Modules are not supported.

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:329)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:200)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$parse$0(JavaParserTypeSolver.java:83)
	... 67 more
```

**Comment by matozoid** [comment]
Two quick ideas:
- Parsing fails because the default Java version used is 8 (since it's the most used one). Check http://javaparser.org/setting-java-8-9-10-etc/
- Use the full API if you want to deal with parse errors in a flexible way: http://javaparser.org/the-quick-and-the-full-api-of-javaparser/

If I look at the stack trace, it seems to be the symbol solver itself tripping over parse errors. I think it would make sense to change it to do something less drastic when parsing fails.

**Comment by daanschipper** [comment]
It is indeed the symbol solver that is failing, I'm only doing the following
```
List<ParseResult<CompilationUnit>> parseResults = sourceRoot.get().tryToParse();
parseResults.forEach(result -> {
    CompilationUnit compilationUnit = result.getResult().get();
    System.out.println(compilationUnit.getStorage().get().getPath());
    for (MethodDeclaration methodDeclaration : compilationUnit.findAll(MethodDeclaration.class)) {
        System.out.println(methodDeclaration.resolve().getQualifiedSignature());
    }
});
```
Setting the java version did unfortunately not work, I've used the API to parse the file within `JavaParserTypeSolver`, and that seemed to solve this particular issue.
