### ISSUE TITLE
Insignificant semicolons make LexicalPreservingPrinter fail

### ISSUE THREAD

**Issue by Otanikotani** [javaparser/javaparser#1460]
This is currently failing unit test for `LexicaltPreservingPrinterTest`:

```java
    @Test
    public void doubleSemicolonIsBeingParsedCorrectly() {
        considerCode("import a;;");

        cu.addImport("b");

        assertEquals("import a;" + EOL + "import b;" + EOL, LexicalPreservingPrinter.print(cu));
    }
```

Error:

```
java.lang.UnsupportedOperationException: NodeText: NodeText{[ChildTextElement{import a;
}, ChildTextElement{import b;
}, ";"   <98>   (line 1,col 10)-(line 1,col 10), ""   <0>   (line 1,col 10)-(line 1,col 10)]}. Difference: Difference{[Kept{child(ImportDeclaration)}, Added{child(ImportDeclaration)}, Kept{token(
)}]} ";"   <98>   (line 1,col 10)-(line 1,col 10)

	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:520)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$2.concreteListChange(LexicalPreservingPrinter.java:198)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:465)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:465)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:69)
	at com.github.javaparser.ast.CompilationUnit.addImport(CompilationUnit.java:346)
	at com.github.javaparser.ast.CompilationUnit.addImport(CompilationUnit.java:300)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinterTest.doubleSemicolonIsBeingParsedCorrectly(LexicalPreservingPrinterTest.java:590)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)


Process finished with exit code 255

```

Locally, I fixed it by adding another condition for Difference:517 - `nodeTextEl.isWhiteSpaceOrComment() || nodeTextEl.isSemicolon()` providing the method semicolon, new token type and etc. I think it is not very good, because I don't fully understand processes in `Difference` class and most likely I broke something by doing so. Hence - no PR, but if you are interested in seeing it - I can do it.

**Comment by matozoid** [comment]
Hmmm, I need to consult @ftomassetti for this. @ftomassetti - how would we treat a ";" that is ignored during parsing? It can only be found as a token in the token list.

**Comment by ftomassetti** [comment]
Why should a semicolon be ignored during parsing?

**Comment by matozoid** [comment]
Like the example above:
```java
import a;
;
import b;
;
class X {}
;
;
```
It's meaningless to Java. (Contrast `while(true);` where the semicolon *is* meaningful.)

**Comment by ftomassetti** [comment]
Mmm I see. I think we could treat those semicolons as they were comments or space: useful only for presentation purposes.It could be tricky as sometimes semicolons are very relevant...
This is something to be fixed when applying the difference I think: if we see a semicolon on the existing code and we do not expect it we should just leave it as it is.

**Comment by jlerbsc** [comment]
In the latest javaparser version the exception UnsupportedOperationException is not throwed any more in this case

**Comment by matozoid** [comment]
Well, that's a relief.
