### ISSUE TITLE
How to get a type resolution from a static ExpressionStatement

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#1474]
I would want to resolve the type of C on this ExpressionStatement but i cannot obtain a FieldDeclaration from the method Navigator.findNodeOfGivenClass. It's probably not the better way to do this. Could you give me a tips?
    C.callStaticC();

**Comment by ftomassetti** [comment]
You have just to find the node describing "C". It can be done in different ways. For example you can get the expression inside the ExpressionStatement and cast it to a MethodCallExpr. At this point you call getScope (or something similar) et voila, here you get the node for "C"

**Comment by ghost** [comment]
This should do the trick as well I think:

```
if(C.isTypeExpr()){
 System.out.println(C.toTypeExpr().get().getType());
}
```

Edit: the difficult part seems to be when someone imports a static method. In that case the actual class is not inside the code anywhere

**Comment by jlerbsc** [comment]
Hi, I got a java.lang.reflect.InvocationTargetException with this code. Where is the mistake?

    CombinedTypeSolver typeSolver = new CombinedTypeSolver();
    typeSolver.add(new ReflectionTypeSolver());
    ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
    JavaParser parser = new JavaParser(parserConfiguration);

    String code = "package test;\n" + "import C;" + "public class A {" + "public void callStatic() {\n"
				+ "		C.callStaticC();\n" + "	}\n" + "}";

    CompilationUnit cu = parser.parse(code);
    MethodCallExpr methodCallExpr = Navigator.findNodeOfGivenClass(cu, MethodCallExpr.class);
    ResolvedType type = JavaParserFacade.get(typeSolver).getType(methodCallExpr);
    System.out.println("method type: " + type.toString());

**Comment by ftomassetti** [comment]
In these cases it helps if you report the whole stack trace

**Comment by jlerbsc** [comment]
Sorry i cannot reproduce it. For now i get this stack. Perhaps it's caused by the fact the C class is defined in another compilation unit.
```
UnsolvedSymbolException{context='Solving C', name='C', typeSolver=null}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:290)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:78)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:388)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:94)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:518)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:278)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:106)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:388)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
```

**Comment by matozoid** [comment]
@ftomassetti @jlerbsc - this issue seems to have stalled. Should I close it?

**Comment by jlerbsc** [comment]
Yes, sorry for the delay.

**Comment by matozoid** [comment]
Okay, no problem.
