### ISSUE TITLE
[Question] How to get the ResolvedType of a MethodCallExpr within a multi catch?

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1482]
How would one get the type of a `MethodCallExpr` within a multi catch? I've provided the following example to illustrate what I exactly mean. Of the two printing statements, I would like to know the types of the arguments. For just the argument `e` I get a ResolvedUnionType of  `java.lang.ArrayIndexOutOfBoundsException | java.lang.ClassCastException`, but when I try to get the type of `e.getMessage()` I receive an UnsupportedException.

```java
public static void main(String[] args) {
    CompilationUnit cu = JavaParser.parse("public class X {\n" +
            "        public void test() {\n" +
            "            try {\n" +
            "                methodWithExceptions();\n" +
            "            } catch (ArrayIndexOutOfBoundsException | ClassCastException e) {\n" +
            "                System.out.println(e);\n" +
            "                System.out.println(e.getMessage());\n" +
            "            }\n" +
            "        }\n" +
            "\n" +
            "        private void methodWithExceptions() throws ArrayIndexOutOfBoundsException, ClassCastException {\n" +
            "            // do something\n" +
            "        }\n" +
            "    }");
    cu.accept(new Visitor(), null);
}

private static class Visitor extends VoidVisitorAdapter<Void> {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        System.out.println("n.toString() = " + n.toString());
        if (n.getArguments().size() != 0) {
            Expression argument = n.getArgument(0);
            // succeeds on e, but fails on e.getMessage()
            ResolvedType type = JavaParserFacade.get(new ReflectionTypeSolver(true)).getType(argument);
        }
    }
}
```

This is the error message I receive when executing the above example
```
Exception in thread "main" java.lang.UnsupportedOperationException: type usage: com.github.javaparser.resolution.types.ResolvedUnionType
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:410)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:111)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:513)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:276)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:109)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:268)
	at visitors.Test$Visitor.visit(Test.java:37)
	at visitors.Test$Visitor.visit(Test.java:31)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:285)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:146)
	at com.github.javaparser.ast.stmt.CatchClause.accept(CatchClause.java:88)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$153(VoidVisitorAdapter.java:593)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:593)
	at com.github.javaparser.ast.stmt.TryStmt.accept(TryStmt.java:143)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$98(VoidVisitorAdapter.java:410)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:120)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:170)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:105)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:131)
	at visitors.Test.main(Test.java:28)
```

**Comment by ftomassetti** [comment]
This is a current limitation of JSS. It should look for common ancestors of all the types involved in the union and use that common ancestor to solve the method calls.

If someone wanted to submit a Pull Request it would be great and we could help him getting done

**Comment by daanschipper** [comment]
Why would you like for the common ancestor of all the types and then only resolve the method call for that common ancestor? Isn't it possible to resolve the method call for each type and merge the `ResolvedType`s together in a `ResolvedUnionType`?

**Comment by ftomassetti** [comment]
No, that would be wrong I think, because if the two types have two unrelated methods that happen to have the same name and a compatible signature I do not think that would be valid. In this case both are Exception and Exception has the method getMessage, so it is valid to refer to it. If both classes defined independently a method named `foo`, `e.foo()` should not work in my opinion (but I could be wrong, is not like these union types are used much...)

**Comment by daanschipper** [comment]
I'm not that familiar with union types. Considering your example, if it is valid to have the same method `foo` defined with different returning types (say `int` and `String`) in a union type environment, wouldn't it make sense that `getType(e.foo())` would return both `int` and `String`?

**Comment by ftomassetti** [comment]
no. That call would not be valid. It should not compile at all

**Comment by matozoid** [comment]
Here's a demo - @ftomassetti has the right algorithm :-)
```java
public class Bla {

    class Q extends Exception {
        public void b() {
        }
    }

    class Ex1 extends Q {
        public void a() {
        }
    }

    class Ex2 extends Q {
        public void a() {
        }
    }

    private void x() throws Ex1, Ex2 {

    }

    private void bla() {
        try {
            x();
        } catch (Ex1 | Ex2 x) {
            // Is okay
            x.b();
            // Does not compile
            x.a();
        }
    }
}
```

**Comment by ftomassetti** [comment]
Still we have to implement it :)
