### ISSUE TITLE
StackOverflowError on getBinaryTypeConcrete (double + String)

### ISSUE THREAD

**Issue by BFergerson** [javaparser/javaparser#1485]
The following code causes a StackOverflowError when solving the method call `System.out.println(result.getReal()+","+result.getImaginary());`:
```java
public class Complex {

    private double real;
    private double imaginary;

    Complex(double _real, double _imaginary) {
        real = _real;
        imaginary = _imaginary;
    }

    Complex(String eval) {
        Complex result = new Complex(0,0);
        System.out.println(result.getReal()+","+result.getImaginary());
    }

    public Complex add(Complex arg) {
        return new Complex(real+arg.getReal(), imaginary+arg.getImaginary());
    }

    public double getReal() {
        return real;
    }

    public double getImaginary() {
        return imaginary;
    }
}
```

I took a swing at trying to solve this one but not quite sure how to. From what I can tell it tries to solve the type of the binary expression `result.getReal()+","` and it tries:
https://github.com/javaparser/javaparser/blob/f8700e351207b99d7034e5973fd3ad203b7615a0/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/model/typesystem/ReferenceTypeImpl.java#L103
but this leads to it overflowing from trying to see if a `java.lang.Double` is assignable by a `java.lang.String`.
\
\
Partial stack trace just in case:
```
Exception in thread "main" java.lang.StackOverflowError
	at javassist.bytecode.SignatureAttribute$ClassType.<init>(SignatureAttribute.java:677)
	at javassist.bytecode.SignatureAttribute$ClassType.make(SignatureAttribute.java:671)
	at javassist.bytecode.SignatureAttribute.parseClassType2(SignatureAttribute.java:1110)
	at javassist.bytecode.SignatureAttribute.parseObjectType(SignatureAttribute.java:1070)
	at javassist.bytecode.SignatureAttribute.parseTypeArgs(SignatureAttribute.java:1132)
	at javassist.bytecode.SignatureAttribute.parseClassType2(SignatureAttribute.java:1104)
	at javassist.bytecode.SignatureAttribute.parseClassType(SignatureAttribute.java:1088)
	at javassist.bytecode.SignatureAttribute.parseSig(SignatureAttribute.java:996)
	at javassist.bytecode.SignatureAttribute.toClassSignature(SignatureAttribute.java:924)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistTypeDeclarationAdapter.getTypeParameters(JavassistTypeDeclarationAdapter.java:74)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.getTypeParameters(JavassistClassDeclaration.java:344)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.deriveParams(ResolvedReferenceType.java:447)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:56)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:65)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:159)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:265)
```

**Comment by BFergerson** [comment]
Some test code and further clarification:
```java
import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.io.File;

public class ComplexTester {
    public static void main(String[] args) throws Exception {
        File file = new File("/home/brandon/IdeaProjects/JavaParserTest/src/test/resources");
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();

        //typeSolver.add(new ReflectionTypeSolver());
        typeSolver.add(new JavaParserTypeSolver(new File("/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/rt.jar")));
        typeSolver.add(new JavaParserTypeSolver(new File("/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/jce.jar")));

        typeSolver.add(new JavaParserTypeSolver(file));

        CompilationUnit unit = JavaParser.parse(new File(file, "Complex.java"));
        unit.accept(new VoidVisitorAdapter<Object>() {
            @Override
            public void visit(final MethodCallExpr n, final Object arg) {
                System.out.println(JavaParserFacade.get(typeSolver).solve(n));
            }
        }, null);
    }
}
```

I'm manually selecting the jars from the JRE to include because of a prior conflict that's forcing me to explicitly parse using Java 7 even when running on Java 8. I noticed that if I comment out the two lines importing JRE jars and uncomment the `ReflectionTypeSolver` that this code won't cause a StackOverflowError but instead thinks that the referenced method is:
```
SymbolReference{Optional[ReflectionMethodDeclaration{method=public void java.io.PrintStream.println(double)}]}
```
It should definitely be `java.io.PrintStream.println(String)`. Being double + string.

**Comment by ftomassetti** [comment]
I tried without specifying the JARs and it works for me. Perhaps it was fixed in the meantime. I will send a PR with the test.
