### ISSUE TITLE
Failed to parse files with /*/ inside strings

### ISSUE THREAD

**Issue by marcosca2** [javaparser/javaparser#159]
It seems the JavaParser throws an StringIndexOutOfBoundsException every time it tries to parse a file containing a String like this:

public class Example {
    private String a = "/*/";
}

Below you can find the stack trace for the exception:

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:762)
    at java.lang.StringBuffer.deleteCharAt(StringBuffer.java:378)
    at japa.parser.ast.comments.CommentsParser.parse(CommentsParser.java:82)
    at japa.parser.ast.comments.CommentsParser.parse(CommentsParser.java:23)
    at japa.parser.JavaParser.insertComments(JavaParser.java:381)
    at japa.parser.JavaParser.parse(JavaParser.java:94)
    at japa.parser.JavaParser.parse(JavaParser.java:139)

**Comment by ftomassetti** [comment]
Hi, I thought we solved something similar in the past. I will check as soon as I can, but just to be sure: are you using the last version of JavaParser?

**Comment by marcosca2** [comment]
We are using the parser for Java 1.7.
I tried to update the parser to the last version and the file is correctly parsed. I think we can move to the last version of the Java Parser to solve the issue.

**Comment by ftomassetti** [comment]
Great to hear that! I will close the issue but please reopen it if necessary
