### ISSUE TITLE
LexicalPreservingPrinter doesn't work well with FieldDeclaration

### ISSUE THREAD

**Issue by jooyunghan** [javaparser/javaparser#1601]
For example, let's consider the following definition,

```java
class A {
 List<B> children;
 void foo(B b) { }
}
```

I tried to change the type `B` to `String` with following visitor.

```java
ModifierVisitor<Void> visitor = new ModifierVisitor<Void>() {
    @Override
    public ClassOrInterfaceType visit(ClassOrInterfaceType n, Void arg) {
        super.visit(n, arg);
        if (n.getNameAsString().equals("B")) {
                n.setName("String");
        }
        return n;
    }
}
```

PrettyPrinter works fine with this. However, LexicalPreservingPrinter doens't.
It shows FieldDeclaration's type as unchanged.

I traced it is due to FieldDeclaration's type information is owned by VariableDeclarator and therefore
LexicalPreservingPrinter keeps its type information as normal token list.

I guess #1359 reveals the related problem with FieldDeclaration.

**Comment by ftomassetti** [comment]
Thank you for this bug report

**Comment by jooyunghan** [comment]
```java
	@Test
	public void changingTypeArgument() {
		FieldDeclaration it = consider("List<A> a;");
		VariableDeclarator variable = it.getVariable(0);
		ClassOrInterfaceType type = (ClassOrInterfaceType) variable.getType();
		NodeList<Type> nodeList = type.getTypeArguments().get();
		nodeList.set(0, JavaParser.parseType("String"));
		assertTransformedToString("List<String> a;", it);
	}
```

I made a test case revealing this behavior. For now this results ...

```
org.junit.ComparisonFailure: expected:<List<[String]> a;> but was:<List<[A]> a;>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.github.javaparser.printer.lexicalpreservation.AbstractLexicalPreservingTest.assertTransformedToString(AbstractLexicalPreservingTest.java:71)
	at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.FieldDeclarationTransformationsTest.changingTypes2(FieldDeclarationTransformationsTest.java:92)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
```

**Comment by jlerbsc** [comment]
In this case it seems that FieldDeclaration data has not been updated on setName() call and it contains the previous value. I don't know how to correct this.

**Comment by jlerbsc** [comment]
There is an issue when you try to modify directly argument type list but you can have the expected result with a new variable type created from previous type.

    class Issue1601Test extends AbstractLexicalPreservingTest  {

    @Test
    public void changingTypeArgument() {
        String s =
                "public class Foo {\n" +
                "  List<A> a;\n" +
                "}";
        considerCode(s);
        FieldDeclaration it = cu.findFirst(FieldDeclaration.class).get();
        VariableDeclarator variable = it.getVariable(0);
       // create a new ClassOrInterfaceType
        ClassOrInterfaceType cloned = (ClassOrInterfaceType) variable.getType().clone(); 
        ClassOrInterfaceType ntype = new ClassOrInterfaceType("String");
        cloned.setTypeArguments(ntype);
        // set th etype to the variable
        variable.setType(cloned);

        assertTransformedToString("List<String> a;", it);
    }
}

Result

    public class Foo {
       List<String> a;
     }
