### ISSUE TITLE
Transforming BinaryExpr fails 

### ISSUE THREAD

**Issue by jooyunghan** [javaparser/javaparser#1610]
Following test case fails

```
/**
 * Transforming BinaryExpr and verifying the LexicalPreservation works as expected.
 */
public class BinaryOperatorTransformationsTest extends AbstractLexicalPreservingTest {

    @Test
    public void instanceToStatic() throws IOException {
        considerExpression("a && b");
        expression.asBinaryExpr().setRight(new NameExpr("c"));
        assertTransformedToString("a && c", expression);
    }

}
```

with 

```
in com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest
instanceToStatic(com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest)  Time elapsed: 0.005 s  <<< ERROR!
java.lang.RuntimeException: Attribute 'operator' does not corresponding to any expected value. Text: AND
	at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest.instanceToStatic(BinaryOperatorTransformationsTest.java:39)
Caused by: java.lang.NoSuchFieldException: AND
	at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.BinaryOperatorTransformationsTest.instanceToStatic(BinaryOperatorTransformationsTest.java:39)
```

**Comment by matozoid** [comment]
Hi! Thanks for the report. I was afraid something like this would happen because the CSM only looks at names of properties, and some of them are ambiguous. This is actually one of the reasons I made the metamodel, to have a reference to every property in the AST. The correct solution would be to use that instead of the current enum with property names.
