### ISSUE TITLE
How to obtain annotation qualified name using Javasymbol solver?

### ISSUE THREAD

**Issue by lvillap** [javaparser/javaparser#1621]
I'm writing a library based on JavaParser, using Javasymbol solver to resolve class names on source files. I'm trying to obtain qualified class names of annotations to classes and methods, but at the moment I'm not able to obtain them.

My current code is:

    final CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    combinedTypeSolver.add(new ReflectionTypeSolver());
    combinedTypeSolver.add(new JarTypeSolver(JUNIT_PATH));
    final JavaParserFacade javaParserFacade = JavaParserFacade.get(combinedTypeSolver);
    final CompilationUnit cu = JavaParser.parse("package apackage;\n" +
            "\n" +
            "import org.junit.*;\n" +
            "\n" +
            "public class ClassToAnalyze {\n" +
            "\n" +
            "@Test\n" +
            "    public void test() {\n" +
            "        \n" +
            "    }\n" +
            "}\n" +
            "");
    final TypeDeclaration<?> typeDeclaration = cu.getTypes().get(0);
    final MethodDeclaration method = typeDeclaration.getMethods().get(0);
    final AnnotationExpr annotation = method.getAnnotation(0);
    final Object solve = javaParserFacade.solve(annotation);
    System.out.println(solve);

But an exception is thrown:

java.lang.ClassCastException: com.github.javaparser.symbolsolver.javassistmodel.JavassistInterfaceDeclaration cannot be cast to com.github.javaparser.resolution.declarations.ResolvedAnnotationDeclaration at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:265) at jlivedoc.collector.specifications.collectors.MultiProjectCollectorSpecifications.analyzeClass(MultiProjectCollectorSpecifications.java:86) at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50) at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47) at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78) at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57) at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290) at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71) at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288) at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58) at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268) at org.junit.runners.ParentRunner.run(ParentRunner.java:363) at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86) at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460) at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

Any idea what I'm doing wrong? I'm using javaparser 3.6.5 and javasymbol solver 0.6.3

Thank you

**Comment by matozoid** [comment]
Hi! One thing to do is to follow the instructions about dependencies: http://javaparser.org/getting-started/

There is no standalone JSS library anymore.

**Comment by lvillap** [comment]
Hello,

I've rewritten the code to use symbol solving using javaparser:
```
    <dependency>
        <groupId>com.github.javaparser</groupId>
        <artifactId>javaparser-core</artifactId>
        <version>3.6.8</version>
    </dependency>
    <dependency>
        <groupId>com.github.javaparser</groupId>
        <artifactId>javaparser-symbol-solver-core</artifactId>
        <version>3.6.8</version>
    </dependency>
```

The code now is:

```
    @Test
    public void canExtractAnnotationClasses() throws Exception {
        final ParserConfiguration configuration = new ParserConfiguration();
        final ReflectionTypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        final JarTypeSolver jarTypeSolver = new JarTypeSolver(
                "/home/luismiguelvilla/.m2/repository/junit/junit/4.12/junit-4.12.jar");
        final CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver,
                jarTypeSolver);
        final JavaSymbolSolver symbolResolver = new JavaSymbolSolver(combinedTypeSolver);
        configuration.setSymbolResolver(symbolResolver);
        new JavaParser(configuration);
        final CompilationUnit cu = JavaParser.parse("package apackage;\n" +
                "\n" +
                "import org.junit.*;\n" +
                "\n" +
                "public class ClassToAnalyze {\n" +
                "\n" +
                "    @Test\n" +
                "    public void test() {\n" +
                "        \n" +
                "    }\n" +
                "}\n" +
                "");
        symbolResolver.inject(cu);
        final TypeDeclaration<?> classToAnalyze = cu.getType(0);
        final MethodDeclaration methodDeclaration = classToAnalyze.getMethods().get(0);
        final AnnotationExpr annotation = methodDeclaration.getAnnotation(0);
        System.out.println(annotation.calculateResolvedType().toString());
    }
```

... but an exception is still thrown:

java.lang.UnsupportedOperationException: com.github.javaparser.ast.expr.MarkerAnnotationExpr
	at com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:15)
	at com.github.javaparser.ast.expr.MarkerAnnotationExpr.accept(MarkerAnnotationExpr.java:69)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:268)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:189)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:561)
	at jlivedoc.collector.specifications.collectors.AnnotationsCollectorSpecifications.canExtractAnnotationClasses(AnnotationsCollectorSpecifications.java:45)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:538)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)

I don't know if this is a bug or if I'm doing something wrong

Thank you all and congratulations for this amazing library

**Comment by realSchoki** [comment]
Is there some progress on this? 

I got the Exception on `annotation.calculateResolvedType()` in

```
@Override
public CompilationUnit visit(CompilationUnit fd, Void arg) {
	super.visit(fd, arg);
	fd.findAll(ClassOrInterfaceDeclaration.class).stream()
	.flatMap(clazz -> clazz.getAnnotations().stream())
	.map(annotation -> annotation.calculateResolvedType().toString())
	.forEach(System.out::println);
	return fd;
}
```

**Comment by jlerbsc** [comment]
Correct, this test code throws an UnsupportedOperationException. It seems that you cannot resolve an annotation expression.

    String code = 
                        "import org.junit.jupiter.api.Test;\n" +
                        "public class Foo {\n" +
                        "    @Test\n" +
                        "    public void test() {\n" +
                        "    }\n" +
                        "}\n";
      
        CompilationUnit cu = StaticJavaParser.parse(code);
        AnnotationExpr ae = cu.findFirst(AnnotationExpr.class).get();
        ResolvedType resolved = ae.calculateResolvedType();

**Comment by jlerbsc** [comment]
But if you use the resolve() method to obtain a declaration you can get the qualified name.

    ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        StaticJavaParser.setConfiguration(config);

        String s = 
                        "public class Foo {\n" +
                        "    @Override\n" +
                        "    public void test() {\n" +
                        "    }\n" +
                        "}\n";
        CompilationUnit cu = StaticJavaParser.parse(s);
        AnnotationExpr ae = cu.findFirst(AnnotationExpr.class).get();
        System.out.println(ae.resolve().getQualifiedName());
