### ISSUE TITLE
UnsolvedSymbolException on Double.valueOf 

### ISSUE THREAD

**Issue by freefire4547** [javaparser/javaparser#1629]
I want to print api calls from code. To get started I wrote following small program. And for testing I am using 'ReversePolishNotation.java' sample file. I have added 'rt.jar' for "java.lang" classes.

```java
        public class Parser
        {

              static CombinedTypeSolver combinedTypeSolver;
              public static void main(String[] args) {
              try 
              {

                   combinedTypeSolver = new CombinedTypeSolver();
                   combinedTypeSolver.add(new ReflectionTypeSolver());
                   combinedTypeSolver.add(new JarTypeSolver("rt.jar"));
                   CompilationUnit cu = JavaParser.parse(new FileInputStream("..../ReversePolishNotation.java"));
                   VoidVisitor<?> methodNameVisitor = new MethodNamePrinter();
                   methodNameVisitor.visit(cu, null);  

             } 
             catch (Exception ex) 
            {
                  Logger.getLogger(Parser.class.getName()).log(Level.SEVERE, null, ex);
            } 
    }
    
    private static class MethodNamePrinter extends VoidVisitorAdapter<Void> {

       @Override
       public void visit(MethodCallExpr  md, Void arg) 
       {
             super.visit(md, arg);
             try
             {                             
    System.out.println(JavaParserFacade.get(combinedTypeSolver).getType(md.getScope().get().asName 
                   Expr()).asReferenceType().getQualifiedName()+" "+md.getName()+"  "+md.getBegin().get().line);
             }
             catch(IllegalStateException ex)
             {                 
             }
       }
    }
}
```
After running this program I get following output with some error 

```
java.lang.String split  25

java.util.Stack pop  33
java.util.Stack pop  34
java.util.Stack push  35
java.util.Stack pop  38
java.util.Stack pop  39
java.util.Stack push  40
java.util.Stack pop  43
java.util.Stack pop  44
java.util.Stack push  45
java.util.Stack pop  48
java.util.Stack pop  49
java.util.Stack push  50
Jun 05, 2018 4:40:13 AM ParserNow.Parser main
SEVERE: null
UnsolvedSymbolException{context='Double', name='Solving Double'}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:288)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:78)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:268)
	at ParserNow.Parser$MethodNamePrinter.visit(Parser.java:53)
	at ParserNow.Parser$MethodNamePrinter.visit(Parser.java:45)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$93(VoidVisitorAdapter.java:400)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:400)
	at ParserNow.Parser$MethodNamePrinter.visit(Parser.java:50)
	at ParserNow.Parser$MethodNamePrinter.visit(Parser.java:45)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:285)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$145(VoidVisitorAdapter.java:556)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:556)
	at com.github.javaparser.ast.stmt.SwitchEntryStmt.accept(SwitchEntryStmt.java:99)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$147(VoidVisitorAdapter.java:563)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:563)
	at com.github.javaparser.ast.stmt.SwitchStmt.accept(SwitchStmt.java:85)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:674)
	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:139)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$93(VoidVisitorAdapter.java:400)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:400)
	at ParserNow.Parser$MethodNamePrinter.visit(Parser.java:50)
	at ParserNow.Parser$MethodNamePrinter.visit(Parser.java:45)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:285)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$98(VoidVisitorAdapter.java:410)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:120)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:170)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:105)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at ParserNow.Parser.main(Parser.java:38)
```

So it means it is not able to get type from "Double.valueOf ". So what can be the problem as I have added correct jar file and used correct TypeSolver.

**Comment by freefire4547** [comment]
I am not sure about solving this problem, but I am able to get api calls using ` System.out.println(JavaParserFacade.get(combinedTypeSolver).solve(md).getCorrespondingDeclaration().declaringType().getQualifiedName()+"   "+md.getNameAsString());
               `

**Comment by matozoid** [comment]
@ftomassetti any idea?

**Comment by freefire4547** [comment]
I understood from https://github.com/javaparser/javaparser/issues/1439 . It was due to 'Double.valueOf' being static method call.

**Comment by freefire4547** [comment]
@matozoid  I am closing the issue.
