### ISSUE TITLE
Fix slow tests

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1630]
PR #1524 broke the slow tests. 

```java
[ERROR] Tests run: 20, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 13.86 s <<< FAILURE! - in com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test
[ERROR] parseCoreJavaparsermodelDeclarations(com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test)  Time elapsed: 1.902 s  <<< FAILURE!
org.junit.ComparisonFailure: Line 21 of /home/danny/IdeaProjects/javaparser/javaparser-symbol-solver-testing/src/test/test_sourcecode/javasymbolsolver_0_6_0/expected_output/java-symbol-solver-core/com_github_javaparser_symbolsolver_javaparsermodel_declarations_JavaParserInterfaceDeclaration.txt is different from what is expected expected:<...).asInterface() ==> [com.github.javaparser.symbolsolver.model.declarations.TypeDeclaration.asInterface()]> but was:<...).asInterface() ==> [ERROR]>
	at com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test.parse(AnalyseJavaSymbolSolver060Test.java:127)
	at com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test.parseCoreJavaparsermodelDeclarations(AnalyseJavaSymbolSolver060Test.java:200)

[ERROR] parseModelTypesystem(com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test)  Time elapsed: 0.717 s  <<< FAILURE!
org.junit.ComparisonFailure: Line 119 of /home/danny/IdeaProjects/javaparser/javaparser-symbol-solver-testing/src/test/test_sourcecode/javasymbolsolver_0_6_0/expected_output/java-symbol-solver-model/com_github_javaparser_symbolsolver_model_typesystem_ReferenceType.txt is different from what is expected expected:<...Values().get(i) ==> [java.util.List.get(int)]> but was:<...Values().get(i) ==> [ERROR]>
	at com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test.parse(AnalyseJavaSymbolSolver060Test.java:127)
	at com.github.javaparser.symbolsolver.resolution.AnalyseJavaSymbolSolver060Test.parseModelTypesystem(AnalyseJavaSymbolSolver060Test.java:331)
```

**Comment by ftomassetti** [comment]
Ok, let's look in these issues but we should probably re-enable as soon as possible the slow tests as part of the build to not be surprised by this

**Comment by matozoid** [comment]
I guess we could change the test results so we can enable the tests and look at this later?

**Comment by ftomassetti** [comment]
This one is not trivial. The fact is that calls inside argument lists of the constructor seems to be resolved in the wrong context

**Comment by matozoid** [comment]
If I understood correctly, only half of this is fixed.

**Comment by ftomassetti** [comment]
I am not sure which is the other half

**Comment by matozoid** [comment]
I guess I misunderstood something as usual.
