### ISSUE TITLE
Resolving reference outside current class

### ISSUE THREAD

**Issue by daanschipper** [javaparser/javaparser#1716]
When trying to get for instance a superclass that resides in another 'source' (read not same class pool of the current typesolver), a `NotFoundException` is thrown and forwarded as `RuntimeException`.

```
java.lang.RuntimeException: javassist.NotFoundException: javax.servlet.http.HttpServlet
    at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.getSuperClass(JavassistClassDeclaration.java:305) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.getAncestors(JavassistClassDeclaration.java:177) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:81) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:89) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:71) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:436) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:413) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:191) ~[javaparser-symbol-solver-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:294) ~[javaparser-core-3.6.13-SNAPSHOT.jar:?]
    at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60) ~[javaparser-core-3.6.13-SNAPSHOT.jar:?]
```

**Comment by daanschipper** [comment]
Discussion from Gitter:

- "perhaps somewhere the JavaParserTypeSolver is not delegating to its parent (the CombinedTypeSolver) the resolution of the type" 
- "I am just considering this: we have a CombinedTypeSolver, a JavaParserTypeSolver and a JarTypeSolver"
- "the JavaParserTypeSolver knows about the Java source code (the class extending the other one) but not about the class in the jar"
- "so a possible explanation of this problem is that we are trying to solve something, and while doing so we involve the JavaParserTypeSolver which can correctly find the Java source code but as it tries to find the parent it fails. It would succeed if it would delegate to its parent, the CombinedTypeSolver"
