### ISSUE TITLE
FieldDeclaration.getElementType().resolve() cause UnsolvedSymbolException

### ISSUE THREAD

**Issue by jGauravGupta** [javaparser/javaparser#1718]
Call to `FieldDeclaration.getElementType().resolve()` cause following error : 

````
UnsolvedSymbolException{context='null', name='Employee', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:477)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.lambda$convertToUsage$2(JavaParserFacade.java:482)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:482)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:452)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:219)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:294)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60)
````

Where field type is `List<Employee>` and loaded `Project` class in compilation unit.

Class 1 : 
````
package xyz;

public class Project {
    private List<Employee> employees;
}
````
Class 2 : 
````
package xyz;

public class Employee{
    private List<Project> projects;
}
````

**Comment by ftomassetti** [comment]
Which typesolver are you using?

**Comment by jGauravGupta** [comment]
Same as mentioned here : https://github.com/javaparser/javasymbolsolver-maven-sample/blob/master/src/main/java/com/yourorganization/maven_sample/MyAnalysis.java

**Comment by jGauravGupta** [comment]
Another error for `Integer` type field : 

````
java.lang.UnsupportedOperationException: InternalTypes not available for com.github.javaparser.symbolsolver.reflectionmodel.ReflectionEnumDeclaration
	at com.github.javaparser.resolution.declarations.ResolvedTypeDeclaration.internalTypes(ResolvedTypeDeclaration.java:46)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver.tryToSolveType(ReflectionTypeSolver.java:98)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:62)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:180)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:72)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:475)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:452)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:219)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:294)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60)
````

**Comment by ftomassetti** [comment]
well, that will not work because you need also a JavaParserTypeSolver to solve links across source files

**Comment by jGauravGupta** [comment]
Thanks @ftomassetti , `JavaParserTypeSolver` solved the issue.
