### ISSUE TITLE
calculateResolvedType throws UnsolvedSymbolException when class implements interface

### ISSUE THREAD

**Issue by kgeilmann** [javaparser/javaparser#1720]
Hi, I'm trying to find all method calls on a certain static type, but I keep getting UnsolvedSymbolExceptions. I was able to find a quite small example, that already crashes.

I use the following setup:
````
    CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    combinedTypeSolver.add(new ReflectionTypeSolver());
    combinedTypeSolver.add(new JavaParserTypeSolver("D:/Users/Kathrin/Repo/JP_Problem/src/main/java/any"));

    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
    JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);
````
Under the given path for the Typesolver I have a file with the following content
````
    package any;
    public interface B {}
````

When I execute 
````
    String src = "package any; public class A implements B { private Object stack; public void clear() { stack.hashCode(); } }";

    CompilationUnit cu = JavaParser.parse(src);
    cu.findAll(MethodCallExpr.class).forEach(mc -> { 
            mc.getScope().ifPresent(s -> System.out.println(s.calculateResolvedType()));
    });
````
I get the following exception 
````
Exception in thread "main" UnsolvedSymbolException{context='null', name='B', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.toReferenceType(JavaParserClassDeclaration.java:435)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:338)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:299)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:81)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:71)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveType(StatementContext.java:198)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveType(StatementContext.java:198)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:50)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:300)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:229)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:561)
	at com.yourorganization.maven_sample.MyAnalysis.lambda$null$0(MyAnalysis.java:36)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.yourorganization.maven_sample.MyAnalysis.lambda$main$1(MyAnalysis.java:36)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.yourorganization.maven_sample.MyAnalysis.main(MyAnalysis.java:35)

````

First of all: why does the solver not find B, I gave it to the TypeSolver and ```combinedTypeSolver.tryToSolveType("B")``` works, so it should be available.
Second: I don't see, why the solver even tries to solve B, it should already know after seeing the declaration of stack, what the resolved type is, no need to go up the hierarchy.

Some more observations:
- After removing ```implements B``` I get the expected result ```ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}```
- If I put the declarations of A and B into the same compilation unit, it works.
 
I tried javaparser-symbol-solver-core 3.6.15 and 3.6.14, both don't work.

Any ideas, my fault or a bug?

**Comment by ftomassetti** [comment]
I think you should add:

```
combinedTypeSolver.add(new JavaParserTypeSolver("D:/Users/Kathrin/Repo/JP_Problem/src/main/java/"));
```

instead of:

```
combinedTypeSolver.add(new JavaParserTypeSolver("D:/Users/Kathrin/Repo/JP_Problem/src/main/java/any"));
```

as `java` is the root of the source directory while any seems a package inside it

**Comment by kgeilmann** [comment]
Thanks a lot. That solves my problem.

Message to self: always check path depth twice
