### ISSUE TITLE
Make sure JP builds with JDK 11

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1759]

**Comment by matozoid** [comment]
We're having this problem: https://hibernate.atlassian.net/browse/HHH-12378

I guess we can make our own annotation for that, for the time being.

**Comment by matozoid** [comment]
Surefire is messing up and has no newer version yet:

```java
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.0:test (default-test) on project javaparser-core-testing: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
[ERROR] The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/danny/IdeaProjects/javaparser/javaparser-core-testing && /home/danny/dev/jdk-11/bin/java -javaagent:/home/danny/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/jacoco.exec -jar /home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/surefire/surefirebooter5021484779841158011.jar /home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/surefire 2018-08-17T11-39-16_513-jvmRun1 surefire8294004720327007618tmp surefire_017871603039179476790tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
[ERROR] Command was /bin/sh -c cd /home/danny/IdeaProjects/javaparser/javaparser-core-testing && /home/danny/dev/jdk-11/bin/java -javaagent:/home/danny/.m2/repository/org/jacoco/org.jacoco.agent/0.8.1/org.jacoco.agent-0.8.1-runtime.jar=destfile=/home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/jacoco.exec -jar /home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/surefire/surefirebooter5021484779841158011.jar /home/danny/IdeaProjects/javaparser/javaparser-core-testing/target/surefire 2018-08-17T11-39-16_513-jvmRun1 surefire8294004720327007618tmp surefire_017871603039179476790tmp
[ERROR] Error occurred in starting fork, check output in log
[ERROR] Process Exit Code: 134
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:671)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:278)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:244)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1194)
```

**Comment by matozoid** [comment]
It's too early to make it buildable, let's wait until everyone has had time to adjust.
