### ISSUE TITLE
Problem with LexicalPreservingPrinter

### ISSUE THREAD

**Issue by stefanleh** [javaparser/javaparser#1766]
Hello,

i've got an 

**java.lang.UnsupportedOperationException: CsmChild child(MarkerAnnotationExpr)**

when using

     LexicalPreservingPrinter lpp = LexicalPreservingPrinter.setup(ParseStart.COMPILATION_UNIT,
				new StringProvider(getFileContent(p))).b;
        lpp.print(cu);

The Method getFileContent just returns the Code read from the Source File as String.

Best regards,
Stefan

**Comment by stefanleh** [comment]
Trace:

	java.lang.UnsupportedOperationException: CsmChild child(MarkerAnnotationExpr)
		at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:248)
		at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:128)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.interpret(LexicalPreservingPrinter.java:425)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$interpret$5(LexicalPreservingPrinter.java:445)
		at java.base/java.lang.Iterable.forEach(Iterable.java:75)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.interpret(LexicalPreservingPrinter.java:445)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.prettyPrintingTextNode(LexicalPreservingPrinter.java:418)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.getOrCreateNodeText(LexicalPreservingPrinter.java:486)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:362)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:350)
		at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
		at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
		at java.base/java.lang.Iterable.forEach(Iterable.java:75)
		at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:365)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:350)
		at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
		at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
		at java.base/java.lang.Iterable.forEach(Iterable.java:75)
		at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:365)
		at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:350)
		...

**Comment by ftomassetti** [comment]
Thanks for reporting this. However to be able to work on that we would need the content of the file you were parsing.

**Comment by stefanleh** [comment]
**Testcase**

	@Test
	void testIssue1766() throws IOException {

		File sourceBefore = new File("src/test/resources/SimpleTestClass.java");
		CompilationUnit cu = JavaParser.parse(sourceBefore);

		LexicalPreservingPrinter lpp = LexicalPreservingPrinter.setup(ParseStart.COMPILATION_UNIT,
			new StringProvider(IOUtils.toString(new FileInputStream(sourceBefore)))).b;

		System.out.println(lpp.print(cu));

	}


**TestClass**

	public class SimpleTestClass {
	
	public SimpleTestClass() {
		// nothing
	}
	
	@Override
	void bubber() {
		// nothing
	}


@ftomassetti 
I hope that helps with finding the issue.
IMHO its just not implemented yet in `com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(CsmElement, Node, List<CsmElement>, Change)`

**Comment by ThLeu** [comment]
Hey @stefanleh, I had a quick look into this and found out that it seems to work with the non deprecated setup method of the `LexicalPreservingPrinter`. Since this one is deprecated and the not deprecated one seems to work fine I am not sure it is worth looking into deeper.
Could you check if switching to the other setup method fixes the issue for you?

```
File sourceBefore = new File("src/test/resources/SimpleTestClass.java");
CompilationUnit cu = LexicalPreservingPrinter.setup(JavaParser.parse(sourceBefore));
        
LexicalPreservingPrinter.print(cu)
```

**Comment by cadrian** [comment]
I have the same problem sometimes.
I never call LexicalPreservingPrinter.setup directly...
My code:
```
final ParserConfiguration parserConfiguration = JavaParser.getStaticConfiguration();
parserConfiguration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_8);
parserConfiguration.setLexicalPreservationEnabled(true);

final CollectionStrategy collectionStrategy = new SymbolSolverCollectionStrategy();
for (int i = 0; i < sources.length(); i++) {
	final String source = sources.getString(i);
	final Path sourcePath = FileSystems.getDefault().getPath(source).toAbsolutePath();
	Log.info("Scanning " + sourcePath);

	final ProjectRoot projectRoot = collectionStrategy.collect(sourcePath);
	for (final SourceRoot sourceRoot : projectRoot.getSourceRoots()) {
		Log.trace("Parsing " + sourceRoot);
		final List<ParseResult<CompilationUnit>> parseResults = sourceRoot.tryToParse();
. . .
```
