### ISSUE TITLE
JAVA_10 parse problem: "var" cannot infer array types

### ISSUE THREAD

**Issue by alexbezhan** [javaparser/javaparser#1786]
The following code is parsed fine with both `LanguageLevel.JAVA_8` and `LanguageLevel.JAVA_9`, but it fails with `LanguageLevel.JAVA_10`:
```Java
public class Run {
    public static void main(String[] args) {
        var arr = new String[]{"a"};
    }
}
```

```
com.github.javaparser.ParseProblemException: (line 3,col 17) "var" cannot infer array types.
    at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:333)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:301)
```

Test code that invokes parser(Kotlin):
```Kotlin
@Test
fun parseJava10() { // fail
    JavaParser.getStaticConfiguration().languageLevel = ParserConfiguration.LanguageLevel.JAVA_10
    JavaParser.parse("""public class Run {
            public static void main(String[] args) {
                var arr = new String[]{ "a" };
            }
        }""")
}

@Test
fun parseJava9() { // success
    JavaParser.getStaticConfiguration().languageLevel = ParserConfiguration.LanguageLevel.JAVA_9
    JavaParser.parse("""public class Run {
            public static void main(String[] args) {
                var arr = new String[]{ "a" };
            }
        }""")
}

@Test
fun parseJava8() { // success
    JavaParser.getStaticConfiguration().languageLevel = ParserConfiguration.LanguageLevel.JAVA_8
    JavaParser.parse("""public class Run {
            public static void main(String[] args) {
                var arr = new String[]{ "a" };
            }
        }""")
}
```

**Comment by matozoid** [comment]
Okay, that's what I get for building on early spec. Will be fixed ASAP. (JLS 10, 14.4 has the correct rules.)

**Comment by matozoid** [comment]
@alexbezhan the next release is on Sunday.

**Comment by alexbezhan** [comment]
@matozoid awesome. Thank you!
