### ISSUE TITLE
StackOverflowError in getAllMethodsVisibleToInheritors() (JSS)

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#1814]
Hey,

I just recently upgraded to JavaParser 3.6.19 which broke several of my Unit Tests:
```text
java.lang.StackOverflowError
	at java.base/sun.net.www.protocol.file.Handler.parseURL(Handler.java:67)
	at java.base/java.net.URL.<init>(URL.java:656)
	at java.base/java.net.URL.<init>(URL.java:523)
	at java.base/jdk.internal.loader.URLClassPath$FileLoader.getResource(URLClassPath.java:1127)
	at java.base/jdk.internal.loader.URLClassPath$FileLoader.findResource(URLClassPath.java:1116)
	at java.base/jdk.internal.loader.URLClassPath.findResource(URLClassPath.java:281)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResourceOnClassPath(BuiltinClassLoader.java:479)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findResource(BuiltinClassLoader.java:303)
	at java.base/java.lang.ClassLoader.getResource(ClassLoader.java:1393)
	at java.base/java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:1729)
	at util.codex.solve.JarSourcesTypeSolver.tryToSolveTypeUncached(JarSourcesTypeSolver.java:28)
	at util.codex.solve.AbstractCodexTypeSolver.tryToSolveType(AbstractCodexTypeSolver.java:85)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:62)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:136)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:526)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:586)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.getReturnType(JavaParserMethodDeclaration.java:71)
	at com.github.javaparser.resolution.MethodUsage.<init>(MethodUsage.java:56)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.getDeclaredMethods(ReferenceTypeImpl.java:150)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethodsVisibleToInheritors(ResolvedReferenceType.java:406)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethodsVisibleToInheritors$9(ResolvedReferenceType.java:412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethodsVisibleToInheritors(ResolvedReferenceType.java:411)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethodsVisibleToInheritors$9(ResolvedReferenceType.java:412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethodsVisibleToInheritors(ResolvedReferenceType.java:411)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethodsVisibleToInheritors$9(ResolvedReferenceType.java:412)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethodsVisibleToInheritors(ResolvedReferenceType.java:411)
// rest omitted for brevity
```

I believe this is related to https://github.com/javaparser/javaparser/pull/1789: Somehow an infinite recursion occurs when the TypeSolver stumbles upon `java.lang.Object`.

I will try to create a minimal test case as reproduction when I've got time for it.

**Comment by ftomassetti** [comment]
Thanks for reporting this.
Yes, a test case would greatly help, thank you
