### ISSUE TITLE
Unable to resolve parent class

### ISSUE THREAD

**Issue by ro11ak** [javaparser/javaparser#1851]
Hi,
I'm working on an analysis tool that would parse through all the javax.security methods in a class and list out all the invoked methods in that class.

I'm trying to parse a class that extends another class and I'm getting the following exception
```java
UnsolvedSymbolException{context='unknown', name='AbstractUsernamePasswordAuthenticationHandler'}
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.toReferenceType(JavaParserClassDeclaration.java:435)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getSuperClass(JavaParserClassDeclaration.java:166)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:321)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:299)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:71)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:436)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:496)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:492)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserFieldDeclaration.getType(JavaParserFieldDeclaration.java:72)
	at com.github.javaparser.symbolsolver.model.resolution.Value.from(Value.java:40)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbolAsValue(ClassOrInterfaceDeclarationContext.java:71)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveSymbolAsValue(AbstractMethodLikeDeclarationContext.java:68)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:112)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:143)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:143)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:149)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:68)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:85)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:224)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:243)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:128)
	at auth.MethodCallGenerator$1.visit(MethodCallGenerator.java:80)
	at auth.MethodCallGenerator$1.visit(MethodCallGenerator.java:1)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:120)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:170)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:105)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:130)
	at auth.MethodCallGenerator.generate(MethodCallGenerator.java:100)
	at auth.Main.start(Main.java:170)
	at auth.Main.main(Main.java:230)
```

In this case AbstractUsernamePasswordAuthenticationHandler is the parent class.

My code is:

```
FileInputStream in = new FileInputStream(driverClass.getPathToClass());
CompilationUnit cu = JavaParser.parse(in);
cu.accept(methodCallVisitor, null);
```

I have a visitor that parses each method
```
		VoidVisitorAdapter<Void> methodCallVisitor = new VoidVisitorAdapter<Void>() {
                         @Override
			public void visit(MethodDeclaration aMethod, Void arg) {
				System.out.println(aMethod.getDeclarationAsString(true, false));
				System.out.println("{");
				List<MethodCallExpr> callExprList = aMethod.findAll(MethodCallExpr.class);
				for (MethodCallExpr callExpr : callExprList) {
					CombinedTypeSolver solver = typeSolver(srcFolders);
					JavaParserFacade j = JavaParserFacade.get(solver);
					SymbolReference<ResolvedMethodDeclaration> methodRef = j.solve(callExpr);
					String methodSignature = methodRef.getCorrespondingDeclaration().getQualifiedSignature();
					if(methodSignature.contains("javax.security.auth") || methodSignature.contains("javax") || methodSignature.contains("security") || methodSignature.contains("auth")) {
						System.out.println(methodSignature);
					}
				}
				System.out.println("}\n");
				super.visit(aMethod, arg);
			}
		};
```

```
public CombinedTypeSolver typeSolver(Set<String> srcFolders) {
		CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
		combinedTypeSolver.add(new ReflectionTypeSolver());
		for(String folder: srcFolders) {
			System.out.println(folder);
			combinedTypeSolver.add(new JavaParserTypeSolver(
					new File(folder)));
		}
		return combinedTypeSolver;
	}
```

What could be the problem?

Thanks!

**Comment by matozoid** [comment]
@ftomassetti ?

**Comment by malteskoruppa** [comment]
Quick question: Is the symbol solver aware of the class `AbstractUsernamePasswordAuthenticationHandler`? I mean, it doesn't look like this class is part of the standard library, so the `ReflectionTypeSolver` won't help you. So the question is: Will one of your `JavaParserTypeSolver`s help you to resolve that class? In other words, is the `AbstractUsernamePasswordAuthenticationHandler` class defined somewhere among the folders that you instantiate a `JavaParserTypeSolver` for?

If not, that is likely your problem. In this case, you have two possible solutions:
* If you have the source code for the module which contains the class `AbstractUsernamePasswordAuthenticationHandler`, add a `JavaParserTypeSolver` for the source folder of that module to your combined type solver.
* If you do not have the source code, but you have a JAR which contains the class `AbstractUsernamePasswordAuthenticationHandler`, add a `JarTypeSolver` for that JAR to your combined type solver.

**Comment by jokster** [comment]
I guess that's related to https://github.com/javaparser/javaparser/issues/1771

**Comment by matozoid** [comment]
#1771 is the main issue now.
