### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by xgulism1** [javaparser/javaparser#1861]
Hi,

I am trying to create a dependency tree for my project using JavaSymbolSolver, but I keep getting error.
I started with a simple class and interface (each one has separate file, but they are in the same package). I am trying to get the relation between the interface and the class.

weapon.java:
```
public interface Weapon {
    public int use();
}
```

axe.java:
```
public class Axe implements Weapon {
    public int use() {
        return 10;
    }
}
```

The code I use to parse the code:
```
String directory = "path_to_directory";
String fileName = directory + "\\axe.java";
TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), new JavaParserTypeSolver(directory));
JavaParserFacade javaParserFacade = JavaParserFacade.get(typeSolver);
try {
    new VoidVisitorAdapter<Void>() {
        @Override
        public void visit(ClassOrInterfaceDeclaration n, Void arg) {
            super.visit(n, arg);
            ResolvedType resolvedType = javaParserFacade.getType(n); // this throws exception
            ResolvedReferenceType resolvedReferenceType = resolvedType.asReferenceType();
            List<ResolvedReferenceType> ancestors = resolvedReferenceType.getAllAncestors();
            System.out.println("Count: " + ancestors.size());
        }
    }.visit(JavaParser.parse(new File(fileName)), null);
} catch (IOException e) {
    //...
}
```

The exception I keep getting:
```
Exception in thread "main" java.lang.UnsupportedOperationException: com.github.javaparser.ast.body.ClassOrInterfaceDeclaration
	at com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:43)
	at com.github.javaparser.symbolsolver.javaparsermodel.DefaultVisitorAdapter.visit(DefaultVisitorAdapter.java:15)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:99)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:268)
	at Main$1.visit(Main.java:91)
	at Main$1.visit(Main.java:80)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:105)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1378)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:267)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at Main.lambda$main$0(Main.java:117)
	at DirectoryExplorer.explore(DirectoryExplorer.java:28)
	at DirectoryExplorer.explore(DirectoryExplorer.java:23)
	at DirectoryExplorer.explore(DirectoryExplorer.java:15)
	at Main.main(Main.java:123)
```

Probably I should use another visitor (not `ClassOrInterfaceDeclaration`), but I don't know which one. Or is there another way? Can someone help me please?

Thanks!

**Comment by xgulism1** [comment]
Solved it.
I can use this in the visit method:
```
List<ResolvedReferenceType> ancestors = javaParserFacade.getTypeDeclaration(n).getAllAncestors();
```
Works fine.

**Comment by matozoid** [comment]
Great! Sorry that nobody had time to help yet :-(
