### ISSUE TITLE
JavaParser fails on no-modifier methods with annotations

### ISSUE THREAD

**Issue by octylFractal** [javaparser/javaparser#188]
```
class Test {
    @Detectable void test() {}
}
```

Parsing that code throws an exception with `2.2.1`.

```
Exception in thread "main" com.github.javaparser.ParseException: Encountered "<EOF>" at line 2, column 35.
Was expecting one of:
    "abstract" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "class" ...
    "default" ...
    "double" ...
    "enum" ...
    "final" ...
    "float" ...
    "int" ...
    "interface" ...
    "long" ...
    "native" ...
    "private" ...
    "protected" ...
    "public" ...
    "short" ...
    "static" ...
    "strictfp" ...
    "synchronized" ...
    "transient" ...
    "void" ...
    "volatile" ...
    <IDENTIFIER> ...
    "{" ...
    "}" ...
    ";" ...
    "@" ...
    "<" ...

    at com.github.javaparser.ASTParser.generateParseException(ASTParser.java:9055)
    at com.github.javaparser.ASTParser.jj_consume_token(ASTParser.java:8928)
    at com.github.javaparser.ASTParser.ClassOrInterfaceBody(ASTParser.java:857)
    at com.github.javaparser.ASTParser.ClassOrInterfaceDeclaration(ASTParser.java:444)
    at com.github.javaparser.ASTParser.TypeDeclaration(ASTParser.java:372)
    at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:185)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:113)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:135)
    at me.kenzierocks.javaparser.DetectAnnotations.main(DetectAnnotations.java:15)
```

**Comment by ptitjes** [comment]
I did not yet run your test case against JavaParser, but at a first glance this error seems very strange to me:

The parser sees `<EOF>` at line 2 column 35 but your sample is three lines long and line 2 is 30 columns wide... Didn't you mismatch the error with another test case, or rewrote the test case ?

(JLaTo parses it fine as shown by your test case https://github.com/ptitjes/jlato/commit/7a7e9ac0a69874d0cbc25a5b59f7a07cb0c914cf)

**Comment by octylFractal** [comment]
Looks like JavaParser might have taken the `\t` as 8 characters, instead of 4? Not sure, that's exactly what I pasted.

**Comment by ptitjes** [comment]
Well I just tested it on JavaParser/master (which is currently 2.2.1) and it also parses it fine.

@kenzierocks Would you mind doing a test case please so that we can spot what brings this error ?

**Comment by ptitjes** [comment]
@kenzierocks Our messages colided :p 
Then maybe you were missing the ending `}` ?
I mean EOF means end-of-file...

**Comment by octylFractal** [comment]
Stick this where you want, it should produce it:

```
CompilationUnit unit = JavaParser.parse(new ByteArrayInputStream(new byte[] { 99, 108, 97, 115, 115, 32, 84,
                101, 115, 116, 32, 123, 10, 9, 64, 68, 101, 116, 101, 99, 116, 97, 98, 108, 101, 32, 118, 111, 105, 100,
                32, 116, 101, 115, 116, 40, 41, 32, 123, 125, 10 }));
```

**Comment by octylFractal** [comment]
Ah, it appears that Eclipse's EOF handling was eating the last bracket. Strange.

**Comment by ptitjes** [comment]
Ah? ok... Glad you solved it! Have a nice day!
