### ISSUE TITLE
Parse error. Found "super", expected "}" 

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#1908]
Hi everyone, 
I've got an error when parsing this Block Statement (body constructor): 
```java
    {
        super();
        this.file_name = new SimpleStringProperty(file_name);
        this.size = new SimpleStringProperty(size);
        this.date_modified = new SimpleStringProperty(date_modified);
    }
```

The error says:
```
com.github.javaparser.ParseProblemException: (line 1,col 1) Parse error. Found "super", expected "}"
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10319)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10178)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3818)
  com.github.javaparser.GeneratedJavaParser.BlockParseStart(GeneratedJavaParser.java:5515)
  com.github.javaparser.JavaParser.parse(JavaParser.java:130)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:329)
  com.github.javaparser.JavaParser.parseBlock(JavaParser.java:313)
  com.AST.VoidVisitorStarter.main(VoidVisitorStarter.java:80)

	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:333)
	at com.github.javaparser.JavaParser.parseBlock(JavaParser.java:313)
	at com.AST.VoidVisitorStarter.main(VoidVisitorStarter.java:80)
```
This is my code: 
```java
public static void main(String[] args){
        try {
            BlockStmt bodyMethod = JavaParser.parseBlock("{\n"
                    + "        super();\n"
                    + "        this.file_name = new SimpleStringProperty(file_name);\n"
                    + "        this.size = new SimpleStringProperty(size);\n"
                    + "        this.date_modified = new SimpleStringProperty(date_modified);\n"
                    + "    }");
            MethodExtractions methodExtractions = new MethodExtractions();
            methodExtractions.visit(bodyMethod, null);
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```
I'm trying to parsing body method or body constructor to find operand and operator within it.
Am I doing anything wrong?

Thanks and best regards,
Rasio

**Comment by matozoid** [comment]
Hi!

Constructor bodies are a special case in the parser's grammar, which is not considered for most body statements. Whether's that's a good idea can be discussed, but it would certainly be nice if `parseBlock` would support it. So I'm making this a possible improvement.

There are many workarounds, the easiest is probably parsing the whole constructor with `parseBodyDeclaration` or even putting a fake class in `parse` (like `parse("class X{X(){yourstuff}}")`) and then using `find(BlockStmt.class)` to find the part you're interested in.

I'm writing this from memory, so if something doesn't work, please ask again.

**Comment by ghost** [comment]
Hi @matozoid ,
Thanks for your answers and i would love to this improvement.
i will try parsing the whole constructor with `parseBodyDeclaration` or putting a fake class.

best regards,
Rasio

**Comment by rtritto** [comment]
Any update?

My code:
```java
class c extends e
{    
    ak() {
        super();
    }
}
```

**Comment by jlerbsc** [comment]
There is no schedule to support this.

**Comment by jlerbsc** [comment]
This case no longer appears to cause an error in the current version as of December 2025.
