### ISSUE TITLE
Problem in ResolveMethodCalls.class in Java-parser-visited

### ISSUE THREAD

**Issue by fayazfaizy** [javaparser/javaparser#1931]
If i parse below class with ResolveMethodCalls parser im getting this errror

"package org.javaparser.examples.chapter5;
class A {
public void foo(Object param) {
**Bar.aMethod();**
System.out.println(1);
System.out.println("hi");
System.out.println(param);
}
}

Error :
**Exception in thread "main" UnsolvedSymbolException{context='Bar.aMethod()', name='Bar', cause='UnsolvedSymbolException{context='Bar', name='Solving Bar', cause='null'}'}
at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:176)
at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:152)
at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:242)
at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:142)
at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
at com.github.javaparser.ast.expr.MethodCallExpr.resolveInvokedMethod(MethodCallExpr.java:321)
at org.javaparser.examples.chapter5.ResolveMethodCalls.lambda$main$0(ResolveMethodCalls.java:27)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.javaparser.examples.chapter5.ResolveMethodCalls.main(ResolveMethodCalls.java:26)
Caused by: UnsolvedSymbolException{context='Bar', name='Solving Bar', cause='null'}
at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:279)
at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:44)
at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:447)
at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:310)
at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:292)
at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:167)
... 9 more**

**Comment by matozoid** [comment]
@SmiddyPence answered this in the old issue. Did it help?
