### ISSUE TITLE
addAndGetAnnotaion  and LexicalPreservingPrinter UnsupportedOperationException:

### ISSUE THREAD

**Issue by loongchow** [javaparser/javaparser#1938]
```java
   val compilationUnit=JavaParser.parse(f);
            val lexicalPreservingPrintercompilationUnit =LexicalPreservingPrinter.setup(compilationUnit)
            lexicalPreservingPrintercompilationUnit.findAll(ClassOrInterfaceDeclaration::class.java).forEach {
                var index=0;
                it.findAll(FieldDeclaration::class.java)
                        .map {field->
                            System.out.println("cast FieldDeclaration")
                            field as FieldDeclaration }
                        .filter {
                            field->
                            System.out.println("filter NeedParcel")
                            field.getAnnotationByClass(NeedParcel::class.java).isPresent }
                        .map {
                            field->
                            if(!field.isAnnotationPresent(PackFlag::class.java))
                            {
                                System.out.println("add  normalAnnotationExpr $field")
                                val normalAnnotationExpr=field.addAndGetAnnotation(PackFlag::class.java)
                                normalAnnotationExpr.addPair("id",index.toString())
                            }
                            else
                            {
                                System.out.println("update  normalAnnotationExpr $field")
                                val optional= field.getAnnotationByClass(PackFlag::class.java)
                                var annotationExpr=optional.get() as NormalAnnotationExpr
                                val nodes=annotationExpr.pairs.filter {
                                    it.name.toString() == "id";
                                }
                                for(node in nodes)
                                {
                                    annotationExpr.remove(node)
                                }

                                annotationExpr.addPair("id",index.toString())
                            }
                            index++
                        }

            }

            val writer=FileWriter(f);
            LexicalPreservingPrinter.print(lexicalPreservingPrintercompilationUnit,writer)
            writer.close()
```

the file content as below
```java
public class SampleParent {
	@NeedParcel
	public String test;
	int parent=0;

}
```

**Comment by loongchow** [comment]
Exception in thread "main" java.lang.UnsupportedOperationException: kept child(ClassOrInterfaceType) vs "String"   <89>   (line 8,col 9)-(line 8,col 14)
        at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:442)
        at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:134)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:233)
        at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
        at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:466)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:466)
        at com.github.javaparser.ast.NodeList.add(NodeList.java:70)
        at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addAnnotation(NodeWithAnnotations.java:59)
        at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addAndGetAnnotation(NodeWithAnnotations.java:87)
        at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addAndGetAnnotation(NodeWithAnnotations.java:110)
        at com.qzone.transform.MainHandler$Companion.realHandle(MainHandler.kt:76)
        at com.qzone.transform.MainHandler$Companion.handle(MainHandler.kt:30)
        at com.qzone.transform.MainHandler$Companion.handle(MainHandler.kt:48)
        at com.qzone.transform.MainHandler$Companion.handle(MainHandler.kt:48)
        at com.qzone.transform.MainHandler$Companion.handle(MainHandler.kt:48)
        at com.qzone.transform.MainHandler$Companion.handle(MainHandler.kt:48)
        at com.qzone.transform.MainHandler$Companion.handle(MainHandler.kt:22)
        at com.qzone.transform.MainHandler.handle(MainHandler.kt)
        at com.qzone.transform.MainClass.main(MainClass.java:12)

**Comment by matozoid** [comment]
Also see #1277

**Comment by immerser** [comment]
I meet the same problem

**Comment by ftomassetti** [comment]
Will look into that. A test case would be great.

**Comment by jlerbsc** [comment]
It seems this issue is resolved

    class Issue1938Test extends AbstractLexicalPreservingTest {

    @Test
    void test() {
        String src = 
                "public class SampleParent {\n" + 
                "    @NeedParcel\n" + 
                "    public String test;\n" + 
                "    int parent=0;\n" + 
                "\n" + 
                "}"; 

        considerCode(src);
        
        FieldDeclaration fd = cu.findFirst(FieldDeclaration.class).get();
        NormalAnnotationExpr nae = fd.addAndGetAnnotation("PackFlag");
        nae.addPair("id","1");
        
        assertEquals("@NeedParcel", fd.getAnnotationByName("NeedParcel").get().toString());
        assertEquals("@PackFlag(id = 1)", fd.getAnnotationByName("PackFlag").get().toString());
    }
    
    }
