### ISSUE TITLE
InvalidPathException when parsing interface with generic interface ancestors

### ISSUE THREAD

**Issue by HoldYourWaffle** [javaparser/javaparser#1948]
Closely related to #1876 (might even be identical), but I think I have some new (and probably better explained) information.
As with my previous issues, there's a [sample project](https://github.com/HoldYourWaffle/JavaParserGenericSuperInterfaceChoke). It mostly speaks for itself this time, there's a diagram in the readme that explains the class hierarchy.

The source of the error is method calls like [these](https://github.com/HoldYourWaffle/JavaParserGenericSuperInterfaceChoke/blob/7a2975344ca0450c6a91dca52121db208a6cc16b/src/main/java/main/MainClass.java#L12) which reference generic super interfaces.
It throws the following exception:
```
com.google.common.util.concurrent.UncheckedExecutionException: java.nio.file.InvalidPathException: Illegal char <<> at index 107: D:\VOLATILE\workspace-2\JavaParserGenericSuperInterfaceChoke\src\main\java/interfaces/GenericSuperInterface<T>.java
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2218)
    at com.google.common.cache.LocalCache.get(LocalCache.java:4147)
    at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5053)
    at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveType(JavaParserTypeSolver.java:172)
    at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:62)
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:163)
    at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.solveType(JavaParserInterfaceDeclaration.java:241)
    at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.toReferenceType(JavaParserInterfaceDeclaration.java:336)
    at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.getAncestors(JavaParserInterfaceDeclaration.java:250)
    at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getAncestors(ResolvedReferenceTypeDeclaration.java:69)
    at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.getDirectAncestors(ReferenceTypeImpl.java:210)
    at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethodsVisibleToInheritors(ResolvedReferenceType.java:416)
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:122)
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:98)
    at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:583)
    at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:156)
    at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:242)
    at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
    at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:142)
    at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
    at TestJavaParser.testReflectionFirst(TestJavaParser.java:58)
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 107: D:\VOLATILE\workspace-2\JavaParserGenericSuperInterfaceChoke\src\main\java/interfaces/GenericSuperInterface<T>.java
    at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
    at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
    at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
    at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
    at java.base/java.nio.file.Paths.get(Paths.java:84)
    at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:204)
    at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$tryToSolveType$4(JavaParserTypeSolver.java:173)
    at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5058)
    at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3708)
    at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2416)
    at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2299)
    at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2212)
    ... 51 more
```
There are more variations of generic super interface method invocations in the sample project. It seems like JavaParser is not able to solve classes that implement interfaces that *extend* a generic interface.
Put in another way:
```
GenericInterface -> Class
```
works perfectly fine, but
```
GenericInterface -> SubInterface -> Class
```
doesn't.

This problem is specific to the `JavaParserTypeSolver`. I know this because a `CombinedTypeSolver` with a `ReflectionTypeSolver` registered first is able to solve this code just fine.

**Comment by matozoid** [comment]
@HoldYourWaffle was this solved in the PR?

**Comment by HoldYourWaffle** [comment]
#1952 is just a workaround

**Comment by matozoid** [comment]
Okay

**Comment by ros3cin** [comment]
Hi, I'm also waiting for this fix.

**Comment by ftomassetti** [comment]
One way to speed up the solution of this would be sending a PR with a failing test-case. The issues which have a testcase are prioritized w.r.t. the others.

**Comment by matozoid** [comment]
@ftomassetti there's a test project for this one.
