### ISSUE TITLE
UnsolvedSymbolException thrown on super.<method> declaration inside inner class

### ISSUE THREAD

**Issue by maartenc** [javaparser/javaparser#1962]
Hi,

consider the following source:

```
public class X { 
    java.util.List x() { 
        return new java.util.ArrayList() { 
            public int size() { 
                return super.size(); 
            } 
        }; 
    } 
}
```

When trying to resolve the `MethodCallExpr`, I get an UnsolvedSymbolException:

```
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to super.size()', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:148)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
```

My code looks like this:

```
[...]
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver(false));
combinedTypeSolver.add(new JavaParserTypeSolver(new File("/path/to/my/sources")));

JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
JavaParser.getStaticConfiguration().setSymbolResolver(symbolSolver);

CompilationUnit cu = JavaParser.parse("public class X { java.util.List x() { return new java.util.ArrayList() { public int size() { return super.size(); } }; } }");
cu.accept(new MethodVisitor(), null);
[...]

public class MethodVisitor extends VoidVisitorAdapter<Void> {
    @Override
    public void visit(MethodCallExpr n, Void arg) {
        ResolvedMethodDeclaration rmd = n.asMethodCallExpr().resolve();
        super.visit(n, arg);
    }
}
```

Is this a bug, or did I something wrong?

Maarten

**Comment by HoldYourWaffle** [comment]
This could be related to #1949.

**Comment by julien-breda** [comment]
I encounter exactly the same problem.
I already use the last version of javaparser (3.15.15)
Does anyone know if this issue would be soon fixed ?

**Comment by maartenc** [comment]
I might have a fix ready... stay tuned.
