### ISSUE TITLE
Emptying method bodys via MethodCallExpr triggers UnsupportedOperationException

### ISSUE THREAD

**Issue by forenbuddy** [javaparser/javaparser#2001]
If I remove the last MethodCallExpr via the ModifierVisitor by returning null in this visitor so that the method body in the modified source code would be empty afterwards "{}", the following exception is thrown instead:

``
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: removed com.github.javaparser.printer.concretesyntaxmodel.CsmIndent@1 vs ChildTextElement{ClassFoo.myLastOrOnlyMethodToBeRemovedBar("arg: Bla");}
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyRemovedDiffElement(Difference.java:394)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:142)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:234)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementRemoved$2(NodeList.java:470)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.notifyElementRemoved(NodeList.java:470)
	at com.github.javaparser.ast.NodeList.remove(NodeList.java:85)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1073)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:255)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1111)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:167)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
	at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$56(ModifierVisitor.java:618)
	at java.util.Optional.map(Optional.java:215)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:618)
...
``

If any other code still exists in the method body after removing method calls, all works fine. The additional code can be above or below the to be removed method call expression(s), the removal will not trigger this exception then.

**Comment by ftomassetti** [comment]
Hi @forenbuddy thank you for reporting this.

Could you please share as much detail as possible about this? Ideally we would like to get a simple example we can run to verify this issue and fix it.

The perfect solution would be to get a PR with a failing test, but any piece of code posted in this issue would also help.

Thank you!

**Comment by forenbuddy** [comment]
I know and I would have done exactly that in my initial report if it were relatively easy.

Unfortunately the related functions are scattered around my code and now I work around the problem by exchanging the unwanted functions with another one that gets removed by the compilers optimizer instead of removing them directly in the source code. This works for me.

I thought you still would like to know the problem and so described it as good as I could.

I may share a function of the to-be-changed code.

In the following code the said exception is thrown if I return null on all three of the found `X.p()` functions:

```
package tests;

import t.X;

public class JavaTests
{

	private static void blubb()
	{
		X.p("blaubb02");
		X.p("blaubb03");
		X.p("blaubb04");
	}

}
```

While in this function all `X.p()` namely `X.p("blaubb02");`, `X.p("blaubb03");` and `X.p("blaubb04");` are taken out and no exception occurs because `int b=0;` will still be remaining in the containing function `blubb()` afterwards: 
```
package tests;

import t.X;

public class JavaTests
{

	private static void blubb()
	{
		int b=0;
		X.p("blaubb02");
		X.p("blaubb03");
		X.p("blaubb04");
	}

}
```

My workaround is to not return null, but create a new function and return it: `new MethodCallExpr(..., ...);`. Then no exception is thrown and all three of them are always exchanged even if no `int b=0;` is present.

**Comment by matozoid** [comment]
I'll see if I can make a test PR.

**Comment by ftomassetti** [comment]
thank you @forenbuddy , we appreciate the time you took to provide more details

**Comment by matozoid** [comment]
Okay, that's reproduced. Thanks @forenbuddy!

**Comment by matf** [comment]
I'm hitting this as well when removing assignment statements from a method via BlockStmt#remove(Node), the exception is triggered when trying to remove the last statement from the block. Happy to help if there is anything I can do. Submitting a PR is probably a bit beyond my current understanding of lexical preservation in JavaParser, but if additional tests are needed I could help with that.

**Comment by matozoid** [comment]
The best way to get things fixed with lexical preservation and symbol resolution is to submit a fix. I wish it was different, but there is nobody with thorough knowledge of these components and enough time right now.

**Comment by matf** [comment]
Ok, good to know, will prepare a PR
