### ISSUE TITLE
Problem resolving type of lambda with Math method invocation inside

### ISSUE THREAD

**Issue by RaulGracia** [javaparser/javaparser#2065]
Hi all,

I found a problem in JSS when lambdas contain calls to Math methods:

Let us consider this simple example:

```
Stream<String> myStream = Files.lines(Paths.get(inputFile));
int countLines = myStream.filter(s -> s.contains("Hamlet"))
					.map(l -> l.length())
					.reduce((a, b) -> Math.max(a, b)).get();
```

When I use JSS (via a JavaParserFacade) to infer the type of  (a, b) -> Math.max(a, b), I got the following exception (full stacktrace can be found at the end of this mail):

> UnsolvedSymbolException{context='Method 'max' with parameterTypes [com.github.javaparser.symbolsolver.model.typesystem.LambdaConstraintType@11a9e7c8, com.github.javaparser.symbolsolver.model.typesystem.LambdaConstraintType@3901d134]', name='ReflectionClassDeclaration{clazz=java.lang.Math}', typeSolver=null}

If I change `Math.max `by any other expression, like `a+b` or `a*b` JSS correctly infers the input type of the lambda:

> reduce((a, b) -> a * b)=java.util.function.BinaryOperator<java.lang.Integer>

My JavaParserFacade is built as follows:
```
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver());
combinedTypeSolver.add(new JavaParserTypeSolver(new File(sourceCodeDirToAnalyze)));
JavaParserFacade.get(combinedTypeSolver);
```

So, maybe this has to do with the fact of solving types of static methods called within lambdas?

Please, let me know if this is a problem related to JSS or related to an bad use of it.

Thanks a lot,
Raúl.

```
UnsolvedSymbolException{context='Method 'max' with parameterTypes [com.github.javaparser.symbolsolver.model.typesystem.LambdaConstraintType@11a9e7c8, com.github.javaparser.symbolsolver.model.typesystem.LambdaConstraintType@3901d134]', name='ReflectionClassDeclaration{clazz=java.lang.Math}', typeSolver=null}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:89)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:481)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:241)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:35)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:86)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:371)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:263)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:257)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:370)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:35)
	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:111)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:371)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:263)
	at main.java.analyzer.visitor.StatementsExtractor.getLambdaTypeFromNode(StatementsExtractor.java:132)
	at main.java.analyzer.visitor.StatementsExtractor.visit(StatementsExtractor.java:104)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:91)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$170(VoidVisitorAdapter.java:567)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:567)
	at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:132)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$168(VoidVisitorAdapter.java:561)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:561)
	at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:109)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:257)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:67)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:105)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:105)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:68)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$158(VoidVisitorAdapter.java:528)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:528)
	at com.github.javaparser.ast.stmt.TryStmt.accept(TryStmt.java:95)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:105)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:105)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:68)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$101(VoidVisitorAdapter.java:366)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:366)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:103)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:150)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:150)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:90)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:170)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at main.java.analyzer.JavaStreamsJobAnalyzer.analyze(JavaStreamsJobAnalyzer.java:94)
	at main.java.analyzer.JavaStreamsJobAnalyzer.analyze(JavaStreamsJobAnalyzer.java:136)
	at test.java.AbstractAnalyzerTest.testAnalyze(AbstractAnalyzerTest.java:58)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at junit.framework.TestCase.runTest(TestCase.java:176)
	at junit.framework.TestCase.runBare(TestCase.java:141)
	at junit.framework.TestResult$1.protect(TestResult.java:122)
	at junit.framework.TestResult.runProtected(TestResult.java:142)
	at junit.framework.TestResult.run(TestResult.java:125)
	at junit.framework.TestCase.run(TestCase.java:129)
	at junit.framework.TestSuite.runTest(TestSuite.java:252)
	at junit.framework.TestSuite.run(TestSuite.java:247)
	at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
```

**Comment by jlerbsc** [comment]
I'm reopening this issue because the solution that has been found doesn't really solve the problem. Here the problem is related to the way JSS infers types from a functional method.

reduce((a, b) -> a * b)=java.util.function.BinaryOperator<java.lang.Integer>

BinaryOperator which is defined by BinaryOperator<T> extends BiFunction<T,T,T> is a special form of BiFunction which is defined by BiFunction<T, U, R>. Later in JP the type U is not inferred.

**Comment by verhasi** [comment]
## Ghostbuster Status: Bug Still Open

Investigated this issue as of `master` (August 2026). Here are the findings:

**Original bug (Math.max in lambda):** ✅ Fixed — resolving `(a, b) -> Math.max(a, b)` inside a 1-arg `reduce()` now works correctly and returns `java.util.function.BinaryOperator<java.lang.Integer>`.

**Remaining bug (BiFunction type inference in 3-arg reduce):** ❌ Still present — as @jlerbsc noted in December 2024, the 3-arg `reduce(identity, accumulator, combiner)` fails when resolving the accumulator lambda. Throws:

```
IllegalStateException: Equivalent types are: [InferenceVariableType{id=1}, InferenceVariableType{id=2},
LambdaConstraintType{bound=ReferenceType{java.lang.String}}, ReferenceType{java.lang.String}]
```

### Reproduction Test

Place this in `javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue2065Test.java`:

```java
package com.github.javaparser.symbolsolver;

import static org.junit.jupiter.api.Assertions.assertDoesNotThrow;
import static org.junit.jupiter.api.Assertions.assertEquals;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.LambdaExpr;
import com.github.javaparser.resolution.types.ResolvedType;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import java.util.List;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

class Issue2065Test {

    @BeforeEach
    void setup() {
        ParserConfiguration config = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        StaticJavaParser.setConfiguration(config);
    }

    @Test
    void lambdaWithMathMaxInReduceShouldResolve() {
        String code = "import java.util.stream.Stream;\n"
                + "public class Test {\n"
                + "    void test() {\n"
                + "        Stream<Integer> stream = Stream.of(1, 2, 3);\n"
                + "        int result = stream.reduce((a, b) -> Math.max(a, b)).get();\n"
                + "    }\n"
                + "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<LambdaExpr> lambdas = cu.findAll(LambdaExpr.class);
        assertEquals(1, lambdas.size());

        LambdaExpr lambda = lambdas.get(0);
        ResolvedType type = assertDoesNotThrow(() -> lambda.calculateResolvedType(),
                "Lambda with Math.max should resolve without UnsolvedSymbolException");
        assertEquals("java.util.function.BinaryOperator<java.lang.Integer>", type.describe());
    }

    @Test
    void biFunctionLambdaInReduceShouldInferTypeU() {
        // Tests jlerbsc's concern: 3-arg reduce with BiFunction<U,? super T,U> accumulator
        String code = "import java.util.stream.Stream;\n"
                + "public class Test {\n"
                + "    void test() {\n"
                + "        Stream<String> stream = Stream.of(\"a\", \"b\", \"c\");\n"
                + "        String result = stream.reduce(\"\", (a, b) -> a + b, (a, b) -> a + b);\n"
                + "    }\n"
                + "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<LambdaExpr> lambdas = cu.findAll(LambdaExpr.class);
        assertEquals(2, lambdas.size());

        LambdaExpr accumulator = lambdas.get(0);
        ResolvedType accType = assertDoesNotThrow(() -> accumulator.calculateResolvedType(),
                "Accumulator lambda in 3-arg reduce should resolve without exception");
        assertEquals("java.util.function.BiFunction<java.lang.String, java.lang.String, java.lang.String>",
                accType.describe());

        LambdaExpr combiner = lambdas.get(1);
        ResolvedType combType = assertDoesNotThrow(() -> combiner.calculateResolvedType(),
                "Combiner lambda in 3-arg reduce should resolve without exception");
        assertEquals("java.util.function.BinaryOperator<java.lang.String>", combType.describe());
    }
}
```

### Results

| Test | On 3.26.2 | On master |
|------|-----------|-----------|
| `lambdaWithMathMaxInReduceShouldResolve` | ✅ Pass | ✅ Pass |
| `biFunctionLambdaInReduceShouldInferTypeU` | ❌ Fail | ❌ Fail |

The underlying issue is that `InferenceVariableType` resolution doesn't properly collapse equivalent types when a `BiFunction<U, ? super T, U>` parameter is encountered in the 3-arg `Stream.reduce()` overload.

---

<small>This analysis was performed by the GitHub Issue Ghostbuster.</small>

**Comment by jlerbsc** [comment]
The reported problem is no longer reproducible. Closing as fixed.
