### ISSUE TITLE
Unable to get types for NameExpr which refer to ClassNames.

### ISSUE THREAD

**Issue by fvanham** [javaparser/javaparser#2069]
I'm unable to get the types for java's common built-in classes, but I cannot figure out where my code is off. Using Symbolsolver 0.6.3 via maven, which pulls in javaparser 3.5.5
```java
public class MathTest {
	public static void main(String[] args) throws FileNotFoundException {
		// set up combined type solver
        CombinedTypeSolver ts = new CombinedTypeSolver();
        ts.add( new ReflectionTypeSolver() );
        ts.add( new JavaParserTypeSolver(new File("./sample") ) );
        // parse to CompilationUnit
        CompilationUnit cu = JavaParser.parse(new File("./sample/Test.java"));
        cu.accept(
            new VoidVisitorAdapter<Void>() {
            	// visit all named expressions
                public void visit( NameExpr n, Void v ) {
                	try
                	{
                		// attempt to get type
                		ResolvedType type = JavaParserFacade.get( ts ).getType( n );
                		System.out.println( n + ":" + type.describe() );
                	}
                	catch ( Exception e )
                	{
                 		e.printStackTrace();
                	}
                	super.visit( n, v );
                }
            },
        null );
    }
}
```
which parses this file content
```java
public class Test {
	public static void main( String[] args )
	{
		System.out.println( Math.round( Math.random() * Integer.parseInt( args[0] ) ) );
	}
}
```
The result is two failed type resolutions on `Math`, one on `System` and one on `Integer`. I'm a bit surprised the typesolver is null in the stacktrace.
```
UnsolvedSymbolException{context='Solving Math', name='Math', typeSolver=null}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:290)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:46)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:78)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:388)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:280)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:274)
	at MathTest$1.visit(MathTest.java:33)
	at MathTest$1.visit(MathTest.java:1)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:84)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$94(VoidVisitorAdapter.java:402)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$80.00000000039BD2F0.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:402)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:104)
	at com.github.javaparser.ast.expr.BinaryExpr.accept(BinaryExpr.java:98)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$93(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$78.00000000039BC990.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$93(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$78.00000000039BC990.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:400)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:112)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:285)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:76)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$77.00000000039BC4E0.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:118)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$98(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$76.00000000039BC030.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:410)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:118)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$75.00000000039BBB80.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:104)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$71.00000000055F7990.accept(Unknown Source)
	at java.util.ArrayList.forEach(ArrayList.java:1260)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:255)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:192)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:126)
	at MathTest.main(MathTest.java:26)
```

Running this in Eclipse with IBM J9 JRE, but Sun's Java JRE gives the same result. Since `args` resolves correctly, I'm assuming I've set things up in the right way. What am I missing?

**Comment by jlerbsc** [comment]
The original issue seems to be resolved now.

    
    @Test
    public void test() {
        
        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);

        String s = 
                "public class Test {\n" + 
                "    public static void main( String[] args )\n" + 
                "    {\n" + 
                "        System.out.println( Math.round( Math.random() * Integer.parseInt( args[0] ) ) );\n" + 
                "    }\n" + 
                "}";
        CompilationUnit cu = StaticJavaParser.parse(s);
        List<NameExpr>  nes = cu.findAll(NameExpr .class);
        nes.forEach(ne -> {
            System.out.println(( ne.calculateResolvedType().describe()));
        });
    }
    }

result

    java.lang.System
    java.lang.Math
    java.lang.Math
    java.lang.Integer
    java.lang.String[]
