### ISSUE TITLE
Resolve an enum that is imported statically causes a stackoverflow error

### ISSUE THREAD

**Issue by tanin47** [javaparser/javaparser#2083]
Here's a sample code:

```
package org.codelab.sample;

import static org.codelab.sample.Simple.SPACES;

public class Simple {
  public enum IndentType {
    SPACES
  }

  public IndentType c = SPACES;
}
```

A part of the stacktrace looks like this: 

```
at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:90)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.solveType(CombinedTypeSolver.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:104)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:130)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)
        at com.github.javaparser.symbolsolver.core.resolution.Context.solveSymbol(Context.java:61)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbol(SymbolSolver.java:60)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbol(SymbolSolver.java:64)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:113)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:160)
        at com.github.javaparser.ast.expr.NameExpr.resolve(NameExpr.java:170)
```

The interesting stacktrace line is `ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:64)`, which corresponds to the code below:

```
    @Override
    public SymbolReference<? extends ResolvedValueDeclaration> solveSymbol(String name) {
        if (typeSolver == null) throw new IllegalArgumentException();

        if (this.getDeclaration().hasVisibleField(name)) {
            return SymbolReference.solved(this.getDeclaration().getVisibleField(name));
        }

        // then to parent
        return getParent().solveSymbol(name);
    }
```

If I understand it correctly, `hasVisibleField(..)` won't return an Enum declaration. So, it invokes `getParent().solveSymbol(..)`, which, in turn, invokes the above method again.

I'm not sure how to fix it. If it's easy, please explain it to me. I'd love to help.

Thank you.

**Comment by matozoid** [comment]
@ftomassetti - can you give a push in the right direction?

**Comment by ftomassetti** [comment]
Probably the declaration should return the list of constants of contained enums. That is at least the first idea I would try

**Comment by tanin47** [comment]
> Probably the declaration should return the list of constants of contained enums

I've noticed that we can use `.getMembers()` and filter the members with `isTypeDeclaration()`. Is this what you meant? Thank you.

**Comment by jlerbsc** [comment]
This issue seems to be resolved

    public class Issue2083Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        
        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);

        String s = 
                "import static Simple.SPACES;\n" + 
                "public class Simple {\n" + 
                "  public enum IndentType {\n" + 
                "    SPACES\n" + 
                "  }\n" + 
                "  public IndentType c = SPACES;\n" + 
                "}";
        CompilationUnit cu = StaticJavaParser.parse(s);
        FieldDeclaration  fd = cu.findFirst(FieldDeclaration.class).get();
        assertEquals("Simple.IndentType", fd.resolve().getType().describe());
        
    }

    }
