### ISSUE TITLE
List with extra comma AND equal elements makes ModifierVisitor throw UnsupportedOperationException

### ISSUE THREAD

**Issue by myronmeier** [javaparser/javaparser#2124]
First off, thanks for the awesome project! Great work.

There is an unusual situation that causes `ModifierVisitor` to throw the following `UnsupportedOperationException` exception when doing lexical preservation:

```
Exception in thread "main" java.lang.UnsupportedOperationException: Csm token token(}) NodeText TOKEN ","   <99>   (line 19,col 60)-(line 19,col 60)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:466)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:141)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListReplacement(LexicalPreservingPrinter.java:218)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listReplacement(PropagatingAstObserver.java:82)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementReplaced$3(NodeList.java:474)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.notifyElementReplaced(NodeList.java:474)
	at com.github.javaparser.ast.NodeList.set(NodeList.java:147)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1078)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:255)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1111)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:117)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.expr.ArrayInitializerExpr.accept(ArrayInitializerExpr.java:72)
	at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$94(ModifierVisitor.java:975)
	at java.util.Optional.map(Optional.java:215)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:975)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:143)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1068)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:255)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1111)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:962)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:116)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:429)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:71)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1068)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:255)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1111)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:167)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
	at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$56(ModifierVisitor.java:618)
	at java.util.Optional.map(Optional.java:215)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:618)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:102)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1068)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:255)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1111)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:239)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:97)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1068)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:255)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1111)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:279)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:49)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:123)
	at ModifierVisitorTest.main(ModifierVisitorTest.java:14)
```

Here is some simple code that causes the exception:

```
public class ModifierVisitorTest {
  public static void main(String... args) throws IOException {
    ModifierVisitor<Void> modifier = new ModifierVisitor<>();
    CompilationUnit cu = JavaParser.parse(Paths.get("src/main/java/ModifierVisitorTest.java"));  // this file
    LexicalPreservingPrinter.setup(cu);
    cu.accept(modifier, null);
    System.out.println(LexicalPreservingPrinter.print(cu));
  }

  private void causesException() {
    String[] listWithExtraCommaAndEqualElements = {"a", "a",};
  }
}
```

The key ingredients seem to be the following:
1. Using `ModifierVisitor` with lexical preservation
2. Having a list (`listWithExtraCommaAndEqualElements` in the above) with an extra comma at the end
3. Having "equal" elements in that list ("equal" in the sense of `Object.equal()`)

Remove any one of those ingredients and the code above works fine with no exception and no loss of lexical detail (including that extra comma).

The problem seems to be specific to `ModifierVisitor` too. When I ran into this, I was trying to manipulate a different expression in a method with a list like that. Doing the manipulation without a `ModifierVisitor` (i.e. just modifying the AST) achieved the result I was after and had no exceptions or unexpected loss of lexical detail.

I debugged down to see if I could understand what was going on, but got pretty lost once I got down into the observer (below `NodeList.java:147`).

One thing I did notice that may be worth mentioning is in the following code in `ModifierVisitor`:

```
    public Visitable visit(NodeList n, A arg) {
        ...
            } else {
                final int i = n.indexOf(change.a);
                // If the user removed this item by hand, ignore the change.
                if (i != -1) {
                    n.set(i, change.b);
                }
            }
        ...
```

Specifically the `n.indexOf(change.a)`. I noticed that the code in `NodeList.indexOf` is doing an "equals" test (as in `Object.equals()`) and not an "identity equals" test (as in `==`). I don't know if that's right or wrong, but that appeared to cause the `ModifierVisitor` to think the 2nd equal element in a list was changed when it wasn't. For example, given the test list of `{"a", "a",}`, `i` was `0` for the 1st list element but it was also `0` for the 2nd list element, when I would have expected it to be `1`. The effect was that it looked like it was trying to change (via `n.set`) the 2nd element into the 1st. The 1st and 2nd elements are "equal" but they are not the same object.

Using the debugger, I forced `i` to be `1` in the above and it made the exception go away in this case, but a simple but totally valid change to the list made it come right back:

```
  private void causesException() {
    Object obj = new Object();
    Object[] listWithExtraCommaAndEqualElements = {obj, obj,};
  }
```

So perhaps `ModifierVisitor`'s reaction to the `NodeList.indexOf` equals vs. `==` behavior may not be related to the underlying cause, but might simply make the occurrence of it more probable. I thought I'd mention it, though, just in case it wasn't intended or is, in fact, related in a way I can't see.

This is using JavaParser 3.12.0. I tried 3.13.3 just to see, but the behavior was the same.

**Comment by matozoid** [comment]
Thanks for the great bug report! I'll what fixing the visit method does.
