### ISSUE TITLE
Deserializer Cast Problem

### ISSUE THREAD

**Issue by EndruK** [javaparser/javaparser#2182]
Hi there,
I got a problem on deserializing JSON ASTs.

```
import javax.json.Json;
import com.github.javaparser.ast.Node;
import com.github.javaparser.serialization.JavaParserJsonDeserializer;

import java.io.StringReader;

public class ASTToCode {
    public static void main(String[] args) {
        String json_string = "{\"!\":\"com.github.javaparser.ast.body.MethodDeclaration\",\"body\":{\"!\":\"com.github.javaparser.ast.stmt.BlockStmt\",\"statements\":[{\"!\":\"com.github.javaparser.ast.stmt.ExpressionStmt\",\"expression\":{\"!\":\"com.github.javaparser.ast.expr.VariableDeclarationExpr\",\"annotations\":[],\"modifiers\":[],\"variables\":[{\"!\":\"com.github.javaparser.ast.body.VariableDeclarator\",\"initializer\":{\"!\":\"com.github.javaparser.ast.expr.MethodCallExpr\",\"arguments\":[{\"!\":\"com.github.javaparser.ast.expr.LambdaExpr\",\"body\":{\"!\":\"com.github.javaparser.ast.stmt.ExpressionStmt\",\"expression\":{\"!\":\"com.github.javaparser.ast.expr.MethodCallExpr\",\"arguments\":[],\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"isArmed\"},\"scope\":{\"!\":\"com.github.javaparser.ast.expr.MethodCallExpr\",\"arguments\":[],\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"getModel\"},\"scope\":{\"!\":\"com.github.javaparser.ast.expr.NameExpr\",\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"button\"}}}}},\"isEnclosingParameters\":\"true\",\"parameters\":[]}],\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"execute\"}},\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"result\"},\"type\":{\"!\":\"com.github.javaparser.ast.type.ClassOrInterfaceType\",\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"Boolean\"},\"annotations\":[]}}]}},{\"!\":\"com.github.javaparser.ast.stmt.ReturnStmt\",\"expression\":{\"!\":\"com.github.javaparser.ast.expr.MethodCallExpr\",\"arguments\":[{\"!\":\"com.github.javaparser.ast.expr.NameExpr\",\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"result\"}}],\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"checkNotNull\"}}}]},\"type\":{\"!\":\"com.github.javaparser.ast.type.PrimitiveType\",\"type\":\"BOOLEAN\",\"annotations\":[]},\"modifiers\":[\"STATIC\"],\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"isArmed\"},\"parameters\":[{\"!\":\"com.github.javaparser.ast.body.Parameter\",\"annotations\":[{\"!\":\"com.github.javaparser.ast.expr.MarkerAnnotationExpr\",\"name\":{\"!\":\"com.github.javaparser.ast.expr.Name\",\"annotations\":[],\"identifier\":\"asd\"}}],\"isVarArgs\":\"false\",\"modifiers\":[\"FINAL\"],\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"button\"},\"type\":{\"!\":\"com.github.javaparser.ast.type.ClassOrInterfaceType\",\"name\":{\"!\":\"com.github.javaparser.ast.expr.SimpleName\",\"identifier\":\"AbstractButton\"},\"annotations\":[]},\"varArgsAnnotations\":[]}],\"thrownExceptions\":[],\"typeParameters\":[],\"annotations\":[{\"!\":\"com.github.javaparser.ast.expr.MarkerAnnotationExpr\",\"name\":{\"!\":\"com.github.javaparser.ast.expr.Name\",\"annotations\":[],\"identifier\":\"RunsInEDT\"}}]}";
        final JavaParserJsonDeserializer deserializer = new JavaParserJsonDeserializer();
        Node node = deserializer.deserializeObject(Json.createReader(new StringReader(json_string)));
    }
}
```
on this AST:
```
{"!":"com.github.javaparser.ast.body.MethodDeclaration","body":{"!":"com.github.javaparser.ast.stmt.BlockStmt","statements":[{"!":"com.github.javaparser.ast.stmt.ExpressionStmt","expression":{"!":"com.github.javaparser.ast.expr.VariableDeclarationExpr","annotations":[],"modifiers":[],"variables":[{"!":"com.github.javaparser.ast.body.VariableDeclarator","initializer":{"!":"com.github.javaparser.ast.expr.MethodCallExpr","arguments":[{"!":"com.github.javaparser.ast.expr.LambdaExpr","body":{"!":"com.github.javaparser.ast.stmt.ExpressionStmt","expression":{"!":"com.github.javaparser.ast.expr.MethodCallExpr","arguments":[],"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"isArmed"},"scope":{"!":"com.github.javaparser.ast.expr.MethodCallExpr","arguments":[],"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"getModel"},"scope":{"!":"com.github.javaparser.ast.expr.NameExpr","name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"button"}}}}},"isEnclosingParameters":"true","parameters":[]}],"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"execute"}},"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"result"},"type":{"!":"com.github.javaparser.ast.type.ClassOrInterfaceType","name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"Boolean"},"annotations":[]}}]}},{"!":"com.github.javaparser.ast.stmt.ReturnStmt","expression":{"!":"com.github.javaparser.ast.expr.MethodCallExpr","arguments":[{"!":"com.github.javaparser.ast.expr.NameExpr","name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"result"}}],"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"checkNotNull"}}}]},"type":{"!":"com.github.javaparser.ast.type.PrimitiveType","type":"BOOLEAN","annotations":[]},"modifiers":["STATIC"],"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"isArmed"},"parameters":[{"!":"com.github.javaparser.ast.body.Parameter","annotations":[{"!":"com.github.javaparser.ast.expr.MarkerAnnotationExpr","name":{"!":"com.github.javaparser.ast.expr.Name","annotations":[],"identifier":"Nonnull"}}],"isVarArgs":"false","modifiers":["FINAL"],"name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"button"},"type":{"!":"com.github.javaparser.ast.type.ClassOrInterfaceType","name":{"!":"com.github.javaparser.ast.expr.SimpleName","identifier":"AbstractButton"},"annotations":[]},"varArgsAnnotations":[]}],"thrownExceptions":[],"typeParameters":[],"annotations":[{"!":"com.github.javaparser.ast.expr.MarkerAnnotationExpr","name":{"!":"com.github.javaparser.ast.expr.Name","annotations":[],"identifier":"RunsInEDT"}}]}
```

This is the exception which is thrown
```
Exception in thread "main" java.lang.ClassCastException: class org.glassfish.json.JsonStringImpl cannot be cast to class javax.json.JsonObject (org.glassfish.json.JsonStringImpl and javax.json.JsonObject are in unnamed module of loader 'app')
	at com.github.javaparser.serialization.JavaParserJsonDeserializer.lambda$deserializeNodeList$2(JavaParserJsonDeserializer.java:129)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.serialization.JavaParserJsonDeserializer.deserializeNodeList(JavaParserJsonDeserializer.java:129)
	at com.github.javaparser.serialization.JavaParserJsonDeserializer.deserializeObject(JavaParserJsonDeserializer.java:91)
	at com.github.javaparser.serialization.JavaParserJsonDeserializer.deserializeObject(JavaParserJsonDeserializer.java:52)
	at ASTToCode.main(ASTToCode.java:11)
```

Here are also the dependencies I am using:
```
dependencies {
    compile 'com.github.javaparser:javaparser-symbol-solver-core:3.13.6'
    compile group: 'com.github.javaparser', name: 'javaparser-core-serialization', version: '3.13.6'
    compile group: 'javax.json', name: 'javax.json-api', version: '1.1.4'
    compile group: 'org.glassfish', name: 'javax.json', version: '1.1.4'
    testCompile group: 'junit', name: 'junit', version: '4.12'
}
```

The error output is not really helpful.
Am I doing something wrong? I followed the code of the tests [here](https://github.com/javaparser/javaparser/blob/master/javaparser-core-serialization/src/test/java/com/github/javaparser/serialization/JavaParserJsonDeserializerTest.java)

Thanks in advance.

**Comment by matozoid** [comment]
Hi! Looks like a class loading problem to me - there is a mention of modules, maybe check that?

**Comment by EndruK** [comment]
Hi,
Thank you Danny.
I figured out what was going wrong.
I used an older serialization of a Method there.

It seems that you changed a few things for some Nodes since then.

If you are curious: here the parts of diff from a new serialization compared to the AST I was using before:


- modifiers were just Attributes back then and are now Nodes:
```
"modifiers": [
  "STATIC"
]
```
became:
```
"modifiers": [
  {
    "!": "com.github.javaparser.ast.Modifier",
    "keyword": "STATIC"
  }
]
```

- Name annotations were removed
```
"name": {
  "!": "com.github.javaparser.ast.expr.Name",
  "annotations": [

  ],
  "identifier": "RunsInEDT"
}
```

However, there could be some more sophisticated exception message, stating which JSON Node caused a problem on deserialization.

Best regards,
André

**Comment by matozoid** [comment]
Ah, I should have seen that :-( When using the serializer for long time storage, be sure to have a process where you deserialize and serialize everything when you upgrade JP. AST changes happen more than you'd like.

For this issue the remaining work is then to create a better error message.
