### ISSUE TITLE
Resolution error when variable name equals type name

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#2192]
(from @v95)

I'm parsing a Java file using JavaParser (version 3.13.9) and encountering the following issue:

B.java contains the following code:
```java
    import org.json.simple.ItemList;
    ....
    {
        NodeList ItemList;
        ItemList = ...
        ItemList.getLength();
    }
```
When I get the MethodCallExpr for "ItemList.getLength()" and call ".resolve()" on it to get a reference, the following error is thrown:
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to ItemList.getLength()', cause='null'}
 
It appears that JavaParser is looking for "getLength()" inside the imported class ("org.json.simple.ItemList") instead of "NodeList" because both the imported class and the variable have the same name. The import is not being used in this code. Can anything be done to force JavaParser to correctly look at NodeList.getLength()?
 
Thank you!

**Comment by qingdujun** [comment]
I have this same problem.

Version 3.14.3

```java
CompilationUnit cu = StaticJavaParser.parse(new File(javaFileName));
for (MethodDeclaration mdc : cu.findAll(MethodDeclaration.class) ) {
	System.out.println(mdc.resolve().getQualifiedSignature());
}
```
error logs.
```
Exception in thread "main" UnsolvedSymbolException{context='null', name='TypeDeclaration', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:567)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:563)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:78)
	at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:61)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:71)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
```

```
Exception in thread "main" UnsolvedSymbolException{context='null', name='MethodDeclaration', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.lambda$convertToUsage$6(JavaParserFacade.java:514)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:514)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:567)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:563)
```

**Comment by jlerbsc** [comment]
This test case shows the issue. JP resolves the first method call expression (ItemList.get(0)) to the method defined in the class ItemList .

    @Test
    void test2192() {
        String code = "import com.github.javaparser.ast.NodeList;\n"
                + "\n"
                + "class A {\n"
                + "    public void m() {\n"
                + "        NodeList ItemList;\n"
                + "        ItemList = new NodeList();\n"
                + "        ItemList.get(0);\n"
                + "    }\n"
                + "    \n"
                + "    public static class ItemList {\n"
                + "        public String get(int i){\n"
                + "            return null;\n"
                + "        }\n"
                + "    }\n"
                + "}";
        TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver());
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(configuration);

        CompilationUnit cu = StaticJavaParser.parse(code);

        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        ResolvedMethodDeclaration rmd = mce.resolve();
        System.out.println(rmd.toString());
    }

**Comment by jlerbsc** [comment]
This issue seems to have been solved.

    @Test
	void test2192() {

		String code =
				"import org.json.simple.ItemList;\n"
				+ "class Foo {\n"
				+ "  void m() {\n"
				+ "        com.github.javaparser.ast.NodeList ItemList = null;\n"
				+ "        ItemList.size();\n"
				+ "   }\n"
				+ "}";

		final JavaSymbolSolver solver = new JavaSymbolSolver(new ReflectionTypeSolver(false));
		StaticJavaParser.getParserConfiguration().setSymbolResolver(solver);
		final CompilationUnit cu = StaticJavaParser.parse(code);

		List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
            System.out.println(mces.get(0).resolve().toString());

	}
