### ISSUE TITLE
javaparser  can not  recongnise       if else  statement

### ISSUE THREAD

**Issue by ZukGit** [javaparser/javaparser#2248]
jarfile : javaparser-core-3.2.8.jar
when I try run JavaParser.parse(new File(Test.java))   , it show exception like that 
```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 54,col 21) Parse error. Found "else", expected "}"
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10037)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:9893)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:3895)
  com.github.javaparser.GeneratedJavaParser.MethodDeclaration(GeneratedJavaParser.java:1297)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBodyDeclaration(GeneratedJavaParser.java:1006)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceBody(GeneratedJavaParser.java:899)
  com.github.javaparser.GeneratedJavaParser.ClassOrInterfaceDeclaration(GeneratedJavaParser.java:463)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:209)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:323)
  com.github.javaparser.JavaParser.parse(JavaParser.java:295)
  B8.main(B8.java:127)

        at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:327)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:295)
        at B8.main(B8.java:127)
```
Maybe  javaparser can not recongnise
```java
 if(randomInt < 5)
 intValue = randomInt;
 else
intValue = -10;
```
=================Test.java==========
```java
import java.util.ArrayList;
import java.util.Date;
import java.util.Random;

public class B8_Test {

    public static void main(String[] args) {
        int int1 = 1;
        int[] intArr = {9, 8, 7, 6, 5, 4, 3, 2, 1};
        String[] strArr = {"Z", "Y", "X", "V", "U"};
        ArrayList<Date> dateList = new ArrayList<Date>();
        long curTime = System.currentTimeMillis();
        dateList.add(new Date());
        dateList.add(new Date(curTime - 1000000000));
        dateList.add(new Date(curTime - 1500000000));
        dateList.add(new Date(curTime - 2000000000));
        method1(int1);
        method2(intArr);
        method3(strArr);
        method4(dateList);
    }

    static void method1(int value) {
        int randomInt = new Random().nextInt(10);
        int intValue = 0;
        if(randomInt < 5)
            intValue = randomInt;
        else
            intValue = -10;
        System.out.println("method1   intValue="+intValue);
    }

    static void method2(int[] value) {
        System.out.println("method2");
    }

    static void method3(String[] strArr) {
        System.out.println("method3");
    }

    static void method4(ArrayList<Date> dateList) {
        System.out.println("method4");
    }
}
```

**Comment by matozoid** [comment]
Hi! That seems unlikely.

Can you upgrade your version? It's about a year old.

**Comment by matozoid** [comment]
Works fine here.
