### ISSUE TITLE
Type resolution issue when type of formal parameter is Object

### ISSUE THREAD

**Issue by Shoreray** [javaparser/javaparser#2259]
Hi,

The method Expression.calculateResolvedType() throws an exception when 1) the expression is a method call, 2) the method has a formal parameter of type Object, and 3) the actual argument is an array.

This piece of code reproduces the error:
```
public class TestClass2 {

	public static void foo(Object o) {
		System.out.println("Verify execution."); // This line not necessary for reproducing the failure
	}

	public static void main(String[] args) {
		foo(new Object[5]);
	}
}
```
The stack trace looks like:
```
java.lang.UnsupportedOperationException: java.lang.Object java.lang.Object[]
	at com.github.javaparser.symbolsolver.logic.InferenceContext.registerCorrespondance(InferenceContext.java:165)
	at com.github.javaparser.symbolsolver.logic.InferenceContext.addPair(InferenceContext.java:58)
	at com.github.javaparser.symbolsolver.declarations.common.MethodDeclarationCommonLogic.resolveTypeVariables(MethodDeclarationCommonLogic.java:61)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.resolveTypeVariables(JavaParserMethodDeclaration.java:96)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveMethodAsUsage(Context.java:193)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:117)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:584)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:267)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:44)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:448)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:310)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:292)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:250)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:564)
```

**Comment by matozoid** [comment]
Thanks for the report!

**Comment by jlerbsc** [comment]
Do you consider an array of objects as an object?
This modified code works perfectly in javaparser 3.14.4

    public class TestClass2 {
	public static void foo(### Object[] o) {
		System.out.println("Verify execution."); // This line not necessary for reproducing the failure
	}
	public static void main(String[] args) {
		foo(new Object[5]);
	}
}

**Comment by Shoreray** [comment]
Right.
It seems that the failure occurs only when the type of the formal parameter is Object.

(It might look horrible to use arrays that way in the small example code, but the intent here is just to reproduce the failure with minimal amount of code.
The real code, with which I found the fault, is a commons-lang library function that manipulates arrays with reflection.)

**Comment by jlerbsc** [comment]
Does anyone know what the InferenceContext.registerCorrespondance(...) method should do in this case?

**Comment by matozoid** [comment]
Let's see if the oracle knows: @ftomassetti :-)
