### ISSUE TITLE
Lambda expression as variable not able to be printed out by using LexicalPreservingPrinter

### ISSUE THREAD

**Issue by au-hao** [javaparser/javaparser#2264]
Source code
```
public class Test {

    public static void main(String[] args) {
        String code = ""
                + "public class Test {\n"
                + "    public Record save(Record recordToSave) {\n"
                + "        return runDatabaseOperation(DatabaseOperation.SAVE, () -> repo.save(recordToSave));\n"
                + "    }\n"
                + "}";
        CompilationUnit parse = StaticJavaParser.parse(code);
        System.out.println(parse);
//        LexicalPreservingPrinter.setup(parse);

        List<MethodDeclaration> methodsByName = parse.getClassByName("Test").get()
                .getMethodsByName("save");

        Node x = methodsByName.get(0).getBody().get().getStatement(0)
                .getChildNodes().get(0);

        for (Node childNode : x.getChildNodes()) {
            if (childNode.toString().equals("() -> repo.save(recordToSave)")) {
                Node newNode = StaticJavaParser
                        .parseExpression("() -> repo.saveAll(recordType)");

                x.replace(childNode, newNode);
            }
        }

//        System.out.println(LexicalPreservingPrinter.print(parse));
        System.out.println(parse);
    }
}
```
It works well without using LexicalPreservingPrinter.

The bug will see after turning on LexicalPreservingPrinter:
```
Exception in thread "main" java.lang.IllegalArgumentException: I could not find child 'repo.saveAll(recordType);' in parent '() -> repo.saveAll(recordType)'. parentNodeText: NodeText{["("   <92>   (?)-(?), ")"   <93>   (?)-(?), " "   <1>   (?)-(?), "->"   <137>   (?)-(?), " "   <1>   (?)-(?), ChildTextElement{repo.saveAll(recordType)}]}
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.tokensPreceeding(LexicalPreservingPrinter.java:371)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findIndentation(LexicalPreservingPrinter.java:540)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.interpret(LexicalPreservingPrinter.java:473)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.prettyPrintingTextNode(LexicalPreservingPrinter.java:464)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.getOrCreateNodeText(LexicalPreservingPrinter.java:532)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.tokensPreceeding(LexicalPreservingPrinter.java:364)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findIndentation(LexicalPreservingPrinter.java:540)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.interpret(LexicalPreservingPrinter.java:473)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.prettyPrintingTextNode(LexicalPreservingPrinter.java:464)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.getOrCreateNodeText(LexicalPreservingPrinter.java:532)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:403)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.expand(ChildTextElement.java:41)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.lambda$expand$0(NodeText.java:196)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.printer.lexicalpreservation.NodeText.expand(NodeText.java:196)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:406)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.print(LexicalPreservingPrinter.java:391)
	at com.autonomic.mojo.Test.main(Test.java:39)
```

I would like to ask for the help to solve the issue above and the goal is to make it happen.  Thanks.

**Comment by matozoid** [comment]
Thanks! We're looking for someone to maintain this component.

**Comment by jlerbsc** [comment]
For the moment a workaround is to use
```java
    x.getParentNode().get().replace(childNode, newNode);
```
Output is 
```java
    public class Test {
    public Record save(Record recordToSave) {
        return runDatabaseOperation(DatabaseOperation.SAVE, () -> repo.save(recordToSave));
    }
}
```

**Comment by jlerbsc** [comment]
I think it's because StaticJavaParser.parseExpression(..) creates a LambdaExpr with an ExpressionStmt child that contains MethodCallExpr child but node data (from LambdaExpr) contains a child of type MethodCallExpr. So LexicalPreservingPrinter.tokensPreceeding(Node node) cannot find the matching field in 

    int index = parentNodeText.tryToFindChild(node);

and throw an exception

    throw new IllegalArgumentException(
                        String.format("I could not find child '%s' in parent '%s'. parentNodeText: %s",
                                node, node.getParentNode().get(), parentNodeText));

I think the question is : why LambdaExpr data contains a child of type CallMethodExpr or why StaticJavaParser.parseExpression generate a tree nodes LambdaExpr / ExpressionStmt / MethodCallExpr ?

**Comment by matozoid** [comment]
That I can answer: A `LambdaExpr`'s content is a statement. A `MethodCallExpr` is an expression. `ExpressionStmt` is used to wrap an expression when it is used as a statement.

**Comment by jlerbsc** [comment]
So probably LambdaExpr data (provided by method getData(..) ) must contain an element which is an ExpressionStmt that wrap MethodCallExpr but it seems it's not the case.

**Comment by matozoid** [comment]
I don't think data has any part in this? (Except for storing the resolution result for caching)

**Comment by jlerbsc** [comment]
Data contains an entry for the LexicalPreservingPrinter with a value which contains NodeText which is used by LexicalPreservingPrinter.tokensPreceeding method to find the index of the sub expression in the parent NodeText . If the index is not found and the parent node is not an VariableDeclarator then a IllegalArgumentException exception is thrown. In this case the parent node type is a ReturnStmt.

**Comment by matozoid** [comment]
Ah, I was confused with the symbol solver :-( I've got nothing then.

**Comment by 3dm1** [comment]
I'm running into this issue after deleting a method unrelated to the `LambdaExpr` (I'm parsing an already existing file), so the suggested workaround doesn't apply in my case. Are there any other suggestions aside from not using `LexicalPreservingPrinter`?

EDIT:
In fact, the printer fails even if I don't change the file at all, but still call `LexicalPreservingPrinter.print(compilationUnit, out);`

**Comment by jlerbsc** [comment]
This bug seems to be corrected in the current version. Do not hesitate to reopen this issue if you encounter your problem again.
