### ISSUE TITLE
Issue with adding annotation to FieldDeclaration

### ISSUE THREAD

**Issue by dtomassi** [javaparser/javaparser#2328]
I am trying to add annotations to fields of classes. I am encountering an error, which is shown in the "Error" snippet. Below is the code for adding the annotation to field, the file("Input") which I am trying to modify, and the error.

Let me know if y'all have any thoughts on the error. Thanks!

Code:
```
public static void addFieldAnnotations(CompilationUnit cu) {
    cu.findAll(FieldDeclaration.class).forEach(fd -> {
        fd.addAnnotation(new MarkerAnnotationExpr("Nullable"));
    });
}
```
Input:
```
public class HelloWorld {
    private Object o;
    public HelloWorld() {
    }

    public static void main(String[] args) {
        HelloWorld h = new HelloWorld();
    }
}
```
Error:
```
Exception in thread "main" java.lang.UnsupportedOperationException: kept child(ClassOrInterfaceType) vs "Object"   <89>   (line 2,col 10)-(line 2,col 15)
        at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:454)
        at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:142)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:274)
        at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
        at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:466)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:466)
        at com.github.javaparser.ast.NodeList.add(NodeList.java:70)
        at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addAnnotation(NodeWithAnnotations.java:59)
        at com.github.dtomassi.AnnotationAdder.lambda$addFieldAnnotations$2(AnnotationAdder.java:128)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.dtomassi.AnnotationAdder.addFieldAnnotations(AnnotationAdder.java:127)
        at com.github.dtomassi.AnnotationAdder.addAnnotations(AnnotationAdder.java:93)
        at com.github.dtomassi.AnnotationAdder.main(AnnotationAdder.java:54
```

**Comment by edefazio** [comment]
I think this is an issue purely with the LexicalPreservingPrinter (sometimes the bookkeeping seems to get messed up when you parse and then make changes).

If you can parse the input without using the LexicalPreservingPrinter (i.e. just using the StaticJavaParser) you should be fine

I just ran this:
````java

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.FieldDeclaration;
import com.github.javaparser.ast.expr.MarkerAnnotationExpr;
import junit.framework.TestCase;
import org.jdraft.Ast;

public class AddAnnotationToField extends TestCase {

    public void testA(){
        class HelloWorld {
            private Object o;
            public HelloWorld() {
            }

            public void main(String[] args) {
                HelloWorld h = new HelloWorld();
            }
        }

        CompilationUnit cu = Ast.of(HelloWorld.class);

        System.out.println( cu );

        cu.findAll(FieldDeclaration.class).forEach(fd -> {
            fd.addAnnotation(new MarkerAnnotationExpr("Nullable"));
        });
        System.out.println( cu );
    }
}
````
and got this back:
````java
public class HelloWorld {

    @Nullable
    private Object o;

    public HelloWorld() {
    }

    public void main(String[] args) {
        HelloWorld h = new HelloWorld();
    }
}
````

**Comment by dtomassi** [comment]
@edefazio That solution works for me. Thank you for your help!

**Comment by jlerbsc** [comment]
@dtomassi , i cannot reproduce your issue with javaparser 3.14.6. Could you share your version?

**Comment by dtomassi** [comment]
@jlerbsc I am using `javaparser-core` version `3.14.9` from via maven.

**Comment by jlerbsc** [comment]
This issue is not reproducible with JP 3.16.3

    public class Issue2328Test {
    @Test
    public void test() {
        String code = 
                "public class HelloWorld {\n" + 
                "    private Object o;\n" + 
                "    public HelloWorld() {\n" + 
                "    }\n" + 
                "\n" + 
                "    public static void main(String[] args) {\n" + 
                "        HelloWorld h = new HelloWorld();\n" + 
                "    }\n" + 
                "}";
        
        StaticJavaParser.setConfiguration(new ParserConfiguration());
      
        CompilationUnit cu = StaticJavaParser.parse(code);
        
        cu.findAll(FieldDeclaration.class).forEach(fd -> {
            fd.addAnnotation(new MarkerAnnotationExpr("Nullable"));
        });
        
        System.out.println(cu.toString());
    }
    }

result

    public class HelloWorld {

    @Nullable
    private Object o;

    public HelloWorld() {
    }

    public static void main(String[] args) {
        HelloWorld h = new HelloWorld();
    }
}
