### ISSUE TITLE
Stackoverflow at JavaParserTypeDeclarationAdapter.checkAncestorsForType

### ISSUE THREAD

**Issue by liiri** [javaparser/javaparser#2349]
I'm running some java parsing on arbitrary github repositories and came across the following. I had this reproduced for a few repos.

Version: 3.14.11
Steps to reproduce:

Clone https://github.com/NCATS-Tangerine/beacon-aggregator
I've cloned it at `Developer` today, for reference, that is head on `d3071da621181d2bdaa5d15f9fd467b080e4c530`.

Set up type solver for repo:

```
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());

        Files.walk(root)
            .filter(Files::isDirectory)
            .forEach(folder -> combinedTypeSolver.add(new JavaParserTypeSolver(folder.toString())));

        return combinedTypeSolver;
```

Then attempt to parse the extending type of `bio.knowledge.aggregator.ontology.Ontology`.

Code snippet:

```
package bio.knowledge.aggregator.ontology;
...
public class Ontology extends bio.knowledge.ontology.Ontology {
...
```

The Stackoverflow trace:

```
java.lang.StackOverflowError
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1012)
	at java.base/java.util.concurrent.ConcurrentHashMap.putIfAbsent(ConcurrentHashMap.java:1541)
	at java.base/java.lang.ClassLoader.getClassLoadingLock(ClassLoader.java:667)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:593)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.ClassLoaderTypeSolver.tryToSolveType(ClassLoaderTypeSolver.java:67)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.ClassLoaderTypeSolver.tryToSolveType(ClassLoaderTypeSolver.java:85)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:217)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:142)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveType(JavaParserClassDeclaration.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.toReferenceType(JavaParserClassDeclaration.java:413)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getSuperClass(JavaParserClassDeclaration.java:177)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:303)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:82)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:101)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:101)
...
```

I verified using debugger that the reason for infinite loop is indeed that `declaration == ancestor.getTypeDeclaration()` in the recursive call.

I know that the code in the repo does not compile and is probably not meant to, as its a develop branch. The same code is stable in master.

I still guess it would be best for parser not to stackoverflow on broken code :)

**Comment by matozoid** [comment]
Thanks!

**Comment by jlerbsc** [comment]
I don't know if it could resolve your issue but i JavaParserTypeSolver must be instanciated with source folder only.

**Comment by liiri** [comment]
@jlerbsc what do you mean? Only root folder? Or only folders that contain .java files? What's the harm in irrelevant folders?

**Comment by jlerbsc** [comment]
Only root folders that contain .java files for example <rootdir>/src/main/java for every sub module.

**Comment by jlerbsc** [comment]
Seems to be related to the issue #2050 . It cannot be reproduced with javaparser 3.16.1

**Comment by jlerbsc** [comment]
This issue is already resolved 

    public class Issue2349Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {
        final Path testRoot = adaptPath("src/test/resources/issue2349");
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(testRoot);
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver, javaParserTypeSolver);
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver));
        StaticJavaParser.setConfiguration(configuration);

        String src = "public class A extends a.A {\n" +
                "\n" +
                "}";

        CompilationUnit cu = StaticJavaParser.parse(src);

        List<TypeDeclaration<?>> tds = cu.getTypes();
        assertEquals("a.A",tds.get(0).resolve().getAllAncestors().get(0).describe());
    }
    }

with class

    package a;
    public class A {    }
