### ISSUE TITLE
Unable to calculate the type of a varargs parameter.

### ISSUE THREAD

**Issue by gpr-indevelopment** [javaparser/javaparser#2368]
I have received an exception when trying to symbol solve the following method:

```
public void execute(final ComponentBase _this) {
        String regexText = null;
        String functionName = "getRegexValues";
	final ObjectContext scemAdapter = _this.getChildByAlias("scem_adapter");
        final Integer outputIdx = scemAdapter.getListString("NWT_RESULTADO_TEXT").indexOf("asyn");
        if (outputIdx >= 0) {
            String outpuText = scemAdapter.getListString("NWT_RESULTADO_TEXT_VALUE").get(outputIdx);
	}
	_this.getParent().set("NWT_RESULTADO_INERCIA", _this.getRoot().executeMethod(functionName,regexText,outpuText,1));
}
```

```
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: _this.getParent().set("NWT_RESULTADO_IEC_ETA_100", _this.getRoot().executeMethod(functionName, regexText, outpuText, 5)), Parameter: _this.getRoot().executeMethod(functionName, regexText, outpuText, 5)
```

The class referenced by `_this` is `ComponentBase.class`, that extends `ObjectContext.class`. Both classes can be found inside a jar file that I added to my `CombinedTypeSolver` via `JarTypeSolver`. I have also added a `new ReflectionTypeSolver()` to the configuration. The method `executeMethod` can be found in `ObjectContext.class` (retrieved by the `getRoot()` method) has the following signature:

```
public Object executeMethod(String methodName, Object... values) {
        //...
}
```

The same exception was thrown on other java files whenever `executeMethod` was called. Since both dependencies were correctly added to the `CombinedTypeSolver`, I wonder:

- Is the symbol solver capable of tracing the reference of a method that takes varargs as a parameter?
- Are there any other reasons of why this might be occurring? Am I missing something?

**Comment by jlerbsc** [comment]
Could you give us the stack trace generated?

**Comment by gpr-indevelopment** [comment]
@jlerbsc sure thing! Here it is:

```
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: _this.getParent().set("NWT_RESULTADO_IEC_ETA_100", _this.getRoot().executeMethod(functionName, regexText, outpuText, 5)), Parameter: _this.getRoot().executeMethod(functionName, regexText, outpuText, 5)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:225)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:240)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:140)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at net.weg.parserpoc.parser.RuleStatisticsDTO.processMethod(RuleStatisticsDTO.java:27)
	at net.weg.parserpoc.parser.JavaParser.lambda$insertMethodsToDTO$0(JavaParser.java:29)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.weg.parserpoc.parser.JavaParser.insertMethodsToDTO(JavaParser.java:29)
	at net.weg.parserpoc.parser.JavaParser.findMethodCallsOn(JavaParser.java:24)
	at net.weg.parserpoc.Programs.lambda$findMethodCalls$0(Programs.java:41)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.weg.parserpoc.Programs.findMethodCalls(Programs.java:41)
	at net.weg.parserpoc.Programs.init(Programs.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.RuntimeException: Method 'executeMethod' cannot be resolved in context _this.getRoot().executeMethod(functionName, regexText, outpuText, 1) (line: 144) MethodCallExprContext{wrapped=_this.getRoot().executeMethod(functionName, regexText, outpuText, 1)}. Parameter types: [ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='int'}]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:587)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:267)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:44)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:448)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:310)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:221)
	... 43 more
```

**Comment by jlerbsc** [comment]
It's not related to varargs (in version 3.14.14) because this test case runs 

    void methodWithVarargsResolution() {
        // configure symbol solver before parsing
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        CompilationUnit cu = StaticJavaParser.parse("class A {" +
                "public void execute() { executeMethod(\"a\",\"\",1); }" +
                "public Object executeMethod(String methodName, Object... values) { return null; }" + 
                "}");
        Optional<MethodCallExpr> mce = cu.findFirst(MethodCallExpr.class);
        assertTrue(mce.isPresent());
        ResolvedMethodDeclaration resolved = mce.get().resolve();
    }

Could you share with us a test case please?

**Comment by gpr-indevelopment** [comment]
I have built a test case on one of many big classes inside the project I am running the analysis on. The `config` object is a class of mine that contains a whole bunch of .jar files, and returns a JavaSymbolSolver made out of a CombinedTypeSolver that contains some JarTypeSolvers. All JarTypeSolvers are built with `JarTypeSolver.getJarTypeSolver(path)`.

Unfortunately I cannot include the .jar files I am using for this symbol solving. I hope this is enough. Please let me know if it is not, or if there is another way of providing the necessary info.

```
@Test
public void varArgsTypeSolving() throws IOException {
    StaticJavaParser.getConfiguration().setSymbolResolver(config.getSolver());
    CompilationUnit cu = StaticJavaParser.parse(new File("src/test/resources/VarArgsBug.java"));
    List<MethodCallExpr> calledExpr = cu.findAll(MethodCallExpr.class);
    try{
        for (MethodCallExpr call : calledExpr) {
            String qualifiedSignature = call.resolve().getQualifiedSignature();
        }
    }
    catch (Exception e){
        e.printStackTrace();
    }
}
```
[VarArgsBug.zip](https://github.com/javaparser/javaparser/files/3626143/VarArgsBug.zip)

**Comment by jlerbsc** [comment]
Could you simplify your test case VarArgsBug.java and provide and simple version of the class ComponentBase and others classes .

**Comment by jlerbsc** [comment]
@gpr-indevelopment I'm not sure but i think your issue is caused by a wrong configuration.
In your case, you have to add a JarTypeSolver for each library (absolute path), a ReflectionTypeSolver, and a JavaParserTypeSolver for each source dir (absolute path). All that is needed to resolve dependency from libraries, others sources, and jdk classes. Could you confirm this configuration?

**Comment by matozoid** [comment]
(remark: it's quite an unhelpful error message if that is the problem)

**Comment by jlerbsc** [comment]
You are right! But without a simple and clear test class which can reproduce this issue it's difficult to help to resove it. First test class show that SymbolSolver understand varargs as a parameter and resolve it.

**Comment by gpr-indevelopment** [comment]
The classes referenced by `_this` and `_this.getRoot()` are inside a relatively big hierarchy tree, and hence it will demand me some time to simplify like you mentioned, with all dependencies fullfilled.

The java class I originally posted on this thread (first post) is actually a simplified version of VarArgsBug.java.

MaestroSolverConfig.zip contains the class I am using to inject my `JavaSymbolSolver`. Please take a look... I believe I have configured correctly.

[MaestroSolverConfig.zip](https://github.com/javaparser/javaparser/files/3630944/MaestroSolverConfig.zip)

**Comment by jlerbsc** [comment]
I think buildCombinedTypeSolver(..) should contain a JavaParserTypeSolver("<sourceDir>") declaration to resolve dependencies in the project sources.
with sourceDir point to the source directory (without package)
Could you verify that properties (for example maestroPath ) point really to a jar file not a folder.
Where do you set SymbolResolver in ParserConfiguration (to create an instance of parser with the specified configuration)?

**Comment by gpr-indevelopment** [comment]
- I think buildCombinedTypeSolver(..) should contain a JavaParserTypeSolver("") declaration to resolve dependencies in the project sources, with sourceDir point to the source directory (without package).

R: You mean create a `JavaParserTypeSolver` pointed to my own project's path? I am only analyzing classes that are outside of the project (inside a database). If I use `JavaParserTypeSolver`, pointed to a source directory, will JavaParser retrieve all dependencies of that project? Including maven dependencies?

- Could you verify that properties (for example maestroPath ) point really to a jar file not a folder?

R: Added `JarImports.jpg` with the paths I have used for the .jar files.

- Where do you set SymbolResolver in ParserConfiguration (to create an instance of parser with the specified configuration)?

R: The class (MaestroSolverConfig.java) I sent you has a `JavaSymbolSolver` solver property. I use it's getter method to retrieve it, and insert to the `StaticJavaParser` like so:

```
StaticJavaParser.getConfiguration().setSymbolResolver(config.getSolver());
```

**Comment by jlerbsc** [comment]
You only need JavaParserTypeSolver if you have to analyse source files too.
The config seems to be ok. I have to write a test case.

**Comment by jlerbsc** [comment]
Is it right?

    public class ObjectContext {
        public Object executeMethod(String methodName, Object... values) {
            return null;
        }
    }

    public class ComponentBase extends ObjectContext {
        ObjectContext root;
        public ObjectContext getRoot() {
            return root;
        }
    }

    public class A {
        public void execute(final ComponentBase _this) {
            _this.getRoot().executeMethod("functionName","regexText","outpuText",1);
        }
    }

**Comment by jlerbsc** [comment]
@Test
    void methodWithVarargsResolution2() throws FileNotFoundException {
     // configure symbol solver before parsing
        String sourceDir = "C:\\Users\\xxx\\Downloads\\MaestroSolverConfig";
        CombinedTypeSolver combined = new CombinedTypeSolver();
        combined.add(new JavaParserTypeSolver(sourceDir));
        combined.add(new ReflectionTypeSolver());
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(combined));
        CompilationUnit cu = StaticJavaParser.parse(new FileInputStream(sourceDir+File.separator+"A.java"));
        Optional<MethodCallExpr> mce = cu.findFirst(MethodCallExpr.class);
        assertTrue(mce.isPresent());
        ResolvedMethodDeclaration resolved = mce.get().resolve();
        System.out.println(""+resolved.getQualifiedName());
    }

display

    ObjectContext.executeMethod

**Comment by jlerbsc** [comment]
I reproduce the issue when i package all source files in a jar. So it's more simpler to see whta's happen.

**Comment by jlerbsc** [comment]
Could you tell us if jar files contain java files or class files?

**Comment by gpr-indevelopment** [comment]
@jlerbsc I tried to build the classes here to test it, and could not replicate the error... there might be something going on with the original .jar. You example looks correct, but there is an intermediate class, called ObjectContextDecorator:

```
public class ObjectContext {
    public Object executeMethod(String methodName, Object... values) {
        return null;
    }
}

public class ObjectContextDecorator extends ObjectContext {
    ObjectContext root;
    public ObjectContext getRoot() {
        return root;
    }
}

public class ComponentBase extends ObjectContextDecorator {
   
}

public class A {
    public void execute(final ComponentBase _this) {
        _this.getRoot().executeMethod("functionName","regexText","outpuText",1);
    }
}
```

**Comment by jlerbsc** [comment]
i can only reproduce your issue if the jar file contains only java sources that is not what is expected.

**Comment by gpr-indevelopment** [comment]
I see... if there is something missing in the jar file, should'nt the exception's message show something that leads us to it? Something it could not resolve?

**Comment by jlerbsc** [comment]
Something like this 

    Unable to calculate the type of a parameter of a method call. Method call: _this.getParent().set("NWT_RESULTADO_IEC_ETA_100", _this.getRoot().executeMethod(functionName, regexText, outpuText, 5))

**Comment by gpr-indevelopment** [comment]
Ya but, all I know from this message is that there is a parameter of this method call, that the solver could not calculate. Sometimes there is a nested method call (like in this case)... This was informed:

```
Parameter: _this.getRoot().executeMethod(functionName, regexText, outpuText, 5)
```
But, I am not able to tell which part of the nested method call is throwing the exception: It could be getRoot(), executeMethod, or something inside it. It's just a suggestion.

Since I could not replicate the scenario with a test case for you guys, I believe we can close the issue. Thank you for all the help you've been giving me.

**Comment by matozoid** [comment]
@gpr-indevelopment - we have a you-open-it-you-close-it policy ;-)

**Comment by hezhou66** [comment]
Has this issue been fixed? I have the same problem on version 3.25.9

**Comment by hezhou66** [comment]
![image](https://github.com/javaparser/javaparser/assets/4961665/f3baf2d2-f65c-499b-ac91-3ee8c730296e)
![image](https://github.com/javaparser/javaparser/assets/4961665/df420074-df25-4021-ac7b-327ca15a5747)

**Comment by jlerbsc** [comment]
To reopen this issue and allow us to work on it, please provide us with a simple test case that reproduces the problem.

**Comment by hezhou66** [comment]
I don't have permission to reopen，  I have debuged to find the code position：
![image](https://github.com/javaparser/javaparser/assets/4961665/18e647c1-2ec4-4693-90a1-f8caf8e47884)
![image](https://github.com/javaparser/javaparser/assets/4961665/7362cd47-ecc2-41b8-8adb-2d2f8cc5f2a6)
Are the definition and implementation of this method reversed in class ReferenceTypeImpl？

**Comment by hezhou66** [comment]
![image](https://github.com/javaparser/javaparser/assets/4961665/abbab00c-059d-4f6d-9dc7-8afbf08de2bf)
![image](https://github.com/javaparser/javaparser/assets/4961665/1f1fe5d9-5c77-42fb-8c76-9c3864400eec)
test case is like this

**Comment by jlerbsc** [comment]
What we need before we can reopen this issue is for you to provide us with a simple test case that reproduces the problem.
This simplistic example does not reproduce the issue.


    @Test
	void issue2368() {
		JavaParserAdapter parser = new JavaParserAdapter(new JavaParser());
        parser.getParserConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        CompilationUnit cu = parser.parse(
        		"class Foo {\n"
        		+ "		void main() {\n"
        		+ "			Foo foo = new Foo();\n"
        		+ "			foo.m(null);\n"
        		+ "		}\n"
        		+ "		void m(String message, Object... args) {}\n"
        		+ "		void m(Object args) {}\n"
        		+ "	}"
        );
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        System.out.println(mce);
        ResolvedMethodDeclaration mrd = mce.resolve();
        System.out.println(mrd.getQualifiedSignature());
	}

**Comment by hezhou66** [comment]
I don’t know how to write a simple test case to get to the problematic code branch. But I debugged and found the problematic code snippet. Mainly in this class ‘MethodResolutionLogic’ . There are two  methods with similar functionality 
 named 'isMoreSpecific'.  One of them has parameter number judgment, and the other one does not，the latter resulted in an array out-of-bounds exception.
![image](https://github.com/javaparser/javaparser/assets/4961665/a2a31afe-b839-4a36-a71f-f8de38e9c70a)
![image](https://github.com/javaparser/javaparser/assets/4961665/dbc0c8cd-b9c9-44e7-b664-8a1790b079be)
![image](https://github.com/javaparser/javaparser/assets/4961665/179b936e-5efe-4752-823a-e2130d5cb0fb)


[jlerbsc] Your use case takes another ‘isMoreSpecific’ mothed witch Judged the number of parameters
![image](https://github.com/javaparser/javaparser/assets/4961665/163d291e-7b40-47c5-aa7a-1ce90624bec5)

**Comment by jlerbsc** [comment]
It's difficult to fix a problem that can't be reproduced, but I don't understand why the code contains 2 different implementations of the same function. I'm going to simplify this. Perhaps this modification will correct your problem.

**Comment by jlerbsc** [comment]
@hezhou66  Please let us know if the latest modification has been helpful in your case.

**Comment by hezhou66** [comment]
@jlerbsc  It's  helpful , thks
