### ISSUE TITLE
Symbol solver fails to solve generic array type

### ISSUE THREAD

**Issue by iTakeshi** [javaparser/javaparser#2406]
I tried to solve the signatures of MethodCallExpr, and got `java.lang.UnsupportedOperationException`.
OS is Linux, run on java 11.0.5, JavaParser version is 3.15.3.

Target code snippet is:
```java
// Main.java
// This is basically a copy of java.util.Arrays.copyOf()

import java.lang.reflect.Array;

public class Main {
    public static <T, U> T[] copyOf(U[] original, int newLength, Class<? extends T[]> newType) {
        @SuppressWarnings("unchecked")
        T[] copy = ((Object) newType == (Object)Object[].class)
            ? (T[]) new Object[newLength]
            : (T[]) Array.newInstance(newType.getComponentType(), newLength);
        System.arraycopy(original, 0, copy, 0, Math.min(original.length, newLength));
        return copy;
    }

    public static void main(String[] args) {
        String[] source = {"a", "b", "c"};
        String[] target = copyOf(source, 2, source.getClass());
        for (String e : target) System.out.println(e);
    }
}
```
And this worked properly.
```sh
$ javac Main.java
$ java Main
a
b
```

JavaParser implementation is:
```java
// Visitor.java

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import java.io.File;
import java.util.Map;


public class Visitor {

    public static class VisitorImpl extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(final MethodCallExpr n, Void arg) {
            System.out.println("================");
            System.out.println(n);
            System.out.println(n.resolve().getQualifiedSignature());
        }
    }

    public static void main(String[] args) throws Exception {
        StaticJavaParser.getConfiguration()
            .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_11)
            .setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        final CompilationUnit cu = StaticJavaParser.parse(new File("Main.java"));
        final VisitorImpl visitor = new VisitorImpl();
        visitor.visit(cu, null);
    }

}
```
And it failed to resolve the callee of the `copyOf` method called in the `Main.main`:
```sh
$ CLASSPATH=~/.m2/repository/com/github/javaparser/javaparser-core/3.15.3/javaparser-core-3.15.3.jar:~/.m2/repository/com/github/javaparser/javaparser-symbol-solver-core/3.15.3/javaparser-symbol-solver-core-3.15.3.jar:~/.m2/repository/com/github/javaparser/javaparser-symbol-solver-model/3.15.3/javaparser-symbol-solver-model-3.15.3.jar javac Visitor.java
$ CLASSPATH=.:~/.m2/repository/com/github/javaparser/javaparser-core/3.15.3/javaparser-core-3.15.3.jar:~/.m2/repository/com/github/javaparser/javaparser-symbol-solver-core/3.15.3/javaparser-symbol-solver-core-3.15.3.jar:~/.m2/repository/com/github/javaparser/javaparser-symbol-solver-model/3.15.3/javaparser-symbol-solver-model-3.15.3.jar:~/.m2/repository/com/github/javaparser/javaparser-symbol-solver-logic/3.15.3/javaparser-symbol-solver-logic-3.15.3.jar java Visitor
================
Array.newInstance(newType.getComponentType(), newLength)
java.lang.reflect.Array.newInstance(java.lang.Class<? extends java.lang.Object>, int)
================
System.arraycopy(original, 0, copy, 0, Math.min(original.length, newLength))
java.lang.System.arraycopy(java.lang.Object, int, java.lang.Object, int, int)
================
copyOf(source, 2, source.getClass())
Exception in thread "main" java.lang.UnsupportedOperationException: com.github.javaparser.resolution.types.ResolvedArrayType com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isAssignableMatchTypeParameters(MethodResolutionLogic.java:146)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isAssignableMatchTypeParametersMatchingQName(MethodResolutionLogic.java:201)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isAssignableMatchTypeParameters(MethodResolutionLogic.java:153)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isApplicable(MethodResolutionLogic.java:109)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.lambda$findMostApplicable$3(MethodResolutionLogic.java:372)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:373)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:354)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:154)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:111)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveMethod(JavaParserClassDeclaration.java:292)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:616)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:154)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:242)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:140)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Visitor$VisitorImpl.visit(Visitor.java:19)
	at Visitor$VisitorImpl.visit(Visitor.java:14)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:121)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$175(VoidVisitorAdapter.java:573)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:573)
	at com.github.javaparser.ast.body.VariableDeclarator.accept(VariableDeclarator.java:149)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$173(VoidVisitorAdapter.java:567)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:268)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:567)
	at com.github.javaparser.ast.expr.VariableDeclarationExpr.accept(VariableDeclarationExpr.java:122)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:259)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:77)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$19(VoidVisitorAdapter.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:268)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:109)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:76)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$104(VoidVisitorAdapter.java:369)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:369)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:106)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$31(VoidVisitorAdapter.java:154)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:268)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:154)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:100)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$43(VoidVisitorAdapter.java:175)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:268)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
	at Visitor.main(Visitor.java:29)
```

Using jdb, I investigated the local variables in the `isAssignableMatchTypeParameters` method, and found a mismatch between actual and expected types like following.
```
main[1] where
  [1] com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isAssignableMatchTypeParameters (MethodResolutionLogic.java:146)
  [2] com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isAssignableMatchTypeParametersMatchingQName (MethodResolutionLogic.java:201)
  [3] com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isAssignableMatchTypeParameters (MethodResolutionLogic.java:153)
~~~snip~~~

main[1] locals
Method arguments:
expected = instance of com.github.javaparser.resolution.types.ResolvedArrayType(id=2178)
actual = instance of com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl(id=2179)
matchedParameters = instance of java.util.HashMap(id=2180)
Local variables:
main[1] print expected
 expected = "ResolvedArrayType{TypeVariable {JPTypeParameter(T, bounds=[])}}"
main[1] print actual
 actual = "ReferenceType{java.lang.Class, typeParametersMap=TypeParametersMap{nameToValue={java.lang.Class.T=WildcardUsage{type=EXTENDS, boundedType=ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}}"
```

Is this a bug in the library? Or, how can I fix it up?
(Perhaps #2397 is related to this, but I'm not sure.)

Thanks for your help!

**Comment by matozoid** [comment]
Thanks for the report!
