### ISSUE TITLE
Problem resolving MethodDeclaration from MethodCallExpr

### ISSUE THREAD

**Issue by Milkaselnuss** [javaparser/javaparser#2459]
Hey there,

I would like to be able to count all called methods for a class. Currently all methods of the class and one layer of external calls is working. So if a method calls a method of another class this method is correctly counted. However, if that method of another class also calls methods, I want to count these aswell and that does not work because an Exception is thrown: `java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.` when trying to resolve the expression.

My current code and and example below:
```
// methods = all methods of the class. In this case all methods of TestClassA so only m1

Set<MethodDeclaration> calledMethods = new HashSet<MethodDeclaration>(methods);
ArrayDeque<MethodDeclaration> todo = new ArrayDeque<MethodDeclaration>(methods);

while(!todo.isEmpty()) {
    MethodDeclaration m = todo.poll();

    for (MethodCallExpr expr : m.findAll(MethodCallExpr.class)) {
        ResolvedMethodDeclaration rmd = expr.resolve();

        if (rmd instanceof JavaParserMethodDeclaration) {
            JavaParserMethodDeclaration jpmd = (JavaParserMethodDeclaration) rmd;
	    MethodDeclaration mdec = jpmd.getWrappedNode();
	
	    if (!calledMethods.containts(mdec)) {
                calledMethods.add(mdec);
                todo.add(mdec);
            }
        }
    }
}

return calledMethods.size();
```

example :
```
public class TestClassA {
    public void m1() {
	new TestClassB().useAll();
    }
}

public class TestClassB {
    public void useAll() {
        m2();
    }

    public void m2() {
        m3();
    }

    public void m3() { /* does nothing */ }
}
```

I want to count the amount of called methods. So my expected result for TestClassA would be 4 (m1, useAll, m2 and m3). Currently the result is 2 (m1 and useAll). The Exception is thrown when trying to get all called methods from useAll, so `m = useAll()` and `expr = m2()`. Then `expr.resolve()` results in the IllegalStateException.

Any ideas?

**Comment by matozoid** [comment]
Hi! This is a problem with your symbol solver setup. The node you are trying to resolve does not know which typesolver to use. That probably means you parsed the tree without configuring the symbol solver on it.

**Comment by matozoid** [comment]
Here is a sample setup: https://github.com/javaparser/javasymbolsolver-maven-sample

**Comment by Milkaselnuss** [comment]
Thanks for the fast reply. I thought I would already do that using the SymbolSolverCollectionStrategy on the whole project.

So basically what I am doing is the following which I thought would be sufficient:

```
ProjectRoot projectRoot = new SymbolSolverCollectionStrategy().collect(pathOfProject);

for (SourceRoot sourceRoot : projectRoot.getSourceRoots()) {
    sourceRoot.getParserConfiguration().setAttributeComments(false); // Ignore comments

    try {
        for (ParseResult<CompilationUnit> r : sourceRoot.tryToParse()) {
	    r.getResult().ifPresent(compilationUnit ->
	        for (ClassOrInterfaceDeclaration c : compilationUnit.findAll(ClassOrInterfaceDeclaration.class)){

                    /* call the above routine to count the amount of methods called from class c */
                }
            });
        }
    } catch (IOException e) { }
}
```

**Comment by matozoid** [comment]
I put the snippets together (please supply working code so people don't have to do this) into this:

```java
package com.github.javaparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration;
import com.github.javaparser.symbolsolver.utils.SymbolSolverCollectionStrategy;
import com.github.javaparser.utils.ProjectRoot;
import com.github.javaparser.utils.SourceRoot;

import java.io.IOException;
import java.nio.file.Paths;
import java.util.ArrayDeque;
import java.util.HashSet;
import java.util.Set;

public class Bla {
    public static void main(String[] args) throws IOException {
        
        ProjectRoot projectRoot = new SymbolSolverCollectionStrategy().collect(Paths.get("").toAbsolutePath());

        for (SourceRoot sourceRoot : projectRoot.getSourceRoots()) {
            sourceRoot.getParserConfiguration().setAttributeComments(false); // Ignore comments

            for (ParseResult<CompilationUnit> r : sourceRoot.tryToParse()) {
                r.getResult().ifPresent(compilationUnit -> {
                    for (ClassOrInterfaceDeclaration c : compilationUnit.findAll(ClassOrInterfaceDeclaration.class)) {

                        System.out.println(c);
                        Set<MethodDeclaration> calledMethods = new HashSet<MethodDeclaration>();
                        ArrayDeque<MethodDeclaration> todo = new ArrayDeque<MethodDeclaration>();

                        while(!todo.isEmpty()) {
                            MethodDeclaration m = todo.poll();

                            for (MethodCallExpr expr : m.findAll(MethodCallExpr.class)) {
                                ResolvedMethodDeclaration rmd = expr.resolve();

                                if (rmd instanceof JavaParserMethodDeclaration) {
                                    JavaParserMethodDeclaration jpmd = (JavaParserMethodDeclaration) rmd;
                                    MethodDeclaration mdec = jpmd.getWrappedNode();

                                    if (!calledMethods.contains(mdec)) {
                                        calledMethods.add(mdec);
                                        todo.add(mdec);
                                    }
                                }
                            }
                        }

                    }
                });
            }
        }
    }
}
```

But that runs fine. Can you break it for me?

**Comment by Milkaselnuss** [comment]
The following code should be ready to run and throws the exception. You might want to set the path to the other project directly. Currently it would open a JFileChooser for you to select the project directory. What is important is that the TestClasses have to be in another project.

```
package javaparser.test;

import java.io.File;
import java.io.IOException;
import java.nio.file.Path;
import java.util.ArrayDeque;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.swing.JFileChooser;

import com.github.javaparser.ParseResult;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration;
import com.github.javaparser.symbolsolver.utils.SymbolSolverCollectionStrategy;
import com.github.javaparser.utils.ProjectRoot;
import com.github.javaparser.utils.SourceRoot;

public class Test {

	public static void main(String[] args) throws IOException {
		
		// You might want to set your own path instead of using the FileChooser
		Path path = openDirFileChooser().toPath();
		
		ProjectRoot projectRoot = new SymbolSolverCollectionStrategy().collect(path);

		for (SourceRoot sourceRoot : projectRoot.getSourceRoots()) {
			sourceRoot.getParserConfiguration().setAttributeComments(false); // Ignore comments

			for (ParseResult<CompilationUnit> r : sourceRoot.tryToParse()) {
				r.getResult().ifPresent(compilationUnit -> {
					for (ClassOrInterfaceDeclaration c : compilationUnit.findAll(ClassOrInterfaceDeclaration.class)){
						
						System.out.println(c.getNameAsString());
						System.out.println(countCalledMethods(c));
					}
				});
			}
		}
	}
	
	private static int countCalledMethods(ClassOrInterfaceDeclaration c) {
		List<MethodDeclaration> methods = c.getMethods();
		
		Set<MethodDeclaration> calledMethods = new HashSet<MethodDeclaration>(methods);
		ArrayDeque<MethodDeclaration> todo = new ArrayDeque<MethodDeclaration>(methods);
		
		while(!todo.isEmpty()) {
			MethodDeclaration m = todo.poll();
			
			for (MethodCallExpr expr : m.findAll(MethodCallExpr.class)) {
				ResolvedMethodDeclaration rmd = expr.resolve();

				if (rmd instanceof JavaParserMethodDeclaration) {
					JavaParserMethodDeclaration jpmd = (JavaParserMethodDeclaration) rmd;
					MethodDeclaration mdec = jpmd.getWrappedNode();
					
					if (!calledMethods.contains(mdec)) {
						calledMethods.add(mdec);
						todo.add(mdec);
					}
				}
			}
		}
		
		return calledMethods.size();
	}
	
	private static File openDirFileChooser() {
		File file = null;
		
		JFileChooser fileChooser = new JFileChooser();
		fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		fileChooser.setAcceptAllFileFilterUsed(false);
		
		if (fileChooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION){
			file = fileChooser.getSelectedFile();
		}
		
		return file;
	}
}
```

And another project with the classes to be tested:
```
package testproject;

public class TA {

	public void m1() {
		new TB().useAll();
	}
}
```

```
package testproject;

public class TB {

    public void useAll() {
        m2();
    }

    public void m2() {
        m3();
    }

    public void m3() { /* does nothing */ }
}
```

This gives me the following Exception:
```
Exception in thread "main" java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
	at com.github.javaparser.ast.Node.getData(Node.java:451)
	at com.github.javaparser.ast.Node.lambda$getSymbolResolver$5(Node.java:713)
	at java.util.Optional.map(Unknown Source)
	at com.github.javaparser.ast.Node.getSymbolResolver(Node.java:712)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at javaparser.test.Test.countCalledMethods(Test.java:58)
	at javaparser.test.Test.lambda$0(Test.java:41)
	at java.util.Optional.ifPresent(Unknown Source)
	at javaparser.test.Test.main(Test.java:37)
```

**Comment by matozoid** [comment]
This is a quality report, thanks! I've reproduced it.

**Comment by matozoid** [comment]
The bug is that the parser configuration does not get set on the JavaParserTypeSolvers that the `SymbolSolverCollectionStrategy` finds. Odd that nobody ran into this before :-/ It's a simple fix, see #2463

**Comment by qingdujun** [comment]
I want to load ast via sourceRoot, not only `StaticJavaParser.parse(new File(filePath));`

java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.



and ...

step 0
load simple ast,
```
static {
	TypeSolver typeSolver = new ReflectionTypeSolver();
    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
    StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
}

public static CompilationUnit getFileAST(String filePath) {
	if (!Config.blackSet.contains(filePath)) {
		try {
			return StaticJavaParser.parse(new File(filePath));
		} catch (Exception e) {
			LogUtil.Exception(e);
		}
	}
	return null;
}
```

step 1
get source root,
```
public static Path getSourceRoot(CompilationUnit compilationUnit) {
	if (compilationUnit != null) {
		try {
			return compilationUnit.getStorage().get().getSourceRoot();
		} catch (Exception e) {
			LogUtil.Exception(e);
		}
	}
	return null;
}
```

step 2

reload ast via sourceRoot
```
public static CompilationUnit getCompilationUnit(String filePath) {
...
String path = getSourceRoot(...)
SourceRoot sourceRoot = new SourceRoot(path); 
ParseResult<CompilationUnit> cu = sourceRoot.tryToParse(packageName, fileName);
if (cu.isSuccessful()) {
	return cu.getResult().get();
}
...
```


step 3

to use
```
CompilationUnit cu = getCompilationUnit(filePath);
for (MethodDeclaration decl : cu.findAll(MethodDeclaration.class)) {
	try {
		System.out.println(decl.resolve().getQualifiedSignature());
	} catch (Exception e) {
		System.out.println(e); //java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
	}
}
```

Emm, I can't   new SourceRoot(path);?

java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.

**Comment by matozoid** [comment]
Hi! SourceRoot creates its own JavaParser instance. That needs a configuration that can be passed in the SourceRoot constructor.

It's a bit confusing to use two entry points to JP, so I suggest to use only sourceroot, or StaticJavaParser, or a JavaParser instance, or SymbolSolverCollectionStrategy.

**Comment by qingdujun** [comment]
@matozoid Hi, I want to get a file's SourceRoot by StaticJavaParser CompilationUnit. I only need the AST(support MethodCallExpr resolve) for one file. Is there any other good way?

**Comment by matozoid** [comment]
i would say:
- you have one instance of `SourceRoot` for a directory. You keep it around as a field or so. That way, you can do all your parsing through that class.
- you have one instance of `ParserConfiguration` with your symbol solver setup in it. You keep it around and give it to objects that want it.

So to make a SourceRoot object from a CompilationUnit (not recommended) ask it for its source root (in the storage field) then create a SourceRoot, passing the configuration you were using.
