### ISSUE TITLE
StackOverflowError in some places

### ISSUE THREAD

**Issue by attenton** [javaparser/javaparser#2460]
Thanks for your works. I get a lot of help from the project. And I meet some problems.
When I want to get the method qualifiedSignature and run the code below:
```java
private static void parseMethodDeclaration(CompilationUnit cu) {
        List<MethodDeclaration> methodDeclarationList = cu.findAll(MethodDeclaration.class);
        for (MethodDeclaration methodDeclaration : methodDeclarationList) {
            try {
                ResolvedMethodDeclaration resolvedMethodDeclaration = methodDeclaration.resolve();
                String methodName = "";
                try {
                    // when the methodName is like [public boolean contains(Object o)], the exception happened in this line:
                    methodName = resolvedMethodDeclaration.getQualifiedSignature();
                    System.out.println("methodName: " + methodName);
                } catch (UnsolvedSymbolException e) {
                    e.printStackTrace();
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
```
or get extendName from class and run this code(ps: I ran this code successfully yesterday, but it failed today and it cannot parse any classes. I don't konw why ^-^):
```java
 List<ClassOrInterfaceType> extendedTypeList = classOrInterfaceDeclaration.getExtendedTypes();
                for (ClassOrInterfaceType extendedType : extendedTypeList) {
                    try{
                        String extendName = extendedType.resolve().getQualifiedName();
                        System.out.println("extend " + extendName);
                       //  addRelationModelList(classOrInterfaceName, extendName, EXTEND);
                    } catch (Exception e){
                        e.printStackTrace();
                    }
                }
```
both of the situation come the same exception:
```java
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:39)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.getRoot(TypeSolver.java:42)
```
It points to the code in `TypeSolver.class` :
```java
public interface TypeSolver {
    default TypeSolver getRoot() {
        // this line
        return this.getParent() == null ? this : this.getParent().getRoot();
    }
```
So how can I solve it? Thanks a lot.

**Comment by attenton** [comment]
In addition，I used it to parse the jdk source code.

**Comment by matozoid** [comment]
Hi! It looks like one of your typesolver is nested in itself or so? Can you post the configuration?

**Comment by attenton** [comment]
```java
public static void main(String args[]) throws Exception{
        String path = "C:\\D\\Document\\Research\\src\\java\\util\\AbstractCollection.java";
        JavaParser javaParser = new JavaParser();
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);
        reflectionTypeSolver.setParent(reflectionTypeSolver);
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(reflectionTypeSolver);
        javaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
        ParseResult<CompilationUnit> parseResult = javaParser.parse(new File(ImportPath));
        if (parseResult.getResult().isPresent()) {
            CompilationUnit cu = parseResult.getResult().get();
            parseMethodDeclaration(cu);
            System.out.println("\r\n");
        }
    }
```
this is the configuration code.
Did I make some mistakes?

**Comment by matozoid** [comment]
There it is: `reflectionTypeSolver.setParent(reflectionTypeSolver)`

It is now the parent of itself, and will loop forever if asked for its parent :-)

**Comment by attenton** [comment]
It works. Thanks a lot.

**Comment by matozoid** [comment]
I'll build in some checks to give future users a better message.
