### ISSUE TITLE
Type resolution fails for scope of method call expression when scope declared outside of block

### ISSUE THREAD

**Issue by httpdigest** [javaparser/javaparser#2477]
Type resolution of the scope expression in a method call expression fails when the variable used as the scope of the method call is declared outside of the block where the method call is contained in. 
The following code works with a simple `JavaParserFacade.get(new ReflectionTypeSolver(true)).getType(scope);` when trying to resolve the type of the `a` scope of the `a.cross(b, v)` method call expression for the following code:
```java
import javax.vecmath.Vector3f;
class X {
    void foo(Vector3f a, Vector3f b) {
        Vector3f v = new Vector3f();
        v.cross(a, b);
    }
}
```
However, the actual code I am trying to do this on (much more complex) has an additional block around the method call, like so:
```java
import javax.vecmath.Vector3f;
class X {
    void foo(Vector3f a, Vector3f b) {
        Vector3f v = new Vector3f();
        {
           v.cross(a, b);
        }
    }
}
```
In this case, type resolution of the `v` variable in the method call expression scope fails with:
```
Exception in thread "main" UnsolvedSymbolException{context='v', name='Solving v', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:300)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:467)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:329)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:311)
	at Test.lambda$1(Test.java:24)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at Test.lambda$0(Test.java:23)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at Test.main(Test.java:17)
```

**Comment by matozoid** [comment]
Thanks for reporting this!

**Comment by jlerbsc** [comment]
Hi @httpdigest It seems that javax.vecmath is an external dependency and  new ReflectionTypeSolver(true) cannot resolve all the classes included in it. You have to setup JarTypeSolver with this library.



    public class Issue2477Test extends AbstractSymbolResolutionTest {

    @Test
    public void test() {

        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        ParserConfiguration config = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(typeSolver));
        StaticJavaParser.setConfiguration(config);

        String s = 
                "import javax.vecmath.Vector3f;\n" +
                "class X {\n" + 
                "    void foo(Vector3f a, Vector3f b) {\n" + 
                "        Vector3f v = new Vector3f();\n" + 
                "        {\n" + 
                "           v.cross(a, b);\n" + 
                "        }\n" + 
                "    }\n" + 
                "}";
        CompilationUnit cu = StaticJavaParser.parse(s);
        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        mces.forEach(mce -> {
            System.out.println(mce.toString());
            System.out.println(mce.resolve().getQualifiedSignature());
        });

    }
    }

**Comment by jlerbsc** [comment]
I am closing this issue as it seems to have been resolved by several PRs.
