### ISSUE TITLE
Modifying some nodes with the lexicalPreservation enabled throws an exception

### ISSUE THREAD

**Issue by quanturium** [javaparser/javaparser#2517]
I'm trying to reorder the parameters in a constructor creation expr.
The first thing I've tried is to reorder the NodeList => Not sucessful (Looked normal since the parent is not aware of the sorting)
Second thing I've tried it to replace it manually, see code below:
```java
      Map<Integer, Expression> positionToParameterMap = new HashMap<>();
      NodeList<Expression> arguments = constructorCallExpr.getArguments();
      for (int i = 0; i < arguments.size(); i++) {
          positionToParameterMap.put(i, arguments.get(i));
      }
      for (Pair<Integer, Integer> deltaPair : constructorChanges.deltaChanges) {
          Expression expression = positionToParameterMap.get(deltaPair.getValue()); // map to element at previous position
          constructorCallExpr.setArgument(deltaPair.getKey(), expression); // Replace element at new position with element from previous position
      }
```

This code above throws:

```
Caused by: java.lang.IllegalArgumentException: fromIndex(116) > toIndex(73)
        at java.util.SubList.<init>(AbstractList.java:624)
        at java.util.AbstractList.subList(AbstractList.java:484)
        at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator$CalculatedSyntaxModel.sub(LexicalDifferenceCalculator.java:66)
        at com.github.javaparser.printer.lexicalpreservation.DifferenceElementCalculator.calculate(DifferenceElementCalculator.java:144)
        at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculateListReplacementDifference(LexicalDifferenceCalculator.java:132)
        at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListReplacement(LexicalPreservingPrinter.java:307)
        at com.github.javaparser.ast.observer.PropagatingAstObserver.listReplacement(PropagatingAstObserver.java:82)
        at com.github.javaparser.ast.NodeList.lambda$notifyElementReplaced$3(NodeList.java:474)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at com.github.javaparser.ast.NodeList.notifyElementReplaced(NodeList.java:474)
        at com.github.javaparser.ast.NodeList.set(NodeList.java:147)
        at com.github.javaparser.ast.nodeTypes.NodeWithArguments.setArgument(NodeWithArguments.java:55)
```

Any idea why? Am I doing something I shouldn't be doing? If no, is there a workaround for this?

**Comment by matozoid** [comment]
It's most probably a bug, so someone will have to examine this.

**Comment by jlerbsc** [comment]
This unit test reproduces the bug. The issue seems to be located in DifferenceElementCalculator.calculate(..)

    public class Issue2517Test extends AbstractLexicalPreservingTest {

    @Test
    public void testMethoCallExpr() {

        String code = "public class A {\n" +
                "    public A(String a , String b) {\n" +
                "    }\n" +
                "    public static A m() {\n" +
                "      return new A(\"a\",\"b\");\n" +
                "    }\n" +
                "}";

        StaticJavaParser.setConfiguration(new ParserConfiguration());

        CompilationUnit cu = StaticJavaParser.parse(code);
        LexicalPreservingPrinter.setup(cu);

        ObjectCreationExpr cd = cu.findFirst(ObjectCreationExpr.class).get();
        NodeList<Expression> args = cd.getArguments();
        Expression a1 = args.get(0);
        Expression a2 = args.get(1);
        NodeList<Expression> newArgs = new NodeList<>(a2, a1);
        cd.setArguments(newArgs);

         System.out.println(LexicalPreservingPrinter.print(cu));
    }
    }
