### ISSUE TITLE
Extract method names with source code and class names from a Java file

### ISSUE THREAD

**Issue by vignesh0710** [javaparser/javaparser#2560]
I have a sample ```Java``` file.  Contents of the file:

```

import java.util.ArrayList;
import java.util.List;

public class SampleClass {
    private static final int var_1 = 5;
    private static final int var_2 = 12;
    
    @Test
    public void sampleFunc() {

        List l = readFile("/path/to/a/textfile.txt");
        Iterator<String> itr = l.iterator();
        while (itr.hasNext())
            System.out.println(itr.next());
    }

    private final class UpdatedClass extends TestClass {

        class ForeignClass {
            public final String text;
            ForeignClass(String text) {
                this.text = text;
            }
        }
        List<sample> Sample;
        UpdatedClass(int width, int height) {
            super();
            testList = new ArrayList<>();
        }
    }
}
```

I want to extract 

1. List <String> of Method names with method source code. List of len 1 in this sample.

`[ "public void sampleFunc() {List l = readFile("/path/to/a/textfile.txt");Iterator<String>itr = l.iterator(); while (itr.hasNext()) System.out.println(itr.next());}" ]`

2. List <String> of Class Names. List of len 4 in this sample.

`["SampleClass","UpdatedClass","TestClass","ForeignClass"]`

Code for OP1:

```
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.*;
import com.github.javaparser.*;
import java.io.FileInputStream;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import java.io.*;

public class HelloWorld {

    public static void listClasses(String filePath) {


                new VoidVisitorAdapter<Object>() {
                    @Override
                    public void visit(MethodDeclaration n, Object arg) {
                        super.visit(n, arg);
                        System.out.println(" * " + n.getName());
                    }
                }.visit(StaticJavaParser.parse(filePath), null);
                System.out.println();
    }

    public static void main(String [] args) throws Exception{
        listClasses("test_file.java");

    }
}
```

Code for OP2:

```
public class HelloWorld {

    public static void listClasses(String filePath) {


                new VoidVisitorAdapter<Object>() {
                    @Override
                    public void visit(ClassOrInterfaceDeclaration n, Object arg) {
                        super.visit(n, arg);
                        System.out.println(" * " + n.getName());
                    }
                }.visit(StaticJavaParser.parse(filePath), null);
                System.out.println();
    }

    public static void main(String [] args) throws Exception{
        listClasses("/Users/D601744/Desktop/test_file_1.java");

    }
}
```
I am getting the same error for both:
```

Exception in thread "main" com.github.javaparser.ParseProblemException: Parse error. Found "/", expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "open" "private" "protected" "public" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10667)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:10526)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:201)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
  com.example.helloworld.HelloWorld.listClasses(HelloWorld.java:20)
  com.example.helloworld.HelloWorld.main(HelloWorld.java:25)

	at com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:260)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:229)
	at com.example.helloworld.HelloWorld.listClasses(HelloWorld.java:20)
	at com.example.helloworld.HelloWorld.main(HelloWorld.java:25)

```

Any suggestions on my mistake would be great.

**Comment by matozoid** [comment]
Ahhh, yes. The `parse` method does not take a path, it takes a string with source code. Check out the Javadoc for plenty of alternative parse methods: https://www.javadoc.io/doc/com.github.javaparser/javaparser-core/latest/com/github/javaparser/StaticJavaParser.html

**Comment by vignesh0710** [comment]
I am very new to Java, can you please explain on how to fix this. My understanding is, should I pass the entire content of `.java` file as a single string to the parse method?

**Comment by vignesh0710** [comment]
Fixed Code:
```import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.*;
import com.github.javaparser.*;
import java.io.FileInputStream;
import java.util.Scanner;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import java.io.*;

public class HelloWorld {

    public static void listClasses(String filePath) {


        new VoidVisitorAdapter<Object>() {
            @Override
            public void visit(MethodDeclaration n, Object arg) {
                super.visit(n, arg);
                System.out.println(" * " + n.getBody());
                System.out.println(" * " + n.getDeclarationAsString());
            }
        }.visit(StaticJavaParser.parse(filePath), null);
        System.out.println();
    }

    public static void main(String [] args) throws Exception{


        File file = new File("/Users/D601744/Desktop/test_file.java");
        String text = "";
        Scanner scanner = new Scanner(file);
        while(scanner.hasNextLine()){
            text+=scanner.nextLine();
        }
        //listClasses(text);
        //System.out.println(text);
       listClasses(text);

    }
}
```

Thanks for the input. This works, but as mentioned please let me know if you would suggest any other methods?

**Comment by matozoid** [comment]
Alright, take your first attempt, then replace
`StaticJavaParser.parse(filePath)`
by
`StaticJavaParser.parse(new File(filePath))`
or
`StaticJavaParser.parse(Paths.get(filePath))`.

I'm typing this without trying it out, so it might need tweaking.

**Comment by vignesh0710** [comment]
Thanks. Option 1 ```StaticJavaParser.parse(new File(filePath))``` worked
