### ISSUE TITLE
StackOverflowError when parsing massive string concatenation

### ISSUE THREAD

**Issue by arekziobrowski** [javaparser/javaparser#2570]
I try to parse [DeepStringConcat.java.txt](https://github.com/javaparser/javaparser/files/4357203/DeepStringConcat.java.txt) (added .txt extension, since GitHub doesn't allow to upload .java files). 

For sake of reproducibility, I parse the file with the following code:

```java
JavaParser jp = new JavaParser();
jp.parse(new File("/path/to/file/DeepStringConcat.java"));
```
I get the following error:
```
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.metamodel.BaseNodeMetaModel.getAllPropertyMetaModels(BaseNodeMetaModel.java:83)
	at com.github.javaparser.ast.validator.chunks.CommonValidators.lambda$new$7(CommonValidators.java:54)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:17)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:19)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:19)
...
```
What is the problem here? A hint could lie in the comment of the problematic source code `Parser.foldStrings() should use iteration instead of recursion.` - this source code is part of Eclipse Ceylon project test sources.

**Comment by edefazio** [comment]
I can reproduce this issue... it also appears to be the same file as:
https://github.com/awh/openjdk7/blob/master/langtools/test/tools/javac/DeepStringConcat.java
which is basically a test case testing how the Javac parser is parsing String concatenations...

Background Info: I think this bug was reported (originally) in the JDK7 by Neil Gafter, 

https://bugs.openjdk.java.net/browse/JDK-4496697

so (since JavaParser is also parsing Java code and specifically "String concatenations" like:

"a" + "a" + "a", ....(ad nauseum)

the bug specifically says you should use "iteration" as apposed to "recursion" likely because we are reaching the maximum (recursion) stack depth at runtime when JavaParser is running.

Anyways, it'll be interesting, this file is really just trying to illustrate how to make the bug appear, and we probably should fix it, but this is internal stuff that we might have to enlist @matazoid to help out with...
(I'll continue to do research until we have an idea how to fix, above is just speculation, but I believe thats whats happening)

**Comment by edefazio** [comment]
Related to #2167

**Comment by MysterAitch** [comment]
Can we label this as a JavaCC issue? 

Or, basically, an upstream issue that we might (potentially) be able to patch around (as opposed to being a javaparser bug)?

**Comment by arekziobrowski** [comment]
I managed to successfully parse this file by setting the `-Xss 999m` flag for JVM. 

_disclaimer_. This value is not the lowest value for the file to parse without `StackOverflowError`.

**Comment by edefazio** [comment]
this seems to be related to an issue with JavaCC...

they encountered this issue with the stack size years ago:
https://sourceforge.net/p/pmd/discussion/188194/thread/542a6e17/

_fun fact, I used to work with Tom Copeland (almost 20 yrs ago) 
(he wrote PMD and the book on JavaCC)
https://thomasleecopeland.com/_

I'll try to reach out to him and see if he's got any ideas, I think he basically said to just increase the stack size using -Xss as well

**Comment by arekziobrowski** [comment]
Great, please let me know if Tom gives you any response on this issue!

**Comment by edefazio** [comment]
incidentally/tangentially just watched/listened to this and it is relevant to this particular problem:

https://www.youtube.com/watch?v=MnctEW1oL-E&feature=youtu.be&t=4160
(iteration over recursion when parsing)

**Comment by MysterAitch** [comment]
> incidentally/tangentially just watched/listened to this and it is relevant to this particular problem:
> 
> https://www.youtube.com/watch?v=MnctEW1oL-E&feature=youtu.be&t=4160
> (iteration over recursion when parsing)

Interesting watch, thank you! 

I'll leave it to the expects to try and figure out how/if it can be applied though!

**Comment by ethan-godden** [comment]
@jlerbsc I think this is a duplicate of #4439, which was addressed in PR #5064

**Comment by jlerbsc** [comment]
Probably resolved by https://github.com/javaparser/javaparser/pull/5064
