### ISSUE TITLE
Parse Failed when parsing file with very long comment. Lexical Error.

### ISSUE THREAD

**Issue by truongthanh96** [javaparser/javaparser#2616]
Hi, I am encountering a problem when trying to parse a file with very long comment line, remove few of those comment line help this parse.

 Version
```
implementation 'com.github.javaparser:javaparser-core:3.15.18'
```
ParseConfig
```java
  final JavaParser javaParser = new JavaParser();
    final ParserConfiguration parserConfiguration = new ParserConfiguration();
    parserConfiguration.setAttributeComments(true);
    parserConfiguration.setIgnoreAnnotationsWhenAttributingComments(false);
    parserConfiguration.setDoNotAssignCommentsPrecedingEmptyLines(false);
    parserConfiguration.setLexicalPreservationEnabled(true);
...
javaParser.parse(...)
...
```

Error
```
Parsing failed:
Lexical error at line 111, column 54.  Encountered: <EOF> after : ""
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:3007)
  com.github.javaparser.GeneratedJavaParser.jj_ntk_f(GeneratedJavaParser.java:10810)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:94)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)

```

Input:
```java
/*
 * JasperReports - Free Java Reporting Library.
 * Copyright (C) 2001 - 2019 TIBCO Software Inc. All rights reserved.
 * http://www.jaspersoft.com
 *
 * Unless you have purchased a commercial license agreement from Jaspersoft,
 * the following license terms apply:
 *
 * This program is part of JasperReports.
 *
 * JasperReports is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Lesser General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * JasperReports is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with JasperReports. If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Contributors:
 */
package net.sf.jasperreports.engine.export;

import java.awt.BasicStroke;

import net.sf.jasperreports.engine.DefaultJasperReportsContext;
import net.sf.jasperreports.engine.JRAbstractExporter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRGenericElementType;
import net.sf.jasperreports.engine.JRPrintPage;
import net.sf.jasperreports.engine.JRPrintText;
import net.sf.jasperreports.engine.JRPropertiesUtil;
import net.sf.jasperreports.engine.JRRuntimeException;
import net.sf.jasperreports.engine.JasperReportsContext;
import net.sf.jasperreports.engine.PrintPageFormat;
import net.sf.jasperreports.engine.export.draw.FrameDrawer;
import net.sf.jasperreports.engine.export.draw.PrintDrawVisitor;
import net.sf.jasperreports.engine.util.JRGraphEnvInitializer;
import net.sf.jasperreports.export.Graphics2DExporterConfiguration;
import net.sf.jasperreports.export.Graphics2DExporterOutput;
import net.sf.jasperreports.export.Graphics2DReportConfiguration;
import net.sf.jasperreports.export.ReportExportConfiguration;
import net.sf.jasperreports.renderers.RenderersCache;


/**
 * Exports a JasperReports document to a <code>Graphics2D</code> object.
 * <p/>
 * JasperReports relies on AWT for text measurements and all sorts of layout calculations
 * during report filling, so documents created using AWT will certainly look perfect when
 * rendered with AWT on a <code>java.awt.Graphics2D</code> context. For this reason, the
 * {@link net.sf.jasperreports.engine.export.JRGraphics2DExporter} is the perfect
 * exporter. The output it produces is considered to be the reference in terms of layout
 * capabilities and element styling.
 * <p/>
 * Generally speaking, the document quality produced by all the other exporters is only an
 * approximation of the perfect output that the Graphics2D exporter can produce. As its
 * name indicates, this exporter is special because it does not produce files or send character
 * or binary data to an output stream. Instead, its only target for rendering the content of a
 * page is a <code>java.awt.Graphics2D</code> object. This exporter is also special because it can
 * export only one page at a time.
 * <p/>
 * This exporter is used by the built-in Swing viewer to render the content of each page, and
 * it is also used when printing the documents. The documents are printed page by page,
 * and the exporter is invoked to draw each document page on the graphic context
 * associated with the selected printer job.
 * <p/>
 * Because we are relying on the same code (same exporter) when viewing the documents
 * using the built-in viewer and when printing them, JasperReports is a perfect WYSIWYG
 * tool. The document quality on paper is the same as on the screen.
 * <p/>
 * In terms of exporter input, note that this exporter does not work in batch mode. If a
 * <code>java.util.List</code> of JasperPrint documents is supplied to it through a
 * {@link net.sf.jasperreports.export.SimpleExporterInput} instance, the exporter
 * considers only the first one for exporting and ignores all the others.
 * <p/>
 * Furthermore, this exporter can export only a single page at a time. The index of the page
 * to be exported can be set using either the
 * {@link net.sf.jasperreports.export.ReportExportConfiguration#getStartPageIndex() getStartPageIndex()}
 * exporter configuration setting or the
 * {@link net.sf.jasperreports.export.implementation 'com.github.javaparser:javaparser-core:3.15.18'
   ReportExportConfiguration#getPageIndex() getPageIndex()}.
 * Note that if present, {@link net.sf.jasperreports.export.ReportExportConfiguration#getPageIndex() getPageIndex()} overrides the value of
 * {@link net.sf.jasperreports.export.ReportExportConfiguration#getStartPageIndex() getStartPageIndex()}.
 * Therefore, this exporter actually exports only the first page from
 * the specified page range, no matter how the page range is specified.
 * <p/>
 * As already mentioned, this exporter needs a target <code>java.awt.Graphics2D</code> object onto
 * which to render the specified page. This Graphics2D object can be set using the special
 * exporter output setting {@link net.sf.jasperreports.export.Graphics2DExporterOutput#getGraphics2D() getGraphics2D()}.
 * If this setting is not present, the exporter will throw an
 * exception signaling to the caller program that no output target was specified for the
 * export process.
 * <p/>
 * By default, the exporter renders the content of the page at normal proportions. However,
 * it can also render it at different proportions if needed. For instance, when used inside the
 * Swing viewer, the Graphics2D exporter must render the page using the user-defined
 * zoom ratio. To set the zoom ratio for the exporter, supply a <code>java.lang.Float</code> value
 * ranging from 0 to 1 as the value for the
 * {@link net.sf.jasperreports.export.Graphics2DReportConfiguration#getZoomRatio() getZoomRatio()} export
 * configuration setting.
 * <p/>
 * The Graphics2D exporter is also used when printing directly from Java. The Java Print
 * Service exporter relies on the Graphics2D exporter
 * and delegates to it all the rendering that needs to be performed on the printer's graphic
 * context. Some of the existing JVM implementations have problems related to the huge
 * size of the printer spool jobs that are created even for small documents. To avoid this, a
 * bug fix was introduced in the Graphics2D exporter to minimize the impact of this
 * problem and reduce the size of print spool jobs, while preserving document quality when
 * printing. However, the bug fix itself is not perfect, and users might experience problems
 * when printing bidirectional writing texts such as Arabic and Hebrew.
 * <p/>
 * This is why the special
 * {@link net.sf.jasperreports.export.Graphics2DReportConfiguration#isMinimizePrinterJobSize() isMinimizePrinterJobSize()}
 * export configuration setting was introduced, along with a configuration property called
 * <code>net.sf.jasperreports.export.graphics2d.min.job.size</code>, to allow users to turn
 * on and off this rendering optimization, depending on their actual needs. The
 * configuration property value is used only in the absence of the export configuration setting.
 *
 * @see net.sf.jasperreports.export.Graphics2DExporterOutput
 * @see net.sf.jasperreports.export.Graphics2DReportConfiguration
 * @see net.sf.jasperreports.export.ReportExportConfiguration
 * @see net.sf.jasperreports.export.SimpleExporterInput
 * @author Teodor Danciu (teodord@users.sourceforge.net)
 */
public class JRGraphics2DExporter extends JRAbstractExporter<Graphics2DReportConfiguration, Graphics2DExporterConfiguration, Graphics2DExporterOutput, JRGraphics2DExporterContext>
{

}


```

[Problem.java.txt](https://github.com/javaparser/javaparser/files/4501053/Problem.java.txt)

**Comment by edefazio** [comment]
I can verify that this is a problem parsing the file but I'm not sure what the problem is at the moment) (I pointed to the current github project and parsed all of the .java files from : 

```java
_codeUnits _cus = _githubProject.of("https://github.com/TIBCOSoftware/jasperreports").load();
System.out.println( _cus.size() );
```

//this is the file it blows up on
"jasperreports-master/jasperreports/src/net/sf/jasperreports/engine/export/JRGraphics2DExporter.java"

all the other 3187 java files parse without a problem, but this file has an issue, Id assume it has something to do with the character encoding of the file, but am unsure.

**Comment by edefazio** [comment]
I have no idea why this is happening, but I can successfully parse the file if I remove this text that is at the top of the file:
```java
 * JasperReports - Free Java Reporting Library.
 * Copyright (C) 2001 - 2019 TIBCO Software Inc. All rights reserved.
 * http://www.jaspersoft.com
 *
```

**Comment by edefazio** [comment]
NOTE: this doesn't appear to be an issue with the "size" of the comments, but specifically the above sequence of characters which is strange... (I replaced the above with:
```java
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
 * XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
```

and it works fine.

**Comment by MysterAitch** [comment]
> 
> 
> I have no idea why this is happening, but I can successfully parse the file if I remove this text that is at the top of the file:
> 
> ```java
>  * JasperReports - Free Java Reporting Library.
>  * Copyright (C) 2001 - 2019 TIBCO Software Inc. All rights reserved.
>  * http://www.jaspersoft.com
>  *
> ```

Would be surprising if it is, but maybe something to do with the `//` in the URL perhaps?

What happens when trying to parse this comment with everything but this part stripped out?

**Comment by edefazio** [comment]
Tried that (removed just the url), didnt work (still threw exception)

tried just parsing this:
```java
        /*
         * JasperReports - Free Java Reporting Library.
         * Copyright (C) 2001 - 2019 TIBCO Software Inc. All rights reserved.
         * http://www.jaspersoft.com
         */
         class F{}
         _class _d = _class.of(F.class);
```
...worked fine

If I just take the part out, everything seems fine (no parse errors)

ALSO the problem is reported much later in the file (line 111).

I'm as confused as anyone and the error comes from our lovely JavaCC generated files (eeek)

**Comment by edefazio** [comment]
I thought it was because we have (2) block comments before the package declaration or something, but that doesnt appear to be the case either.

**Comment by MysterAitch** [comment]
Bizarre...

**Comment by edefazio** [comment]
This appears to be a regression in newer versions of JavaParser

I rolled back to `3.15.1`, and I was able to parse this file successfully...

I think perhaps the changes made previously for Comment parsing might not have been completely rolled back because this appears comment parsing related.

**Comment by matozoid** [comment]
My bet is on the JavaCC upgrade.

Side note: BulkParseTest.java has some tests can be run manually on a huge, good test set. That would probably have found this.

**Comment by MysterAitch** [comment]
Well this is an involved one! 

So I have managed to kinda get a handle on this -- it seems to be related to the size of the token versus the size of the char stream buffer when reading the contents of the file. 

You can test/examine this for yourself -- try increasing the default buffer size to e.g. 8,192 or 12,288 on line 35 of `AbstractCharStream` and see how that affects the success (or not) of parsing the file. Similarly, try setting it to a lower value such as 600 to try to induce failure. Note that this file is generated.

The exact effect seems to depend on the value chosen and how this aligns with the source code (e.g. if it is still inside of the comment, the end of the comment and the document will be parsed but with some parts missing -- alternatively there might be an error such as unexpected EOL if the end of a comment is skipped thus we're still "inside" the comment at that point).

While I'm not sure of the exact issue here, this is definitely looking like a strong contender here! (maybe the buffer isn't increasing in size correctly to allow for large sized tokens?).

For now though, I must sleep/rest! :) 

![image](https://user-images.githubusercontent.com/1537214/80322373-90525c80-881c-11ea-835b-e2b940c3ad32.png)

![idea64_javaparser-parent_–_AbstractCharStream java_ javap_KjUrxUZyrE_20200426_231731 852](https://user-images.githubusercontent.com/1537214/80322392-a6f8b380-881c-11ea-8d73-78f695f5f418.png)


![image](https://user-images.githubusercontent.com/1537214/80322354-60a35480-881c-11ea-9bf0-7a0a6e26d1b1.png)

**Comment by MysterAitch** [comment]
Hmm, might not necessarily be this straightforward...

The buffer is seemingly able to expand in size, but inspecting the contents of the buffer shows that it has the incorrect values inside of it. 

Not sure yet how `bufpos` is set or why it seems to be getting "corrupted" (if that's the correct word).

![image](https://user-images.githubusercontent.com/1537214/80322948-1c19b800-8820-11ea-8a3c-fe8a457bc435.png)

**Comment by MysterAitch** [comment]
> 
> 
> My bet is on the JavaCC upgrade.
> 
> Side note: BulkParseTest.java has some tests can be run manually on a huge, good test set. That would probably have found this.

I've just confirmed that reverting back to v3.0.0 (from 4.1.3) does indeed seem to solve this.

The bulk parse test doesn't seem to pick this up - well, at least not specifically. On both versions, it fails with the following (probably better off in a separate issue though, if one doesn't already exist).


```
Parsing zip entry "langtools-19293ea3999f/test/tools/javac/DeepStringConcat.java"
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.ast.validator.chunks.CommonValidators.lambda$new$7(CommonValidators.java:74)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:38)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
```

**Comment by paulk-asert** [comment]
The following file also seems to display this error:
https://github.com/apache/groovy/blob/master/src/main/java/groovy/transform/builder/DefaultStrategy.java
```
Error: Lexical error at line 287, column 0. Encountered: after : ""
Problem stacktrace :
  com.github.javaparser.GeneratedJavaParserTokenManager.getNextToken(GeneratedJavaParserTokenManager.java:3007)
  com.github.javaparser.GeneratedJavaParser.jj_ntk_f(GeneratedJavaParser.java:10810)
  ...
```
(but as noted for the other example, I'd guess that line number is somewhat after the problematic code)
