### ISSUE TITLE
UnsolvedSymbolException when String::valueOf is used in streams

### ISSUE THREAD

**Issue by d-kay23** [javaparser/javaparser#2657]
Hello everyone.
I've noticed that String::valueOf method reference is not resolved in stream.
Here is the example of code:
```
String s =
                "import java.util.HashSet;\n" +
                        "import java.util.Set;\n" +
                        "import java.util.stream.Collectors;\n" +
                        "\n" +
                        "public class StreamTest {\n" +
                        "    \n" +
                        "    public void streamTest () {\n" +
                        "        Set<Integer> intSet = new HashSet<Integer>() {{\n" +
                        "           add(1);\n" +
                        "           add(2);\n" +
                        "        }};\n" +
                        "        Set <String> strings = intSet.stream().map(String::valueOf).collect(Collectors.toSet());\n" +
                        "    }\n" +
                        "}";
        TypeSolver typeSolver = new ReflectionTypeSolver();
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(s);
        Set<MethodCallExpr> methodCallExpr = new HashSet<>(cu.findAll(MethodCallExpr.class));
        for (MethodCallExpr expr : methodCallExpr) {
            ResolvedMethodDeclaration rd = expr.resolve();
            System.out.println("\t Solved : " + rd.getQualifiedSignature());
        }
```
Result:
```
 Solved : java.util.HashSet.add(E)
Exception in thread "main" UnsolvedSymbolException{context='intSet.stream().map(String::valueOf).collect(Collectors.toSet())', name='intSet.stream().map(String::valueOf)', cause='java.lang.UnsupportedOperationException'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:155)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:269)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:131)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Parser.main(Parser.java:40)
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.toMethodUsage(JavaParserFacade.java:413)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:542)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:91)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:484)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:346)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:355)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:328)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 6 more
```

I use the newest javaparser-symbol-solver-core 3.15.21.
Is this a new bug? Do you plan to fix this?

**Comment by MysterAitch** [comment]
Based on your description it seems like a bug (it's not possible to resolve e.g. a filter or collect in next steps without first being able to resolve a map), but would need to actually look ta the code and dig into it to be sure.

With respect to fixes, you've done great by providing what looks like a runnable minimal failing test case. 

I can't make any promises re: timelines though as we're all volunteers and the backlog is running pretty long!

**Comment by d-kay23** [comment]
@MysterAitch 
Ok, I am using workarounds, but I hope for a fix in a following version.
Thank you for information.
