### ISSUE TITLE
UnsolvedSymbolException in resolving method reference in filter method

### ISSUE THREAD

**Issue by d-kay23** [javaparser/javaparser#2666]
Hi everyone.
Looks like I've found one more bug in resolving streams.
Here is example of class where resolving has been failed:
```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.util.HashSet;
import java.util.Set;

public class Parser {

    public static void main(String[] args) {

        String s =
                "import java.util.stream.Stream;\n" +
                        "\n" +
                        "public class StreamTest {\n" +
                        "\n" +
                        "    public void streamTest() {\n" +
                        "        String[] arr = {\"1\", \"2\", \"3\", \"\", null};\n" +
                        "        Stream.of(arr).filter(this::isNotEmpty).forEach(s -> System.out.println(s));\n" +
                        "    }\n" +
                        "\n" +
                        "    private boolean isNotEmpty(String s) {\n" +
                        "        return s != null && s.length() > 0;\n" +
                        "    }\n" +
                        "}\n";
        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(s);
        Set<MethodCallExpr> methodCallExpr = new HashSet<>(cu.findAll(MethodCallExpr.class));
        for (MethodCallExpr expr : methodCallExpr) {
            ResolvedMethodDeclaration rd = expr.resolve();
            System.out.println("\t Solved : " + rd.getQualifiedSignature());
        }
}
}
```
The result is:
```
	 Solved : java.util.stream.Stream.of(T...)
	 Solved : java.util.stream.Stream.filter(java.util.function.Predicate<? super T>)
	 Solved : java.lang.String.length()
Exception in thread "main" java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: System.out.println(s), Parameter: s
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:253)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:268)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:132)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Parser.main(Parser.java:35)
Caused by: java.lang.RuntimeException: Error calculating the type of parameter s -> System.out.println(s) of method call Stream.of(arr).filter(this::isNotEmpty).forEach(s -> System.out.println(s))
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:673)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.LambdaExprContext.solveSymbolAsValue(LambdaExprContext.java:72)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:120)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:150)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:73)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:78)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:299)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:249)
	... 5 more
Caused by: UnsolvedSymbolException{context='Stream.of(arr).filter(this::isNotEmpty).forEach(s -> System.out.println(s))', name='Stream.of(arr).filter(this::isNotEmpty)', cause='java.lang.UnsupportedOperationException'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:155)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:270)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:132)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:413)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:162)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:377)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:671)
	... 16 more
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.toMethodUsage(JavaParserFacade.java:396)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:543)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:91)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:356)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:329)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 25 more

```
The problem is reproduced with the latest javaparser-symbol-solver-core 3.15.22.
Sure, method reference can be substituted by predicate ```s -> isNotEmpty(s)``` and it works, but it's  pitfall when you are writing new code.

**Comment by MysterAitch** [comment]
Something that comes to mind to explore -- what is `this::isNotEmpty` picked up as _(off the top of my head I'm not sure what it should be)_? And is it resolved correctly? 

Similarly, what is the return type of `.filter(this::isNotEmpty)`?

... and how does this differ to the return types when using `s -> isNotEmpty(s)`?

Figuring out where the differences are here looks like an interesting thing to dig into! My presumption is that the important bit here is the `this::` as an extension to the recent fix re: `String::`.

**Comment by d-kay23** [comment]
In addition to previous problem, I found one more stream issue. I didn't dive to the parser code, so maybe the root cause of the problem is the same, but the following code isn't resolved as well:
```
import java.util.ArrayList;
import java.util.List;

public class ListTest {

    public static void main (String [] args) {
        List<Integer> integerList = new ArrayList<Integer>(){{
            add(4);
            add(5);
            add(1);
        }};

        int min = integerList.stream().min(Integer::compare).orElse(-1);
        System.out.println(min);
    }

}
```
Exception:
```
Exception in thread "main" UnsolvedSymbolException{context='integerList.stream().min(Integer::compare).orElse(-1)', name='integerList.stream().min(Integer::compare)', cause='java.lang.UnsupportedOperationException'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:155)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:270)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:132)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Parser.main(Parser.java:39)
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.toMethodUsage(JavaParserFacade.java:429)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:543)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:91)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:356)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:329)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 6 more
```
If I use ```Integer::compareTo``` method reference, the solver doesn't throw the exception.

**Comment by MysterAitch** [comment]
This last example seems like it might be "unbound non-static methods" that aren't handled. I've still got some reading to do to figure out what that means though!

Note `public int compareTo(Integer anotherInteger) {` vs `public static int compare(int x, int y) {`.

https://www.javaworld.com/article/2946534/java-101-the-essential-java-language-features-tour-part-7.html

> An unbound non-static method reference refers to a non-static method that's not bound to a receiver object. Its syntax is `className::instanceMethodName`, where `className` identifies the class that declares the instance method and `instanceMethodName` identifies the instance method. An example is `String::toLowerCase`.
> 
> `String::toLowerCase` is an unbound non-static method reference that identifies the non-static `String toLowerCase()` method of the `String` class. However, because a non-static method still requires a receiver object (in this example a String object, which is used to invoke `toLowerCase()` via the method reference), the receiver object is created by the virtual machine. `toLowerCase()` will be invoked on this object. 
> 
> `String::toLowerCase` specifies a method that takes a single String argument, which is the receiver object, and returns a String result. `String::toLowerCase()` is equivalent to lambda `(String s) -> { return s.toLowerCase(); }`. 


> ```java
> import java.util.function.Function;
> 
> public class MRDemo
> {
>    public static void main(String[] args)
>    {
>       print(String::toLowerCase, "STRING TO LOWERCASE");
>       print(s -> s.toLowerCase(), "STRING TO LOWERCASE");
>       print(new Function<String, String>()
>       {
>          @Override
>          public String apply(String s) // receives argument in parameter s;
>          {                             // doesn't need to close over s
>             return s.toLowerCase();
>          }
>       }, "STRING TO LOWERCASE");
>    }
> 
>    public static void print(Function<String, String> function, String
> s)
>    {
>       System.out.println(function.apply(s));
>    }
> }
> ```
