### ISSUE TITLE
org.json chaining method issue

### ISSUE THREAD

**Issue by d-kay23** [javaparser/javaparser#2667]
Hello.
There is a problem with ReflectionTypeSolver and json lib:
```
        <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20140107</version>
        </dependency>
```
Code:
```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.util.HashSet;
import java.util.Set;

public class Parser {

    public static void main(String[] args) {

        String s =
                "import org.json.JSONObject;\n" +
                        "\n" +
                        "public class ChainingTest {\n" +
                        "\n" +
                        "    public static void main (String args[]) {\n" +
                        "        JSONObject jsonObject = new JSONObject();\n" +
                        "        jsonObject.put(\"k1\", 1).put(\"k2\", \"v2\");\n" +
                        "    }\n" +
                        "\n" +
                        "}\n";
        TypeSolver typeSolver = new ReflectionTypeSolver(false);
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(s);
        Set<MethodCallExpr> methodCallExpr = new HashSet<>(cu.findAll(MethodCallExpr.class));
        for (MethodCallExpr expr : methodCallExpr) {
            ResolvedMethodDeclaration rd = expr.resolve();
            System.out.println("\t Solved : " + rd.getQualifiedSignature());
        }
    }
}

```
Exception:
```
Exception in thread "main" UnsolvedSymbolException{context='jsonObject.put("k1", 1).put("k2", "v2")', name='jsonObject.put("k1", 1)', cause='com.github.javaparser.resolution.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,boolean) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='boolean'}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,double) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='double'}]}. First declared in org.json.JSONObject'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:155)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:270)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:132)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Parser.main(Parser.java:32)
Caused by: com.github.javaparser.resolution.MethodAmbiguityException: Ambiguous method call: cannot find a most applicable method: MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,boolean) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='boolean'}]}, MethodUsage{declaration=ReflectionMethodDeclaration{method=public org.json.JSONObject org.json.JSONObject.put(java.lang.String,double) throws org.json.JSONException}, paramTypes=[ReferenceType{java.lang.String, typeParametersMap=TypeParametersMap{nameToValue={}}}, PrimitiveTypeUsage{name='double'}]}. First declared in org.json.JSONObject
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicableUsage(MethodResolutionLogic.java:581)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.solveMethodAsUsage(ReflectionClassDeclaration.java:224)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:182)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:428)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:121)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:679)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:289)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:504)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:329)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 6 more
```

I'm not sure is this the parser bug, but the problem is disappear when methods are not chained:
```
public static void main (String args[]) {
        JSONObject jsonObject = new JSONObject();
        jsonObject.put("k1", 1);
        jsonObject.put("k2", "v2");
    }
```
Maybe someone can shed some light to this strange parser behavior.

**Comment by MysterAitch** [comment]
Thanks for the report! :) 

I've labelled it as a symbol solver bug for now, but can change it if any new information comes to light -- e.g. if it's actually an issue with the reflection or if there is an issue with the parser side of things.

Are you able to whittle this down to a smaller reproducible testcase? Ideally one which doesn't need any dependencies and can be included as a JUnit test or similar, so that tests run on travis etc are able to pick it up now (and as a regression test later).

**Comment by jlerbsc** [comment]
Curiously you don't use JarTypeSolver to resolve the json library!!

**Comment by d-kay23** [comment]
@MysterAitch 
I've tried to create a little test-case, but it isn't reproduced when code is in the same class, so I guess it's somehow related to ReflectionTypeSolver
@jlerbsc 
Yes, but I use ReflectionTypeSolver(false) and this lib was added to classpath.
