### ISSUE TITLE
UnsupportedOperationException in SymbolSolver handling a lambda expression

### ISSUE THREAD

**Issue by michaelhkay** [javaparser/javaparser#2754]
Handling this code fragment:

```
            @Override
            public Iterator<XdmAtomicValue> iterator() {
                return new MappingJavaIterator<>(
                        getUnderlyingValue().keyValuePairs().iterator(),
                        kvp -> (XdmAtomicValue) XdmValue.wrap(kvp.key));
            }
```

and calling `calculateResolvedType` on the `FieldAccessExpr` representing `kvp.key`, I get:

```
Exception in thread "main" java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.LambdaExprContext.solveSymbolAsValue(LambdaExprContext.java:176)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:129)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:154)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:73)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:78)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:297)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:526)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:340)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:281)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:564)
	at XmlPrinterMHK.output(XmlPrinterMHK.java:76)
```

The UnsupportedOperationException is thrown when solving the symbol "kvp", if the parent of the expression is not a `MethodCallExpr`, `VariableDeclarator`, or `ReturnStmt`; in this case it is an `ObjectCreationExpr` corresponding to `new MappingJavaIterator<>(getUnderlyingValue().keyValuePairs().iterator(), kvp -> (XdmAtomicValue) XdmValue.wrap(kvp.key))`.

I wiill attempt to put together a minimal repro.

**Comment by michaelhkay** [comment]
Repro attached. Run Issue2754Repro from the command line with no arguments; it processes the source code in Issue2754TestClass.java.

[Issue2754Repro.java.txt](https://github.com/javaparser/javaparser/files/4899834/Issue2754Repro.java.txt)
[Issue2754TestClass.java.txt](https://github.com/javaparser/javaparser/files/4899835/Issue2754TestClass.java.txt)

**Comment by jlerbsc** [comment]
Hi @michaelhkay thanks for reporting this. I have reproduce your issue with your test case. I'm not sure I can fix this quickly because it's a relatively complex part of the symbol solver component that requires a deep understanding of how it works.
