### ISSUE TITLE
UnsupportedOperationException thrown when solving method calls contains Varargs

### ISSUE THREAD

**Issue by hunan889** [javaparser/javaparser#2796]
Exception will be thrown in MethodCallExprContext when solve a method contains statements like:
```java
    public static BodyDeclaration parseInterfaceBodyDeclaration(String body) {
        System.out.println(String.format("abc","def"));
        return simplifiedParse(INTERFACE_BODY, provider(body));
    }
```

Call stack:
```
 java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: System.out.println(String.format("abc", "def")), Parameter: String.format("abc", "def")
	at MethodUsage.processJavaFile(MethodUsage.java:95)
	at MethodUsage.main(MethodUsage.java:110)
Caused by: java.lang.UnsupportedOperationException: Unable to resolve the type typeParametersValues in a MethodUsage. Expected type: ArrayTypeUsage{ReferenceTypeUsage{declaration=ReflectionClassDeclaration{clazz=java.lang.Object}, typeParametersValues=[]}}, Actual type: ReferenceTypeUsage{declaration=ReflectionClassDeclaration{clazz=java.lang.String}, typeParametersValues=[]}. Method Declaration: ReflectionMethodDeclaration{method=public static java.lang.String java.lang.String.format(java.lang.String,java.lang.Object[])}. MethodUsage: MethodUsage{declaration=ReflectionMethodDeclaration{method=public static java.lang.String java.lang.String.format(java.lang.String,java.lang.Object[])}, paramTypes=[ReferenceTypeUsage{declaration=ReflectionClassDeclaration{clazz=java.lang.String}, typeParametersValues=[]}, ArrayTypeUsage{ReferenceTypeUsage{declaration=ReflectionClassDeclaration{clazz=java.lang.Object}, typeParametersValues=[]}}]}
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.resolveMethodTypeParameters(MethodCallExprContext.java:73)
	at me.tomassetti.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:196)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:620)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:269)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:157)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:135)
	at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:118)
	at MethodUsage.processJavaFile(MethodUsage.java:85)
```

**Comment by hunan889** [comment]
seems this bug is because of Variable Length Arguments,

Expected: String.format(String, Object...)
Actual: String.format("abc","def")
the expected type for second parameters is "Object[]", but actual type is "String"(the constant "def"), problem occurs in class JavaParserFacade.solveMethodAsUsage:

![image](https://user-images.githubusercontent.com/6399498/92924751-07a32880-f46c-11ea-836e-93c831963f6f.png)

**Comment by jlerbsc** [comment]
What JavaParser version are you using? Could you provide us a test case please?

**Comment by hunan889** [comment]
@jlerbsc sorry for that I used a wrong sample code for testing and it makes the mistake.... Issue closed

**Comment by jlerbsc** [comment]
You're welcome
