### ISSUE TITLE
Get UnsolvedSymbolException when trying to resolve type

### ISSUE THREAD

**Issue by dwen77** [javaparser/javaparser#2823]
Hi people,

I am facing an issue at this moment,  a `UnsolvedSymbolException` is thrown when resolving ```FieldAccessExpr``` object.

Basically, I want to resolve the type of an object which field is accessed. You could reproduce the error by the following steps.

- Create a java Class `ClassA`
```
public class ClassA {

    public ClassB obj;
}
```

- Create a second java class `ClassB`

```
public class ClassB {

    public Long value;
}
```

- Create a third class `TestClass` which is the java file I would like to parse.
```
public class TestClass {

    public Long getValue() {

        Optional<ClassA> classA = Optional.of(new ClassA());

        return classA.map(a -> a.obj)
                .map(b -> b.value)
                .orElse(null);
    }
}
```
- Create a class to parse the  `TestClass.java` and resolve type of objects which filed is accessed. In this example, my goal is to resolve what are the types of objects which field are accessed in the `getValue` method. I hide the real file path name in the code snippet below. 

```
public class Inspect {

    public static void main(String[] args) throws FileNotFoundException {
        JavaSymbolSolver javaSymbolSolver = createSymbolSolver();
        StaticJavaParser.getConfiguration().setSymbolResolver(javaSymbolSolver);
        String path = "PATH_TO_TestClass.java";
        CompilationUnit cu = StaticJavaParser.parse(new File(path));
        cu.findAll(FieldAccessExpr.class).forEach(
                FieldAccessExpr::resolve
        );
    }

    private static JavaSymbolSolver createSymbolSolver() {
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("PATH_TO_ROO_PACKAGE"));
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver(reflectionTypeSolver, javaParserTypeSolver);
        return new JavaSymbolSolver(combinedTypeSolver);
    }
}
```

The exception I got when executing `Inspect` is 
```
Caused by: UnsolvedSymbolException{context='null', name='obj', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:237)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:526)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:340)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:475)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:162)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:526)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:367)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:340)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 26 more
```

I also noticed that types can be resolved if I change the `getValue` method of `TestClass` as below 

```
import java.util.Optional;

public class TestClass {

    public Long getValue() {

        Optional<ClassA> classA = Optional.of(new ClassA());

        final Optional<ClassB> classB = classA.map(a -> a.obj);
        return classB
                .map(b -> b.value)
                .orElse(null);
    }
}
```

As you can see that the `map` methods are not chained , instead, the return of first `map` method is assigned explicitly to a local variable. To me, it seems the types can NOT be resolved if there is a chain of method invocations and methods have lambda function as input parameters. 

I don't know if I misused the library or I am missing some configurations. Could anyone please provide some suggestions? I really appreciate it!

**Comment by jlerbsc** [comment]
Hi @dwen77 Could you confirm that "PATH_TO_ROO_PACKAGE" means the path to the source directory.

**Comment by dwen77** [comment]
> Hi @dwen77 Could you confirm that "PATH_TO_ROO_PACKAGE" means the path to the source directory.

Yes, the value is `/project-absolute-path/src/main/java`

**Comment by jlerbsc** [comment]
Thank you for reporting this bug.

**Comment by dwen77** [comment]
> Thank you for reporting this bug.

Thank you for checking it!
