### ISSUE TITLE
IllegalStateException/UnsupportedOperationException when adding extended type to a ClassOrInterfaceDeclaration

### ISSUE THREAD

**Issue by Deaglancb** [javaparser/javaparser#2826]
Hi folks,

 Working on a project I wanted one class to extend another. The simple example being:
I want Customer to extend Person

`public class Person {}
`
`public class Customer{}
`

However an IllegalStateException is bring thrown which was confusing me:

> Exception in thread "main" java.lang.IllegalStateException: Cannot keep element because we reached the end of nodetext: NodeText{[ChildTextElement{public }, " "   <1>   (line 1,col 7)-(line 1,col 7), "class"   <19>   (line 1,col 8)-(line 1,col 12), " "   <1>   (line 1,col 13)-(line 1,col 13), ChildTextElement{Customer}, "{"   <98>   (line 1,col 22)-(line 1,col 22), "}"   <99>   (line 1,col 23)-(line 1,col 23), "extends"   <27>   (?)-(?), " "   <1>   (?)-(?), ChildTextElement{Person}, " "   <1>   (?)-(?)]}. Difference: Difference{[Kept{child(Modifier)}, Kept{token( )}, Kept{token(class)}, Kept{token( )}, Kept{child(SimpleName)}, Kept{token( )}, Added{token(extends)}, Added{token( )}, Added{child(ClassOrInterfaceType)}, Added{token( )}, Kept{token({)}, Kept{com.github.javaparser.printer.concretesyntaxmodel.CsmIndent@1}, Kept{token(
)}, Kept{com.github.javaparser.printer.concretesyntaxmodel.CsmUnindent@2}, Kept{token(})}]}
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyLeftOverDiffElements(Difference.java:207)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:154)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:312)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:488)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:488)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:72)
	at com.github.javaparser.ast.nodeTypes.NodeWithExtends.addExtendedType(NodeWithExtends.java:92)
	at Main.main(Main.java:52)

The error is perhaps a little more specific if the Customer class has something in it:

```java
public class Customer{
    public Customer(){}
}
```
Results in an UnsupportedOperationException

> Exception in thread "main" java.lang.UnsupportedOperationException: kept token({) vs ChildTextElement{public Customer() {
}}
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:537)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:168)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:312)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:488)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:488)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:72)
	at com.github.javaparser.ast.nodeTypes.NodeWithExtends.addExtendedType(NodeWithExtends.java:92)
	at Main.main(Main.java:52)

A way to get this working, is either to add a space between Customer and the braces:
`public class Customer {}`
Or else to disable Lexical Preservation when initialising the parser.

You can pull sample code here (I assume it's handier than pasting individual files in an issue report?): https://github.com/Deaglancb/JavaParserInheritanceIssue
Bouncing between the Customer class in resources (adding/removing the space), and the Main (commenting out line 32 & 43-45).

**Comment by jlerbsc** [comment]
I think there is bug in DifferenceElementCalculator.calculate(..) but it's a complex algorithm that takes a long time to understand how it works.

**Comment by jlerbsc** [comment]
This issue is resolved in the current version (JP 3.16.4-snapshot).

    public class Issue2826Test extends AbstractLexicalPreservingTest {

    @Test
    public void test() {
        
        StaticJavaParser.setConfiguration(new ParserConfiguration());

        String s = "public class Person  {}";
        CompilationUnit cu = StaticJavaParser.parse(s);
        LexicalPreservingPrinter.setup(cu);
        
        ClassOrInterfaceType extend = new ClassOrInterfaceType("Customer"); 
        
        ClassOrInterfaceDeclaration cd = cu.findFirst(ClassOrInterfaceDeclaration.class).get();
        cd.addExtendedType(extend);
        System.out.println(LexicalPreservingPrinter.print(cu));
        
    }
    }
