### ISSUE TITLE
Exceeded the file descriptors limit during looping JarTypeSolver

### ISSUE THREAD

**Issue by d6ms** [javaparser/javaparser#2829]
Hi people,

I am using javaparser 3.16.1 in my project.
While parsing Java projects, I faced the following error.

```
Caused by: java.nio.file.FileSystemException: Too many open files
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.walk(Files.java:3824)
        at java.base/java.nio.file.Files.walk(Files.java:3878)
```

This is caused by this code.

```java
for (TargetProject project : projects) {
    ...
    CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    Files.list(project.dependenciesDir)
            .forEach(path -> combinedTypeSolver.add(new JarTypeSolver(path)));
    JavaParser parser = new JavaParser();
    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
    parser.getParserConfiguration().setSymbolResolver(symbolSolver);
    ...
}
```

`JarTypeSolver` adds classes in a jar file into classpath and not removes from classpath automatically when it destructs. This may not be the problem as far as simply parsing a few projects. But I am parsing very many projects for machine learning preprocess use. In my case, file descriptors appear to increase accumulatively by looping project parsing procedure.

Is there any alternative way to avoid this problem?

**Comment by jlerbsc** [comment]
Hi @d6ms Thanks for reporting this bug. Could you share with us your system and user limit (open files) and the full stacktrace.
It seems that JarTypeSolver.addPathToJar(..) add a JarFile's to a Map which are never closed. It may be the source of your issue.

**Comment by jlerbsc** [comment]
Hi @maartenc, maybe we could provide a method in the TypeSolver interface to possibly free the resources. The default implementation would take no action. In the case of the JarTypeSolver class it would browse all the jar files and close them. AarTypeSolver would delegate this task to the internal JarTypeSolver. What do you think of this proposal?

**Comment by d6ms** [comment]
@jlerbsc Thanks for responding.

As for "open files" limit, they are 315982184 as OS limit and 1048576 as user limit respectively. In addition, when I encountered these errors, 51200 were permitted for my Java process. Since this is shared computing cluster environment, I cannot change the limit easily.

My system was running as many concurrent threads, so I faced a lot of such errors. One of the full stacktrace of an error is below.

```
java.io.UncheckedIOException: java.nio.file.FileSystemException: /home/u00312/test/data/rawdata/resolved/msokolov__lux: Too many open files
java.util.concurrent.ExecutionException: java.io.UncheckedIOException: java.nio.file.FileSystemException: /home/u00312/test/data/rawdata/resolved/msokolov__lux: Too many open files
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at preprocessor.Preprocessor.preprocess(Preprocessor.java:74)
        at preprocessor.App.main(App.java:41)
Caused by: java.io.UncheckedIOException: java.nio.file.FileSystemException: /home/u00312/test/data/rawdata/resolved/msokolov__lux: Too many open files
        at preprocessor.ProjectOrganizer.organizeProject(ProjectOrganizer.java:42)
        at preprocessor.Preprocessor.preprocessTask(Preprocessor.java:108)
        at preprocessor.Preprocessor.lambda$preprocess$0(Preprocessor.java:68)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.nio.file.FileSystemException: /home/u00312/test/data/rawdata/resolved/msokolov__lux: Too many open files
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:100)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newDirectoryStream(UnixFileSystemProvider.java:432)
        at java.base/java.nio.file.Files.newDirectoryStream(Files.java:471)
        at java.base/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:300)
        at java.base/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:322)
        at java.base/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
        at java.base/java.nio.file.Files.walk(Files.java:3824)
        at java.base/java.nio.file.Files.walk(Files.java:3878)
        at preprocessor.ProjectOrganizer.organizeProject(ProjectOrganizer.java:31)
        ... 7 more
```

The place this error occurred is not the place `JarTypeSolver` is created, but it seems like file descriptors opened by `JarTypeSolver` affect other places that open files.

**Comment by maartenc** [comment]
Are we sure the JarTypeSolver is the problem here?
I would expect the garbage collector to cleanup the unused JarTypeSolver instances, this should close the JarFiles as well.

@d6ms : Can you take a look at the open file handles to check that most of them are referencing jar files? And are you sure you don't hold a reference to these JarTypeSolver instances anywhere so they can be cleaned up by the garbage collector.

**Comment by jlerbsc** [comment]
@d6ms the solution may take a little time to come because I have to consult the other contributors of the project to share a solution together. During this time can you also confirm that a large part of open files are libraries (with command lsof -p <pid>)

**Comment by jlerbsc** [comment]
@maartenc I'm not sure the gc is freeing system resources in this case. This can be easily demonstrated using the lsof command (lsof -p <pid>)

**Comment by maartenc** [comment]
Yes, when the JarTypeSolver, and eventually, the JarFile itself is gc'ed, the JarFile is closed by its finalize() method.

But nonetheless, having some kind of cleanup() method on TypeSolver could be usefull. It can be tricky to implement it correctly because you'll have to recreate the JarFile instance when the TypeSolver wants to solve another type. Another option could be to not keep the JarFile open in the JarTypeSolver, but only open it when needed and close it again. In that case, we don't need such a cleanup() method, however, this could have a performance impact.

**Comment by jlerbsc** [comment]
@maartenc You are right.

**Comment by jlerbsc** [comment]
@d6ms Could you check what types of file are mostly referenced (with lsof -p)?

**Comment by d6ms** [comment]
@jlerbsc 
Sorry, I had another work. I will be able to check it before long.

**Comment by d6ms** [comment]
This is the result of `lsof -p` of my system. Open jar files increase as time to go. And most of the open files are jar files.

```
$ lsof -p 25551 | wc -l && lsof -p 25551 | grep ".jar" | wc -l
12977
11486
$ lsof -p 25551 | wc -l && lsof -p 25551 | grep ".jar" | wc -l
13563
12090
$ lsof -p 25551 | wc -l && lsof -p 25551 | grep ".jar" | wc -l
14524
13072
$ lsof -p 25551 | wc -l && lsof -p 25551 | grep ".jar" | wc -l
21697
20154
```

**Comment by d6ms** [comment]
Also, I implemented a minimum program to reproduce the problem.

```java
public class Main {
    public static void main(String[] args) throws Exception {
        Set<Path> jarFiles = Files.walk(Paths.get("/home/u00312/.m2/repository"))
                .filter(path -> path.getFileName().toString().endsWith(".jar"))
                .collect(Collectors.toSet());
        System.out.println(jarFiles.size());  // 149660
        for (Path jarFile : jarFiles) {
            JarTypeSolver jarTypeSolver = new JarTypeSolver(jarFile);
        }
    }
}
```

If a JarTypeSolver that is not referenced still has opened jar files, this process will exceed the open files limit. But in fact, this program produces no errors.

So, it should be wrong that JarTypeSolver does not free file descriptors, and what @maartenc said would be right. My program may accidentally have reference to JarTypeSolver which is no longer used.

**Comment by d6ms** [comment]
Anyway, the cause of the problem would not be javaparser implementations. So, I will close this issue and continue to debug my program. If I can find some errors, I will reopen this issue or create another.

Thanks for your advice, @jlerbsc and @maartenc !
