### ISSUE TITLE
NoSuchElementException in PhantomNodeLogic after adding node

### ISSUE THREAD

**Issue by ovesh** [javaparser/javaparser#2926]
I have the following logic to add a call in the middle of a few chained calls:
```java
    @Override
    public Visitable visit(final MethodCallExpr n, final Void arg) {
        final Visitable visit = super.visit(n, arg);
        if (!n.getName().getIdentifier().equals("build")) {
            return visit;
        }
        n.getScope()
                .filter(Expression::isMethodCallExpr)
                .map(Expression::asMethodCallExpr)
                .filter(method -> method.getName().getIdentifier().equals("withB"))
                .ifPresent(method -> {
                    final Node leftSide = n.getChildNodes().get(0);
                    final Optional<Expression> scope = n.getScope();
                    final MethodCallExpr withC = new MethodCallExpr("withC", new NameExpr("c"));
                    leftSide.replace(withC);
                    scope.ifPresent(withC::setScope);
                });
        return visit;
    }
```

When I try to print the resulting file with `LexicalPreservingPrinter`, I get this exception stack trace:
```
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:58)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:365)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:376)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:376)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:376)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:376)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:376)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:376)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$storeInitialText$3(LexicalPreservingPrinter.java:345)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialText(LexicalPreservingPrinter.java:342)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$setup$0(LexicalPreservingPrinter.java:112)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.setup(LexicalPreservingPrinter.java:111)
...
```

**Comment by jlerbsc** [comment]
Hi @ovesh did you setup the LexicalPreservingPrinter? I cannot reproduce your issue with this unit test

    @Test
    public void test() {
        String code = "public class A {\n" +
                "  public void m() {\n" +
                "     a.withA().withB().withC().build;\n" +
                "  }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        LexicalPreservingPrinter.setup(cu);
        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        for (MethodCallExpr expr : mces) {
            expr.getScope()
                    .filter(Expression::isMethodCallExpr)
                    .map(Expression::asMethodCallExpr)
                    .filter(method -> method.getName().getIdentifier().equals("withB"))
                    .ifPresent(method -> {
                        final Node leftSide = expr.getChildNodes().get(0);
                        final Optional<Expression> scope = expr.getScope();
                        final MethodCallExpr withC = new MethodCallExpr("withC", new NameExpr("c"));
                        leftSide.replace(withC);
                        scope.ifPresent(withC::setScope);
                    });
        }
        System.out.println(LexicalPreservingPrinter.print(cu));
    }
    }

**Comment by ovesh** [comment]
I can reproduce with this test case:
```java
    @Test
    public void testX() {
        String code = "public class A {\n" +
                "  public void m() {\n" +
                "     a.withA().withB().build();\n" +
                "  }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        for (MethodCallExpr expr : mces) {
            expr.getScope()
                    .filter(Expression::isMethodCallExpr)
                    .map(Expression::asMethodCallExpr)
                    .filter(method -> method.getName().getIdentifier().equals("withB"))
                    .ifPresent(method -> {
                        final Node leftSide = expr.getChildNodes().get(0);
                        final Optional<Expression> scope = expr.getScope();
                        final MethodCallExpr withC = new MethodCallExpr("withC", new NameExpr("c"));
                        leftSide.replace(withC);
                        scope.ifPresent(withC::setScope);
                    });
        }
        LexicalPreservingPrinter.setup(cu);
        System.out.println(LexicalPreservingPrinter.print(cu));
    }
```

(the biggest change being that I moved where I set up the printer to the end)

**Comment by jlerbsc** [comment]
But LexicalPreservingPrinter must be setup before the compilation unit is updated.

**Comment by ovesh** [comment]
Yeah, I realized that thanks to your comment. I still think the stack trace is a little inscrutable for most users. It can be fixed by catching the exception and throwing something with a hint in the error message. I can create a PR if you think it's worth it.

**Comment by jlerbsc** [comment]
You are right the stacktrace is not user friendly (but it's a bug!). I will patch the bug on Optional.get() usage. Thank you for your comment.

**Comment by ovesh** [comment]
I tried this out locally, and it ends up reporting an error further down, which I think is not really helpful (something like the node is missing a range). In addition to fixing the unsafe `Optional.get()` calls, it would make sense IMO to throw an exception that suggests to check if the printer is initialized.
