### ISSUE TITLE
UnsolvedSymbolException thrown on Stream.<func>(<some lambda>).

### ISSUE THREAD

**Issue by qzchenwl** [javaparser/javaparser#2943]
When parsing following code:
```java
package foo;
import java.util.stream.Collectors;
import java.util.stream.IntStream;
import java.util.stream.Stream;
public class TestPeek {
    public void foo() {
        Stream.of(1,2,3).peek(info -> { System.out.println(info); }).collect(Collectors.toList());
    }
}
```

When trying to resolve the `MethodCallExpr`, I get the following exception:
```
Exception in thread "main" UnsolvedSymbolException{context='Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
}).collect(Collectors.toList())', name='Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
})', cause='java.lang.RuntimeException: Method 'peek' cannot be resolved in context Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
}) (line: 7) MethodCallExprContext{wrapped=Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
})}. Parameter types: [com.github.javaparser.resolution.types.ResolvedVoidType@179ece50]'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:171)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:321)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:183)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at com.sankuai.ia.parser.Test.lambda$null$0(Test.java:45)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.sankuai.ia.parser.Test.lambda$main$1(Test.java:42)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.ifClassOrInterfaceDeclaration(ClassOrInterfaceDeclaration.java:276)
	at com.sankuai.ia.parser.Test.main(Test.java:40)
Caused by: java.lang.RuntimeException: Method 'peek' cannot be resolved in context Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
}) (line: 7) MethodCallExprContext{wrapped=Stream.of(1, 2, 3).peek(info -> {
    System.out.println(info);
})}. Parameter types: [com.github.javaparser.resolution.types.ResolvedVoidType@179ece50]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:748)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:320)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:97)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:551)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:398)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:414)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:380)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:172)
	... 10 more
```

For reproduction:
```java
package test;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.body.TypeDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.stmt.Statement;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class Test {
    public static void main(String[] args) {
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(
                "package foo;\n"
                        + "import java.util.stream.Collectors;\n"
                        + "import java.util.stream.IntStream;\n"
                        + "import java.util.stream.Stream;\n"
                        + "public class TestPeek {\n"
                        + "    public void foo() {\n"
                        + "        Stream.of(1,2,3).peek(info -> { System.out.println(info); }).collect(Collectors.toList());\n"
                        + "    }\n"
                        + "}"
        );

        for (TypeDeclaration<?> type : cu.getTypes()) {
            type.ifClassOrInterfaceDeclaration(classDecl -> {
                for (MethodDeclaration method : classDecl.getMethods()) {
                    method.getBody().ifPresent(body -> {
                        for (Statement stmt : body.getStatements()) {
                            for (MethodCallExpr methodCallExpr : stmt.findAll(MethodCallExpr.class)) {
                                ResolvedMethodDeclaration resolvedMethodCall = methodCallExpr.resolve();
                                String methodSig = resolvedMethodCall.getQualifiedSignature();
                                System.out.println(methodSig);
                            }
                        }
                    });
                }
            });
        }
    }
}

```

**Comment by jlerbsc** [comment]
@MysterAitch I need your help to solve this issue. I cannot determine the point where the logic is not correct.
What I understood is when JP tries to solve the type of 

    Stream.of(1,2,3).peek(info -> { System.out.println(info); })

it tries to solve a MethodCallExpr with one parameter of type LambdaExpr
it solves the argument expression "info -> { System.out.println(info);}" to a ResolvedVoidType
So it seeks a method defined as follows Stream.peek(ResolvedVoidType)
It cannot find this method and throws a RuntimeTimeException then an UnsolvedSymbolException.

Perhaps in JavaParserfacade.solveMethodAsUsage(MethodCallExpr call). In the case of a method like Stream.peek (which takes a Consumer function in parameter) the return type of the Consumer function must not define the type parameter of the method peek. It's not easy to translate but I try an explanation. Sorry if i am confused.

**Comment by jlerbsc** [comment]
Thanks @qzchenwl for your contribution.
