### ISSUE TITLE
Cannot resolve MethodCallExpr with generic type argument.

### ISSUE THREAD

**Issue by qzchenwl** [javaparser/javaparser#2960]
Parsing the following code:
```java
package foo;
import foo.A;
import foo.B;
public class Test {
    public void foo() {
        A a = new A();
        B b = new B();
        a.a(b.b());
    }
}
```
while `A` and `B` is defined:
```java
// -------- File: foo/A.java -----------
package foo;
public class A {
    public void a(Long x) {
    }
}
// -------- File: foo/B.java -----------
package foo;
public class B {
    public <T> T b() {
        return null;
    }
}
```
when solve `MethodCallExpr` `a.a(b.b())`, throws exception:
```java
Unsolved symbol : We are unable to find the method declaration corresponding to a.a(b.b())
UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to a.a(b.b())', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:167)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
...
```

---
Code to reproduce:
```java
    @Test
    public void testIt() {
        ParserConfiguration config = new ParserConfiguration();
        CombinedTypeSolver typeResolver = new CombinedTypeSolver(new ReflectionTypeSolver(false));
        typeResolver.add(new JavaParserTypeSolver("src/test/resources/issue2960"));
        config.setSymbolResolver(new JavaSymbolSolver(typeResolver));
        StaticJavaParser.setConfiguration(config);

        String code = "package foo;\n"
                + "import foo.A;\n"
                + "import foo.B;\n"
                + "public class Test {\n"
                + "    public void foo() {\n"
                + "        A a = new A();\n"
                + "        B b = new B();\n"
                + "        a.a(b.b());\n"
                + "    }\n"
                + "}";

        CompilationUnit cu = StaticJavaParser.parse(code);
        for (MethodCallExpr methodCallExpr : cu.findAll(MethodCallExpr.class)) {
            if (methodCallExpr.getNameAsString().equals("a")) {
                methodCallExpr.resolve();
            }
        }
    }
```

**Comment by qzchenwl** [comment]
Maybe `ReferenceTypeImpl(Long).isAssignableBy(TypeVariable(T))` should return true.

Reference issue: https://github.com/javaparser/javasymbolsolver/issues/247
