### ISSUE TITLE
StackOverflow error

### ISSUE THREAD

**Issue by mfarsikov** [javaparser/javaparser#2987]
Solving method call causes StackOverflow error on `v3.18.0`.
Parsed class:
```java
class ClassA {
    void f() {
        String s = "";
        String t = (s.length() == 0 ? "*" : s) + "" ;
    }
}
```

Setup:
```kotlin
fun main() {

    val path = Paths.get("src/test/resources/stackoverflowErr")

    val javaSymbolSolver = JavaSymbolSolver(CombinedTypeSolver(ReflectionTypeSolver(), JavaParserTypeSolver(path)))
    
    SourceRoot(path, ParserConfiguration().setSymbolResolver(javaSymbolSolver))
        .tryToParse()
        .map { it.result.get() }
        .map { it.accept(MethodCallResolver(), Unit) }

}

class MethodCallResolver : GenericListVisitorAdapter<Any, Unit>() {
    override fun visit(methodCall: MethodCallExpr, arg: Unit): List<*> {
        methodCall.resolve()
        return emptyList<Any>()
    }
}
```

```
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.getContext(JavaParserFactory.java:138)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:32)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
...
```

**Comment by duTianze** [comment]
## i found it !!  
*use 3.17.0 Can solve this problem*

**Comment by zhangziqiang1** [comment]
Try use 3.18.0 to solve it

**Comment by jlerbsc** [comment]
Hi @mfarsikov have you try the version 3.18.0? Is this issue still present in this version?

**Comment by mfarsikov** [comment]
Hi @jlerbsc! Yes, as I mentioned, I use `3.18.0`

**Comment by twelveand0** [comment]
I have encountered the same StackOverflow error when resolving ConditionalExpr. However, I found this error didn't happen in version 3.16.1.
