### ISSUE TITLE
 methodCallExpr.resolve()  StackOverflowError

### ISSUE THREAD

**Issue by wuyqcode** [javaparser/javaparser#3024]
Hi.when i  use methodCallExpr.resolve() in this code, StackOverflowError happened. 
Can anyone see what caused this. Thanks

## version
```pom
		<dependency>
			<groupId>com.github.javaparser</groupId>
			<artifactId>javaparser-symbol-solver-core</artifactId>
			<version>3.18.0</version>
		</dependency>
```
##  code
```java
    public static void main(String[] args) {
        StaticJavaParser.getConfiguration()
                        .setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        
        CompilationUnit parse = StaticJavaParser.parse("public class Test {\n" +
                                                       "\n" +
                                                       "    public static Test getInstance() {\n" +
                                                       "        return new Test();\n" +
                                                       "    }\n" +
                                                       "\n" +
                                                       "    public void validateBean() {\n" +
                                                       "        Test.getInstance().new InnerClass();\n" +
                                                       "    }\n" +
                                                       "\n" +
                                                       "    public class InnerClass {\n" +
                                                       "        private boolean hasErrors;\n" +
                                                       "    }\n" +
                                                       "}");

        List<MethodCallExpr> methodCallExprList = parse.findAll(MethodCallExpr.class);
        for (MethodCallExpr methodCallExpr : methodCallExprList) {
            methodCallExpr.resolve();
        }
    }
```

## error log
```java
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.utils.Log.makeFormattingSupplier(Log.java:123)
	at com.github.javaparser.utils.Log.trace(Log.java:119)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:318)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:97)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:551)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:398)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:380)
```

**Comment by jlerbsc** [comment]
It's reproducible with your test case, thanks for reporting this bug.

**Comment by jlerbsc** [comment]
Resolution of the scope of the method call expression is delegated to parent context. In this case the parent context is an object creation expression [Test.getInstance().new InnerClass()] that have a method call expression scope [Test.getInstance()]. So JP loops indefinitely. To avoid this Jp must ensure that the scope of the parent context is not the same as the current node.
