### ISSUE TITLE
Unable to parse class with generic parameter using JavaParserTypeSolver 

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3027]
Hello guys.
First of all, thanks for this amazing tool!

When I was working with it, i noticed that sometimes the _JavaParserTypeSolver_ was unable to resolve some of the Classes.
When diving deeper in what was going on, noticed that all of them were generic types, like the class C in the example below.

```java
package com.example;

public class A<X> {

    private class B {}

    private class C<Z> extends A<Z>.B {}

}
```

During debuging found out the issue was related with the **JavaParserTypeSolver** that tried to look for a file that doesn't exist.
In the given example the file would look for "/A\<Z\>/B.java" instead of Class B inside of "A.java".

#### Expected Behavior

When resolving a type that can't be found by a type solver, it should throw a _UnsolvedSymbolException_ (Based on [documentation](https://javadoc.io/doc/com.github.javaparser/javaparser-symbol-solver-model/latest/com/github/javaparser/symbolsolver/model/resolution/TypeSolver.html#solveType-java.lang.String-)).

#### Current Behavior

When resolving the class an _UncheckedExecutionException_ is thrown.
```
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.nio.file.InvalidPathException: Illegal char <<> at index 65: C:\Users\User\AppData\Local\Temp\tempProject6055408844541354802/A<Z>/B.java
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2051)
	at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:4848)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveType(JavaParserTypeSolver.java:202)
	at com.github.javaparser.symbolsolver.model.resolution.TypeSolver.solveType(TypeSolver.java:66)
	at pt.forever.university.analyser.TestBug.test0(TestBug.java:788)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.ExpectException.evaluate(ExpectException.java:19)
	... 17 more
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 65: C:\Users\User\AppData\Local\Temp\tempProject6055408844541354802/A<Z>/B.java
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:94)
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:255)
	at java.nio.file.Paths.get(Paths.java:84)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.tryToSolveTypeUncached(JavaParserTypeSolver.java:234)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.lambda$tryToSolveType$4(JavaParserTypeSolver.java:203)
	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:4853)
	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3529)
	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2278)
	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2155)
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2045)
	... 31 more
```

#### Test for issue

The following test can recreate the issue.
The test is composed of the following steps:

1. Create a path with the root sources (may be empty);
2. Create a new JavaParserTypeSolver and provide the root sources as parameter;
3. Use the created type solver to resolve a type with inner class and a outer class where the outer class has a generic parameter.

Test 1:
```java
@Test(expected = UnsolvedSymbolException.class)
public void testUsingParameterizedClass() throws IOException {

    Path temporaryProject = Files.createTempDirectory("temporaryProject");
    new JavaParserTypeSolver(temporaryProject)
            .solveType("A<Z>");
}
```

Test 2:
```java
@Test(expected = UnsolvedSymbolException.class)
public void testUsingParameterizedOuterClass() throws IOException {

    Path temporaryProject = Files.createTempDirectory("temporaryProject");
    new JavaParserTypeSolver(temporaryProject)
            .solveType("A<Z>.B");
}
```

**Comment by MysterAitch** [comment]
Thank you for the detailed report!

**Comment by jlerbsc** [comment]
At this stage i'm not sure that JP have to throw an UnsolvedSymbolException exception perhaps just returns an unsolved SymbolReference.
