### ISSUE TITLE
JavaParserInterfaceDeclaration#containerType() throwing IllegalArgumentException

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3061]
When trying to get the container type of a JavaParserInterfaceDeclaration is throwing an IllegalArgumentException.
```java
void originalTest() {
    StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));

    ResolvedReferenceTypeDeclaration classOrInterface = StaticJavaParser.parse("interface A {}")
            .findFirst(ClassOrInterfaceDeclaration.class)
            .get()
            .resolve();
    assertNotNull(classOrInterface.containerType());
}
```
```java
void simplifiedTest() {
  TypeSolver typeSolver = new ReflectionTypeSolver();
  ClassOrInterfaceDeclaration classOrInterface = StaticJavaParser.parse("interface A {}")
          .findFirst(ClassOrInterfaceDeclaration.class)
          .get();
  JavaParserInterfaceDeclaration interfaceDeclaration = new JavaParserInterfaceDeclaration(classOrInterface, typeSolver);
  assertNotNull(interfaceDeclaration.containerType());
}
```

The stack trace is the following:
```
java.lang.IllegalArgumentException: com.github.javaparser.ast.CompilationUnit

	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.toTypeDeclaration(JavaParserFactory.java:180)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeAdapter.lambda$containerType$0(JavaParserTypeAdapter.java:164)
	at java.util.Optional.map(Optional.java:215)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeAdapter.containerType(JavaParserTypeAdapter.java:164)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserInterfaceDeclaration.containerType(JavaParserInterfaceDeclaration.java:370)
```

**Comment by 4everTheOne** [comment]
After additional testing, noticed that this issue also affects classes and enums.

```java
@Test
void testWithClass() {
    StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));

    ResolvedReferenceTypeDeclaration classOrInterface = StaticJavaParser.parse("class A {}")
            .findFirst(ClassOrInterfaceDeclaration.class)
            .get()
            .resolve();
    assertNotNull(classOrInterface.containerType());
}

@Test
void testWithEnum() {
    StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));

    ResolvedReferenceTypeDeclaration classOrInterface = StaticJavaParser.parse("enum A {}")
            .findFirst(EnumDeclaration.class)
            .get()
            .resolve();
    assertNotNull(classOrInterface.containerType());
}
```

**Comment by jlerbsc** [comment]
What is the expected result? According to you what is the **container** type of a ClassOrInterfaceDeclaration?

**Comment by 4everTheOne** [comment]
To be honest, i still learning about the terms used, and the term "container type" is not fully clear what it is. 
But my interpretation of the container is where the class is declared. In this case, since it is in the compilation unit i would expect to be the compilation unit itself or an empty container.

**Comment by jlerbsc** [comment]
I believe the term refers to the container node that contains the current node. This is also what is implemented. The container node is a CompilationUnit which does not represent a type. So i don't think there is an issue in this case.
