### ISSUE TITLE
Prevent JarTypeSolver from Analysing

### ISSUE THREAD

**Issue by dimizisis** [javaparser/javaparser#3065]
I wrote the following code, in order to create a symbol solver instance:

```java
private static void createSymbolSolver() {
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(getCurrentProject()));
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();

        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();

        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
}
```

But after some code analysis I observed that JarSymbolSolver is triggered, too (I only want Java source code analysis). Is there any way to prevent JarTypeSolver from analyzing the jars in the project? For now, I just delete all the jars.

Sorry for possible dump question, it's my first issue opening. :)

Tested with javaparser version 3.18.0

**Comment by jlerbsc** [comment]
It's curious are you sure?

**Comment by dimizisis** [comment]
I believe I am. I encountered an error in projects that had dummy jars. When I deleted them, the analysis was successful. 

Here's a snapshot of the error I kept (unfortunatelly is not complete):

```
Collecting source roots...
Exception in thread "main" java.lang.RuntimeException: javassist.NotFoundException: /home/nikolaidis/Documents/projects/nifi/nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/resources/dummy-lib.jar
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver.addPathToJar(JarTypeSolver.java:110)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver.<init>(JarTypeSolver.java:67)
        at com.github.javaparser.symbolsolver.utils.SymbolSolverCollectionStrategy$1.visitFile(SymbolSolverCollectionStrategy.java:87)
        at com.github.javaparser.symbolsolver.utils.SymbolSolverCollectionStrategy$1.visitFile(SymbolSolverCollectionStrategy.java:75)
        at java.nio.file.Files.walkFileTree(Files.java:2670)
        at java.nio.file.Files.walkFileTree(Files.java:2742)
        at com.github.javaparser.symbolsolver.utils.SymbolSolverCollectionStrategy.collect(SymbolSolverCollectionStrategy.java:75)
        at metricsCalculator.calculator.MetricsCalculator.getProjectRoot(MetricsCalculator.java:64)
        at metricsCalculator.calculator.MetricsCalculator.start(MetricsCalculator.java:45)
        at main.Main.getMetricsCalculatorMetrics(Main.java:183)
        at main.Main.main(Main.java:44)
Caused by: javassist.NotFoundException: /home/nikolaidis/Documents/projects/nifi/nifi-nar-bundles/nifi-jms-bundle/nifi-jms-processors/src/test/resources/dummy-lib.jar
        at javassist.JarClassPath.<init>(ClassPoolTail.java:152)
        at javassist.ClassPoolTail.makePathObject(ClassPoolTail.java:274)
        at javassist.ClassPoolTail.appendClassPath(ClassPoolTail.java:266)
        at javassist.ClassPool.appendClassPath(ClassPool.java:982)
        at com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver.addPathToJar(JarTypeSolver.java:107)
        ... 10 more
```

**Comment by jlerbsc** [comment]
It seems that SymbolSolverCollectionStrategy uses JarTypeSolver.

**Comment by dimizisis** [comment]
Any ideas on how to edit the collection strategy?

**Comment by jlerbsc** [comment]
What do you mean?

**Comment by dimizisis** [comment]
Is there any way to give instruction to the SymbolSolverCollectionStrategy, in order not to use JarTypeSolver?

**Comment by jlerbsc** [comment]
You can maybe change strategy and use the class ParserCollectionStrategy

**Comment by jlerbsc** [comment]
Did you try ParserCollectionStrategy ?

**Comment by dimizisis** [comment]
Sorry for the delayed response,

I tried this:

```java
TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(getCurrentProject()));
TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();

CombinedTypeSolver combinedSolver = new CombinedTypeSolver();

combinedSolver.add(reflectionTypeSolver);
combinedSolver.add(javaParserTypeSolver);

ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(combinedSolver));

StaticJavaParser
          .setConfiguration(parserConfiguration);
```

and this:

```java
return new ParserCollectionStrategy(StaticJavaParser.getConfiguration())
                .collect(Paths.get(getCurrentProject()));
```
Indeed, now it does not try to parse JAR files. So to my understanding, with this code I only parse Java files, given a source root? If yes, that's exactly what I need. I'm not sure about the necessity of ReflectionTypeSolver, though.

Thanks!

**Comment by jlerbsc** [comment]
If you need to solve symbols you have to configure the symbol solver otherwise you don't need to configure a TypeSolver.
