### ISSUE TITLE
StackOverflowError when get all method invocations and resolve them

### ISSUE THREAD

**Issue by lingchaochen** [javaparser/javaparser#3069]
When I am trying to get all method invocations in a file and resolve them, I get StackOverflowError when the source code likes:
```
public class Pair<K, V> {
        @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Pair)) {
            return false;
        } else {
            Pair<?, ?> oP = (Pair<?, ?>) o;
            return (key == null ?
                    oP.key == null :
                    key.equals(oP.key)) &&
                (value == null ?
                 oP.value == null :
                 value.equals(oP.value));
        }
    }
}
```
The stack trace shows as following:
```
Exception in thread "main" java.lang.StackOverflowError
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.getContext(JavaParserFactory.java:138)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:32)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
```

My solver is using:
```
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(srcPath));
        combinedSolver.add(javaParserTypeSolver);
        combinedSolver.add(reflectionTypeSolver);
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        StaticJavaParser
            .getConfiguration()
            .setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(new FileInputStream(filePath));
```

**Comment by jlerbsc** [comment]
Hi @lingchaochen There is no parsing error in the current JP version and the unit test below doesn't generate  any exception

    @Test
    void d() {
        String code = 
                "public class Pair<K, V> {\n" + 
                **"    K key;\n" + 
                "    V value;" +**
                "    @Override\n" + 
                "    public boolean equals(Object o) {\n" + 
                "        if (this == o) {\n" + 
                "            return true;\n" + 
                "        }\n" + 
                "        if (!(o instanceof Pair)) {\n" + 
                "            return false;\n" + 
                "        } else {\n" + 
                "            Pair<?, ?> oP = (Pair<?, ?>) o;\n" + 
                "            return (key == null ?\n" + 
                "                    oP.key == null :\n" + 
                "                    key.equals(oP.key)) &&\n" + 
                "                (value == null ?\n" + 
                "                 oP.value == null :\n" + 
                "                 value.equals(oP.value));\n" + 
                "        }\n" + 
                "    }\n" + 
                "};";
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);

        List<MethodCallExpr> exprs = cu.findAll(MethodCallExpr.class);
        exprs.forEach(expr -> {
            System.out.println(expr.toString() + " resolved to " +expr.resolve().getQualifiedName());
        });

Can you specify the problem you are having?

**Comment by lingchaochen** [comment]
> Hi @lingchaochen There is no parsing error in the current JP version and the unit test below doesn't generate any exception
> 
> ```
> @Test
> void d() {
>     String code = 
>             "public class Pair<K, V> {\n" + 
>             **"    K key;\n" + 
>             "    V value;" +**
>             "    @Override\n" + 
>             "    public boolean equals(Object o) {\n" + 
>             "        if (this == o) {\n" + 
>             "            return true;\n" + 
>             "        }\n" + 
>             "        if (!(o instanceof Pair)) {\n" + 
>             "            return false;\n" + 
>             "        } else {\n" + 
>             "            Pair<?, ?> oP = (Pair<?, ?>) o;\n" + 
>             "            return (key == null ?\n" + 
>             "                    oP.key == null :\n" + 
>             "                    key.equals(oP.key)) &&\n" + 
>             "                (value == null ?\n" + 
>             "                 oP.value == null :\n" + 
>             "                 value.equals(oP.value));\n" + 
>             "        }\n" + 
>             "    }\n" + 
>             "};";
>     ParserConfiguration config = new ParserConfiguration();
>     config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
>     StaticJavaParser.setConfiguration(config);
> 
>     CompilationUnit cu = StaticJavaParser.parse(code);
> 
>     List<MethodCallExpr> exprs = cu.findAll(MethodCallExpr.class);
>     exprs.forEach(expr -> {
>         System.out.println(expr.toString() + " resolved to " +expr.resolve().getQualifiedName());
>     });
> ```
> 
> Can you specify the problem you are having?

Hi @jlerbsc, thanks for your reply. When I run the unit test I still get the same exception.
```
java.lang.StackOverflowError
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFactory.getContext(JavaParserFactory.java:138)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:32)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnclosedExprContext.patternExprsExposedFromChildren(EnclosedExprContext.java:33)
```

I am building with Maven 3.6.3, Java 1.8.0_131, OS macos 10.16, Javaparser 3.18.0.
Is it because of my environment configuration?

**Comment by jlerbsc** [comment]
Can you try with the snapshot version?

**Comment by lingchaochen** [comment]
Sure, I just try with the lasted 3.18.1-SNAPSHOT on Github. It still has the same error.

**Comment by jlerbsc** [comment]
On my side the result is

    key.equals(oP.key) resolved to java.lang.Object.equals
    value.equals(oP.value) resolved to java.lang.Object.equals

**Comment by lingchaochen** [comment]
I try another machine on Unbuntu 18.04.2. It works well.

**Comment by jlerbsc** [comment]
Did you solve this issue? Maybe is it related to your environment?

**Comment by jlerbsc** [comment]
This issue is not reproducible, I am closing it but you can reopen it if you can provide additional information allowing us to confirm the problem.
