### ISSUE TITLE
Unable to solve NameExpr in Annotation

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3094]
I have the following class
```java
@interface Foo { 
    int a = 0; 
    int b = a; 
}
```
When i try to resolve the reference, it throws a UnsupportedOperationException. This happens because method `getAllFields` is not implemented `JavaParserAnnotationDeclaration` and according to issue https://github.com/javaparser/javaparser/issues/1837 annotations should not have fields. The problem gets confusing when the AST parses the annotation with a field declaration on it.

Should it be consider a problem with  `JavaParserAnnotationDeclaration` or with the parser?

#### AST from the example
![graphviz](https://user-images.githubusercontent.com/5434488/108416838-28e02000-7227-11eb-88c6-2f34b6f8147f.png)

#### Stack trace
```
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserAnnotationDeclaration.getAllFields(JavaParserAnnotationDeclaration.java:68)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.hasField(ResolvedReferenceTypeDeclaration.java:150)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AnnotationDeclarationContext.solveSymbol(AnnotationDeclarationContext.java:53)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveSymbol(Context.java:115)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbol(SymbolSolver.java:70)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbol(SymbolSolver.java:74)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:171)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:181)
	at com.github.javaparser.ast.expr.NameExpr.resolve(NameExpr.java:170)
	at org.junit.jupiter.api.AssertDoesNotThrow.assertDoesNotThrow(AssertDoesNotThrow.java:72)
```

#### Unit test
```java
@Test
void test() {
  StaticJavaParser.getConfiguration()
		.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));

  String sourceCode = "@interface Foo { int a = 0; int b = a; }";

  CompilationUnit cu = StaticJavaParser.parse(sourceCode);

  Optional<NameExpr> nameExpr = cu.findFirst(NameExpr.class);
  assertTrue(nameExpr.isPresent());
  assertDoesNotThrow(nameExpr.get()::resolve);
}
```

**Comment by jlerbsc** [comment]
It seems that AnnotationTypeMemberDeclaration can be can be a ConstantDeclaration (https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-AnnotationTypeBody 9.6.1. Annotation Type Elements). I'm not sure that these constante declarations must be returned by getAllFields method. @matozoid , @MysterAitch @ftomassetti have you an idea on this topic?

**Comment by 4everTheOne** [comment]
Looking at the documentation, the definition of Constant Declaration (https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-ConstantDeclaration) shows:

> Every field declaration in the body of an interface is implicitly public, static, and final. It is permitted to redundantly specify any or all of these modifiers for such fields.

With this I think it's safe to say it's a field. What is the team opinion?

**Comment by MysterAitch** [comment]
I originally got muddled between `AnnotationTypeElementDeclaration` (the ones with the `()` at the end that indicate members of the annotation) versus regular fields. This led down a rabbit hole of having it extend field etc... I was wrong there! Turns out we can have both :)

Summary: My understanding is that annotation declarations _can_ have fields (and nested-classes/interfaces/enums etc), so the method `getAllFields()` _should_ be implemented. 



Note: 
> Unless explicitly modified herein, all of the rules that apply to normal interface declarations apply to annotation type declarations. 
> https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6

**Comment by 4everTheOne** [comment]
Thank you for the feedback MysterAitch! Can I submit a PR with the fix for this?
