### ISSUE TITLE
IllegalArgumentException when solving ClassOrInterfaceType

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3099]
JP Symbol Solver throws a `IllegalArgumentException` when we have a type definition that matches the name of a implemented type.

#### File structure:
```
.
└── com/example
    ├── Alpha.java
    └── Beta.java
```
#### Files content
Alpha.java
```java
package com.example;

interface Alpha {
  interface CustomInterface {}
}
```

Beta.java
```java
package com.example;

class Beta implements Alpha.CustomInterface {
  
  public interface CustomInterface<T> {}

  private final CustomInterface<Object> instanceOfBetaInnerClass;

}
```

### Explanation
The solver solves `CustomInterface` as `Alpha.CustomInterface` instead of  `Beta.CustomInterface`.

### Possible fix
I think this issue is related with the logic in method `ClassOrInterfaceDeclarationContext#solveType(String)` that gives priority to implemented and extended types over the local logic. I think this could be fixed by prioritizing the local search over the others.
https://github.com/javaparser/javaparser/blob/be4e455f228eaf6500e6aa47c8472b708826ee27/javaparser-symbol-solver-core/src/main/java/com/github/javaparser/symbolsolver/javaparsermodel/contexts/ClassOrInterfaceDeclarationContext.java#L108-L144

### Stack trace
```
java.lang.IllegalArgumentException: expected either zero type arguments or has many as defined in the declaration (0). Found 1

	at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:78)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:76)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:646)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:606)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:281)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:314)
```
### Unit test
```java
@Test
void illegalArgumentExceptionWhenSolvingName() throws IOException {

  // Setup symbol solver
  JavaParserTypeSolver javaParserTypeSolver = new JavaParserTypeSolver(adaptPath("src/test/resources/issueXXX/"));
  StaticJavaParser.getConfiguration()
		  .setSymbolResolver(new JavaSymbolSolver(
				  new CombinedTypeSolver(new ReflectionTypeSolver(), javaParserTypeSolver))
		  );
  
  // Parse the File
  Path filePath = adaptPath("src/test/resources/issueXXX/com/example/Beta.java");
  CompilationUnit cu = StaticJavaParser.parse(filePath);
  
  // Get the expected inner class
  List<ClassOrInterfaceDeclaration> classes = cu.findAll(ClassOrInterfaceDeclaration.class);
  assertEquals(2, classes.size());
  ResolvedReferenceTypeDeclaration innerInterface = classes.get(1).resolve();
  assertTrue(innerInterface.isInterface());
  
  // Check if the value is present
  Optional<ResolvedReferenceType> resolvedType = cu.findFirst(VariableDeclarator.class)
		  .map(VariableDeclarator::getType)
		  .map(Type::resolve)
		  .filter(ResolvedType::isReferenceType)
		  .map(ResolvedType::asReferenceType);
  assertTrue(resolvedType.isPresent());
  assertEquals(innerInterface, resolvedType.get().getTypeDeclaration().orElse(null));
}
```

**Comment by 4everTheOne** [comment]
Looks like the issue is not that simple. Tried to reorder the logic, but it creates side effects.

**Comment by 4everTheOne** [comment]
To make it easier to test the issue, here is a branch with the test case.
https://github.com/4everTheOne/javaparser/blob/test-case/3099/javaparser-symbol-solver-testing/src/test/java/com/github/javaparser/symbolsolver/Issue3099Test.java
