### ISSUE TITLE
Resolving a type in a context 

### ISSUE THREAD

**Issue by bonbunpiw** [javaparser/javaparser#3116]
I got 2 issues after tried this code example when update FILE_PATH and SRC_PATH to my specific project.

1. reflectionTypeSolver.setParent(reflectionTypeSolver);
error:
Exception in thread "main" java.lang.IllegalStateException: The parent of this TypeSolver cannot be itself.
	at com.github.javaparser.symbolsolver.resolution.typesolvers.ClassLoaderTypeSolver.setParent(ClassLoaderTypeSolver.java:60)
	at CustomContextSolver.main(CustomContextSolver.java:20)

2. System.out.println("Field type: " + fieldDeclaration.getVariables().get(0).getType().resolve().asReferenceType().getQualifiedName());
error:
Exception in thread "main" UnsolvedSymbolException{context='null', name='Options', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:670)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:645)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:281)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:301)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60)
	at CustomContextSolver.main(CustomContextSolver.java:34)

Is it about the project path ? (I attach the main source code and file structure, see below)
<img width="1039" alt="Screen Shot 2564-02-26 at 09 34 05" src="https://user-images.githubusercontent.com/13906128/109247181-06956600-7816-11eb-887b-27da6a4bb5a5.png">
<img width="1282" alt="Screen Shot 2564-02-26 at 09 35 32" src="https://user-images.githubusercontent.com/13906128/109247185-085f2980-7816-11eb-993b-644adb3c9c4c.png">

**Comment by MysterAitch** [comment]
You're correct that it's the project path that's the problem.

Currently, `SRC_PATH` seems to refer to what I call the "project root".

Instead, the source root is required (the directory to which packages are relative) -- usually the `src/main/java/` directory within maven projects.

**Comment by jlerbsc** [comment]
Answers have been given to these questions. I'm closing this issue but you can reopen it if you want more information.
For the first question the message " The parent of this TypeSolver cannot be itself."  seems to be explicit enough. It doesn't make sense to create a solver-like hierarchy that reference each other. It would certainly produce an infinite loop.
