### ISSUE TITLE
Java Symbol Solver not able to resolve Symbol containing FieldAccessExpr as Argument 

### ISSUE THREAD

**Issue by f71uday** [javaparser/javaparser#3117]
File 1 :   Test.java 

```
import javax.servlet.http.HttpServletRequest;

public class Test {
    public static final String a = "none";
   

}

```
File 2 : JavaFiletobeResolved.java
```
import javax.net.ssl.SSLContext;
import java.security.NoSuchAlgorithmException;

public class JavaFiletobeResolved {
   
    public void test4() throws NoSuchAlgorithmException {
        SSLContext.getInstance(Test.A);
    }
}


```

File 3:  ResolveMethodCalling.java

```
private static void resolveMethodCall(MethodCallExpr methodCallExpr) {
        try {

            ResolvedMethodDeclaration resolvedMethodDeclaration = methodCallExpr.resolve();
           
            

        }catch(UnsolvedSymbolException e){
            logException(e);
        }catch(Exception e){
            logException(e);
        }
    }

```
Note :  Test.java and JavaFiletobeResolved.java are in same package.

Java Symbol Solver not able to be resolve FieldAccessExpr passed as Argument in ` SSLContext.getInstance(Test.A);`   

Error msg :
```
UnsolvedSymbolException{context='null', name='A', cause='null'}

StackTrace :  UnsolvedSymbolException{context='null', name='A', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:237)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:526)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:260)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:279)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:143)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at com.sast.java.scanners.ResolveMethodCalling.resolveMethodCall(ResolveMethodCalling.java:47)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.sast.java.scanners.ResolveMethodCalling.scanJavaFile(ResolveMethodCalling.java:40)
	at com.sast.java.scanners.ResolveMethodCalling.findAll(ResolveMethodCalling.java:30)
	at com.sast.java.utility.SASTApp.scanAll(SASTApp.java:48)
	at com.sast.java.ScannerMain.main(ScannerMain.java:42)
```

**Comment by f71uday** [comment]
@jlerbsc 
a Helping hand would be great.

and if you find this as a real issue , would like to work on it as well

**Comment by f71uday** [comment]
Issue resolved !!  I was passing the wrong path in the JavaParserTypeSolver

**Comment by MysterAitch** [comment]
> Issue resolved !!  I was passing the wrong path in the JavaParserTypeSolver
> 
> 

Apologies I didn't reply sooner!

Really glad you got it sorted in the end :+1:
