### ISSUE TITLE
Bug Report: `java.lang.StackOverflowError` when analyzing a static method call expression

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#3207]
I want to get the fully-qualified name of the type referenced in a method call expression. The core code is as follows:
```java
@Override
public void visit(MethodCallExpr n, Void arg) {
    if (n.getScope().isPresent()) {
        Expression expression = n.getScope().get();
        System.out.println(expression.calculateResolvedType().describe());
    }
    super.visit(n, arg);
}
```
When I analyze the following method within [PageData.java](https://github.com/unclebob/fitnesse/blob/master/src/fitnesse/wiki/PageData.java) of [fitnesse](https://github.com/unclebob/fitnesse):
```java
public void setContent(String content) {
    this.content = StringUtils.remove(content, '\r'); // when get the fully name of StringUtils, it will throws an StackOverflowError
  }
```
I got an `StackOverflowError` error, described as follows:
```java
[10:06:33:527] [INFO] - org.yliu.cumin.solvers.parse.ParseLibsSolverforPREM$1$1.visit(ParseLibsSolverforPREM.java:68) - methodcallexpr: (line 135,col 20), remove
Exception in thread "main" java.lang.StackOverflowError
        at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:4021)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4857)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4802)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4800)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4800)
        at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4765)
        at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4888)
        at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4396)
        at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4857)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4802)
        at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4800)
        at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:4022)
        at java.base/java.util.regex.Pattern$Start.match(Pattern.java:3675)
        at java.base/java.util.regex.Matcher.search(Matcher.java:1728)
        at java.base/java.util.regex.Matcher.find(Matcher.java:772)
        at java.base/java.util.Formatter.parse(Formatter.java:2702)
        at java.base/java.util.Formatter.format(Formatter.java:2655)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:3290)
        at com.github.javaparser.resolution.declarations.ResolvedTypeParameterDeclaration.getQualifiedName(ResolvedTypeParameterDeclaration.java:148)
        at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParametersMap$Builder.setValue(ResolvedTypeParametersMap.java:61)
        at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:87)
        at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:70)
        at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:72)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionFactory.typeUsageFor(ReflectionFactory.java:93)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserEnumDeclaration.getAncestors(JavaParserEnumDeclaration.java:256)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getAncestors(ResolvedReferenceTypeDeclaration.java:71)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserEnumDeclaration.getAllFields(JavaParserEnumDeclaration.java:242)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.hasField(ResolvedReferenceTypeDeclaration.java:153)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnumDeclarationContext.solveSymbol(EnumDeclarationContext.java:62)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:148)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:79)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnumDeclarationContext.solveSymbol(EnumDeclarationContext.java:67)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:148)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:79)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnumDeclarationContext.solveSymbol(EnumDeclarationContext.java:67)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:148)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:79)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnumDeclarationContext.solveSymbol(EnumDeclarationContext.java:67)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:148)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:79)
        at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.EnumDeclarationContext.solveSymbol(EnumDeclarationContext.java:67)
        ...
        
```

The strange thing is that if I only analyze this statement, no error will be reported. 
```java
    public static void main(String[] args) throws IOException {
        Path pathToJar1 = Paths.get("/Users/liuyuan/Workspaces/Task/cumin_test_dataset/fitnesse-jars/commons-lang3-3.9.jar");
        ParserConfiguration config = new ParserConfiguration();
        CombinedTypeSolver cts = new CombinedTypeSolver();
        cts.add(new ReflectionTypeSolver(false));
        cts.add(new JarTypeSolver(pathToJar1));
        config.setSymbolResolver(new JavaSymbolSolver(cts));
        StaticJavaParser.setConfiguration(config);

        String str = "import org.apache.commons.lang3.StringUtils;\n"
                   + "public class foo{ \n"
                   +     "\tprivate String content = \"\";\n"
                   +     "\tpublic void setContent(String content) { \n"
                   +         "\tthis.content = StringUtils.remove(content, '\\r');\n"
                   +      "}}";
        System.out.println(str);
        CompilationUnit cu = StaticJavaParser.parse(str);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        System.out.println(mce.resolve().getQualifiedSignature());
        Expression expression = mce.getScope().get();
        System.out.println(expression.calculateResolvedType().describe());
    }
```

I modify the `Xss`  arg of JVM, but the program will always stay on the analysis of the method call expression (i.e., `StringUtils.remove(content, '\r')`). 

Any suggestions would be greatly appreciated!

**Comment by ghost** [comment]
I have tried the latest JavaParser version packaged by the master branch, it doesn't work.

**Comment by ghost** [comment]
In addition, by testing a single java file including `StringUtils.remove(content, '\r')`, I don't think it was caused by the conflicting jars feed to `JarTypeSolver `. 

So I think this may be a bug.

**Comment by MysterAitch** [comment]
Thank you for the detailed report @liuyuanOUC !

**Comment by jlerbsc** [comment]
I haven't noticed this problem in the current version. It may have been fixed. I am closing this issue but it can be re-opened if the problem has not gone away.
