### ISSUE TITLE
Can't resolve a class

### ISSUE THREAD

**Issue by ronsigal** [javaparser/javaparser#3325]
Hi, 

I have two classes, 
```
package io.grpc.examples.classes2;

public class C1 {
   int i;
   double d;
   C3 c3;
   
   public C1(int i, double d, C3 c3) {
      this.i = i;
      this.d = d;
      this.c3 = c3;
   }
}
```
and
```
package io.grpc.examples.classes2;

public class C3 {
   String s;
   
   public C3(String s) {
      this.s = s;
   }
}
```
and, even though C3 is getting parsed, it's not getting resolved in C1. The code is
```
   private void processClasses(String[] args, StringBuilder sb) throws IOException {

      Path path = Path.of("/home/rsigal/tmp/git.protobuf2/Resteasy/providers/resteasy-protobuf-provider/src/main/java/io/grpc/examples/classes2");
      SourceRoot sourceRoot = new SourceRoot(path);
      TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
      TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(path);
      CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
      combinedTypeSolver.add(reflectionTypeSolver);
      combinedTypeSolver.add(javaParserTypeSolver);
      symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
      sourceRoot.getParserConfiguration().setSymbolResolver(symbolSolver);
      List<ParseResult<CompilationUnit>> list = sourceRoot.tryToParseParallelized();
      for (ParseResult<CompilationUnit> p : list) {
         System.out.println("cu: " + p.getResult().get());  // Finds C1 and C3
         classVisitor.visit(p.getResult().get(), sb);
      }
   }
   ...

   static class ClassVisitor extends VoidVisitorAdapter<StringBuilder> {

      public void visit(final ClassOrInterfaceDeclaration subClass, StringBuilder sb)   {
         ResolvedReferenceTypeDeclaration rrtd = subClass.resolve();
         String fqn = rrtd.getPackageName() + "." + rrtd.getClassName();

         // Scan all variables in class.
         for (BodyDeclaration<?> bd: subClass.getMembers()) {
            if (bd instanceof FieldDeclaration) {
               FieldDeclaration fd = (FieldDeclaration) bd;
               for (VariableDeclarator vd : fd.getVariables()) {
                        ...
                  } else { // Defined message type
                     ReferenceTypeImpl rt = (ReferenceTypeImpl) vd.getType().resolve(); // throws Exception (see below)
                     rrtd = rt.getTypeDeclaration().get();
                            ...
                  }
               }
            }
         }
```
The exception is
```
Exception in thread "main" UnsolvedSymbolException{context='null', name='C3', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:670)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:645)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:281)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:301)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60)
	at org.jboss.resteasy.plugins.protobuf.JavaToProtobufGenerator2$ClassVisitor.visit(JavaToProtobufGenerator2.java:244)
	at org.jboss.resteasy.plugins.protobuf.JavaToProtobufGenerator2$ClassVisitor.visit(JavaToProtobufGenerator2.java:1)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:100)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$43(VoidVisitorAdapter.java:175)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
	at org.jboss.resteasy.plugins.protobuf.JavaToProtobufGenerator2.processClasses(JavaToP
```
Am I doing something really dumb? Any help is greatly appreciated.

-Ron [rsigal@redhat.com]

**Comment by MysterAitch** [comment]
Hi,

Consider your source root:

```java
Path path = Path.of("/home/rsigal/tmp/git.protobuf2/Resteasy/providers/resteasy-protobuf-provider/src/main/java/io/grpc/examples/classes2");
SourceRoot sourceRoot = new SourceRoot(path);
```

Normally the source root is the top level directory, where your files with no package would be stored (usually the `src/main/java` directory for a maven-style project).

Perhaps you could try:
```java
Path path = Path.of("/home/rsigal/tmp/git.protobuf2/Resteasy/providers/resteasy-protobuf-provider/src/main/java"); // /io/grpc/examples/classes2");
SourceRoot sourceRoot = new SourceRoot(path);
```

**Comment by ronsigal** [comment]
Hey @MysterAitch,

Thank you for your rapid response! Indeed, it works! Strangely, I was sure I had tried that yesterday, but, well, who knows. Of course, I get a lot of classes I don't want to  process, but I can deal with that.

You've saved me hours of staring, and I do appreciate it. At some point I'm hoping to use the parser in our project (https://resteasy.github.io/), and I'll make an announcement if that happens.

Thanks again,
Ron

**Comment by MysterAitch** [comment]
Brill -- thank you for the update, glad it helped! 

I look forward to hearing more about your use of JavaParser in RESTEasy :+1:
