### ISSUE TITLE
Failed to resolve methods that evaluate as argument

### ISSUE THREAD

**Issue by apixandru** [javaparser/javaparser#3399]
I'm trying to test the library against the hotspot sources included from oracle.com but I'm not getting very far. 

I attached the classes that I'm working with, I'm pretty sure that any jdk will do as the main entrypoint

[DelegatingSymbolResolver.java](https://github.com/javaparser/javaparser/files/7430868/DelegatingSymbolResolver.java.txt)
[MethodResolverTest.java](https://github.com/javaparser/javaparser/files/7430869/MethodResolverTest.java.txt)

It seems to resolve parseByte(s, radix) fine and when trying to resolve valueOf(parseByte(s, radix)) it seems to know that it's looking for a valueOf method that takes a byte as argument but for some reason it's not picking it up.

I went in to debug it for a bit and in MethodResolutionLogic, lines 179 and 180 have 
expectedDeclaredType = byte
actualArgumentType = byte 
So it's properly identifying the types, just not finding the method

```
Attempting to resolve Class.getPrimitiveClass("byte")
 - belongs to java.lang.Class
Attempting to resolve Integer.toString((int) b, 10)
 - belongs to java.lang.Integer
Attempting to resolve Integer.parseInt(s, radix)
 - belongs to java.lang.Integer
Attempting to resolve parseByte(s, 10)
 - belongs to java.lang.Byte
Attempting to resolve parseByte(s, radix)
 - belongs to java.lang.Byte
Attempting to resolve valueOf(parseByte(s, radix))
Exception in thread "main" UnsolvedSymbolException{context='Serializable', name='com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationExtendsContext@248db3d9', cause='null'}
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveType(SymbolSolver.java:114)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.canBeAssignedTo(JavaParserClassDeclaration.java:287)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.canBeAssignedTo(JavaParserClassDeclaration.java:277)
	at com.github.javaparser.symbolsolver.model.typesystem.ReferenceTypeImpl.isAssignableBy(ReferenceTypeImpl.java:113)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isApplicable(MethodResolutionLogic.java:186)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.lambda$findMostApplicable$3(MethodResolutionLogic.java:522)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:523)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:233)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:111)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveMethod(JavaParserClassDeclaration.java:330)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:820)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:177)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:324)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:186)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.apixandru.java.DelegatingSymbolResolver.resolveDeclaration(DelegatingSymbolResolver.java:15)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:315)
	at com.apixandru.java.MethodResolverTest.visit(MethodResolverTest.java:48)
	at com.apixandru.java.MethodResolverTest.visit(MethodResolverTest.java:17)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:122)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$146(VoidVisitorAdapter.java:474)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:474)
	at com.github.javaparser.ast.stmt.ReturnStmt.accept(ReturnStmt.java:84)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$19(VoidVisitorAdapter.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:109)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:76)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$105(VoidVisitorAdapter.java:370)
	at java.base/java.util.Optional.ifPresent(Optional.java:176)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:370)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:104)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$31(VoidVisitorAdapter.java:154)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:154)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:98)
	at com.apixandru.java.MethodResolverTest.main(MethodResolverTest.java:35)

Process finished with exit code 1

```

**Comment by jlerbsc** [comment]
Hi @apixandru JavaParserTypeSolver must reference the root source dir of the project that you want to parse. If you want to resolve libraries you have to use JarTypeSolver.
Reading the book javaparservisited might be useful to you https://leanpub.com/javaparservisited

In your case, a common initialization of the TypeSolver could be inspired by 

    TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), new JarTypeSolver(pathToJar));

**Comment by apixandru** [comment]
@jlerbsc thanks for the quick response

What I'm doing is actually parsing the hotspot source classes as if they were my own source files, I'm only using them as an example of a diverse codebase that has a little bit of everything. So I extracted the sources into a folder then pointing to that particular folder.

I attached the sources from the jdk below for your convenience if you want to try and run the MethodResolverTest.java
with this root and see if you can reproduce my issue

[src.zip](https://github.com/javaparser/javaparser/files/7431543/src.zip)

P.S. I did go through the book. It had some good examples but this particular case is not covered in it.

**Comment by jlerbsc** [comment]
So your setup must be something like this

    TypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), new JavaParserTypeSolver (pathToSrcDir));

In a standard maven project pathToSrcDir points to src/main/java

**Comment by apixandru** [comment]
It's my understanding that ReflectionTypeSolver uses the current classpath (and in this case jre) but this is not what i'm trying to achieve.

Let me step back and explain what I'm trying to do. 

Currently I'm running java 14 but i'm trying to analyze java 8 by using only the sources included as a self-contained unit. So when i want to resolve java.lang.Byte, i want it to resolve the java 8 sources that I provided it, not to use the current the jvm's java.lang.Byte. I don't want anything related to the current JDK loaded into the search context, just specifically what i'm passing to it.

I'm trying to analyze various sources of a project in the context that they were compiled with, so for instance if some library was compiled using java9, i would load a JavaParserTypeSolver with the java 9 sources (while my actual jvm would still be 14), and then the sources of that library.
If something was compiled with java 8, i would load a JavaParserTypeSolver with the java 8 sources (while my jvm would still be 14) and the sources of that library. 

If i use reflection type solver, i would always need to be running the exact jvm that i'm trying to inspect and that makes me limit my code analyzer to a certain featureset (for instance if i'm analyzing a java 5 compiled library, i don't want to actually be running java 5 and removing all lambdas and all that, but i don't also want it to resolve java 14's java.lang.Byte)

For the most part, analyzing the jvm's java source code as a self contained unit without any reflection, just sources, works perfectly fine with this library. The only issue i have so far is that it didn't find its own method when evaluating "Byte.valueOf(parseByte(s, radix))"

**Comment by apixandru** [comment]
I can get the intended result with exactly the same code that I attached in the issue, using only the java parser type solver by just modifying the SymbolSolver like so 

![image](https://user-images.githubusercontent.com/4395571/139279706-8bd8edcc-19f8-4ef2-8d09-83b313dc9b12.png)

this also works and looks more backwards compatible but I'm not sure if it's the right way to get the fully qualified name of the type

![image](https://user-images.githubusercontent.com/4395571/139280159-b6a8af17-9f43-46b6-b16e-24867361b7fc.png)

Since `typeSolver.tryToSolveType(nameWithScope)` just by itself seems to correctly resolve the symbol but `JavaParserFactory.getContext(type, typeSolver).solveType(name)` doesn't, I'm wondering if the context built by it is too restrictive and excludes symbols that are actually "in the context", perhaps the real fix is nested somewhere deep in that method? 

(I'm not suggesting that this exact code be added, the correct version of this should be applied with proper handling and so on, this is a quick and dirty way to just pass my particular test)

```
Attempting to resolve Class.getPrimitiveClass("byte")
 - belongs to java.lang.Class
Attempting to resolve Integer.toString((int) b, 10)
 - belongs to java.lang.Integer
Attempting to resolve Integer.parseInt(s, radix)
 - belongs to java.lang.Integer
Attempting to resolve parseByte(s, 10)
 - belongs to java.lang.Byte
Attempting to resolve parseByte(s, radix)
 - belongs to java.lang.Byte
Attempting to resolve valueOf(parseByte(s, radix))
 - belongs to java.lang.Byte
Attempting to resolve valueOf(s, 10)
 - belongs to java.lang.Byte
Attempting to resolve Integer.decode(nm)
 - belongs to java.lang.Integer
Attempting to resolve valueOf((byte) i)
 - belongs to java.lang.Byte
Attempting to resolve parseByte(s, 10)
 - belongs to java.lang.Byte
Attempting to resolve Integer.toString((int) value)
 - belongs to java.lang.Integer
Attempting to resolve Byte.hashCode(value)
 - belongs to java.lang.Byte
Attempting to resolve ((Byte) obj).byteValue()
 - belongs to java.lang.Byte
Attempting to resolve compare(this.value, anotherByte.value)
 - belongs to java.lang.Byte

```

**Comment by jlerbsc** [comment]
Thank you for reporting this bug.
