### ISSUE TITLE
Removing a node with LexicalPreservingPrinter causes UnsupportedOperationException

### ISSUE THREAD

**Issue by xmcp** [javaparser/javaparser#3440]
I use JavaParser with LexicalPreservingPrinter to modify source codes.

It seems that if a node is removed / replaced in the AST, an exception (`java.lang.UnsupportedOperationException: Removed`) is thrown.

Here is a minimal example to reproduce this error:

```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.NodeList;
import com.github.javaparser.ast.stmt.SwitchEntry;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class TestPrinter {
    final static String src = "public class Foo { public void bar() { switch(1) {case 1: break; } } }";

    public static void main(String[] args) {
        CompilationUnit cu = StaticJavaParser.parse(src);
        LexicalPreservingPrinter.setup(cu);

        SwitchEntry entry = cu.findFirst(SwitchEntry.class).get();

        entry.setStatements(new NodeList<>());
    }
}
```

Exception:
```
Exception in thread "main" java.lang.UnsupportedOperationException: Removed
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyLeftOverDiffElements(Difference.java:228)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:165)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:177)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concretePropertyChange(LexicalPreservingPrinter.java:193)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$5(Node.java:614)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:614)
	at com.github.javaparser.ast.stmt.SwitchEntry.setStatements(SwitchEntry.java:166)
	at TestPrinter.main(TestPrinter.java:16)
```

I am using `javaparser-core-3.23.1` on Java 1.8.0_271.

Is this a bug or nodes just cannot be removed with LexicalPreservingPrinter by design?

**Comment by xmcp** [comment]
And if this is by design, is there a workaround to "opt-out" LexicalPreservingPrinter for a code block so that I can modify it?

**Comment by jlerbsc** [comment]
Hi @xmcp It's probably a bug. I will try to watch this today
