### ISSUE TITLE
JavaParser doesn't accept its own output

### ISSUE THREAD

**Issue by xmcp** [javaparser/javaparser#3446]
Consider this code:
```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.stmt.BlockStmt;

public class TestJavaParser {
    public static void main(String[] args) {
        BlockStmt blk = StaticJavaParser.parseBlock("{();}");
        StaticJavaParser.parseBlock(blk.toString()); // -> ParseProblemException
    }
}
```

The second statement throws following exception:
```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 2,col 6) Parse error. Found "->", expected one of  "%=" "&=" "*=" "++" "+=" "--" "-=" "/=" ";" "<<=" "=" ">>=" ">>>=" "^=" "|="
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:13708)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13554)
  com.github.javaparser.GeneratedJavaParser.StatementExpression(GeneratedJavaParser.java:5999)
  com.github.javaparser.GeneratedJavaParser.Statement(GeneratedJavaParser.java:5505)
  com.github.javaparser.GeneratedJavaParser.BlockStatement(GeneratedJavaParser.java:5755)
  com.github.javaparser.GeneratedJavaParser.Statements(GeneratedJavaParser.java:2667)
  com.github.javaparser.GeneratedJavaParser.Block(GeneratedJavaParser.java:5636)
  com.github.javaparser.GeneratedJavaParser.BlockParseStart(GeneratedJavaParser.java:8120)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parseBlock(JavaParser.java:318)
  com.github.javaparser.StaticJavaParser.parseBlock(StaticJavaParser.java:251)
  TestJavaParser.main(TestJavaParser.java:12)

	at com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:270)
	at com.github.javaparser.StaticJavaParser.parseBlock(StaticJavaParser.java:251)
	at TestJavaParser.main(TestJavaParser.java:12)
```

It seems that `{();}` is somehow recognized by JavaParser and `blk.toString()` generates `{()->{};}`, which is invalid and causes the next line to throw ParseProblemException.

So it is very counterintuitive that JavaParse may not parse its own output.

**Comment by jlerbsc** [comment]
Hi @xmcp it seems to me that this code is not syntactically correct! It does not compile.

> {();}

**Comment by xmcp** [comment]
Yes this code is syntactically incorrect.

The actual problem is that `BlockStmt::toString()` may (when fed with incorrect source code) print a representation that even `BlockStmt` itself cannot parse.
As a library user I think the reasonable behavior is to reject `{();}` when parsing, instead of recognizing it as a valid AST but fails later.

**Comment by jlerbsc** [comment]
You are certainly right, but the prerequisite for using JavaParser is that the code must compile. It's probably because we cannot handle all the cases that cause compilation errors :-)

**Comment by jlerbsc** [comment]
This code 

> {();}

doesn't compile! compilation  is a prerequisite to use JavaParser.

> Constructor call must be the first statement in a constructor

**Comment by matozoid** [comment]
Oh, I'd like to add that JP does indeed *parses* quite a few things that cannot compile. A class can extend an interface and it won't complain, for example. In this case it might be nice to add a validator that checks if ehmmm, it looks like a lambda? A validator that checks if there is a lambda at the top level of a block statement and emits an error. Want me to put one together?

**Comment by MysterAitch** [comment]
I think there are potential problems here, but I don't think we have quite clarified/extracted exactly what those problems are.

- **Issue (1):** 
  - The code `();` appears to be parsed as a lambda.
  - This is surprising to me, and I have not investigated how/why this happens but this appears to be the root cause.
- **Issue (2):** 
  - The pretty printer is outputting invalid syntax.
  - (this appears to be the problem that @xmcp appears to be concerned with / is being surprised by)


Given this, I will reopen this issue.

Below are some sample test examples which illustrate things a little.


---

This is the part which is surprising to me, and the area where I would prefer attention to be focussed -- `();` is parsed as a `LambdaExpr` (despite the lack of `->` or similar), meaning that zero parse problems are reported on the first parse.


```java
        String inputText = "{();}";

        JavaParser javaParser = new JavaParser();
        ParseResult<BlockStmt> parseResult = javaParser.parseBlock(inputText);


        /*
         * Output:
         *     parseResult.isSuccessful() = true
         *     parseResult.getProblems().size() = 0
         *     parseResult.getResult().isPresent() = true
         *     parseResult.getResult().get().toString() = {
         *         () -> {
         *         };
         *     }
         */
        System.out.println("parseResult.isSuccessful() = " + parseResult.isSuccessful());
        System.out.println("parseResult.getProblems().size() = " + parseResult.getProblems().size());
//        for (int i = 0; i < parseResult.getProblems().size(); i++) {
//            System.out.println("problem #" + i + ": " + parseResult.getProblems().get(i));
//        }
        System.out.println("parseResult.getResult().isPresent() = " + parseResult.getResult().isPresent());
        System.out.println("parseResult.getResult().get().toString() = " + parseResult.getResult().get().toString());
```


![image](https://user-images.githubusercontent.com/1537214/163876635-1563d736-613b-45d9-bbcf-b2a5f445a45e.png)


----

... once the `();` gets interpreted as a `LambdaExpr`, this is then pretty-printed. My current view is that the pretty printer behaves correctly, given the AST the pretty-printer is has been provided (the core problem being that the pretty printer was provided an invalid AST).

Note here that use of the `StaticJavaParser` causes exceptions to be thrown when parse problems occur. 

```java
        String inputText = "" +
                "{\n" +
                "    () -> {\n" +
                "    };\n" +
                "}" +
                "";
        StaticJavaParser.parseBlock(inputText); // -> ParseProblemException
```

--- 

Personally I prefer to use the non-static implementation (my use-cases, historically, require a bit more detail / understanding of _why_ the parse failed -- the use cases of other folks won't necessarily need this nuance).

Note that, within the example below, no exception is thrown but the partial AST is still available and details about the parse problems are queryable:

```java

        String inputText = "" +
                "{\n" +
                "    () -> {\n" +
                "    };\n" +
                "}" +
                "";

        JavaParser javaParser = new JavaParser();
        ParseResult<BlockStmt> parseResult = javaParser.parseBlock(inputText);


        /*
         * Output:
         *     parseResult.isSuccessful() = false
         *     parseResult.getProblems().size() = 1
         *     parseResult.getResult().isPresent() = true
         *     parseResult.getResult().get().toString() = {
         *         ???;
         *     } 
         */
        System.out.println("parseResult.isSuccessful() = " + parseResult.isSuccessful());
        System.out.println("parseResult.getProblems().size() = " + parseResult.getProblems().size());
//        for (int i = 0; i < parseResult.getProblems().size(); i++) {
//            System.out.println("problem #" + i + ": " + parseResult.getProblems().get(i));
//        }
        System.out.println("parseResult.getResult().isPresent() = " + parseResult.getResult().isPresent());
        System.out.println("parseResult.getResult().get().toString() = " + parseResult.getResult().get().toString());
```
---

Here is a fuller example, chaining the two parts together per @xmcp 's code sample.

```java
        String inputText = "{();}";

        JavaParser javaParser = new JavaParser();
        ParseResult<BlockStmt> parseResult = javaParser.parseBlock(inputText);


        /*
         * Output:
         *     parseResult.isSuccessful() = true
         *     parseResult.getProblems().size() = 0
         *     parseResult.getResult().isPresent() = true
         *     parseResult.getResult().get().toString() = {
         *         () -> {
         *         };
         *     }
         */
        System.out.println("parseResult.isSuccessful() = " + parseResult.isSuccessful());
        System.out.println("parseResult.getProblems().size() = " + parseResult.getProblems().size());
//        for (int i = 0; i < parseResult.getProblems().size(); i++) {
//            System.out.println("problem #" + i + ": " + parseResult.getProblems().get(i));
//        }
        System.out.println("parseResult.getResult().isPresent() = " + parseResult.getResult().isPresent());
        System.out.println("parseResult.getResult().get().toString() = " + parseResult.getResult().get().toString());

        ParseResult<BlockStmt> secondParseResult = javaParser.parseBlock(
                parseResult.getResult().get().toString()
        );

        /*
         * Output:
         *     secondParseResult.isSuccessful() = false
         *     secondParseResult.getProblems().size() = 1
         *     secondParseResult.getResult().isPresent() = true
         *     secondParseResult.getResult().get().toString() = {
         *         ???;
         *     }
         */
        System.out.println("secondParseResult.isSuccessful() = " + secondParseResult.isSuccessful());
        System.out.println("secondParseResult.getProblems().size() = " + secondParseResult.getProblems().size());
        System.out.println("secondParseResult.getResult().isPresent() = " + secondParseResult.getResult().isPresent());
//        for (int i = 0; i < secondParseResult.getProblems().size(); i++) {
//            System.out.println("problem #" + i + ": " + secondParseResult.getProblems().get(i));
//        }
        System.out.println("secondParseResult.getResult().get().toString() = " + secondParseResult.getResult().get().toString());
```

**Comment by MysterAitch** [comment]
I agree with @jlerbsc 's labels on this issue that there is a potential grammar problem (which might/might not be solved via a validator @matozoid ).

That said, I should ask/sanity check: is `()` a valid lambda expression? I don't think so, but if it is then i take my comments above back.

**Comment by xmcp** [comment]
I use JavaParser to post-process code snippets generated by a neural network. Many generated snippets are not valid Java program, as what we expect from a neural network. Therefore I parse them into AST (the invalid ones should be rejected here), and then do post-processing on the AST.

Occasionally I find a corner case (`{();}`) when the code is successfully parsed by JavaParser but the consequent post-processing part crashes (something like `parseBlock(full_src.replace("some_placeholder", ast_node_from_neural_network.toString());`).

I believe it is a bug of JavaParser, because `BlockStmt.toString()` and `parseBlock()` can be seen as a serialization/deserialization of AST. A normal user will be definitely surprised when a serialized value cannot be deserialized by the same library.

**Comment by xmcp** [comment]
> I think there are potential problems here, but I don't think we have quite clarified/extracted exactly what those problems are.
> 
> - Issue (1):
>   The code (); appears to be parsed as a lambda.
>   This is surprising to me, and I have not investigated how/why this happens but this appears to be the root cause.
> - Issue (2):
>   The pretty printer is outputting invalid syntax.
>   (this appears to be the problem that @xmcp appears to be concerned with / is being surprised by)

So yes the issue I am concerned with is the *inconsistency* of `toString()` and `parseBlock()`.

As Java syntax is rather complicated, it is fine if JavaParser accepts a slightly looser syntax (because a program parsed by JavaParser is not guaranteed to pass the compiler semantic checking anyway). But even the syntax is looser, I expect it to be *consistent* inside JavaParser -- if `();` is considered valid, code playing with it should never crash; otherwise, it should not be successfully parsed from the beginning.

**Comment by jlerbsc** [comment]
> I agree with @jlerbsc 's labels on this issue that there is a potential grammar problem (which might/might not be solved via a validator @matozoid ).
> 
> That said, I should ask/sanity check: is `()` a valid lambda expression? I don't think so, but if it is then i take my comments above back.

Hi @MysterAitch it looks like it's not a valid lambda expression because the symbol '->' is needed and the body must be an expression or a block.
https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.27.2

**Comment by matozoid** [comment]
My suggestion to use a validator is because catching an error in a validator will result in an AST and a specific error message, whereas solving it in the grammar will result in *no* AST and a vague, javacc-generated error message. I would in general advise to write a grammar that creates a usable parse from as wide a range of inputs as possible, and move more precise checking and manipulation to the post-step.

Of course you can argue what use it is to support "();" as an invalid statement, and in this case it might even be caught by the error recovery in the grammar.

**Comment by jlerbsc** [comment]
My view is that the parser should validate grammar and syntactical errors as much as possible and that validators can only validate code that is too complex or specific for the parser to check. Since I don't know this part of the project code, I leave you the choice of the most appropriate method.
