### ISSUE TITLE
An error occurred in calculateresolvedtype of lambdaexpr

### ISSUE THREAD

**Issue by ZeroAicy** [javaparser/javaparser#3476]
`java.util.Collections.sort(new ArrayList<String>(), (s1, s2) -> s1.compareTo(s2));`
From lambdaexpr in the above statement, calling calculateresolvedtype appears Java lang.RuntimeException. The error is as follows: `
java.lang.RuntimeException: Method 'compareTo' cannot be resolved in context s1.compareTo(s2) (line: 16) MethodCallExprContext{wrapped=s1.compareTo(s2)}. Parameter types: [LambdaConstraintType{bound=TypeVariable {JavassistTypeParameter{T}}}]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:827)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:523)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:116)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:556)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:403)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:385)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.lambda$resolveLambda$9$TypeExtractor(TypeExtractor.java:755)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor$$ExternalSyntheticLambda0.apply(Unknown Source:4)
	at java.util.Optional.map(Optional.java:211)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.lambda$resolveLambda$10$TypeExtractor(TypeExtractor.java:755)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor$$ExternalSyntheticLambda1.apply(Unknown Source:4)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:203)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1367)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:133)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:489)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:475)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:236)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:482)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.resolveLambda(TypeExtractor.java:757)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:696)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:162)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:556)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:403)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:385)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:291)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:550)`

**Comment by jlerbsc** [comment]
It seems to me that this issue is not easy to solve because to know the type of the return value of the lambda expression it is necessary to solve the java.util.Collections.sort(..) method and to solve this method you need to know the type of each parameter.
