### ISSUE TITLE
JavaSymbolSolver Not resolving the method call

### ISSUE THREAD

**Issue by saketh2341** [javaparser/javaparser#3483]
While parsing the JavaParser-core github Repository.
In ( `javaparser-core/src/main/javacc-support/com/github/javaparser/GeneratedJavaParserTokenManagerBase.java` )
In this Method `tokenrange` the call `TokenRange` is been resolved by JavaSymbolsolver.

```java
    private static TokenRange tokenRange(Token token) {
        JavaToken javaToken = token.javaToken;
        return new TokenRange(javaToken, javaToken);
    }
```

Link to the file I am parsing::
[https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/javacc-support/com/github/javaparser/GeneratedJavaParserTokenManagerBase.java](url)

I am doing 

```java
        for(MethodDeclaration method:classorInterface.getMethods()) {
		    	System.out.println(method.getNameAsString());
		    	method.findAll(MethodCallExpr.class).forEach(mc->{
		    		System.out.println("call: "+mc.getNameAsString());				    		
		    			System.out.println("resolve: "+mc.resolve().getClassName());//This is the line I am getting error
		    		}
        }
```

it is giving error:
```
UnsolvedSymbolException{context='null', name='Token', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:682)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:740)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:736)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69)
	at com.github.javaparser.symbolsolver.model.resolution.Value.from(Value.java:45)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveSymbolAsValueInParentContext(Context.java:148)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:161)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:78)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:83)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:533)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:291)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:566)
	at net.javaguides.springboot.springboothelloworldtutorial.UserController.lambda$3(UserController.java:490)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at net.javaguides.springboot.springboothelloworldtutorial.UserController.lambda$2(UserController.java:417)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at net.javaguides.springboot.springboothelloworldtutorial.UserController.SymbolSolver(UserController.java:403)
	at net.javaguides.springboot.springboothelloworldtutorial.UserController.GetJson(UserController.java:620)
	at net.javaguides.springboot.springboothelloworldtutorial.UserController.getJson(UserController.java:120)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:681)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:540)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:382)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:895)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1732)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

According to me `TokenRange` is not Imported thats why `SymbolSolver` not able to resolve it.
Any Idea Why it is giving error?

**Comment by jlerbsc** [comment]
Hi @saketh2341 This issue is probably due because the type solver is not correctly initialized.

**Comment by saketh2341** [comment]
Hii @jlerbsc Thanks for reply.Iam using combinedTypeSolver

 CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
		    combinedTypeSolver.add(new ReflectionTypeSolver());
		    combinedTypeSolver.add(new JavaParserTypeSolver(pathName+"/src/main/java-templates"));
		    combinedTypeSolver.add(new JavaParserTypeSolver(pathName+"/src/main/java"));
		    combinedTypeSolver.add(new JavaParserTypeSolver(pathName+"/src/main/javacc-support"));

		    JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
		    StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);
Is this wrong way to do?

**Comment by saketh2341** [comment]
Hii @jlerbsc Thanks for reply.Iam using combinedTypeSolver

```java
CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(new ReflectionTypeSolver());
combinedTypeSolver.add(new JavaParserTypeSolver(pathName+"/src/main/java-templates"));
combinedTypeSolver.add(new JavaParserTypeSolver(pathName+"/src/main/java"));
combinedTypeSolver.add(new JavaParserTypeSolver(pathName+"/src/main/javacc-support"));
JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

CompilationUnit compilationUnit = StaticJavaParser.parse(new File(file.getPath())); //file path=javaparser-core/src/main/javacc-support/com/github/javaparser/GeneratedJavaParserTokenManagerBase.java

ClassOrInterfaceDeclaration classorInterface= compilationUnit.findAll(ClassOrInterfaceDeclaration.class);
for(MethodDeclaration method:classorInterface.getMethods()) {
    System.out.println(method.getNameAsString());
    method.findAll(MethodCallExpr.class).forEach(mc->{
         System.out.println("call: "+mc.getNameAsString());
         System.out.println("resolve: "+mc.resolve().getClassName());//This is the line iam getting error
    }
}
```


Is this wrong way to do?

**Comment by jlerbsc** [comment]
Hi @saketh2341 When you are trying to resolve the method `private static TokenRange tokenRange(Token token)` the symbol solver cannot know the Token class because it is generated in another directory (/javaparser-symbol-solver-testing/target/generated-sources/javacc). Try to configure `CombinedTypeSolver` with this directory too.

**Comment by saketh2341** [comment]
You Mean Bug in javasymbolSolver or Bug in repository Which Iam parsing(JavaParser).

**Comment by jlerbsc** [comment]
I guess this comment answered the question.
