### ISSUE TITLE
java.lang.NoClassDefFoundError on Expression.calculateResolvedType()

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3504]
I consider a JavaParserFacace instanciated as the following:

	private static final ThreadLocal<JavaParserFacade> TL_JAVAPARSER = ThreadLocal.withInitial(() -> {
		CombinedTypeSolver ts = new CombinedTypeSolver();

		// We allow processing any type available to default classLoader
		boolean jreOnly = false;

		ts.add(new ReflectionTypeSolver(jreOnly));
		return JavaParserFacade.get(ts);
	});

Given an Expression, I try to resolve its type:

	protected Optional<ResolvedType> optResolvedType(Expression scope) {
		ResolvedType calculateResolvedType;
		try {
			calculateResolvedType = scope.calculateResolvedType();
		} catch (RuntimeException e) {
                       ...
		}

In some case, it fails with the following stack:

```
Caused by: java.lang.NoClassDefFoundError: org/springframework/web/reactive/function/server/ServerResponse$Context
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.Class.getDeclaredClasses0(Native Method)
	at java.base/java.lang.Class.getDeclaredClasses(Class.java:2196)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.internalTypes(ReflectionClassDeclaration.java:396)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:151)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:169)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:126)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:106)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:122)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.FieldAccessContext.solveType(FieldAccessContext.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:434)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:99)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:90)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:554)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:401)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:383)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:291)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:566)
	at eu.solven.cleanthat.language.java.rules.AJavaParserRule.optResolvedType(AJavaParserRule.java:79)
```

Indeed, `org/springframework/web/reactive/function/server/ServerResponse$Context` is referred a way or another by input expression, and indeed this class is not available in the classloader. 

Still, is this expected to have a `java.lang.NoClassDefFoundError` bubbling up? Would it be preferable to receive an exception, wrapping the Error? (As a user, I would not expect such a lack of Type in current classLoader to lead to an Error, but to some applicative exception (e.g. CanNotResolveTypeException)).

**Comment by jlerbsc** [comment]
Hi @blacelle  usually when it comes to exception handling it is not good practice to catch exceptions that are not checked. In your case it seems to be a JSS configuration issue. Also, there are a multitude of places in the code that do not catch all exceptions. It would certainly be too complex to attempt to do so at present. We can try to do it here and there but it would not be homogeneous.

**Comment by blacelle** [comment]
> usually when it comes to exception handling it is not good practice to catch exceptions that are not checked

Catching RuntimeException looks very OK to me. I agree catching Error is often a bad-practise. However, here, javaParser is doing Reflection stuff, hence it is quite expected to encounter such kind of NoClassDefFoundError. 

(e.g. just like when you use Class.forName, in some cases (especially libraries), you would catch some Errors (LinkageError, ExceptionInInitializerError, e.g. to wrap them into IllegalStateException for instance) as the indirect-caller (i.e. library user) should not have to deal with such internal mechanism (i.e. reflection) ).

>  In your case it seems to be a JSS configuration issue.

Certainly. However, in my case, I would just not have access to this type by reflection. I'll investigate deeper as I'm not even sure why given type is actually loaded.

---

I agree considering this as unexpected behavior is opinionated. In such a case, is catching NoClassDefFoundError the proper way to manage the situation?

**Comment by jlerbsc** [comment]
So we can catch all throwables in this method ReflectionClassDeclaration.internalTypes and throw an UnsolvedSymbolException instead which wraps the throwable to keep the error context.
