### ISSUE TITLE
How can I say to symbolSolver to resolve only local classes?

### ISSUE THREAD

**Issue by GholamaliIrani** [javaparser/javaparser#3568]
I want to resolve only local classes in the project context and ignore java or other jar file imports. 

I tried this: 

```
        combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());

        // startDir is the src folder of project
    	Files.walk(startDir).filter(entry -> !entry.equals(startDir))
        .filter(Files::isDirectory).forEach(subdirectory ->
        {
        	//System.out.println(subdirectory.toFile().toString());
                combinedTypeSolver.add(new JavaParserTypeSolver(subdirectory.toFile().toString()));
        });
    	
        symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

```

but I have this error on calling allvisiblefields:

`  	List<ResolvedFieldDeclaration> allFields = declaration.resolve().getVisibleFields();    	
`
the error:  

```
UnsolvedSymbolException{context='null', name='CompilationUnit', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertClassOrInterfaceTypeToUsage(JavaParserFacade.java:713)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:660)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:798)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:794)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69)
	at com.github.javaparser.resolution.MethodUsage.<init>(MethodUsage.java:51)
	at com.github.javaparser.symbolsolver.logic.AbstractTypeDeclaration.getAllMethods(AbstractTypeDeclaration.java:50)
	at analyzer.visitors.gVisitor.visit(gVisitor.java:337)
	at analyzer.visitors.gVisitor.visit(gVisitor.java:1)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:98)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$43(VoidVisitorAdapter.java:175)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:290)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:175)
	at analyzer.AbstractVoidVisitorAdapter.visit(AbstractVoidVisitorAdapter.java:19)
	at analyzer.Analyzer.visitFile(Analyzer.java:153)
	at analyzer.Analyzer.visitFile(Analyzer.java:1)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2811)
	at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
	at analyzer.AnalyzerRunner.run(AnalyzerRunner.java:45)
	at analyzer.AnalyzerRunner.run(AnalyzerRunner.java:23)
	at gFrame.newProjectFrame.actionPerformed(newProjectFrame.java:123)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by MysterAitch** [comment]
My understanding is that what you describe is currently not possible -- all relevant/used dependencies must be provided to the type solver for it to work. I believe that this only relates to the types you resolve (and their type/dependency chains) but would need to experiment to be sure.


What does your variable `declaration` refer to? 

If it's not internal to the project or your currently running JRE/JDK (given your use of `ReflectionTypeSolver`), I presume this is a class which uses/references a type provided by a dependency?

**Comment by jlerbsc** [comment]
Maybe just catching exceptions is enough to do what you want to achieve?

**Comment by GholamaliIrani** [comment]
Thanks a lot for the response,
the declaration type is : `ClassOrInterfaceDeclaration` in visitor class. 

```java
@Override
    public void visit(ClassOrInterfaceDeclaration declaration, Classs classs) {
    ....
    }
```

I try @jlerbsc response, 
thanks.

**Comment by GholamaliIrani** [comment]
Thanks a lot @jlerbsc , my problem solved. 
```
    	Set<MethodUsage> allinheritedmethods = null;    	
    	try {
    		allinheritedmethods = declaration.resolve().getAllMethods();
    		for (MethodUsage mi : allinheritedmethods)
        	{
                        //do 
        	}
    	}
    	catch (Exception e) {
			System.out.println("can not read methods of inherited external classes");
	}

```
