### ISSUE TITLE
UnsolvedSymbolException when package declaration contains comment

### ISSUE THREAD

**Issue by mominet2** [javaparser/javaparser#3614]
I have a file A2.java :
```
package org.demo./*aaaaa*/project1.test;
class A2 {
...
}
```

CompilationUnitContext.java
Line 202:            
```
String qName = this.wrappedNode.getPackageDeclaration().get().getName().toString() + "." + name;
            SymbolReference<ResolvedReferenceTypeDeclaration> ref = typeSolver.tryToSolveType(qName);
            if (ref != null && ref.isSolved()) {
                return SymbolReference.adapt(ref, ResolvedTypeDeclaration.class);
            }
```

The name is "A1“，and the qName is "`org.demo.project1/*aaaaa*/\r\n.test.A1`";
It caused an error of JavaParserTypeSolver.java.

JavaParserTypeSolver.java 

```
    private SymbolReference<ResolvedReferenceTypeDeclaration> tryToSolveTypeUncached(String name) {
        String[] nameElements = name.split("\\.");

        for (int i = nameElements.length; i > 0; i--) {
            StringBuilder filePath = new StringBuilder(srcDir.toAbsolutePath().toString());
            for (int j = 0; j < i; j++) {
                filePath.append(File.separator)
                        .append(nameElements[j]);
            }
            filePath.append(".java");
```

**Comment by mominet2** [comment]
/*aaaaa*/ is  a block comment.
The asterisk is hidden by the editor.

**Comment by matozoid** [comment]
Looks like someone did some quick&dirty string magic where the parser should have been used.

**Comment by matozoid** [comment]
Haven't checked, but JP.parseName and asString will help here, I think.

**Comment by mominet2** [comment]
**Test.java**
```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.List;

public class Test {
    public static void main(String[] args) throws FileNotFoundException {
        TypeSolver[] typeSolverArray = new TypeSolver[2];
        typeSolverArray[0] = new ReflectionTypeSolver(false);
        typeSolverArray[1] = new JavaParserTypeSolver("E:\\workspace-demo\\demo-project1\\src\\main\\java");

        TypeSolver typeSolver = new CombinedTypeSolver(typeSolverArray);

        JavaSymbolSolver javaSymbolSolver = new JavaSymbolSolver(typeSolver);

        StaticJavaParser.getConfiguration().setSymbolResolver(javaSymbolSolver);

        File file = new File("E:\\workspace-demo\\demo-project1\\src\\main\\java\\org\\demo\\project1\\test\\ClassTwo.java");
        CompilationUnit compilationUnit = StaticJavaParser.parse(file);

        List<MethodCallExpr> methodCallList = compilationUnit.findAll(MethodCallExpr.class);
        for (MethodCallExpr mce : methodCallList) {
            ResolvedMethodDeclaration resolvedMethodDeclaration = mce.resolve();

            System.out.println(resolvedMethodDeclaration);
        }

    }
}
```

**ClassOne.java**
```
package org.demo.project1.test;

public class ClassOne {
	public void f1() {
		
	}
}
```

**ClassTwo.java**
```
package org.demo./*aaaaa*/project1.test;
//package org.demo.project1.test;

public class ClassTwo {
	public void test() {
		ClassOne classOne = new ClassOne();
		classOne.f1();
	}
}
```

**Exception**
```
Exception in thread "main" UnsolvedSymbolException{context='classOne.f1()', name='classOne', cause='UnsolvedSymbolException{context='null', name='ClassOne', cause='null'}'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:222)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:166)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:317)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:179)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:161)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:317)
	at Test.main(Test.java:32)
Caused by: UnsolvedSymbolException{context='null', name='ClassOne', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertClassOrInterfaceTypeToUsage(JavaParserFacade.java:713)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:660)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:798)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:794)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserVariableDeclaration.getType(JavaParserVariableDeclaration.java:59)
```
