### ISSUE TITLE
interface[]  ParseException

### ISSUE THREAD

**Issue by ghost** [javaparser/javaparser#3649]
![image](https://user-images.githubusercontent.com/15818895/181412463-eb573884-cc4c-479a-a525-0ea45df5a85e.png)

definition interface value array
use below code to format:(the content of a is above code)

```
 CompilationUnit cu = StaticJavaParser.parse(file);
            System.out.println(cu);
```

Problem stacktrace :
```
com.github.javaparser.ParseProblemException: (line 4,col 15) Parse error. Found "[", expected one of  ";" "default"
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:13709)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13554)
  com.github.javaparser.GeneratedJavaParser.AnnotationTypeMemberDeclaration(GeneratedJavaParser.java:7881)
  com.github.javaparser.GeneratedJavaParser.AnnotationBodyDeclaration(GeneratedJavaParser.java:7788)
  com.github.javaparser.GeneratedJavaParser.AnnotationTypeBody(GeneratedJavaParser.java:7740)
  com.github.javaparser.GeneratedJavaParser.AnnotationTypeDeclaration(GeneratedJavaParser.java:7634)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:167)
  com.github.javaparser.JavaParser.parse(JavaParser.java:123)
  com.github.javaparser.JavaParser.parse(JavaParser.java:199)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:138)
	at com.github.javaparser.StaticJavaParser.handleResult(StaticJavaParser.java:270)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:138)
```

**Comment by jlerbsc** [comment]
Hi @CJunHub your declaration does not compile!

This is a valid declaration

    @interface ToDo { 
        String[] items(); 
    }

**Comment by ghost** [comment]
Hi @jlerbsc   I'm sure my declaration can compile.


I declare an annotation  ToDo

```
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
public @interface ToDo {
    String items()[];
}

```

Define a class ToDoUse, add annotations and its properties

```
@ToDo(items = {"1", "2"})
public class ToDoUse {
    
}
```

I can compile and run normally to get the annotation value through reflection.

```
public class ToDoUseTest {
    public static void main(String[] args) throws ClassNotFoundException {
        Class cla = Class.forName("ToDoUse");
        for (Annotation annotation : cla.getAnnotations()) {
            System.out.println(annotation);
        }
    }
}

```
![image](https://user-images.githubusercontent.com/15818895/181672914-cc45a940-b921-4bac-a969-b0835a1475ab.png)

**Comment by ghost** [comment]
The result of my test is that the array before and after does not affect the compilation and operation.

**Comment by jlerbsc** [comment]
What is your java version?

**Comment by ghost** [comment]
> 你的java版本是多少？

jdk8

```
java version "1.8.0_321"
Java(TM) SE Runtime Environment (build 1.8.0_321-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.321-b07, mixed mode)
```

**Comment by jlerbsc** [comment]
> @Target(ElementType.TYPE)
> @Retention(RetentionPolicy.RUNTIME)
> public @interface ToDo {
>     String items()[];
> }

This declaration generates a complation error in eclipse. Maybe this is an eclipse specific error.


> Extended dimensions are illegal in an annotation attribute declaration

**Comment by ghost** [comment]
I use Intellij IDEA .
Can this problem be fixed？

**Comment by jlerbsc** [comment]
For information, i think the related part in the JLS can be find in https://docs.oracle.com/javase/specs/jls/se8/html/jls-9.html#jls-9.6


> The declaration of a method that returns an array is allowed to place the bracket pair that denotes the array type after the empty formal parameter list. This syntax is supported for compatibility with early versions of the Java programming language. It is very strongly recommended that this syntax is not used in new code.


This modification needs to know the syntax of javaCC.
