### ISSUE TITLE
symbolResolver.calculateType(f.getScope().get()) throws UnsolvedSymbolException when using a method from external library

### ISSUE THREAD

**Issue by satyadonka** [javaparser/javaparser#3662]
I am facing the below error during symbolResolver.calculateType(f.getScope().get()) on a methodcallexpr super.xyz().
The super class is in an external library which is not in the ast. 
I want to confine to my project code itself. 
Can you please guide me, how to instruct the javaparser to not to look at the external libraries or just to ignore/pass when it encounters such method calls. Appreciate your help here.

Exception in thread "main" UnsolvedSymbolException{context='null', name='AbstractActivity', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.toReferenceType(JavaParserClassDeclaration.java:485)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.**getSuperClass**(JavaParserClassDeclaration.java:211)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:428)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:71)
	**at com.github.javaparser.ast.expr.SuperExpr.accept(SuperExpr.java:75)**
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:547)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:394)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:376)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:291)

**Comment by jlerbsc** [comment]
Hi @satyadonka in your case the best way is probably to catch the UnsolvedSymbolException exception.
