### ISSUE TITLE
isAssignableBy method StackOverflowError

### ISSUE THREAD

**Issue by shlsky** [javaparser/javaparser#3673]
new ReflectionTypeSolver().solveType("java.util.List").isAssignableBy(typeDeclaration)

java.lang.StackOverflowError
	at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
	at sun.util.locale.provider.LocaleResources.getDecimalFormatSymbolsData(LocaleResources.java:164)
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:616)
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:113)
	at sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:180)
	at java.util.Formatter.getZero(Formatter.java:2283)
	at java.util.Formatter.<init>(Formatter.java:1892)
	at java.util.Formatter.<init>(Formatter.java:1914)
	at java.lang.String.format(String.java:2940)
	at com.github.javaparser.resolution.declarations.ResolvedTypeParameterDeclaration.getQualifiedName(ResolvedTypeParameterDeclaration.java:154)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParametersMap.getValue(ResolvedTypeParametersMap.java:107)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$describe$0(ResolvedReferenceType.java:157)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.describe(ResolvedReferenceType.java:158)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:219)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:83)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:282)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:225)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:83)

**Comment by jlerbsc** [comment]
What's the value of the typeDeclaration parameter?
Can you provide a simple test case?

**Comment by shlsky** [comment]
new ReflectionTypeSolver().solveType("java.util.List").isAssignableBy(typeDeclaration)

typeDeclaration resolve from JarTypeSolver.
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/11934728/185825238-e3ffe3e3-789a-4774-9ca3-95251069d269.png">

**Comment by jlerbsc** [comment]
Can you improve this unit test to demonstrate the problem.

    @Test
    void test3673() {

        TypeSolver ts = new ReflectionTypeSolver();
        ResolvedReferenceTypeDeclaration rrtd1 = ts.solveType("java.util.List");
        ResolvedReferenceTypeDeclaration rrtd2 = ts.solveType("java.util.ArrayList");
        System.out.println(rrtd1.isAssignableBy(rrtd2));
    }

**Comment by jlerbsc** [comment]
Since there was no response, I am closing the case but you are free to reopen it if you provide additional information.

**Comment by seijikun** [comment]
@jlerbsc Hi! Thank you so much for your work on this awesome library!
I have the same problem as OP.
That's where it fails for me:

```java
TypeSolver typeSolver = new CombinedTypeSolver(
    new ReflectionTypeSolver(),
    new JarTypeSolver(Path.of("/home/seiji/.m2/repository/org/json/json/20220320/json-20220320.jar"))
);
var list = typeSolver.solveType("java.util.List");
var other = typeSolver.solveType("org.json.JSONObject");
System.out.println(list.isAssignableBy(other));
```
JavaParser: `javaparser-symbol-solver-core 3.25.2`

StackTrace:
```
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.AbstractCollection.<init>(AbstractCollection.java:68)
	at java.base/java.util.AbstractList.<init>(AbstractList.java:78)
	at java.base/java.util.ArrayList.<init>(ArrayList.java:168)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.begin(ReduceOps.java:164)
	at java.base/java.util.stream.Sink$ChainedReference.begin(Sink.java:253)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:483)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.deriveParams(ResolvedReferenceType.java:511)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:63)
	at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:67)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:82)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:270)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:224)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:82)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:270)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:224)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.isAssignableBy(ReflectionInterfaceDeclaration.java:82)
[...]
```

**Comment by jlerbsc** [comment]
Thank you for reporting this bug with more details.

**Comment by jsilbereisen** [comment]
Hello, currently running into the same issue.

From what I've seen, seemingly (in my case) the execution makes an infinite loop over the `ReflectionInterfaceDeclaration.isAssignableBy`, because it calls
`otherTypeDeclaration.getTypeDeclaration().get().canBeAssignedTo(this)`.

In my case, `other` is a  `JavassistInterfaceDeclaration` (resolved from a JAR), which does not override `ResolvedReferenceTypeDeclaration.canBeAssignedTo`, so it calls its default implementation, which says
`other.isAssignableBy(this)` (where `other` is the previous mentioned `ReflectionInterfaceDeclaration`), causing this loop.

Not sure if this helps - maybe you know this already

**Comment by seijikun** [comment]
Unfortunately, #4118 does not seem to completely fix the issue for me yet. (I am on 3.25.5)
My reproduction example from above is fixed, though.
I had problems creating a small reproduction sample this time, because the parser is involved with a large codebase. I hope this gives you enough of a hint to work with:

The code:
```java
    typeA.isAssignableBy(typeB);
```
where
- `typeA` is `java.util.Optional` [reflection]
- `typeB` is a custom enum class with integer parameter [java parser].


![image](https://github.com/javaparser/javaparser/assets/820845/31437dff-1dbd-4cff-93e8-c78df053333f)

Stacktrace:
```
java.lang.StackOverflowError
        at java.base/java.lang.String.coder(String.java:4545)
        at java.base/java.lang.String.length(String.java:1481)
        at java.base/java.lang.String.substring(String.java:2708)
        at javassist.bytecode.SignatureAttribute$ClassType.<init>(SignatureAttribute.java:799)
        at javassist.bytecode.SignatureAttribute$ClassType.make(SignatureAttribute.java:794)
        at javassist.bytecode.SignatureAttribute.parseClassType2(SignatureAttribute.java:1238)
        at javassist.bytecode.SignatureAttribute.parseObjectType(SignatureAttribute.java:1200)
        at javassist.bytecode.SignatureAttribute.parseTypeArgs(SignatureAttribute.java:1259)
        at javassist.bytecode.SignatureAttribute.parseClassType2(SignatureAttribute.java:1232)
        at javassist.bytecode.SignatureAttribute.parseClassType(SignatureAttribute.java:1217)
        at javassist.bytecode.SignatureAttribute.parseSig(SignatureAttribute.java:1122)
        at javassist.bytecode.SignatureAttribute.toClassSignature(SignatureAttribute.java:1054)
        at com.github.javaparser.symbolsolver.javassistmodel.JavassistTypeDeclarationAdapter.getTypeParameters(JavassistTypeDeclarationAdapter.java:221)
        at com.github.javaparser.symbolsolver.javassistmodel.JavassistEnumDeclaration.getTypeParameters(JavassistEnumDeclaration.java:145)
        at com.github.javaparser.resolution.types.ResolvedReferenceType.deriveParams(ResolvedReferenceType.java:509)
        at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:63)
        at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:67)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
        at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.canBeAssignedTo(ResolvedReferenceTypeDeclaration.java:268)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.isAssignableBy(ReflectionClassAdapter.java:193)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:281)
        at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.isAssignableBy(ReflectionClassDeclaration.java:321)
[...]
```

**Comment by jlerbsc** [comment]
Thank you for your vigilance, there are indeed still cases that cause this type of bug. I can reproduce this type of error with your detailed description.
