### ISSUE TITLE
Text Block Literals are not supported error

### ISSUE THREAD

**Issue by AhmedSalihCezayir** [javaparser/javaparser#3767]
I am currently using  javaparser-symbol-solver-core 3.24.8 and getting an "Text Block Literals are not supported" error.

My javaparser code:
```
public static void main(String[] args) {
        System.out.println("Hello world!");
        CombinedTypeSolver combinedTypedSolver = new CombinedTypeSolver();
        combinedTypedSolver.add(new ReflectionTypeSolver());
        combinedTypedSolver.add(new JavaParserTypeSolver("src/main/java"));
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypedSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        ArrayList<String> paths = new ArrayList<>();
        paths.add("src/main/java/org/classes");

        List<String> javaFiles = getFilesBySuffixInPaths(".java", paths);
        System.out.println(javaFiles);

        for (String file: javaFiles) {
            try {
                CompilationUnit cu = StaticJavaParser.parse(new File(file));
                cu.findAll(MethodDeclaration.class).forEach(md -> {
                    System.out.println("file path: " + file + "  -- " + md.getNameAsString());
                    md.findAll(MethodCallExpr.class).forEach(mce -> {
                        System.out.println("inside of " + md.getNameAsString() + "  --  called method: " + mce.resolve().getQualifiedSignature());
                    });
                });
            } catch (FileNotFoundException e) {
                System.out.println(e.getMessage());
            } catch (UnsolvedSymbolException e) {
                System.out.println("file path: " + file + " -- " + e.getMessage());
            }
        }
    }
```

Code that I am parsing:
```
public class CallGraphManager {
    public static void main(String[] args) {
        String a = """
                   MERGE (caller: Function { name: $callerFuncName, className: $callerFuncClassName })
                   ON CREATE
                       SET
                           caller.start = $callerFuncStart,
                           caller.end = $callerFuncEnd
                   ON MATCH
                       SET
                           caller.start = $callerFuncStart,
                           caller.end = $callerFuncEnd
                   RETURN caller
                   """;

        String b = """
                   MATCH (caller: Function)
                   WHERE caller.name = $callerFuncName AND caller.className = $callerFuncClassName

                   MERGE (callee: Function { name: $calleeFuncName, className:$calleeFuncClassName })
                   ON CREATE
                       SET
                           callee.start = $defaultFuncStart,
                           callee.end = $defaultFuncEnd

                   CREATE (caller)-[:CALLS { line: $callLine }]->(callee)
                   RETURN caller, callee
                   """;
    }
}
```

Output: 
```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 22,col 20) Text Block Literals are not supported.
(line 34,col 20) Text Block Literals are not supported.

	at com.github.javaparser.JavaParserAdapter.handleResult(JavaParserAdapter.java:63)
	at com.github.javaparser.JavaParserAdapter.parse(JavaParserAdapter.java:75)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:141)
	at org.example.Main.main(Main.java:41)
```
 
I believe javaparser supports text blocks but I don't know why this code causes problem

**Comment by jlerbsc** [comment]
You need to configure Javaparser to use Java 15.

    configuration.setLanguageLevel(LanguageLevel.JAVA_15);

**Comment by AhmedSalihCezayir** [comment]
@jlerbsc Thanks a lot
