### ISSUE TITLE
Replacing nodes causes error in lexical preserving printer if some nodes are identical

### ISSUE THREAD

**Issue by YuanyeMa** [javaparser/javaparser#3773]
Hi everyone I encountered an exception handling aaaa.java following the code below. 
What may cause it? 
How can I fix it? 
Thanks very much .

```java
public class Main {

    public static void main(String[] args) throws IOException {
        Path url = Paths.get("D:/JAVA/log_control_sample/aaaa.java");

        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setLexicalPreservationEnabled(true);
        JavaParser parser = new JavaParser(parserConfiguration);

        ParseResult<CompilationUnit> parsedResult = null;
        parsedResult = parser.parse(url);
        if (parsedResult.getResult().get() != null) {
            FunctionVisitor funVisitor = new FunctionVisitor();

            funVisitor.visit(parsedResult.getResult().get(), null);

            File file=new File(url.toString()+"paserd");
            java.io.FileWriter fw=new java.io.FileWriter(file,false);
            fw.write(LexicalPreservingPrinter.print(parsedResult.getResult().get()));
        }
    }
}


public class FunctionVisitor extends VoidVisitorAdapter<Object> {

    @Override
    public void visit(MethodCallExpr node, Object arg) {
        if (node.getScope().isPresent() && node.getName() != null) {
            String nodeScope = node.getScope().get().toString();
            String nodeName = node.getName().toString();
            if (nodeScope.equals("Log") ) {
                if (nodeName.equals("d")) {
                    // get parent node save variable for replace
                    if (node.getParentNode().isPresent()) {
                        Node parentNode = node.getParentNode().get();

                        // replace parent node by if statement
                        try {
                            String replaceNode = "if ( Log.Level <= 3 ) { " +
                                    LexicalPreservingPrinter.print(parentNode) + " }";

                            ParserConfiguration parserConfiguration = new ParserConfiguration();
                            parserConfiguration.setLexicalPreservationEnabled(true);
                            JavaParser parser = new JavaParser(parserConfiguration);

                            ParseResult<Statement> parserResult = parser.parseStatement(replaceNode);
                            parentNode.replace(parserResult.getResult().get());
                        } catch (Exception e1) {
                            e1.printStackTrace();
                        }
                    }
                }
            }
        }

        super.visit(node, arg);
    }
}
```
The content of the aaaa.java s is as follows : 
```java
class A {
	public String output = "Contents of ";
	
	public String debug(String output) {

		Log.d("Debug", output1);   
		Log.d("Debug", output2);   
		Log.d("Debug", output3);   			
		Log.d("Debug", output4); 
		
		output = "1";
		Log.d("Debug", output1);
		
		output = "2";
		Log.d("Debug", output2);
		
		output = "3";
		Log.d("Debug", output3);
		
		Log.d("Debug", "");   
		Log.d("Debug", "");  
		Log.d("Debug", "3");   
		Log.d("Debug", "4");   
		
		return "";
	}
}
```
The exception contents are as follows: 
```
java.lang.UnsupportedOperationException: kept child(ExpressionStmt) vs "}"   <100>   (line 26,col 2)-(line 26,col 2)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:533)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:190)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListReplacement(LexicalPreservingPrinter.java:347)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listReplacement(PropagatingAstObserver.java:82)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementReplaced$3(NodeList.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.notifyElementReplaced(NodeList.java:498)
	at com.github.javaparser.ast.NodeList.set(NodeList.java:149)
	at com.github.javaparser.ast.stmt.BlockStmt.replace(BlockStmt.java:133)
	at com.github.javaparser.ast.Node.replace(Node.java:583)
```

**Comment by jlerbsc** [comment]
It is not a way of proceeding which is very conventional. Why don't you modify the AST instead of manipulating character strings ?

**Comment by jlerbsc** [comment]
What is the version you are using? In the current snapshot version there is no exception but there have been many issues resolved since the last released version . What result would you like to achieve?

**Comment by YuanyeMa** [comment]
@jlerbsc  
Thanks so much for your prompt response. 
We are using version 3.24.2.
Because we want to add a judgment statement to the original code without changing the line number of the original code. 
So we can only constructing a string parser, then inserted into the AST of the original code. 

While this is stupid, modifying the AST directly changes the line number of the original code, so that's the only way.

**Comment by jlerbsc** [comment]
There is indeed a bug that I will fix today. Here is the test case that I suggest to you. Does it correspond to what you want to do? Try it.


	@Test
    void test3773() {
		considerCode(
                "class A {\r\n"
                + "	public String output = \"Contents of \";\r\n"
                + "	\r\n"
                + "	public String debug(String output) {\r\n"
                + "\r\n"
                + "		Log.d(\"Debug\", output1);   \r\n"
                + "		Log.d(\"Debug\", output2);   \r\n"
                + "		Log.d(\"Debug\", output3);   			\r\n"
                + "		Log.d(\"Debug\", output4); \r\n"
                + "		\r\n"
                + "		output = \"1\";\r\n"
                + "		Log.d(\"Debug\", output1);\r\n"
                + "		\r\n"
                + "		output = \"2\";\r\n"
                + "		Log.d(\"Debug\", output2);\r\n"
                + "		\r\n"
                + "		output = \"3\";\r\n"
                + "		Log.d(\"Debug\", output3);\r\n"
                + "		\r\n"
                + "		Log.d(\"Debug\", \"\");   \r\n"
                + "		Log.d(\"Debug\", \"\");  \r\n"
                + "		Log.d(\"Debug\", \"3\");   \r\n"
                + "		Log.d(\"Debug\", \"4\");   \r\n"
                + "		\r\n"
                + "		return \"\";\r\n"
                + "	}\r\n"
                + "}");
		String expected = 
        		"class A {\r\n"
        		+ "	public String output = \"Contents of \";\r\n"
        		+ "	\r\n"
        		+ "	public String debug(String output) {\r\n"
        		+ "\r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output1);   \r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output2);   \r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output3);   			\r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output4); \r\n"
        		+ "		\r\n"
        		+ "		output = \"1\";\r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output1);\r\n"
        		+ "		\r\n"
        		+ "		output = \"2\";\r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output2);\r\n"
        		+ "		\r\n"
        		+ "		output = \"3\";\r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", output3);\r\n"
        		+ "		\r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", \"\");   \r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", \"\");  \r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", \"3\");   \r\n"
        		+ "		if (Log.Level >= 3)\r\n"
        		+ "		    Log.d(\"Debug\", \"4\");   \r\n"
        		+ "		\r\n"
        		+ "		return \"\";\r\n"
        		+ "	}\r\n"
        		+ "}";
		
		FunctionVisitor funVisitor = new FunctionVisitor();
               funVisitor.visit(cu, null);
		
		
		assertEqualsStringIgnoringEol(expected, LexicalPreservingPrinter.print(cu));
	}
	
	public class FunctionVisitor extends ModifierVisitor<Object> {

		@Override
		public Visitable visit(ExpressionStmt node, Object arg) {
			List<MethodCallExpr> mces = node.getChildNodesByType(MethodCallExpr.class);
			if (mces.isEmpty())
				return node;
			MethodCallExpr mce = mces.get(0);
			if (mce.getScope().isPresent() && mce.getName() != null) {
				String nodeScope = mce.getScope().get().toString();
				String nodeName = mce.getName().toString();
				if (nodeScope.equals("Log")) {
					if (nodeName.equals("d")) {
						IfStmt ifStmt = makeIfStmt(node);
						return ifStmt;
					}
				}
			}
			return node;
		}
	}

**Comment by YuanyeMa** [comment]
@jlerbsc  Thanks so much for your prompt response.

Our input code is as follows:
```java
class A {
	public String debug(String output) {

		Log.d("Debug", output1);   
		Log.d("Debug", output2);   
		Log.d("Debug", output3);   			
		Log.d("Debug", output4); 
		
		output = "1";
		Log.d("Debug", output1);
		
		output = "2";
		Log.d("Debug", output2);
		
		output = "3";
		Log.d("Debug", output3);
		
		Log.d("Debug", "");  
		Log.d("Debug", "");  
		Log.d("Debug", "3");   
		Log.d("Debug", "4");   
		
		Log.d("Debug", "aaa" + 
			"bbbbb"); 
		
		return "";
	}
}
```

The following output code is expected:
```java
class A {
	public String debug(String output) {

		if ( Log.Level <= 3 ) { Log.d("Debug", output1);}   
		if ( Log.Level <= 3 ) { Log.d("Debug", output2);}   
		if ( Log.Level <= 3 ) { Log.d("Debug", output3);}  			
		if ( Log.Level <= 3 ) { Log.d("Debug", output4);} 
		
		output = "1";
		if ( Log.Level <= 3 ) { Log.d("Debug", output1);}
		
		output = "2";
		if ( Log.Level <= 3 ) { Log.d("Debug", output2);}
		
		output = "3";
		if ( Log.Level <= 3 ) { Log.d("Debug", output3);}
		
		if ( Log.Level <= 3 ) { Log.d("Debug", "");}  
		if ( Log.Level <= 3 ) { Log.d("Debug", "");}  
		if ( Log.Level <= 3 ) { Log.d("Debug", "3");}   
		if ( Log.Level <= 3 ) { Log.d("Debug", "4");}  
			
		if ( Log.Level <= 3 ) { Log.d("Debug", "aaa" + 
						"bbbbb"); }
		
		return "";
	}
}
```
That means we don t want the line number of the source file changing after inserting the if statement.


I just tested your suggested solution and still report the following error.
And the source file line number has changed after inserting the if statement.

```
Exception in thread "main" java.lang.UnsupportedOperationException: kept child(ExpressionStmt) vs "}"   <100>   (line 27,col 2)-(line 27,col 2)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:533)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:190)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListReplacement(LexicalPreservingPrinter.java:347)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listReplacement(PropagatingAstObserver.java:82)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementReplaced$3(NodeList.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at com.github.javaparser.ast.NodeList.notifyElementReplaced(NodeList.java:498)
	at com.github.javaparser.ast.NodeList.set(NodeList.java:149)
	at com.github.javaparser.ast.NodeList.set(NodeList.java:49)
	at com.github.javaparser.utils.Utils.replaceElementByObjectIdentity(Utils.java:250)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1136)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:169)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:70)
	at com.github.javaparser.ast.visitor.ModifierVisitor.lambda$visit$60(ModifierVisitor.java:670)
	at java.util.Optional.map(Optional.java:215)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:670)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:98)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:243)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:92)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:1129)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:51)
	at com.github.javaparser.ast.NodeList.accept(NodeList.java:277)
	at com.github.javaparser.ast.visitor.ModifierVisitor.modifyList(ModifierVisitor.java:1168)
	at com.github.javaparser.ast.visitor.ModifierVisitor.visit(ModifierVisitor.java:306)
	at logcontroltool.Main.main(Main.java:30)

Process finished with exit code 1

```

**Comment by jlerbsc** [comment]
The test fails because I haven't pushed the patch yet. Don't be in such a rush ;-)

**Comment by YuanyeMa** [comment]
> The test fails because I haven't pushed the patch yet. Don't be in such a rush ;-)

Sorry for that. :grin: I will test that later.
Thanks very much.
