### ISSUE TITLE
Symbol solver is unable to resolve inner classes of ancestors when they are prefixed with a subclass

### ISSUE THREAD

**Issue by freya022** [javaparser/javaparser#3866]
## Problem
The symbol solver is unable to resolve the return type of `MyActivityImpl#getTimestamps`

<details>
<summary>Test code</summary>

```java
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.util.List;

public class JavaParserBugTest {
    public static void main(String[] args) {
        final String code = """
            public interface MyActivity {
                class MyTimestamps {}
               
                MyTimestamps getTimestamps();
            }
            
            public interface MyRichPresence extends MyActivity { }
           
            class MyActivityImpl implements MyActivity {
                @Override
                public MyActivityImpl.MyTimestamps getTimestamps() {
                    return timestamps;
                }
            }
            """;

        final JavaSymbolSolver solver = new JavaSymbolSolver(new ReflectionTypeSolver(false));

        StaticJavaParser.getParserConfiguration().setSymbolResolver(solver);
        final CompilationUnit compilationUnit = StaticJavaParser.parse(code);

        final List<String> returnTypes = compilationUnit.findAll(ClassOrInterfaceDeclaration.class)
                .stream()
                .map(ClassOrInterfaceDeclaration::resolve)
                .flatMap(typeDeclaration -> typeDeclaration.getDeclaredMethods().stream())
                .map(ResolvedMethodDeclaration::getReturnType)
                .map(Object::toString)
                .toList();

        System.out.println("returnTypes = " + returnTypes);
    }
}
```

</details>

<details>
<summary>Exception</summary>

```
Exception in thread "main" UnsolvedSymbolException{context='null', name='MyActivityImpl.MyTimestamps', cause='null'}
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:606)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:639)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.getReturnType(JavaParserMethodDeclaration.java:87)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1715)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at com.freya02.docs.JavaParserBugTest.main(JavaParserBugTest.java:47)
```

</details>

However, changing the return type from `MyActivityImpl.MyTimestamps` to `MyActivity.MyTimestamps` or `MyTimestamps` does work.

Source of the test case:
https://github.com/DV8FromTheWorld/JDA/blob/299f4d0dcaa4c9b7fe88cf4dca1b71cef15fafcf/src/main/java/net/dv8tion/jda/internal/entities/ActivityImpl.java#L92

**Comment by jlerbsc** [comment]
That's right. Thanks for identifying this bug and providing a simplified unit test.

**Comment by jlerbsc** [comment]
It looks like JP doesn't handle composite type names correctly.
