### ISSUE TITLE
LexicalPreservingPrinter fails when replacing a VariableDeclarationExpr type to `var`

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3898]
With javaparser 3.25.0:

I get :

```
Exception in thread "main" java.lang.UnsupportedOperationException: kept child(VariableDeclarator) vs "<"   <110>   (line 7,col 7)-(line 7,col 7)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:695)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:342)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:165)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concretePropertyChange(LexicalPreservingPrinter.java:204)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$5(Node.java:617)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:617)
	at com.github.javaparser.ast.body.VariableDeclarator$1.propertyChange(VariableDeclarator.java:135)
	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$5(Node.java:617)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:617)
	at com.github.javaparser.ast.body.VariableDeclarator.setType(VariableDeclarator.java:218)
	at eu.solven.cleanthat.engine.java.refactorer.it.ReportLocalVariableTypeInference.processNotRecursively(ReportLocalVariableTypeInference.java:45)
	at eu.solven.cleanthat.engine.java.refactorer.it.ReportLocalVariableTypeInference.lambda$0(ReportLocalVariableTypeInference.java:56)
	at com.github.javaparser.ast.Node.walk(Node.java:858)
	at com.github.javaparser.ast.Node.walk(Node.java:866)
	at eu.solven.cleanthat.engine.java.refactorer.it.ReportLocalVariableTypeInference.main(ReportLocalVariableTypeInference.java:55)
```

with :

```
package eu.solven.cleanthat.engine.java.refactorer.it;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.Node;
import com.github.javaparser.ast.body.VariableDeclarator;
import com.github.javaparser.ast.expr.VariableDeclarationExpr;
import com.github.javaparser.ast.type.VarType;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class ReportLocalVariableTypeInference {
	static final String testCase = "package eu.solven.cleanthat.engine.java.refactorer.cases.do_not_format_me;\n" + "\n"
			+ "import java.util.HashMap;\n"
			+ "import java.util.Map;\n"
			+ "public class LocalVariableTypeInferenceCases {\n"
			+ "	public Object pre() {\n"
			+ "			Map<String, ?> i = new HashMap<>();\n"
			+ "			return i;"
			+ "	}\n"
			+ "}\n"
			+ "";

	static boolean processNotRecursively(Node node) {
		if (!(node instanceof VariableDeclarationExpr)) {
			return false;
		}
		VariableDeclarationExpr variableDeclarationExpr = (VariableDeclarationExpr) node;

		if (variableDeclarationExpr.getVariables().size() >= 2) {
			return false;
		}

		VariableDeclarator singleVariableDeclaration = variableDeclarationExpr.getVariable(0);

		if (singleVariableDeclaration.getType().isVarType()) {
			return false;
		}

		singleVariableDeclaration.setType(new VarType());

		return true;
	}

	public static void main(String[] args) {
		CompilationUnit node = StaticJavaParser.parse(testCase);

		node = LexicalPreservingPrinter.setup(node);

		node.walk(innerNode -> {
			processNotRecursively(innerNode);
		});
	}
}

```

It seems related with https://github.com/javaparser/javaparser/issues/3296

**Comment by blacelle** [comment]
In `com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Kept, TextElement, boolean, boolean)`, over `Map<String, ?> i = new HashMap<>();` we replaced `Map` by `var` but `<String, ?>` is left. It is unclear to me what/where should (be) discarded the generic types in this case.

**Comment by jlerbsc** [comment]
I take back the comment I made on this issue which is relative to a similar subject.

https://github.com/javaparser/javaparser/issues/3365

> I advise you to create a new declaration. Indeed the problem you encounter is related to the way the lexical preserving printer assigns the tokens to the nodes and in addition to the presence of phantom nodes (virtual nodes).
First, the lexical preserving printer tries to assign java tokens to AST nodes according to the position of the nodes. It traverses all the nodes from the root of the AST as well as all the children in a resursive way with the exception of the nodes which have no position and the 'virtual/phantom' nodes. During this processing, the java tokens are assigned to the node closest to the token and whose position includes that of the token. Unfortunately, this logic does not work in the case of a variable declaration because the tokens describing the type of the variable are positioned before the actual declaration of the variable in the AST. In fact they are assigned to the expression in which the variable is declared. I am describing all this because when you modify a type, the modification is propagated to the direct parent but not to the grand parent or the great grand parent... So the modification does not reach the node which carries the tokens corresponding to the type of the variable and the modification is not taken into account by the lexical preserving printer.
In conclusion, it is extremely complicated to modify this mechanism and I strongly advise you to create a new declaration to replace the previous one.

**Comment by blacelle** [comment]
Thanks @jlerbsc .

The following code (in the context of above snippet) is working as expected:

		Expression initializer = singleVariableDeclaration.getInitializer().orElse(null);
		singleVariableDeclaration
				.replace(new VariableDeclarator(new VarType(), singleVariableDeclaration.getName(), initializer));
