### ISSUE TITLE
Hi ,sometimes(not every times, very small percent possibility) parse will cause stackoverflow error

### ISSUE THREAD

**Issue by LeoYelton** [javaparser/javaparser#3901]
```
Caused by: java.lang.StackOverflowError
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.lambda$static$0(ResolvedReferenceTypeDeclaration.java:125)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getAllAncestors(ResolvedReferenceTypeDeclaration.java:115)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getAllAncestors(ResolvedReferenceTypeDeclaration.java:104)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassAdapter.getAllFields(ReflectionClassAdapter.java:163)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionClassDeclaration.getAllFields(ReflectionClassDeclaration.java:303)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.lambda$getAllFields$2(JavaParserClassDeclaration.java:121)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAllFields(JavaParserClassDeclaration.java:121)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.getVisibleFields(ResolvedReferenceTypeDeclaration.java:225)
	at com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration.hasVisibleField(ResolvedReferenceTypeDeclaration.java:213)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:70)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolInType(SymbolSolver.java:140)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveSymbol(CompilationUnitContext.java:105)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:184)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveSymbol(ClassOrInterfaceDeclarationContext.java:75)
```

The project I parse is
https://github.com/isr-uci-edu/ArchStudio5

The version I use is 
3.24.0

**Comment by blacelle** [comment]
May relate with https://github.com/javaparser/javaparser/issues/3940

**Comment by jlerbsc** [comment]
Hi @Yelixing Without a simple test case that reproduces the anomaly we cannot work on this issue.
