### ISSUE TITLE
java.lang.UnsupportedOperationException: T[] while resolving generic method with type parameter with arrays like List<T[]>

### ISSUE THREAD

**Issue by CptGit** [javaparser/javaparser#3911]
javaparser-core version: 3.25.0
javaparser-symbol-solver-core version: 3.25.0

Test case
```java
import com.github.javaparser.StaticJavaParser;                                                                                                           
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class TypeParamIsArray {

    public static void main(String[] args) {
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(
                "import java.util.List;\n" +
                "import java.util.ArrayList;\n" +
                "class D {\n" +
                "    void main() {\n" +
                "        Integer[] a = new Integer[]{ Integer.valueOf(1), Integer.valueOf(2) };\n" +
                "        List<Integer[]> l = new ArrayList<>();\n" +
                "        l.add(a);\n" +
                "        m(l);\n" +
                "    }\n" +
                "    <T extends Number> void m(List<T[]> a) {}\n" +
                "}\n");
        MethodCallExpr method = cu.findFirst(MethodCallExpr.class, c -> c.getNameAsString().equals("m")).get();
        System.out.println(method.calculateResolvedType());
    }
}
```

Stack trace
```
Exception in thread "main" java.lang.UnsupportedOperationException: T[]
        at com.github.javaparser.resolution.logic.MethodResolutionLogic.isAssignableMatchTypeParametersMatchingQName(MethodResolutionLogic.java:313)
        at com.github.javaparser.resolution.logic.MethodResolutionLogic.isAssignableMatchTypeParameters(MethodResolutionLogic.java:258)
        at com.github.javaparser.resolution.logic.MethodResolutionLogic.isApplicable(MethodResolutionLogic.java:156)
        at com.github.javaparser.resolution.logic.MethodResolutionLogic.lambda$findMostApplicable$3(MethodResolutionLogic.java:539)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at com.github.javaparser.resolution.logic.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:540)
        at com.github.javaparser.resolution.logic.MethodResolutionLogic.findMostApplicable(MethodResolutionLogic.java:520)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveMethod(JavaParserTypeDeclarationAdapter.java:275)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveMethod(ClassOrInterfaceDeclarationContext.java:106)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveMethodAsUsage(AbstractJavaParserContext.java:277)
        at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.solveMethodAsUsage(JavaParserClassDeclaration.java:169)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:180)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:476)
        at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:121)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:659)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:329)
        at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
        at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)                                                                                            
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:294)
        at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:552)
        at TypeParamIsArray.main(TypeParamIsArray.java:29)
```

Please let me know if any more information is required, thanks!

**Comment by jlerbsc** [comment]
What version of java are you using?

**Comment by CptGit** [comment]
> What version of java are you using?

java version "11.0.18" 2023-01-17 LTS
Java(TM) SE Runtime Environment 18.9 (build 11.0.18+9-LTS-195)
Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.18+9-LTS-195, mixed mode)

Also, just realized the parsed compilation unit in the test code does not compile. I have updated it.

**Comment by jlerbsc** [comment]
Thank you for reporting this bug.

**Comment by jlerbsc** [comment]
I think the problem is that the type returned by the Arrays.asList(int[]) method is seen by the symbol solver as a 'List< Integer >' instead of a List<int[]>. I think it's a bug but I need another opinion. The problem is probably located in this method MethodCallExprContext.resolveMethodTypeParameters(..). @ftomassetti @matozoid @MysterAitch Any help would be welcome.

    Arrays.class
    public static<T>List<T> asList(T...a) {
         return newArrayList<>(a);
    }

**Comment by jlerbsc** [comment]
It's a more subtle bug than I thought a few hours ago. Indeed

    Arrays.asList(new Integer[] {1, 2}) -> must returns List<Integer>
    Arrays.asList(new int[] {1, 2}) -> must returns List<int[]>

I probably have the solution but I'm not sure it's definitive.

**Comment by jlerbsc** [comment]
I see you changed the example because the previous one doesn't compile. The fix works with this new test case.

**Comment by CptGit** [comment]
> I see you changed the example because the previous one doesn't compile. The fix works with this new test case.

Thanks a lot for fixing.
