### ISSUE TITLE
Method 'valueOf' cannot be resolved in context MyEnum.One.valueOf("")

### ISSUE THREAD

**Issue by Mewtwo0** [javaparser/javaparser#3916]
javaparser-core version: 3.25.0
javaparser-symbol-solver-core version: 3.25.0

Test case: 

`import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class Test {
    public static void main(String[] args) throws Exception {

        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        String code = "public class Test1 {\n" +
                "    private String str;\n" +
                "    public void setStr(String str) {\n" +
                "        this.str = str;\n" +
                "    }\n" +
                "\n" +
                "    public void test() {\n" +
                "        switch (MyEnum.One.valueOf(\"\")) {\n" +
                "            case One:\n" +
                "                setStr(str);\n" +
                "                break;\n" +
                "        }\n" +
                "    }\n" +
                "\n" +
                "    enum MyEnum {\n" +
                "        One;\n" +
                "    }\n" +
                "}";

        CompilationUnit cu = StaticJavaParser.parse(code);

        cu.findAll(MethodDeclaration.class).forEach(methodDeclaration -> {
            methodDeclaration.findAll(MethodCallExpr.class).forEach(methodCallExpr -> {
                System.out.println(methodCallExpr.resolve().getQualifiedSignature());
            });
        });
    }
}`

**Comment by Mewtwo0** [comment]
java version "1.8.0_212"
Java(TM) SE Runtime Environment (build 1.8.0_212-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.212-b10, mixed mode)


Stack trace

Exception in thread "main" java.lang.RuntimeException: Method 'valueOf' cannot be resolved in context MyEnum.One.valueOf("") (line: 8) MethodCallExprContext{wrapped=MyEnum.One.valueOf("")}. Parameter types: [com.github.javaparser.resolution.model.typesystem.LazyType@2b4a2ec7]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:662)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:329)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.SwitchEntryContext.solveSymbol(SwitchEntryContext.java:54)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:170)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbol(StatementContext.java:307)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbol(StatementContext.java:192)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:170)
	at com.github.javaparser.resolution.Context.solveSymbolAsValueInParentContext(Context.java:194)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:144)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:76)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:82)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:339)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:66)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:81)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:254)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:271)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:164)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:319)
	at Test.lambda$null$0(Test.java:42)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at Test.lambda$main$1(Test.java:41)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at Test.main(Test.java:40)

Process finished with exit code 1

**Comment by jlerbsc** [comment]
It seems to me that valueOf method allows you to retrieve a particular enum by passing its name.
So if your test case try it

    switch (MyEnum.valueOf("One"))

Then the result is 


    Test1.MyEnum.valueOf(java.lang.String)
    Test1.setStr(java.lang.String)

Even if your code compiles (there is still a warning "MyEnum should be accessed in a static way") I can't consider it a bug.

**Comment by Mewtwo0** [comment]
> It seems to me that valueOf method allows you to retrieve a particular enum by passing its name. So if your test case try it
> 
> ```
> switch (MyEnum.valueOf("One"))
> ```
> 
> Then the result is
> 
> ```
> Test1.MyEnum.valueOf(java.lang.String)
> Test1.setStr(java.lang.String)
> ```
> 
> Even if your code compiles (there is still a warning "MyEnum should be accessed in a static way") I can't consider it a bug.

Thanks for your reply.
Yes, I agree with your. But for some reasons, there are some such code needs to be parsed to MethodCallExpr.
Do you have any good suggestions without modifying the source code ?
Thanks.

**Comment by jlerbsc** [comment]
You can exclude method calls whose scope is an enumeration from analysis. I don't know if this can fit your needs. Without more information on what you want to do it is difficult to have proposals.

**Comment by jlerbsc** [comment]
Should this issue remain open or have our answers allowed you to make progress on your subject?

**Comment by Mewtwo0** [comment]
> Should this issue remain open or have our answers allowed you to make progress on your subject?

Thanks for your reply.
I still have some question.
Please allow me to send them in a few hours.
Thanks.

**Comment by Mewtwo0** [comment]
Thank you for waiting.
Can you please parse the method Test01#test01(Test02) as MethodCallExpr?
When there is a static enum, parsing ‘switch (Test02.MyEnum.valueOf(test02.getField1())) {’ to MethodCallExpr will report an error.


`public class Test01 {

	public void test01(Test02 test02) {

		switch (Test02.MyEnum.valueOf(test02.getField1())) {
		case One:
			System.out.println(test02.getField2());
			break;
		}

	}

}`

`public class Test02 {

	public String getField1() {
		return "";
	}

	public String getField2() {
		return "";
	}

	public static enum MyEnum {
		One;
	}

}`

**Comment by jlerbsc** [comment]
This is probably a particular case of inner class but if you use this syntax (with the import statement) the result is correct.

    switch (MyEnum.valueOf(test02.getField1()))

**Comment by Mewtwo0** [comment]
> This is probably a particular case of inner class but if you use this syntax (with the import statement) the result is correct.
> 
> ```
> switch (MyEnum.valueOf(test02.getField1()))
> ```

Thanks for your reply.
It's work! Thanks!
And I want to know if this kind of case will be fixed in the future.
Thanks again!

**Comment by jlerbsc** [comment]
We are not going to close the issue so that we can deal with it later. Included classes are handled in JP but there must be a bug on the enumerations.

**Comment by Mewtwo0** [comment]
> We are not going to close the issue so that we can deal with it later. Included classes are handled in JP but there must be a bug on the enumerations.

Thank you!!!
It's helped me.
Waiting for your good news!
All the best!
