### ISSUE TITLE
JavaParserTypeDeclarationAdapter resolving wrong Type via Ancestor

### ISSUE THREAD

**Issue by mytlogos** [javaparser/javaparser#3918]
## Problem

Given these two source files:

```java
package org.example;

public class Ancestor {
    public static class Iterator {

    }
}
```

```java
package org.example;

import java.util.ArrayList;
import java.util.List;

public class Descendant extends Ancestor {
    public void doAThing() {
        List<Object> list = new ArrayList<>();
        java.util.Iterator<Object> iterator = list.iterator();
    }
}
```

Parsing the file Descendant.java and resolving the type java.util.Iterator leads to an IllegalArgumentException:

```
Exception in thread "main" java.lang.IllegalArgumentException: expected either zero type arguments or has many as defined in the declaration (0). Found 1
	at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:74)
	at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:67)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:357)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:620)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:284)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:325)
	at org.example.Main.main(Main.java:49)

```

## Test Case

See example repo at https://github.com/mytlogos/JavaParserAncestorBug
Can be executed via `./gradlew run` (linux).

Example Output from the Repo:

```
Resolving type: void
Type: void; Resolved: com.github.javaparser.resolution.types.ResolvedVoidType@41ee392b
Resolving type: List<Object>
Type: List<Object>; Resolved: ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}
Resolving type: ArrayList<>
Type: ArrayList<>; Resolved: ReferenceType{java.util.ArrayList, typeParametersMap=TypeParametersMap{nameToValue={}}}
Resolving type: java.util.Iterator<Object>
Exception in thread "main" java.lang.IllegalArgumentException: expected either zero type arguments or has many as defined in the declaration (0). Found 1
        at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:74)
        at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:67)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:357)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:620)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:284)
        at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:325)
        at org.example.Main.main(Main.java:49)

```

Example Output if Iterator is generic:

```
Resolving type: void
Type: void; Resolved: com.github.javaparser.resolution.types.ResolvedVoidType@41ee392b
Resolving type: List<Object>
Type: List<Object>; Resolved: ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}
Resolving type: ArrayList<>
Type: ArrayList<>; Resolved: ReferenceType{java.util.ArrayList, typeParametersMap=TypeParametersMap{nameToValue={}}}
Resolving type: java.util.Iterator<Object>
Type: java.util.Iterator<Object>; Resolved: ReferenceType{org.example.Ancestor.Iterator, typeParametersMap=TypeParametersMap{nameToValue={org.example.Ancestor.Iterator.E=ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}}}}}
Resolving type: Ancestor
Type: Ancestor; Resolved: ReferenceType{org.example.Ancestor, typeParametersMap=TypeParametersMap{nameToValue={}}}
```

## Cause

JavaParserTypeDeclarationAdapter looks up the typename "Iterator"  in line 133, successfully resolving to the wrong type in the ancestor class and ignoring the rest of the fully qualified name. As the wrong type does not have any type parameters, this fails (as it should).

## Possible Solutions

Ignore type resolved from ancestor if the used type is fully qualified and does not match the fully qualified name from the ancestor. This would elevate the resolving to another ParentContext which maybe? could successfully resolve this type.

## Comments

I do not have control over the real code this example was extracted from.

**Comment by jlerbsc** [comment]
Thank you for reporting this bug and specifying all these details.
