### ISSUE TITLE
Removing ImportDeclaration with Annotated package through LexicalPreservingPrinter

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3924]
I consider JavaParser 3.25.0.

I get an exception :

```
Exception in thread "main" java.lang.UnsupportedOperationException: kept child(PackageDeclaration) vs "@"   <107>   (line 7,col 1)-(line 7,col 1)
	at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:695)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:342)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:400)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementRemoved$2(NodeList.java:492)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.ast.NodeList.notifyElementRemoved(NodeList.java:492)
	at com.github.javaparser.ast.NodeList.remove(NodeList.java:156)
	at com.github.javaparser.ast.CompilationUnit.remove(CompilationUnit.java:603)
	at com.github.javaparser.ast.Node.remove(Node.java:573)
	at eu.solven.cleanthat.engine.java.refactorer.report_javaparser.LexicalPreservingAnnotatedPackage.main(LexicalPreservingAnnotatedPackage.java:48)
```

with the following code:

```
package eu.solven.cleanthat.engine.java.refactorer.report_javaparser;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter;

public class LexicalPreservingAnnotatedPackage {
	static final String testCase = "/*\n" + " * Licensed under the Apache License, Version 2.0 (the \"License\");\n"
			+ " * you may not use this file except in compliance with the License.\n"
			+ " * You may obtain a copy of the License at\n"
			+ " */\n"
			+ "\n"
			+ "@XmlSchema(\n"
			+ "		xmlns = {\n"
			+ "				@XmlNs(prefix = \"order\", namespaceURI = \"http://www.camel.apache.org/jaxb/example/order/1\"),\n"
			+ "				@XmlNs(prefix = \"address\", namespaceURI = \"http://www.camel.apache.org/jaxb/example/address/1\")\n"
			+ "		}\n"
			+ ")\n"
			+ "package net.revelc.code.imp;\n"
			+ "\n"
			+ "import net.revelc.code.imp.Something;\n"
			+ "\n"
			+ "@Component\n"
			+ "public class UnusedImports {\n"
			+ "}\n"
			+ "";

	public static void main(String[] args) {
		CompilationUnit node = StaticJavaParser.parse(testCase);

		node = LexicalPreservingPrinter.setup(node);

		node.getImport(0).remove();  // < -------- THIS FAILS ---------

		System.out.println(LexicalPreservingPrinter.print(node));
	}
}

```

FYI, We are considering using Javaparser as an alternative way to strip unused imports in spotless: https://github.com/diffplug/spotless/pull/1589

**Comment by jlerbsc** [comment]
Hi @blacelle I think this is mostly related to how the parser assigns positions to nodes.
In this case, we see that the position of the package declaration does not include the position of the annotation. However, the annotation is an attribute of the node. I'll look into it soon I hope.

**Comment by blacelle** [comment]
Thanks @jlerbsc . FYI, JavaParser is integrated in [CleanThat](https://github.com/solven-eu/cleanthat) for various automated refactoring rules, and [UnnecessaryImport](https://github.com/solven-eu/cleanthat/blob/master/java/src/main/java/eu/solven/cleanthat/engine/java/refactorer/mutators/UnnecessaryImport.java) will be used as `removeUnusedImports` engine in [Spotless](https://github.com/diffplug/spotless) (as alternative to [Google java Format](https://github.com/google/google-java-format/blob/master/core/src/main/java/com/google/googlejavaformat/java/RemoveUnusedImports.java), in order to support JDK17 source-code from JDK11 runtime.
