### ISSUE TITLE
SymbolResolver.calculateType(Expression) may fails on first try, then succeed on later tries

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3939]
I consider an expression for which I want to resolve its type. The resolution is expected to fail as the code refers to classes which are not available to the TypeSolver. However, I encounter cases where a first try fails while and immediate second try succeed.

- Is the initial failure a bug?
- Is the later success a bug?
- Is this a limitation ?
- Should I always retry any type resolution to get a consistant type resolution? (For now, I do that.)

Here is a reproduction scenario:

```
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.resolution.types.ResolvedType;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class UnconsistantTypeResolution {
	static final String testCase = "import java.util.List;\n" + "import java.util.stream.Collectors;\n"
			+ "\n"
			+ "import eu.solven.cleanthat.engine.java.refactorer.meta.IMutator;\n"
			+ "\n"
			+ "public class Case_UnclearGenericBounds {\n"
			+ "\n"
			+ "    public void pre(List<Class<?>> classNames) {\n"
			+ "        classNames.stream().map(c -> c.asSubclass(IMutator.class));\n"
			+ "    }\n"
			+ "}";

	public static void main(String[] args) {
		System.out.println(testCase);

		StaticJavaParser.setConfiguration(
				new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(true))));
		var unit = StaticJavaParser.parse(testCase);

		Expression expr = unit.findFirst(MethodCallExpr.class).get();
		
		System.out.println(expr);

		try {
			ResolvedType type = expr.getSymbolResolver().calculateType(expr);
			System.out.println(type);  // <-- Not called as previous resolution failed
		} catch (RuntimeException e) {
			e.printStackTrace();

			ResolvedType typeSecondTry = expr.getSymbolResolver().calculateType(expr);
			System.out.println(typeSecondTry); // <-- This prints some type detail
		}

	}
}
```

which prints:

```
UnsolvedSymbolException{context='null', name='IMutator', cause='null'}
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347)
	at com.github.javaparser.ast.type.WildcardType.convertToUsage(WildcardType.java:272)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.lambda$convertToUsage$3(ClassOrInterfaceType.java:352)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:352)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:163)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.CastExpr.accept(CastExpr.java:77)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.resolveLambda(TypeExtractor.java:546)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:496)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.LambdaExpr.accept(LambdaExpr.java:164)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:359)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:101)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:659)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:323)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:332)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:294)
	at eu.solven.cleanthat.engine.java.refactorer.report_javaparser.UnconsistantTypeResolution.main(UnconsistantTypeResolution.java:55)

ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=InferenceVariableType{id=0}}}}
```

**Comment by jlerbsc** [comment]
At first glance, this would be a bug.

**Comment by blacelle** [comment]
I suppose this relates to type resolution cache, but I was not able to find anything relevant.

**Comment by blacelle** [comment]
Having a new look into this, I believe the issue comes from `JavaParserFacade.getType`:

The relevant code is:

```
            if (!node.containsData(TYPE_WITH_LAMBDAS_RESOLVED)) { // <-- This returns true on first call, but false on second call: it skips the throwing `getType`
                ResolvedType res = getTypeConcrete(node, solveLambdas);

                node.setData(TYPE_WITH_LAMBDAS_RESOLVED, res);  // <-- This will write in cache as soon as first pass, but won't be cleaned in case of exception

                boolean secondPassNecessary = false;
                if (node instanceof MethodCallExpr) {
                    MethodCallExpr methodCallExpr = (MethodCallExpr) node;
                    for (Node arg : methodCallExpr.getArguments()) {
                        if (!arg.containsData(TYPE_WITH_LAMBDAS_RESOLVED)) {
                            getType(arg, true);  // <-- This fails due to unknown symbol: it is legit, but it should lead to `node.setData(...)` cancellation 
                            secondPassNecessary = true;
                        }
                    }
                }
                if (secondPassNecessary) {
                    node.removeData(TYPE_WITH_LAMBDAS_RESOLVED);
                    ResolvedType type = getType(node, true);
                    node.setData(TYPE_WITH_LAMBDAS_RESOLVED, type);

                }
                Log.trace("getType on %s  -> %s", () -> node, () -> res);
            }
            return node.getData(TYPE_WITH_LAMBDAS_RESOLVED);
```

In other words:

1. On first call, `if (!node.containsData(TYPE_WITH_LAMBDAS_RESOLVED)) {` return true so we try type resolution
2. First pass is a success and `node.setData(TYPE_WITH_LAMBDAS_RESOLVED, res);` is successfully executed
3. Second pass is a failure around `getType(arg, true);`, as we see in the stack: `at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358`
4. So first try leads to an exception
5. On second try, `if (!node.containsData(TYPE_WITH_LAMBDAS_RESOLVED)) {` returns false and we return the cached result (from first pass), skipping the failing `getType`

Is it proper fix to add some `try/catch` block to cancel `node.getData` in case of exception in second pass? If yes, I'm willing to open a PR.

**Comment by jlerbsc** [comment]
I think your analysis is correct, but the solution can certainly be improved.

**Comment by jlerbsc** [comment]
The curious thing about this method is the notion of a second pass. Unfortunately, the reason why this second pass is necessary is not documented, and it is difficult to understand its author's logic.

This second pass seems to be necessary when the node whose type we are looking for corresponds to a method invocation. In this particular case, the algorithm tries to resolve the type of the arguments before launching a new search for the type of the method call.

So I wonder whether it wouldn't be a good idea in this case to reverse the type analysis by first checking the type of the arguments and then looking for the type of the node corresponding to the method call. This would remove the confusing notion of a second pass, it would solve your problem and it would improve the performance of the algorithm because the method invocation would only be analysed once.

I've tested this solution and it passes all the tests, but despite everything I'm not completely reassured because I'm missing information to better understand the author's intention.
