### ISSUE TITLE
StackOverFlow on TypeResolution

### ISSUE THREAD

**Issue by blacelle** [javaparser/javaparser#3940]
The following code produces a StackOverFLow:

```
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class StackOverFLowOnTypeResolution {
	static final String testCase = "package org.apache.logging.log4j.core.async;\n" + "\n"
			+ "public class AsyncLoggerConfig {\n"
			+ "\n"
			+ "    public static class RootLogger {\n"
			+ "\n"
			+ "        public static class Builder<B extends Builder<B>> extends RootLogger.Builder<B> {\n"
			+ "\n"
			+ "            @Override\n"
			+ "            public LoggerConfig build() {\n"
			+ "                LevelAndRefs container = LoggerConfig.getLevelAndRefs(getLevel(), getRefs(), getLevelAndRefs(),\n"
			+ "                        getConfig());\n"
			+ "                return new AsyncLoggerConfig(LogManager.ROOT_LOGGER_NAME);\n"
			+ "            }\n"
			+ "        }\n"
			+ "    }\n"
			+ "}\n"
			+ "";

	public static void main(String[] args) {
		System.out.println(testCase);

		StaticJavaParser.setConfiguration(
				new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(true))));
		var unit = StaticJavaParser.parse(testCase);

		Expression expr = unit.findFirst(MethodCallExpr.class).get();

		expr.getSymbolResolver().calculateType(expr);
	}
}
```

```
Exception in thread "main" java.lang.StackOverflowError
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3963)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4749)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
	at java.base/java.util.regex.Pattern$BranchConn.match(Pattern.java:4713)
	at java.base/java.util.regex.Pattern$GroupTail.match(Pattern.java:4863)
	at java.base/java.util.regex.Pattern$BmpCharPropertyGreedy.match(Pattern.java:4344)
	at java.base/java.util.regex.Pattern$GroupHead.match(Pattern.java:4804)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4749)
	at java.base/java.util.regex.Pattern$Branch.match(Pattern.java:4747)
	at java.base/java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3964)
	at java.base/java.util.regex.Pattern$Start.match(Pattern.java:3619)
	at java.base/java.util.regex.Matcher.search(Matcher.java:1729)
	at java.base/java.util.regex.Matcher.find(Matcher.java:773)
	at java.base/java.util.Formatter.parse(Formatter.java:2702)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeParameter.getQualifiedName(JavaParserTypeParameter.java:142)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParametersMap.getValue(ResolvedTypeParametersMap.java:103)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$typeParametersValues$5(ResolvedReferenceType.java:273)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.typeParametersValues(ResolvedReferenceType.java:273)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.replaceTypeVariables(ResolvedReferenceType.java:175)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParametersMap.replaceAll(ResolvedTypeParametersMap.java:138)
	at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.lambda$getDirectAncestors$5(ReferenceTypeImpl.java:232)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.getDirectAncestors(ReferenceTypeImpl.java:233)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethods(ResolvedReferenceType.java:404)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethods$6(ResolvedReferenceType.java:404)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethods(ResolvedReferenceType.java:404)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethods$6(ResolvedReferenceType.java:404)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethods(ResolvedReferenceType.java:404)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethods$6(ResolvedReferenceType.java:404)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethods(ResolvedReferenceType.java:404)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethods$6(ResolvedReferenceType.java:404)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethods(ResolvedReferenceType.java:404)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethods$6(ResolvedReferenceType.java:404)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.getAllMethods(ResolvedReferenceType.java:404)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.lambda$getAllMethods$6(ResolvedReferenceType.java:404)
```

**Comment by csuhqh** [comment]
i also meet the same problem, this seem a bug, which is the extends class name can't be the same with class name
