### ISSUE TITLE
ConfilictingGenericTypesException is thrown when an Object type is expected as a parameter and an interface is provided as the actual parameter

### ISSUE THREAD

**Issue by dwragge** [javaparser/javaparser#3951]
Hi,

The following code throws a `ConfilictingGenericTypesException` hinting that the interface class can not be substituted for the `Object` on the `Map.containsKey()` call. Resolving the `containsKey` method directly works, but attempting to resolve the `assertThat` method throws the exception.

Reproducing test case:
```java
package test;,
import java.util.HashMap;,
import java.util.Map;,
interface Foo {,
    String getFoo();,
    String getBar();,
}

class FooImpl implements Foo {,
    String getFoo() { return foo; }
    String getBar() { return bar; }
}
public class Application {,
    public static void main() {
        Foo f = new FooImpl();
        Map<Foo, Object> m = new HashMap<>();
        assertThat(m.containsKey(f));
    }
    public static void assertThat(Object m) {
        assert m != null;
    }
};
```

Exception thrown:
```
com.github.javaparser.resolution.logic.ConfilictingGenericTypesException: No matching between ReferenceType{java.lang.Object, typeParametersMap=TypeParametersMap{nameToValue={}}} (formal) and ReferenceType{test.Foo, typeParametersMap=TypeParametersMap{nameToValue={}}} (actual)

	at com.github.javaparser.resolution.logic.InferenceContext.registerCorrespondance(InferenceContext.java:92)
	at com.github.javaparser.resolution.logic.InferenceContext.addPair(InferenceContext.java:66)
	at com.github.javaparser.symbolsolver.reflectionmodel.ReflectionInterfaceDeclaration.solveMethodAsUsage(ReflectionInterfaceDeclaration.java:160)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:180)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:482)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:121)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:659)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:323)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:503)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:350)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:254)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:271)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:164)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:319)
```

**Comment by jlerbsc** [comment]
Can you provide us with a simple unit test that demonstrates your problem.

**Comment by dwragge** [comment]
Sure thing

```java
package com.github.javaparser.symbolsolver;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.*;

import com.github.javaparser.*;
import com.github.javaparser.ast.*;
import com.github.javaparser.ast.expr.*;
import com.github.javaparser.symbolsolver.resolution.*;
import com.github.javaparser.symbolsolver.resolution.typesolvers.*;

public class Issue3951 extends AbstractResolutionTest {
    @Test
    public void test() {
        final String code = String.join(System.lineSeparator(),
                                          "package test;",
                                          "import java.util.HashMap;",
                                          "import java.util.Map;",
                                          "interface Foo {",
                                          "    String getFoo();",
                                          "    String getBar();",
                                          "}",
                                          "class FooImpl implements Foo {",
                                          "    String getFoo() { return \"foo\"; } ",
                                          "    String getBar() { return \"bar\"; } ",
                                          "}",
                                          "",
                                          "public class Application {",
                                          "    public static void main() {",
                                          "        Foo f = new FooImpl();",
                                          "        Map<Foo, Object> m = new HashMap<>();",
                                          "        assertThat(m.containsKey(f));",
                                          "    }",
                                          "    public static void assertThat(Object m) {",
                                          "        assert m != null;",
                                          "    }",
                                          "}");

        CompilationUnit cu = JavaParserAdapter.of(createParserWithResolver(new ReflectionTypeSolver())).parse(code);

        MethodCallExpr getOrDefaultCall = cu.findAll(MethodCallExpr.class).stream()
            .filter(m -> m.getNameAsString().equals("assertThat"))
            .findFirst()
            .get();

        assertEquals("test.Application.assertThat", getOrDefaultCall.resolve().getQualifiedName());
    }
}
```

**Comment by jlerbsc** [comment]
Thank you for reporting this bug.
