### ISSUE TITLE
StackOverflowError when resolving type of scope of a MethodCall

### ISSUE THREAD

**Issue by abego** [javaparser/javaparser#3972]
_(with JavaParser 3.25.2-SNAPSHOT)_

Trying to resolve the type of the scope of the method call

```
cls.getSuperclass().getSuperclass().toString()
```

in this code

```
class C {
    void f() throws NoSuchMethodException {
        Class cls = getClass();
        cls.getSuperclass().getSuperclass().toString();
    }
}
```

using this test method

```
    @Test
    public void testStackOverflowInResolvedTypeParameterValueProvider() {
        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver(false)));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(
                "class C {\n" +
                        "    void f() throws NoSuchMethodException {\n" +
                        "        Class cls = getClass();\n" +
                        "        cls.getSuperclass().getSuperclass().toString();\n" +
                        "    }\n" +
                        "}"
        );

        for (MethodCallExpr methodCallExpr : cu.findAll(MethodCallExpr.class)) {
            methodCallExpr.getScope().ifPresent(s -> {
                String type = s.calculateResolvedType().describe();
            });
        }
    }
```

results in a

```
java.lang.StackOverflowError
	at java.base/java.lang.Character.getType(Character.java:10990)
	at java.base/java.text.DecimalFormatSymbols.lambda$findNonFormatChar$0(DecimalFormatSymbols.java:844)
	at java.base/java.util.stream.IntPipeline$9$1.accept(IntPipeline.java:368)
	at java.base/java.lang.StringUTF16$CharsSpliterator.tryAdvance(StringUTF16.java:1191)
	at java.base/java.util.stream.IntPipeline.forEachWithCancel(IntPipeline.java:163)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.findFirst(IntPipeline.java:528)
	at java.base/java.text.DecimalFormatSymbols.findNonFormatChar(DecimalFormatSymbols.java:845)
	at java.base/java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:824)
	at java.base/java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:115)
	at java.base/sun.util.locale.provider.DecimalFormatSymbolsProviderImpl.getInstance(DecimalFormatSymbolsProviderImpl.java:85)
	at java.base/java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:182)
	at java.base/java.util.Formatter.getZero(Formatter.java:2437)
	at java.base/java.util.Formatter.<init>(Formatter.java:1956)
	at java.base/java.util.Formatter.<init>(Formatter.java:1978)
	at java.base/java.lang.String.format(String.java:3292)
	at com.github.javaparser.resolution.declarations.ResolvedTypeParameterDeclaration.getQualifiedName(ResolvedTypeParameterDeclaration.java:158)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParametersMap.getValue(ResolvedTypeParametersMap.java:103)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.typeParamValue(ResolvedReferenceType.java:376)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:48)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
	at com.github.javaparser.resolution.types.parametrization.ResolvedTypeParameterValueProvider.useThisTypeParametersOnTheGivenType(ResolvedTypeParameterValueProvider.java:58)
...
```

**Comment by jlerbsc** [comment]
Thanks for reporting this bug

**Comment by jlerbsc** [comment]
This is caused by the way type parameters are handled. This is a part that is poorly documented and relatively complex. It will be difficult to find a solution. A starting point would be in the class MethoUsage.replaceTypeParameter(..)

**Comment by abego** [comment]
@jlerbsc Thanks for fixing this issue. This fixed the problem in my project.
