### ISSUE TITLE
typesolver can't parse in parallel

### ISSUE THREAD

**Issue by jiaxian-lin** [javaparser/javaparser#3978]
I know that because JavaParserFacade is a static class, javaparser can't allocate a separate parser for each thread, but I still get deadlocks when parsing multiple java files with the same type parser.

this is my code:
```
CountDownLatch countDownLatch = new CountDownLatch(repoClasses.size());
for (RepoClass repoClass : repoClasses) {
    parseExecutorService.execute(() -> {
        try {
            VoidVisitor<RepoClass> methodCallVisitor = new MethodCallVisitor();
            methodCallVisitor.visit(repoClass.getAST(), repoClass);
        } catch (Exception e) {
        } finally {
             countDownLatch.countDown();
        }
    });
}
countDownLatch.countDown();

class MethodCallVisitor extends VoidVisitorAdapter<RepoClass>{
        @Override
        public void visit(MethodCallExpr methodCallExpr, RepoClass rootClass){
            super.visit(methodCallExpr, rootClass);
            ResolvedMethodDeclaration resCall = methodCallExpr.resolve();
        }
```
Here is the stack state of the thread
```
"pool-3-thread-172" #229 prio=5 os_prio=0 cpu=33196.09ms elapsed=33.50s tid=0x00007fab90efca90 nid=0x7dda0 runnable  [0x00007fab8d8f2000]
   java.lang.Thread.State: RUNNABLE
	at java.util.WeakHashMap.get(java.base@17.0.6/WeakHashMap.java:409)
	at com.github.javaparser.symbolsolver.cache.InMemoryCache.get(InMemoryCache.java:60)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver.tryToSolveType(CombinedTypeSolver.java:153)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.CompilationUnitContext.solveType(CompilationUnitContext.java:196)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:151)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:101)
	at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractMethodLikeDeclarationContext.solveType(AbstractMethodLikeDeclarationContext.java:122)
	at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
	at com.github.javaparser.resolution.Context.solveType(Context.java:120)
	at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
	at com.github.javaparser.resolution.Context.solveType(Context.java:120)
	at com.github.javaparser.resolution.Context.solveTypeInParentContext(Context.java:154)
	at com.github.javaparser.resolution.Context.solveType(Context.java:120)
	at com.github.javaparser.resolution.Context.solveType(Context.java:97)
```

**Comment by jlerbsc** [comment]
JP was not designed to be used with multiple threads. You will find several references to this subject in different issues.
