### ISSUE TITLE
ArrayIndexOutOfBoundsException throws when method param is variadic

### ISSUE THREAD

**Issue by challwang** [javaparser/javaparser#4037]
- In the flying visit, I call **MethodReferenceExpr.resolve()** method. 
```
    @Override
    public void visit(MethodReferenceExpr methodReferenceExpr, Context context) {
        // some code
        methodReferenceExpr.resolve();
        // other code
    }
```
- Then I debugged into **TypeExtractor.visit(MethosReferenceMethod node, Boolean solveLambdas)**
- At line 595, the **getParamPos(node);** method returns the position of the input parameter, then at line 638, the refMethod.getCorrespondingDeclaration().getParam(pos).getType() method returns the ResolvedType of this parameter. 
```
int pos = getParamPos(node);        // the value of pos variable is 1
```
- But when the parameter is variadic, there is only one parameter in **refMethod.getCorrespondingDeclaration()** method. So **ArrayIndexOutOfBoundsException** throws if the source code calls the method with more than one parameter.
```
// refMethod.getCorrespondingDeclaration().getNumberOfParams() is 1 because param is variadic
return refMethod.getCorrespondingDeclaration().getParam(pos).getType();    // ArrayIndexOutOfBoundsException throws
```

**Comment by jlerbsc** [comment]
Can you provide us with a simple reproducible test case please?

**Comment by challwang** [comment]
Here is the test case:
**entry class**:
```
public class Test1 {
    public List<String> p() {
        Wrappers.lambdaQuery(new TestPOJO()).do2(TestPOJO::getD1, TestPOJO::getD2);
        return null;
    }
}
```

```
@FunctionalInterface
public interface SFunction<T, R> extends Function<T, R>, Serializable{
}
```

```
public interface Func<Children, R> extends Serializable {
    default Children do2(R... rs) {
        return null;
    }
    Children do1(boolean b, boolean b1, R... rs);
}
```

```
public abstract class AbstractWrapper<T, R, Children extends AbstractWrapper<T, R, Children>> implements Func<Children, R> {
    protected void initEntityClass() {}
    @Override
    public Children do1(boolean b, boolean b1, R... rs) {
        return null;
    }
```

```
public abstract class AbstractLWrapper<T, Children extends AbstractWrapper<T, Children>> extends AbstractWrapper<T, SFunction<T, ?>, Children> {
    @Override
    protected void initEntityClass() {
        super.initEntityClass();
    }
}
```

```
public class LambdaQWrapper<T> extends AbstractLWrapper<T, LambdaQWrapper<T>> {
    public LambdaQWrapper(T entity) {
    }
}
```

```
public final class Wrappers {
    public static <T> LambdaQWrapper<T> lambdaQuery(T entity) {
        return new LambdaQWrapper<>(entity);
    }
}
```

```
public class TestPOJO {
    private BigDecimal d2;
    private LocalDateTime d1;

    public BigDecimal getD2() { return this.d2; }
    public LocalDateTime getD1() { return this.d1; }
```

When visits the MethodReferenceExpr, exception throws
```
    @Override
    public void visit(MethodReferenceExpr methodReferenceExpr, Context context) {
        // some code
        methodReferenceExpr.resolve();
        // other code
    }
```

The exception stack trace is :
```
java.lang.IllegalArgumentException: No param with index 1. Number of params: 1
    at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.getParam(JavaParserMethodDeclaration.java:98)
......
```

**Comment by jlerbsc** [comment]
Thanks for this test case but isn't there a way to provide a much simpler test case?

**Comment by challwang** [comment]
Sorry, how about this test case
```
public class Test1 {
    public static BigDecimal getD2() { return null; }
    public static LocalDateTime getD1() { return null; }
    public void do(Supplier... rs) { }

    public void test() {
        new Test1().do(Test1::getD1, Test1::getD2);    // exception throws
    }
}
```
The exception stack trace is :
```
java.lang.IllegalArgumentException: No param with index 1. Number of params: 1
    at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.getParam(JavaParserMethodDeclaration.java:98)
......
```

**Comment by jlerbsc** [comment]
It seems that you have identified a problem with methods having a variable number of parameters and which particularly appears when trying to resolve a method parameter which is a method reference.
