### ISSUE TITLE
Parsing fails with comment cannot be commented for valid source file

### ISSUE THREAD

**Issue by javeleon** [javaparser/javaparser#404]
Turns out that the following lines will throw the parser off:

``` java
​mAvailablePrimaryConnection = openConnectionLocked(mConfiguration,
        true /*primaryConnection*/); // comment
```

Source file from:
https://raw.githubusercontent.com/requery/sqlite-android/master/sqlite-android/src/main/java/io/requery/android/database/sqlite/SQLiteConnectionPool.java

**Comment by DeepSnowNeeL** [comment]
Here is the test to add to parsing_scenarios.story

```
Scenario: The method call has comments in its parameters
Given a CompilationUnit
When the following source is parsed:
public class Example {
  Object mAvailablePrimaryConnection;
  public Example(String arg) {
     ​mAvailablePrimaryConnection = openConnectionLocked(mConfiguration,
        true /*primaryConnection*/); // comment
  }
}
Then no errors are reported
```

The actual error is :

```
com.github.javaparser.TokenMgrException: Lexical error at line 4, column 6.  Encountered: "\u200b" (8203), after : ""
    at com.github.javaparser.ASTParserTokenManager.getNextToken(ASTParserTokenManager.java:2394)
    at com.github.javaparser.ASTParser.jj_scan_token(ASTParser.java:9671)
    at com.github.javaparser.ASTParser.jj_3R_102(ASTParser.java:7670)
    at com.github.javaparser.ASTParser.jj_3R_190(ASTParser.java:8369)
    at com.github.javaparser.ASTParser.jj_3R_136(ASTParser.java:8377)
    at com.github.javaparser.ASTParser.jj_3R_96(ASTParser.java:8418)
    at com.github.javaparser.ASTParser.jj_3_8(ASTParser.java:8470)
    at com.github.javaparser.ASTParser.jj_2_8(ASTParser.java:5322)
    at com.github.javaparser.ASTParser.ConstructorDeclaration(ASTParser.java:1513)
...
```

**Comment by matozoid** [comment]
There's an odd unicode character just before "mAvailable..."
http://www.fileformat.info/info/unicode/char/200B/index.htm

**Comment by matozoid** [comment]
Okay, I've added support for  all unicode whitespace characters. Now there's another error:

```
java.lang.RuntimeException: A comment can not be commented

    at com.github.javaparser.ast.Node.setComment(Node.java:237)
    at com.github.javaparser.CommentsInserter.attributeLineCommentToNodeOrChild(CommentsInserter.java:201)
    at com.github.javaparser.CommentsInserter.attributeLineCommentToNodeOrChild(CommentsInserter.java:212)
    at com.github.javaparser.CommentsInserter.insertCommentsInNode(CommentsInserter.java:149)
    at com.github.javaparser.CommentsInserter.insertCommentsInNode(CommentsInserter.java:138)
    at com.github.javaparser.CommentsInserter.insertCommentsInNode(CommentsInserter.java:138)
    at com.github.javaparser.CommentsInserter.insertCommentsInNode(CommentsInserter.java:138)
    at com.github.javaparser.CommentsInserter.insertCommentsInCu(CommentsInserter.java:106)
    at com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:58)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:174)
    at com.github.javaparser.JavaParser.parse(JavaParser.java:165)
    at com.github.javaparser.Bla.woefjwe(Bla.java:10)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runners.Suite.runChild(Suite.java:128)
    at org.junit.runners.Suite.runChild(Suite.java:27)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by ftomassetti** [comment]
I think this can be fixed adding on line 199 of CommentsInserter a check to verify that the target node is not a comment. I can prepare a PR for this and try to parse the given example. Is there any patch you are working on that I should include? the one one in #411?

**Comment by matozoid** [comment]
Woohoo, three people fixed this problem at once :) But I was first in #411 ;)

**Comment by ftomassetti** [comment]
Good, better too many and one too few :)

**Comment by matozoid** [comment]
Available on master.
