### ISSUE TITLE
MethodCallExpr that calls user-written methods cannot be solved

### ISSUE THREAD

**Issue by julian5392** [javaparser/javaparser#4058]
When I try to figure out where the method in the call expression is declared, an UnsolvedSymbolException error occurs. I'm a novice using javaparser, please let me know if there's any problem.
Here's a testcase that can be reproduced

```
public class MethodCallResolve {
    public static void main(String[] args) throws Exception {
        TypeSolver myTypeSolver = new CombinedTypeSolver(
                new ReflectionTypeSolver(),
                new JavaParserTypeSolver("src\\main\\java\\testcode")
        );
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(myTypeSolver);
        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(new File("src\\main\\java\\testcode\\file2.java"));
        cu.findAll(MethodCallExpr.class).forEach(mce ->
                System.out.println(mce.resolve().getQualifiedSignature()));
    }
}

```
The testcode file folder contains two files.
File1.java

```
package testcode;
import java.util.Arrays;
public class File1 {
    public void printHello() {
        System.out.println("Hello from File1!");
    }
    public int sumArray(int[] arr) {
        return Arrays.stream(arr).sum();
    }
}

```
File2.java

```
package testcode;
import java.util.Random;
public class File2 {
    public void printWelcome() {
        System.out.println("Welcome from File2!");
    }

    public void generateRandomNumbers() {
        Random random = new Random();
        int num1 = random.nextInt(100);
        int num2 = random.nextInt(100);
        System.out.println("Random Numbers: " + num1 + ", " + num2);
    }

    public static void main(String[] args) {
        File1 file1 = new File1();
        file1.printHello();
        int[] numbers = {1, 2, 3, 4, 5};
        int sum = file1.sumArray(numbers);
        System.out.println("Sum: " + sum);
        File2 file2 = new File2();
        file2.printWelcome();
        file2.generateRandomNumbers();
    }
}

```
The result：
java.io.PrintStream.println(java.lang.String)
java.util.Random.nextInt(int)
java.util.Random.nextInt(int)
java.io.PrintStream.println(java.lang.String)
Exception in thread "main" UnsolvedSymbolException{context='file1.printHello()', name='file1', cause='UnsolvedSymbolException{context='null', name='File1', cause='null'}'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:176)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:152)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:242)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:140)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at com.ju.process.MethodCallResolve.lambda$main$0(MethodCallResolve.java:41)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at com.ju.process.MethodCallResolve.main(MethodCallResolve.java:40)
Caused by: UnsolvedSymbolException{context='null', name='File1', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:567)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserSymbolDeclaration.getType(JavaParserSymbolDeclaration.java:146)
	at com.github.javaparser.symbolsolver.model.resolution.Value.from(Value.java:40)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
	at java.base/java.util.LinkedList$LLSpliterator.tryAdvance(LinkedList.java:1253)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:150)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:543)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveWithAsValue(AbstractJavaParserContext.java:149)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbolAsValue(StatementContext.java:135)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:147)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:68)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:73)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:277)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:44)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:79)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:448)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:310)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:292)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:167)
	... 8 more

Process finished with exit code 1

**Comment by jlerbsc** [comment]
Hi, your JavaParserTypeSolver must no contain package déclaration

    new JavaParserTypeSolver("src\\main\\java")

**Comment by julian5392** [comment]
Thank you very much. I have solved it successfully. But there is another problem: the test code still works correctly when it contains calls to deprecated methods. However, when solving for this call expression, the solver will fail. Is there a solution to this?

**Comment by jlerbsc** [comment]
We don't have enough information to answer your question. Can you provide us with a simple test case that solves your problem? We don't know the nature of the error or which method call fails.

**Comment by julian5392** [comment]
Sorry, I rechecked and found that the issue is not related to the deprecation method. I don't know how to describe the problem, but here's a reproducible testcase. I analyzed the code using javaparser, but had trouble solving the typesolver part.
```
public class MethodCallResolve {
    public static void main(String[] args) throws Exception {
        TypeSolver myTypeSolver = new CombinedTypeSolver(
                new ReflectionTypeSolver(),
                new JavaParserTypeSolver("src\\main\\java")
        );
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(myTypeSolver);
        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(new File("src\\main\\java\\testcode\\HelloWorld.java"));
        cu.findAll(MethodCallExpr.class).forEach(mce ->
                System.out.println(mce.resolve().getQualifiedSignature()));
    }
}
```
HelloWorld.java
```
public class HelloWorld {
    public static List<String> libraries=new ArrayList<>(Arrays.asList("G:\\maven_repository\\repository\\com\\github\\javaparser\\javaparser-core\\3.25.3\\javaparser-core-3.25.3.jar"));

    public static void main(String[] args) throws IOException {
        CombinedTypeSolver myTypeSolver = new CombinedTypeSolver();
        myTypeSolver.add(new ReflectionTypeSolver());
        myTypeSolver.add(new JavaParserTypeSolver("F:\\unreachabletest\\test_pro\\src\\main\\java"));
        for (String library : libraries) {
            myTypeSolver.add(JarTypeSolver.getJarTypeSolver(library));
        }
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(myTypeSolver);

        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);

    }
}
```
The error report
```
java.util.Arrays.asList(T...)
Exception in thread "main" UnsolvedSymbolException{context='null', name='ReflectionTypeSolver', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:484)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:287)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:44)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.accept(ObjectCreationExpr.java:112)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:448)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:310)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:221)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:240)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:140)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at hello.MethodCallResolve.lambda$main$0(MethodCallResolve.java:26)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at hello.MethodCallResolve.main(MethodCallResolve.java:25)
\\\
```

**Comment by jlerbsc** [comment]
ReflectionTypeSolver is defined in javaparser-core-symbol-solver library.
