### ISSUE TITLE
Text Block Literals are not supported

### ISSUE THREAD

**Issue by Mohamed-Hammada** [javaparser/javaparser#4064]
I am currently using the com.github.javaparser:javaparser-core:3.25.3 library in my Java project. According to the release notes for version 3.25.2, Text Block support should be available. However, when attempting to parse code containing Text Block literals, I encountered the following exception:

```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 11,col 31) Text Block Literals are not supported.
	at com.github.javaparser.JavaParserAdapter.handleResult(JavaParserAdapter.java:83)
	at com.github.javaparser.JavaParserAdapter.parse(JavaParserAdapter.java:99)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:173)
	at com.foo.zain.cvm.ProjectTreePrinter.processJavaFile(ProjectTreePrinter.java:41)
```
-------------------------------------------------------------

-- my javaparser config

```

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.ast.body.EnumDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;

public class ProjectTreePrinter {
    public static boolean skipVariables=true;

    public static void main(String[] args) throws IOException {
        args=new String[]{"path/to/workspace"};
        if (args.length != 1) {
            System.out.println("Usage: java ProjectTreePrinter <projectDir>");
            System.exit(1);
        }

        Path projectDir=Paths.get(args[0]);

        Files.walk(projectDir)
                .filter(Files::isRegularFile)
                .filter(path->
                        !path.toString().contains("\\repositories") &&
                                !path.toString().contains("\\entities") &&
                                !path.toString().contains("\\EmailNotificationService") &&
                                !path.toString().contains("\\DailyReportService") &&
                        path.toString().endsWith(".java")
                                && !path.toString().contains("\\dto") && !path.toString().endsWith("ProjectTreePrinter.java"))
                .forEach(ProjectTreePrinter::processJavaFile);
    }

    private static void processJavaFile(Path javaFilePath) {
        try {
            System.out.println(javaFilePath);
            CompilationUnit cu=StaticJavaParser.parse(javaFilePath);

            System.out.println("Package: " + cu.getPackageDeclaration().map(pd->pd.getName().asString()).orElse("[default package]"));
            new ClassVisitor().visit(cu, null);
            new EnumVisitor().visit(cu, null);
            new InterfaceVisitor().visit(cu, null);
        } catch (IOException e) {
            System.err.println("Error processing file " + javaFilePath);
            e.printStackTrace();
        }
    }

    public static String getMethodType(MethodDeclaration method) {
        if (method.isPublic()) {
            return "public";
        } else if (method.isPrivate()) {
            return "private";
        } else if (method.isProtected()) {
            return "protected";
        } else {
            return "default";
        }
    }

    private static class ClassVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(ClassOrInterfaceDeclaration n, Void arg) {
            super.visit(n, arg);
            String classType=n.isInterface() ? "Interface" : (n.isEnumDeclaration() ? "Enum" : "Class");
            System.out.println("  " + classType + ": " + n.getName());
            if (skipVariables)
                n.getFields().forEach(field->{
                    System.out.println("    Class Variable: " + field.getElementType() + " " + field.getVariable(0).getName());
                });
            n.getMethods().forEach(method->{
                String methodType=getMethodType(method);
                System.out.println("    Class Method: " + methodType + " " + method.getName());
            });
        }
    }

    private static class EnumVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(EnumDeclaration n, Void arg) {
            super.visit(n, arg);
            System.out.println("  Enum: " + n.getName());
        }
    }

    private static class InterfaceVisitor extends VoidVisitorAdapter<Void> {
        @Override
        public void visit(ClassOrInterfaceDeclaration n, Void arg) {
            super.visit(n, arg);
            if (n.isInterface()) {
                System.out.println("  Interface: " + n.getName());
                if (skipVariables)
                    n.getFields().forEach(field->{
                        System.out.println("    Interface Variable: " + field.getElementType() + " " + field.getVariable(0).getName());
                    });
                n.getMethods().forEach(method->{
                    String methodType=getMethodType(method);
                    System.out.println("    Interface Method: " + methodType + " " + method.getName());
                });

            }
        }
    }
}

```

- Sample Not working 

```

import java.io.IOException;

import com.slack.api.Slack;

public class TestSlackSender {

    public static void main(String[] args) throws IOException {

            String   content ="""
                           {
                              "username": "Webhook",
                              "icon_url": "https://i.imgur.com/4M34hi2.png",
                              "text": "Text message. Up to 2000 characters.",
                              "attachments": [
                                {
                                  "author_name": "Birdie♫",
                                  "author_link": "https://www.reddit.com/r/cats/",
                                  "author_icon": "https://i.imgur.com/R66g1Pe.jpg",
                                  "title": "Title",
                                  "title_link": "https://google.com/",
                                  "text": "Text message. You can use Markdown here. *Italic* **bold** __underline__ ~~strikeout~~ [hyperlink](https://google.com) `code`",
                                  "color": "#e8d44f",
                                  "fields": [
                                    {
                                      "title": "Text",
                                      "value": "More text",
                                      "short": true
                                    },
                                    {
                                      "title": "Even more text",
                                      "value": "Yup",
                                      "short": true
                                    },
                                    {
                                      "title": "Use `\\"inline\\": true` parameter, if you want to display fields in the same line.",
                                      "value": "okay..."
                                    },
                                    {
                                      "title": "Thanks!",
                                      "value": "You're welcome :wink:"
                                    }
                                  ],
                                  "thumb_url": "https://upload.wikimedia.org/wikipedia/commons/3/38/4-Nature-Wallpapers-2014-1_ukaavUI.jpg",
                                  "image_url": "https://upload.wikimedia.org/wikipedia/commons/5/5a/A_picture_from_China_every_day_108.jpg",
                                  "footer": "Woah! So cool! :smirk:",
                                  "footer_icon": "https://i.imgur.com/fKL31aD.jpg"
                                }
                              ]
                            }
                            
                    """;


            Slack slack=Slack.getInstance();

            slack.send("https://hooks.slack.com/services/", content);

    }
}
```

and this is my gradle dependency 

`implementation 'com.github.javaparser:javaparser-core:3.25.3'`

**Comment by jlerbsc** [comment]
It's probably a bad parser configuration But without more information I can't be more precise. Ideally, you should send us a simple test case that reproduces your problem.

**Comment by Mohamed-Hammada** [comment]
@jlerbsc Please review the latest updates and feel free to ask for any additional details you may need.

**Comment by jlerbsc** [comment]
Your issue seems to be related to the parser configuration because text blocks were introduced in java 15. In your case you have to add.

    StaticJavaParser.getParserConfiguration().setLanguageLevel(LanguageLevel.JAVA_15);

**Comment by Mohamed-Hammada** [comment]
@jlerbsc Thanks for your response, and yes you are correct however, I have a suggestion to improve the error message when encountering Text Block literals in the JavaParser library. Currently, it would be helpful to include a comment in the error message with the solution:

``` 
Exception: Text Block Literals are not supported. To enable Text Block support, add this line before parsing the Java file: StaticJavaParser.getParserConfiguration().setLanguageLevel(LanguageLevel.JAVA_15);
```

This comment provides clear guidance on configuring the JavaParser library to use Java 15 language level and would assist developers facing this issue.

Thank you for considering this suggestion.

**Comment by jlerbsc** [comment]
I am closing this issue and opening a new one to take your recommendation into account https://github.com/javaparser/javaparser/issues/4075
