### ISSUE TITLE
Unsolved symbol : xxx  UnsolvedSymbolException ?

### ISSUE THREAD

**Issue by jayrrrrr** [javaparser/javaparser#4080]
hi，
I am facing an issue.
my code Example.java
```
public class Example {

    public void param( Gson gson) {
        //do nothing;
    }
}
```

my test code :
```
class ExampleTest {
    @Test
    public void test() throws FileNotFoundException {
        CombinedTypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver());
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(new File("./src/main/java/com/sample/type/Example.java"));
        List<MethodDeclaration> all = cu.findAll(MethodDeclaration.class);

        for (MethodDeclaration methodDeclaration : all) {
            NodeList<Parameter> parameters = methodDeclaration.getParameters();
            for (Parameter parameter : parameters) {
                ResolvedType resolve = parameter.getType().resolve();
                System.out.println(resolve.arrayLevel());
            }
        }
    }
}
```
Error stack
```
Unsolved symbol : Gson
UnsolvedSymbolException{context='null', name='Gson', cause='null'}
	at com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:609)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:620)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:284)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:325)
	at com.sample.type.ExampleTest.test(ExampleTest.java:31)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```
I suspect it's because Gson is a third-party jar file, and it hasn't been initialized yet, so it can't infer the context. However, I don't know how to resolve this problem.

**Comment by jlerbsc** [comment]
You must initialize the CombinedTypeSolver with a JarTypeSolver that references the Gson is a third-party.

**Comment by jayrrrrr** [comment]
JarTypeSolver is indeed feasible, but are there any other solutions available?

**Comment by jlerbsc** [comment]
No, it's the only solution to resolve classes declared in a library. Have you taken the time to read the documentation available on Javaparser?

**Comment by singhstronaut** [comment]
Here's the working code to resolve `UnsolvedSymbolException` with javaparser v3.27.1 :

```
// false in constructor will solve UnsolvedSymbolException exception for jdk classes.
// because by default true only includes jre classes and not all classes.
TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);

CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(reflectionTypeSolver);

// jarsPath will have all jars 'fully qualified names' to resolve UnsolvedSymbolException for the classes reported.
for (String jarPath : jarsPath) {
	combinedTypeSolver.add(new JarTypeSolver(jarPath));
}

JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
```
