### ISSUE TITLE
UnsolvedSymbolException for the methods in javax.servlet

### ISSUE THREAD

**Issue by julian5392** [javaparser/javaparser#4105]
One explanation I've found is:“The javax.servlet.http.HttpServletRequest class is part of the Java Servlet API, which is provided by servlet containers such as Apache Tomcat or Jetty. It is not included in the standard Java libraries.”
So I had to try to join“myTypeSolver.add(JarTypeSolver.getJarTypeSolver("G:\\maven_repository\\repository\\Maven_Repository\\javax\\servlet\\servlet-api\\2.5\\servlet-api-2.5.jar"));” But it still dosent work.
 The error report:
```
 Exception in thread "main" UnsolvedSymbolException{context='null', name='HttpServletResponse', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:509)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:567)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:563)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:78)
	at com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:61)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:71)
	at com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:82)
	at testcode.Main.main(Main.java:48)
```

```
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;

import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;

import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.io.IOException;
import java.util.List;

public class Main {
    public static void main(String[] args) throws IOException {

        String sourcecode = "\n" +
                "import javax.servlet.http.HttpServletRequest;\n" +
                "\n" +
                "public class ExampleServlet extends HttpServlet {\n" +
                "\n" +
                "    protected void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {\n" +
                "        StringBuffer url = request.getRequestURL();\n" +
                "\n" +
                "        System.out.println(\"Request URL: \" + url);\n" +
                "    }\n" +
                "}\n";
        CombinedTypeSolver myTypeSolver = new CombinedTypeSolver();
        myTypeSolver.add(new ReflectionTypeSolver(false));
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(myTypeSolver);

        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(sourcecode);
        List<MethodDeclaration> methods = cu.findAll(MethodDeclaration.class);
        for (MethodDeclaration method : methods) {
            String fullCallerMethodName = method.resolve().getQualifiedSignature();

            System.out.println(fullCallerMethodName);
            List<MethodCallExpr> methodCallees = method.findAll(MethodCallExpr.class);
            for (MethodCallExpr callee : methodCallees) {

                String calleeMethodName = callee.resolve().getQualifiedSignature();
                System.out.println(calleeMethodName);
                System.out.println("\"" + fullCallerMethodName + "\"" + " -> " + "\"" + calleeMethodName + "\"");
            }
        }
    }
}

```

**Comment by jlerbsc** [comment]
I don't see this declaration in your code


    myTypeSolver.add(JarTypeSolver.getJarTypeSolver...
