### ISSUE TITLE
Bug: An error occurred while solving the AnnotationMemberDeclaration

### ISSUE THREAD

**Issue by julian5392** [javaparser/javaparser#4108]
Javaparser treats AnnotationMemberDeclaration as MethodDeclaration, and an error occurs.

The error report:
Exception in thread "main" java.lang.UnsupportedOperationException: com.github.javaparser.symbolsolver.reflectionmodel.ReflectionAnnotationDeclaration
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.solveMethodInType(MethodResolutionLogic.java:619)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:154)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:242)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:125)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:140)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at javaparsetest.Main.getMethodInvocation(Main.java:125)
	at javaparsetest.Main.main(Main.java:48)

The Main.java and HasRoles.java are the code to be analyzed. And here is the reproduced testcase.
```
package javaparsetest;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ConstructorDeclaration;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JarTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Main {
    public static void main(String[] args) throws IOException {
        CombinedTypeSolver myTypeSolver = new CombinedTypeSolver();
        myTypeSolver.add(new ReflectionTypeSolver(false));
        myTypeSolver.add(new JavaParserTypeSolver("F:\\unreachabletest\\testjava\\src\\main\\java"));
        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(myTypeSolver);

        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
        File sourcePath = new File("F:\\unreachabletest\\testjava\\src\\main\\java");
        List<File> filelist = getAllJavaFiles(sourcePath);
        List<String> constructorsDeclarations = new ArrayList<>();
        for (File f : filelist) {
            try {
                List<String> constructor = getConstructorDeclaration(f);
                System.out.println(constructor);
            } catch (IOException e) {
                // Handle the exception here
            }
        }
        for (File f : filelist) {
            try {
                List<String> methodInvocations = getMethodInvocation(f, constructorsDeclarations);
                System.out.println(methodInvocations);

            } catch (IOException e) {
                // Handle the exception here
            }
        }
    }
    public static List<File> getAllJavaFiles(File path) {
        List<File> fileList = new ArrayList<>();
        if (path.exists()) {
            File[] files = path.listFiles();
            if (files != null) {
                for (File f : files) {

                    if (f.isDirectory()) {
                        File subfile = new File(f.getAbsolutePath());
                        fileList.addAll(getAllJavaFiles(subfile));
                    } else if (f.isFile() && f.getName().endsWith(".java")) {
                        fileList.add(f);
                    }
                    }
            }
        }
        return fileList;
    }
    public static List<String> getConstructorDeclaration(File file) throws IOException {
        List<String> constructorNames = new ArrayList<>();

        CompilationUnit cu = StaticJavaParser.parse(file);
        List<ConstructorDeclaration> constructors = cu.findAll(ConstructorDeclaration.class);
        for (ConstructorDeclaration constructor : constructors) {
            String constructorName = constructor.resolve().getQualifiedSignature();
            constructorNames.add("\""+constructorName+"\"");

        }
        return constructorNames;
    }
    public static List<String> getMethodInvocation(File file,List<String> constructorDeclarations ) throws IOException {
        CompilationUnit cu = StaticJavaParser.parse(file);
        List<String> methodInvocations = new ArrayList<>();

        List<ConstructorDeclaration> constructors = cu.findAll(ConstructorDeclaration.class);
        for (ConstructorDeclaration constructor : constructors) {
            String fullCallerMethodName = constructor.resolve().getQualifiedSignature();
            methodInvocations.add("\""+fullCallerMethodName+"\"");
            System.out.println(fullCallerMethodName);

            List<MethodDeclaration> methodDecls = constructor.findAll(MethodDeclaration.class);
            for (MethodDeclaration methodDecl : methodDecls) {
                String methodDeclName = methodDecl.resolve().getQualifiedSignature();
                methodInvocations.add("\"" + fullCallerMethodName + "\"" + " -> " + "\"" + methodDeclName + "\"");
            }

            List<MethodCallExpr> methodCallees = constructor.findAll(MethodCallExpr.class);
            for (MethodCallExpr callee : methodCallees) {
                String calleeMethodName = callee.resolve().getQualifiedSignature();
                if (!calleeMethodName.startsWith("java.") && !calleeMethodName.startsWith("javax.")) {
                    methodInvocations.add("\"" + fullCallerMethodName + "\"" + " -> " + "\"" + calleeMethodName + "\"");
                }
            }
            List<ObjectCreationExpr> objectCallees = constructor.findAll(ObjectCreationExpr.class);
            for (ObjectCreationExpr callee : objectCallees) {
                String calleeMethodName = callee.resolve().getQualifiedSignature();
                if (constructorDeclarations.contains("\"" + calleeMethodName + "\"")){
                    methodInvocations.add("\"" + fullCallerMethodName + "\"" + " -> " + "\"" + calleeMethodName + "\"");
                }
            }
        }

        List<MethodDeclaration> methods = cu.findAll(MethodDeclaration.class);
        for (MethodDeclaration method : methods) {
            String fullCallerMethodName = method.resolve().getQualifiedSignature();
            methodInvocations.add("\""+fullCallerMethodName+"\"");
            System.out.println(fullCallerMethodName);
            List<MethodCallExpr> methodCallees = method.findAll(MethodCallExpr.class);
            for (MethodCallExpr callee : methodCallees) {
                String calleeMethodName = callee.resolve().getQualifiedSignature();
                if (!calleeMethodName.startsWith("java.") && !calleeMethodName.startsWith("javax.")) {
                    methodInvocations.add("\"" + fullCallerMethodName + "\"" + " -> " + "\"" + calleeMethodName + "\"");
                }
            }
            List<ObjectCreationExpr> objectCallees = method.findAll(ObjectCreationExpr.class);
            for (ObjectCreationExpr callee : objectCallees) {
                String calleeMethodName = callee.resolve().getQualifiedSignature();
                if (constructorDeclarations.contains("\"" + calleeMethodName + "\"")){
                    methodInvocations.add("\"" + fullCallerMethodName + "\"" + " -> " + "\"" + calleeMethodName + "\"");
                }
            }
        }
        return methodInvocations;
    }
}
```

Main.java
```
package hello;

public class Main {
    public static void main(String[] args) {
        HasRoles hasRoles = null;
        if (hasRoles != null) {
            if (hasRoles.skipCheck()) {
            }
        }
    }
}
```
HasRoles.java

```
package hello;
import java.lang.annotation.*;

@Target(value = {ElementType.TYPE, ElementType.METHOD})
@Retention(RetentionPolicy.RUNTIME)
@Documented
public @interface HasRoles {
    boolean skipCheck() default false;
}

```

**Comment by jlerbsc** [comment]
What version of JP are you using?

**Comment by julian5392** [comment]
3.25.4

**Comment by jlerbsc** [comment]
If HasRoles is an annotation why did you declare this. Even if this statement does not generate a compilation error it seems to me that it is not semantically correct.

    HasRoles hasRoles = null;

If you declare your interface as you should, there is no issue.

    public interface HasRoles {
	    boolean skipCheck();
	}

**Comment by julian5392** [comment]
However, in practice, there may be such expressions.Here's another example. When annotation classes are involved, an error is reported.
Main.java
```
package hello;
import java.lang.reflect.Field;
import java.util.HashMap;
import java.util.Map;

public class Request {
    private Class clazz;

    private Map<String, Field> fieldMap = new HashMap<>();
    private void fieldMapInit() {
        Field[] fields = clazz.getDeclaredFields();
        for (Field field : fields) {
            if (field.isAnnotationPresent(DbFiled.class)) {
                fieldMap.put(field.getAnnotation(DbFiled.class).value(), field);
            } else {
                fieldMap.put(field.getName(), field);
            }
        }
    }
}
```
DbFiled.java
```
package hello;
import java.lang.annotation.*;
public @interface DbFiled {
    String value();
}
```

**Comment by jlerbsc** [comment]
This is a marginal use case for annotations. In your examples you declare variables having a type that extends the Annotation class. I couldn't find anything in the JLS indicating that one can use the annotations like you do. Although I consider this to be a programming error, IDEs support this syntax so I have no objection to JP supporting this behavior as well. That's why I'm tagging your comment as a bug.
