### ISSUE TITLE
UnsolvedSymbolException for the classes in java.sql

### ISSUE THREAD

**Issue by mateju25** [javaparser/javaparser#4112]
Hi, I am trying to resolve types for some source code I found on the internet (stuff for school) and I keep getting UnsolvedSymbolException for class that is present in java.sql package. Code that occurs for example in java.lang or java.util works just fine and is correctly found by parser.

Exception:
```
Caused by: UnsolvedSymbolException{context='null', name='SQLException', cause='null'}
	at com.github.javaparser.core@3.25.4/com.github.javaparser.ast.type.ClassOrInterfaceType.convertToUsage(ClassOrInterfaceType.java:347)
	at com.github.javaparser.symbolsolver.core@3.25.4/com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:607)
	at com.github.javaparser.symbolsolver.core@3.25.4/com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:639)
	at com.github.javaparser.symbolsolver.core@3.25.4/com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:635)
	at com.github.javaparser.symbolsolver.core@3.25.4/com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:69)
	at com.github.javaparser.core@3.25.4/com.github.javaparser.resolution.declarations.ResolvedParameterDeclaration.describeType(ResolvedParameterDeclaration.java:60)
	at com.github.javaparser.core@3.25.4/com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getSignature(ResolvedMethodLikeDeclaration.java:70)
	at com.github.javaparser.core@3.25.4/com.github.javaparser.resolution.declarations.ResolvedMethodLikeDeclaration.getQualifiedSignature(ResolvedMethodLikeDeclaration.java:81)


````
Way i add solvers to parser:
```
        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        combinedSolver.add(new ReflectionTypeSolver());
        combinedSolver.add(new JavaParserTypeSolver(new File(CONCRETE_TEST)));
        jarFiles.forEach(jarFile -> {
            try {
                combinedSolver.add(new JarTypeSolver(jarFile));
            } catch (IOException e) {
                e.printStackTrace();
            }
        });


        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        StaticJavaParser
                .getParserConfiguration()
                .setSymbolResolver(symbolSolver);

        for (File javaFile : javaFiles) {
            CompilationUnit cu = StaticJavaParser.parse(javaFile);

```

Problematic source code that cannot be parsed:
```
package net.javaguides.todoapp.dao;

import java.sql.SQLException;
import java.util.List;

import net.javaguides.todoapp.model.Todo;

public interface TodoDao {

	void insertTodo(Todo todo) throws SQLException;

	Todo selectTodo(long todoId);

	List<Todo> selectAllTodos();

	boolean deleteTodo(int id) throws SQLException;

	boolean updateTodo(Todo todo) throws SQLException;

}
```

Thx for your help!

**Comment by mateju25** [comment]
My bad!

In order to locate java.sql by ReflectionTypeSolver, i needed to add requires java.sql to module-info.

```
module main {
    requires java.sql;    

    opens main to javafx.fxml;
    exports main;
    exports main.core;
}
```
