### ISSUE TITLE
Top-level class containerType() throws an exception instead of Optional.empty()

### ISSUE THREAD

**Issue by ark100** [javaparser/javaparser#4133]
ResolvedReferenceTypeDeclaration#containerType() in the case of the top-level class throws an exception, but I think it is appropriate to return Optional.empty().
I can catch the exception and work around the problem.

[Version]
```
dependencies {
    implementation 'com.github.javaparser:javaparser-symbol-solver-core:3.25.4'
}

JDK: amazon-corretto-11.0.18.10
```

[Error sample]
```java
package sample;

import com.github.javaparser.JavaParser;
import com.github.javaparser.JavaParserAdapter;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.ClassOrInterfaceDeclaration;
import com.github.javaparser.resolution.declarations.ResolvedReferenceTypeDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.util.Optional;

public class ErrorSample2 {
    public static void main(String[] args) {
        JavaParser p = new JavaParser(
            new ParserConfiguration().setSymbolResolver(
                new JavaSymbolSolver(
                    new CombinedTypeSolver(
                        new ReflectionTypeSolver()
                    )
                )
            )
        );
        
        String code =
            "public class Foo {\n"
            + "    public static class Bar {\n"
            + "        public static class Baz {\n"
            + "        }\n"
            + "    }\n"
            + "}\n";
        
        CompilationUnit cu = JavaParserAdapter.of(p).parse(code);
    
        for(ClassOrInterfaceDeclaration d : cu.findAll(ClassOrInterfaceDeclaration.class)){
            ResolvedReferenceTypeDeclaration rd = d.resolve();
            try{
                Optional<ResolvedReferenceTypeDeclaration> outer = rd.containerType();
                if(outer.isPresent()){
                    System.out.println("(Inner) "+rd.getQualifiedName()+" (Outer) "+outer.get().getQualifiedName());
                }
                else {
                    System.out.println("(TopLevel) "+rd.getQualifiedName());
                }
            }
            catch(RuntimeException e){
                System.out.println("(Exception) "+rd.getQualifiedName());
                e.printStackTrace(System.out);
                System.out.println();
            }
        }
    }
}
```

[Output]
```
(Exception) Foo
java.lang.IllegalArgumentException: Cannot get a reference type declaration from com.github.javaparser.ast.CompilationUnit
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toTypeDeclaration(JavaSymbolSolver.java:317)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeAdapter.lambda$containerType$0(JavaParserTypeAdapter.java:160)
	at java.base/java.util.Optional.map(Optional.java:265)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserTypeAdapter.containerType(JavaParserTypeAdapter.java:160)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.containerType(JavaParserClassDeclaration.java:455)
	at sample.ErrorSample2.main(ErrorSample2.java:40)

(Inner) Foo.Bar (Outer) Foo
(Inner) Foo.Bar.Baz (Outer) Foo.Bar
```

**Comment by ark100** [comment]
Sorry, there was already an issue. #2427

**Comment by jlerbsc** [comment]
Since we are trying to get the type declaration from a CompilationUnit I consider this to be a bug.
