### ISSUE TITLE
UnsolvedSymbolException for certain library

### ISSUE THREAD

**Issue by dexieBirb** [javaparser/javaparser#4175]
Hi,

I'm trying to get the qualified name of the corresponding declaration for a method call expression. I'm using ReflectionTypeSolver() which should resolve classes from the JRE that is currently running (I'm using JavaSE-17). However, it's unable to solve the JShell library :(

When I use ReflectionTypeSolver(false), it is working but is it still checking on the current JRE?

I hope someone can help me here. Thanks!

Here's my code:
`	
	public static void main(String[] args) {
	
	    CompilationUnit cu = StaticJavaParser.parse("public class X {\n" +
	            "        public void test() {\n" +
	            "            try {\n" +
	            "				 List<String> disList = new java.util.ArrayList<>();\n" +
	            "                methodWithExceptions();\n" +
	            "				 jdk.jshell.JShell.create();\n" +
	            "            } catch (ArrayIndexOutOfBoundsException | ClassCastException e) {\n" +
	            "                System.out.println(e);\n" +
	            "                System.out.println(e.getMessage());\n" +
	            "            }\n" +
	            "        }\n" +
	            "\n" +
	            "        private void methodWithExceptions() throws ArrayIndexOutOfBoundsException, ClassCastException {\n" +
	            "            // do something\n" +
	            "        }\n" +
	            "    }");
	    cu.accept(new Visitor(), null);
	}

	private static class Visitor extends VoidVisitorAdapter<Void> {
	    @Override
	    public void visit(MethodCallExpr n, Void arg) {
	        System.out.println("n.toString() = " + n.toString());
	            
			ResolvedMethodDeclaration methodDeclaration = JavaParserFacade.get(new ReflectionTypeSolver()).solve(n)
					.getCorrespondingDeclaration();
			String parentClass = methodDeclaration.declaringType().getQualifiedName();
			System.out.println("***" + parentClass);
	    }
	}
`

This is the output and encountered exception.

`**n.toString() = System.out.println(e)
***java.io.PrintStream
n.toString() = System.out.println(e.getMessage())
***java.io.PrintStream
n.toString() = methodWithExceptions()
***X
n.toString() = jdk.jshell.JShell.create()**
Exception in thread "main" UnsolvedSymbolException{context='jdk.jshell.JShell.create()', name='jdk.jshell.JShell', cause='UnsolvedSymbolException{context='null', name='JShell', cause='null'}'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:209)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:150)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134)
	at TestParser$Visitor.visit(TestParser.java:76)
	at TestParser$Visitor.visit(TestParser.java:1)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:124)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:260)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:79)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$19(VoidVisitorAdapter.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:109)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:535)
	at com.github.javaparser.ast.stmt.TryStmt.accept(TryStmt.java:143)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$19(VoidVisitorAdapter.java:109)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:109)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:78)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$106(VoidVisitorAdapter.java:371)
	at java.base/java.util.Optional.ifPresent(Optional.java:178)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:371)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:106)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$32(VoidVisitorAdapter.java:155)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:155)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:103)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$44(VoidVisitorAdapter.java:176)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:176)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:132)
	at TestParser.main(TestParser.java:56)
Caused by: UnsolvedSymbolException{context='null', name='JShell', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:275)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.FieldAccessExpr.accept(FieldAccessExpr.java:92)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:331)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:200)
	... 35 more
`

**Comment by jlerbsc** [comment]
> it is working but is it still checking on the current JRE?

Hi @dexieBirb ,

Yes the ReflectionTypeSolder uses the ClassLoader of the running JVM to load classes.

ReflectionTypeSolver accepts a parameter that specifies whether we only want to resolve classes from the java and javax packages. By default this parameter is true so the ReflectionTypeSolver does not resolve classes located for example in the jdk package.

**Comment by dexieBirb** [comment]
Great. Thank you so much!

**Comment by jlerbsc** [comment]
You are welcome. If you no longer have any questions on this topic you can close the issue :-)
