### ISSUE TITLE
UnsolvedSymbolException resolving MethodCallExpr using generics

### ISSUE THREAD

**Issue by fabgo** [javaparser/javaparser#4185]
MethodCallExpr.resolve() throws UnsolvedSymbolException for a method call  to a method that uses generics.

**Comment by fabgo** [comment]
Exception:

```
Exception in thread "main" UnsolvedSymbolException{context='Stream.of(base, additions).filter(Objects::nonNull).flatMap(Collection::stream).collect(Collectors.toList())', name='Stream.of(base, additions).filter(Objects::nonNull).flatMap(Collection::stream)', cause='UnsolvedSymbolException{context='Stream.of(base, additions).filter(Objects::nonNull).flatMap(Collection::stream)', name='Stream.of(base, additions).filter(Objects::nonNull)', cause='java.lang.RuntimeException: Method 'filter' cannot be resolved in context Stream.of(base, additions).filter(Objects::nonNull) (line: 13) MethodCallExprContext{wrapped=Stream.of(base, additions).filter(Objects::nonNull)}. Parameter types: [ReferenceType{java.util.function.Predicate, typeParametersMap=TypeParametersMap{nameToValue={java.util.function.Predicate.T=WildcardUsage{type=SUPER, boundedType=ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=TypeVariable {JPTypeParameter(T, bounds=[])}}}}}}}}}}}]'}'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:204)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:150)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:164)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:319)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.flashresolve.parsertester.SymbolResolverTest.main(SymbolResolverTest.java:22)
Caused by: UnsolvedSymbolException{context='Stream.of(base, additions).filter(Objects::nonNull).flatMap(Collection::stream)', name='Stream.of(base, additions).filter(Objects::nonNull)', cause='java.lang.RuntimeException: Method 'filter' cannot be resolved in context Stream.of(base, additions).filter(Objects::nonNull) (line: 13) MethodCallExprContext{wrapped=Stream.of(base, additions).filter(Objects::nonNull)}. Parameter types: [ReferenceType{java.util.function.Predicate, typeParametersMap=TypeParametersMap{nameToValue={java.util.function.Predicate.T=WildcardUsage{type=SUPER, boundedType=ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=TypeVariable {JPTypeParameter(T, bounds=[])}}}}}}}}}}}]'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:204)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:150)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:595)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:379)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:648)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:325)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:331)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:195)
	... 7 more
Caused by: java.lang.RuntimeException: Method 'filter' cannot be resolved in context Stream.of(base, additions).filter(Objects::nonNull) (line: 13) MethodCallExprContext{wrapped=Stream.of(base, additions).filter(Objects::nonNull)}. Parameter types: [ReferenceType{java.util.function.Predicate, typeParametersMap=TypeParametersMap{nameToValue={java.util.function.Predicate.T=WildcardUsage{type=SUPER, boundedType=ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=ReferenceType{java.util.List, typeParametersMap=TypeParametersMap{nameToValue={java.util.List.E=TypeVariable {JPTypeParameter(T, bounds=[])}}}}}}}}}}}]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:659)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:325)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:331)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:195)
	... 22 more
```

**Comment by fabgo** [comment]
Test case:


```
public class SymbolResolverTest {
    public static void main(String[] args) throws FileNotFoundException {
        ParserConfiguration config = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()))
                .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(new FileInputStream("SampleCode.java"));
        cu.findAll(MethodCallExpr.class).forEach(MethodCallExpr::resolve);
    }
}
```

**Comment by fabgo** [comment]
Sample code which fails to resolve:

```
public class SampleCode {
    // The method calls in this method fail to resolve
    public static <T> List<T> concatLists(final List<T> base, final List<T> additions) {
        return Stream
                .of(base, additions)
                .filter(Objects::nonNull)
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
    }


    // The method calls in this method resolve fine
    public static List<String> concatStrings(final List<String> base, final List<String> additions) {
        return Stream
                .of(base, additions)
                .filter(Objects::nonNull)
                .flatMap(Collection::stream)
                .collect(Collectors.toList());
    }
}
```

**Comment by jlerbsc** [comment]
Thank you for declaring this bug.

**Comment by ethan-godden** [comment]
@jlerbsc I believe this is a duplicate of #4936 (or the other way around since this came first)

**Comment by jlerbsc** [comment]
You’re right, so I’m closing this issue. The issue cannot be reproduced with the current development version.
