### ISSUE TITLE
UnsolvedSymbolException resolving MethodCallExpr using MethodReferenceExpr

### ISSUE THREAD

**Issue by fabgo** [javaparser/javaparser#4188]
I am getting an UnsolvedSymbolException when I attempt to resolve a method call that has a method reference:

```
Exception in thread "main" UnsolvedSymbolException{context='priority.map(bar::convert).orElse("0")', name='priority.map(bar::convert)', cause='java.lang.UnsupportedOperationException'}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:209)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethod(MethodCallExprContext.java:150)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:273)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:164)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:319)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.flashresolve.parsertester.SymbolResolverTest.main(SymbolResolverTest.java:28)
Caused by: java.lang.UnsupportedOperationException
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.toMethodUsage(JavaParserFacade.java:443)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:627)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.accept(MethodReferenceExpr.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:331)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.findTypeDeclarations(AbstractJavaParserContext.java:200)
	... 7 more
```

**Comment by fabgo** [comment]
Sample code which does not resolve:

```
public class MethodInvocation {
    Map<String, String> testMap = new ConcurrentHashMap<>();

    // Resolves successfully
    public void staticMethodInvocation(Foo foo) {
        Optional<Integer> priority = Optional.of(4);
        priority.map(Foo::staticConvert).orElse("0");
    }

    // Does not resolve
    public void instanceMethodInvocation(Foo foo) {
        Optional<Integer> priority = Optional.of(4);
        priority.map(foo::convert).orElse("0");
    }

    // Does not resolve
    public void defaultMethodInvocation(Bar bar) {
        Optional<Integer> priority = Optional.of(4);
        priority.map(bar::convert).orElse("0");
    }

    public class Foo {
        public String convert(int priority) {
            return Integer.toString(priority);
        }

        public static String staticConvert(int priority) {
            return Integer.toString(priority);
        }
    }

    public interface Bar {
        default String convert(int priority) {
            return Integer.toString(priority);
        }
    }
}
```

**Comment by fabgo** [comment]
Class used for testing:

```
public class SymbolResolverTest {
    public static void main(String[] args) throws FileNotFoundException {
        CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
        combinedTypeSolver.add(new ReflectionTypeSolver());
        combinedTypeSolver.add(new JavaParserTypeSolver(Path.of(".")));

        ParserConfiguration config = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver))
                .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_17);
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(new FileInputStream("MethodInvocation.java"));
        cu.findAll(MethodCallExpr.class).forEach(MethodCallExpr::resolve);
    }
}
```

**Comment by fabgo** [comment]
It looks like this line in toMethodUsage() is the problem:

```
instanceMethodParamTypes.remove(0); // remove the first one
```

I removed it, and it now works, and all tests pass.

But I assume this line was added for a reason?

Context:

```
// instance methods are called on the first param and should match all other params
List<MethodUsage> instanceMethodUsages = allMethods.stream()
        .filter(it -> !it.getDeclaration().isStatic())
        .collect(Collectors.toList());

List<ResolvedType> instanceMethodParamTypes = new ArrayList<>(paramTypes);
instanceMethodParamTypes.remove(0); // remove the first one
```

**Comment by jlerbsc** [comment]
I don't think the solution is as trivial as you suggest. Indeed, in a first approach, the implementation proposed in JP that you point to, seems to correspond to an incomplete implementation of this specification "In the second search, if P1, ..., Pn is not empty and P1 is a subtype of ReferenceType, then the method reference expression is treated as if it were a method invocation expression with argument expressions of types P2, ..., Pn. If ReferenceType is a raw type, and there exists a parameterization of this type, G<...>, that is a supertype of P1, the type to search is the result of capture conversion (§5.1.10) applied to G<...>; otherwise, the type to search is the same as the type of the first search. Again, the type arguments, if any, are given by the method reference expression."
https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html#jls-15.13

**Comment by singhstronaut** [comment]
Here's the working code to resolve `UnsolvedSymbolException` with javaparser v3.27.1 :

```
// false in constructor will solve UnsolvedSymbolException exception for jdk classes.
// because by default true only includes jre classes and not all classes.
TypeSolver reflectionTypeSolver = new ReflectionTypeSolver(false);

CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
combinedTypeSolver.add(reflectionTypeSolver);

// jarsPath will have all jars 'fully qualified names' to resolve UnsolvedSymbolException for the classes reported.
for (String jarPath : jarsPath) {
	combinedTypeSolver.add(new JarTypeSolver(jarPath));
}

JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedTypeSolver);
StaticJavaParser.getParserConfiguration().setSymbolResolver(symbolSolver);
```
