### ISSUE TITLE
Consultation on problems encountered when using GraalVM to perform AOT

### ISSUE THREAD

**Issue by cyw3** [javaparser/javaparser#4189]
## Questions
- Why does this problem occur?
- how to solve this problem?

## Reproduction steps:

1. Set up graalvm
- download [graalvm](https://github.com/graalvm/graalvm-ce-builds/releases/)
- set up JAVA_HOME and PATH

2. download [demo project - javaparser-gradle-sample ](https://github.com/javaparser/javaparser-gradle-sample).

3. Modify the java file `javaparser-gradle-sample/src/main/resources/Blabla.java`:
```java
package com.sec.servlet;

import java.io.IOException;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import java.sql.Connection;
import java.sql.DriverManager;
// import java.sql.PreparedStatement;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 * Servlet implementation class InfoServlet
 */
public class InfoServlet extends HttpServlet {
	private static final long serialVersionUID = 1L;
       
    /**
     * @see HttpServlet#HttpServlet()
     */
	@Override
	protected void service(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
		// TODO Auto-generated method stub
		
		req.setCharacterEncoding("utf-8");
		resp.setContentType("text/html;charset=utf-8");
		
		UserInfoFound(req,resp);  
	}

	private void UserInfoFound(HttpServletRequest req, HttpServletResponse resp){
		 // TODO Auto-generated method stub
         String message = req.getParameter("msg");

         try {
             resp.getWriter().println(message);
 
         } catch (IOException e) {
             // TODO Auto-generated catch block
             e.printStackTrace();
         }
	}

}
```
4. AOT
```bash
./gradlew shadowJar

java -agentlib:native-image-agent=config-merge-dir=src/main/resources/META-INF/native-image,experimental-class-define-support -jar build/libs/javaparser-gradle-sample-shadow-1.0-SNAPSHOT-beta.jar

native-image -jar build/libs/javaparser-gradle-sample-shadow-1.0-SNAPSHOT-beta.jar -H:Name=javaparser -R:-RemoveNeverExecutedCode -H:-RemoveNeverExecutedCode -H:+AllowIncompleteClasspath

```

5. run the binary file and get the error:
```bash
$ ./javaparser
New source root at "/data/test"
Parsing /data/test/Blabla.java
Exception in thread "main" java.lang.NoSuchFieldError: variables
        at com.github.javaparser.metamodel.PropertyMetaModel.getValue(PropertyMetaModel.java:252)
        at com.github.javaparser.ast.validator.language_level_validations.chunks.CommonValidators.lambda$new$7(CommonValidators.java:78)
        at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:38)
        at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
        at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
        at com.github.javaparser.ast.validator.Validators.lambda$accept$0(Validators.java:64)
        at java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.ast.validator.Validators.accept(Validators.java:64)
        at com.github.javaparser.ast.validator.Validators.lambda$accept$0(Validators.java:64)
        at java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.ast.validator.Validators.accept(Validators.java:64)
        at com.github.javaparser.ParserConfiguration.lambda$new$4(ParserConfiguration.java:313)
        at com.github.javaparser.JavaParser.lambda$parse$0(JavaParser.java:127)
        at java.util.ArrayList.forEach(ArrayList.java:1541)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:127)
        at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:130)
        at com.github.javaparser.utils.SourceRoot.tryToParse(SourceRoot.java:145)
        at com.github.javaparser.utils.SourceRoot.parse(SourceRoot.java:261)
        at com.yourorganization.maven_sample.LogicPositivizer.main(LogicPositivizer.java:31)
```

while the jar file and works:
```bash
$ java -jar build/libs/javaparser-gradle-sample-shadow-1.0-SNAPSHOT-beta.jar 
New source root at "/data/test"
Parsing /data/test/Blabla.java
Positivizing!
Saving all files (1) to /data/test/output
Saving /data/yale/test/output/Blabla.java
```

**Comment by jlerbsc** [comment]
Your issue seems to come from a GraalVM configuration problem, unfortunately I don't really know this product and its specificities. You can try to repeat the example without making any changes. If it works, the problem is in the code or a dependency.

**Comment by cyw3** [comment]
The same steps for the example without making any changes, it works.

But I still don't know how to solve this problem.

**Comment by jlerbsc** [comment]
Have you correctly configured the version of Java with which the parser must be compatible?
Can you give me the code with which you configured the parser?

**Comment by jlerbsc** [comment]
Did you find a solution to fix your issue?

**Comment by cyw3** [comment]
My fault.

1. when i put the `Blabla.java` at `javaparser-gradle-sample/src/main/resources`, the binary file works well.
2. And when i put the other path(such as `/data/test/Blabla.java`), the binary file dose not  work, then encountered the above error.

**Comment by jlerbsc** [comment]
Thank you for sharing your feedback. Are there any other questions on this topic?

**Comment by cyw3** [comment]
No more, thanks.
