### ISSUE TITLE
Unnamed Patterns and Variables (Preview) JEP 443

### ISSUE THREAD

**Issue by jlerbsc** [javaparser/javaparser#4219]
https://openjdk.org/jeps/443

**Comment by donalmurtagh** [comment]
This feature was [previewed in JDK 21 and finalized in JDK 22](https://openjdk.org/jeps/456). The parser fails when it encounters a variable named `_` with the following error

```
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 51,col 38) '_' is a reserved keyword.

        at com.github.javaparser.JavaParserAdapter.handleResult(JavaParserAdapter.java:83)
        at com.github.javaparser.JavaParserAdapter.parse(JavaParserAdapter.java:99)
        at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:173)
```

**Comment by jlerbsc** [comment]
Java 22 features not yet supported

**Comment by jlerbsc** [comment]
@johannescoetzee Can you confirm that this issue has been fully resolved?

**Comment by jlerbsc** [comment]
Unnamed variable are supported now.
