### ISSUE TITLE
update method body and save throw "Range not present on node"

### ISSUE THREAD

**Issue by cbooy** [javaparser/javaparser#4250]
step:
1.update class/method 
2.store for origin format
3.print 

-----
I found that there was no change in the range before and after modifying the method, which led to an error in the setup method when it judged hasRange().

Test Code:
```java
CompilationUnit cu = StaticJavaParser.parse(Paths.get("/local/Foo.java"));

        MethodDeclaration methodDeclaration = cu.getClassByName("Foo")
                .orElseThrow()
                .getMethodsByName("foo")
                .get(0);

        BlockStmt methodBody = new BlockStmt();
        methodBody.addStatement("System.out.println(\"-----------------------------------------\");");
        methodDeclaration.setBody(methodBody);

        LexicalPreservingPrinter.setup(cu);

        String printedCode = LexicalPreservingPrinter.print(cu);
        System.out.println(printedCode);
```

thorw exception:
```java
Exception in thread "main" java.lang.RuntimeException: Range not present on node {
    System.out.println("-----------------------------------------");
}
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialTextForOneNode(LexicalPreservingPrinter.java:463)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.access$300(LexicalPreservingPrinter.java:63)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$2.process(LexicalPreservingPrinter.java:429)
	at com.github.javaparser.ast.visitor.TreeVisitor.visitBreadthFirst(TreeVisitor.java:80)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$storeInitialText$3(LexicalPreservingPrinter.java:432)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialText(LexicalPreservingPrinter.java:414)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$setup$0(LexicalPreservingPrinter.java:100)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.setup(LexicalPreservingPrinter.java:99)
```

**Comment by jlerbsc** [comment]
Lexical preservation must be initialized before modifying the AST.

**Comment by jlerbsc** [comment]
If we have answered your question, could you close this issue?

**Comment by jlerbsc** [comment]
No response so I'm closing the issue.
