### ISSUE TITLE
java code parsing failed

### ISSUE THREAD

**Issue by Elfe-w** [javaparser/javaparser#4255]
java code parsing failed.
The source code content is as follows：
```
package ${package};

import org.apache.wicket.request.mapper.parameter.PageParameters;
import org.apache.wicket.markup.html.basic.Label;
import org.apache.wicket.markup.html.WebPage;

public class HomePage extends WebPage {
private static final long serialVersionUID = 1L;

public HomePage(final PageParameters parameters) {
add(new Label("version", getApplication().getFrameworkSettings().getVersion()));
// TODO Add your page's components here
}
}
```

The error message is as follows：
Exception in thread "main" com.github.javaparser.ParseProblemException: Parse error. Found "package", expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "non-sealed" "open" "private" "protected" "public" "record" "sealed" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
Problem stacktrace : 
  com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:14041)
  com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:13886)
  com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:208)
  com.github.javaparser.JavaParser.parse(JavaParser.java:125)
  com.github.javaparser.JavaParser.parse(JavaParser.java:305)
  com.github.javaparser.JavaParserAdapter.parse(JavaParserAdapter.java:107)
  com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:253)
  DataFlowGraphBuilder.main(DataFlowGraphBuilder.java:27)

	at com.github.javaparser.JavaParserAdapter.handleResult(JavaParserAdapter.java:83)
	at com.github.javaparser.JavaParserAdapter.parse(JavaParserAdapter.java:107)
	at com.github.javaparser.StaticJavaParser.parse(StaticJavaParser.java:253)
	at DataFlowGraphBuilder.main(DataFlowGraphBuilder.java:27)

**Comment by jlerbsc** [comment]
This line of code is not compilable code. This is what caused the ParseProblemException error

    package ${package};
