### ISSUE TITLE
Exception when resolving ObjectCreationExpr with nested varargs

### ISSUE THREAD

**Issue by yakovsh** [javaparser/javaparser#4270]
While trying to parse the code below, I am getting an exception. From what I can tell it seems that there is a mismatch between the expected type and the array of that type (which is what varargs creates).

The code I'm trying to parse is:
```
public class Test {
    public void write(final Path path, final OpenOption... options) throws IOException {
        BufferedInputStream in = new BufferedInputStream(Files.newInputStream(path, options));
    }
}
```

Here is the test case:
```
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.ObjectCreationExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import org.junit.jupiter.api.Test;

public class Issue4270Test {
    @Test
    public void test_vargs_inside_object_create() {
        ParserConfiguration parserConfiguration = new ParserConfiguration();
        parserConfiguration.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        StaticJavaParser.setConfiguration(parserConfiguration);

        CompilationUnit compilationUnit = StaticJavaParser.parse(
                  "import java.io.BufferedInputStream;\n" +
                        "import java.io.IOException;\n" +
                        "import java.nio.file.Files;\n" +
                        "import java.nio.file.OpenOption;\n" +
                        "import java.nio.file.Path;\n" +
                        "\n" +
                        "public class Test {\n" +
                        "    public void write(final Path path, final OpenOption... options) throws IOException {\n" +
                        "        BufferedInputStream in = new BufferedInputStream(Files.newInputStream(path, options));\n" +
                        "    }\n" +
                        "}"
        );

        for (ObjectCreationExpr expr : compilationUnit.findAll(ObjectCreationExpr.class)) {
            String name = expr.resolve().getName();
            System.out.println(name);
        }
    }
}
```

Here is the exception I'm getting:
```
java.lang.UnsupportedOperationException: Unable to resolve the type typeParametersValues in a MethodUsage. 
Expected type: ReferenceType{java.nio.file.OpenOption, typeParametersMap=TypeParametersMap{nameToValue={}}}, 
Actual type: ResolvedArrayType{ReferenceType{java.nio.file.OpenOption, typeParametersMap=TypeParametersMap{nameToValue={}}}}. 
Method Declaration: ReflectionMethodDeclaration{method=public static java.io.InputStream java.nio.file.Files.newInputStream(java.nio.file.Path,java.nio.file.OpenOption[]) throws java.io.IOException}. 
MethodUsage: MethodUsage{declaration=ReflectionMethodDeclaration{method=public static java.io.InputStream java.nio.file.Files.newInputStream(java.nio.file.Path,java.nio.file.OpenOption[]) throws java.io.IOException}, paramTypes=[ReferenceType{java.nio.file.Path, typeParametersMap=TypeParametersMap{nameToValue={}}}, ResolvedArrayType{ReferenceType{java.nio.file.OpenOption, typeParametersMap=TypeParametersMap{nameToValue={}}}}]}
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.resolveMethodTypeParameters(MethodCallExprContext.java:369)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:656)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:325)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:254)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:220)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:142)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:174)
	at com.github.javaparser.ast.expr.ObjectCreationExpr.resolve(ObjectCreationExpr.java:369)

```

**Comment by yakovsh** [comment]
This might be a regression caused by #3995, I'm getting this error on version 3.25.7 but if I go back to v3.25.0 which predates that fix, no exception is thrown

**Comment by jlerbsc** [comment]
This seems to be a bug. Thanks for reporting it.

**Comment by yakovsh** [comment]
Thank you!
