### ISSUE TITLE
Method 'getDown' cannot be resolved in context methodNode.getDown()

### ISSUE THREAD

**Issue by huajiaoyu** [javaparser/javaparser#4277]
javaparser-symbol-solver-core version: 3.25.7

when I ran TestJavaParser.main, I encountered this exception:
```
Exception in thread "main" java.lang.RuntimeException: Method 'getDown' cannot be resolved in context methodNode.getDown() (line: 16) MethodCallExprContext{wrapped=methodNode.getDown()}. Parameter types: []
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:659)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:325)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:331)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.calculateType(JavaSymbolSolver.java:294)
	at com.github.javaparser.ast.expr.Expression.calculateResolvedType(Expression.java:575)
	at TestJavaParser.lambda$null$0(TestJavaParser.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at TestJavaParser.lambda$null$1(TestJavaParser.java:56)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at TestJavaParser.lambda$main$2(TestJavaParser.java:53)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at TestJavaParser.main(TestJavaParser.java:52)
```

```
public class TestJavaParser {

    private static final String SRC_PATH = "C:/MyWorkSpaceNew/drawio-flow-chart-gen/src/main/java";
    private static final String FILE_PATH = SRC_PATH+"/tests/A.java";

    public static void main(String[] args) throws FileNotFoundException {
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File(SRC_PATH));

        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        StaticJavaParser
                .getConfiguration()
                .setSymbolResolver(symbolSolver);
        CompilationUnit cu = StaticJavaParser.parse(new File(FILE_PATH));

        cu.findAll(MethodDeclaration.class).forEach(method -> {
            method.findAll(MethodCallExpr.class).forEach(callExpr -> {
                NodeList<Expression> arguments = callExpr.getArguments();
                arguments.forEach(arg->System.out.println(arg.calculateResolvedType()));
            });
        });
    }
}
```
A.java:
```
public class A {

    void func1(Object obj, int a){
        if(a==0) return;
        List<Object> xs = Arrays.asList(new int[]{1,2,3,4});
        MethodNode methodNode = new MethodNode("m1");
        func1(methodNode.getDown(), a-1);
    }
}
```

MethodNode.java:
```
import lombok.Data;

public @Data  class MethodNode {
    MethodNode next = null;
    MethodNode down = null;

    String name;
    String note = "";

    public MethodNode(String name){
        this.name = name;
    }
}
```

**Comment by huajiaoyu** [comment]
I found out this caused by Lombok: javasymbolparser cannot resolve getter/setter generated by Lombok, even if I added lombok-1.18.30.jar in `JarTypeSolver` to `CombinedSolver`.
```
TypeSolver jarTypeSolver = new JarTypeSolver(new File(JAR_PATH));
combinedSolver.add(jarTypeSolver);
```
can someone provide solutions to this?

**Comment by jlerbsc** [comment]
It seems to me that lombok does a bytecode injection during the project build. If this is the case, I don't see a simple way to take this into account except a solution which would consist of packaging your application in a jar file.

**Comment by huajiaoyu** [comment]
Thank you, I tried add application jar file and it worked well.

 > It seems to me that lombok does a bytecode injection during the project build. If this is the case, I don't see a simple way to take this into account except a solution which would consist of packaging your application in a jar file.
