### ISSUE TITLE
`ClassCastException` when resolving `MethodCallExpr` inside an enhanced switch statement

### ISSUE THREAD

**Issue by PalashSharma20** [javaparser/javaparser#4284]
Exception:

```
Exception in thread "main" java.lang.ClassCastException: class com.github.javaparser.ast.expr.SwitchExpr cannot be cast to class com.github.javaparser.ast.stmt.SwitchStmt (com.github.javaparser.ast.expr.SwitchExpr and com.github.javaparser.ast.stmt.SwitchStmt are in unnamed module of loader 'app')
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.SwitchEntryContext.solveSymbol(SwitchEntryContext.java:53)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:166)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.BlockStmtContext.solveSymbol(BlockStmtContext.java:106)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:166)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbol(StatementContext.java:312)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.StatementContext.solveSymbol(StatementContext.java:194)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.AbstractJavaParserContext.solveSymbolInParentContext(AbstractJavaParserContext.java:166)
	at com.github.javaparser.resolution.Context.solveSymbolAsValueInParentContext(Context.java:194)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveSymbolAsValue(MethodCallExprContext.java:145)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:76)
	at com.github.javaparser.symbolsolver.resolution.SymbolSolver.solveSymbolAsValue(SymbolSolver.java:82)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:335)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:65)
	at com.github.javaparser.ast.expr.NameExpr.accept(NameExpr.java:81)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:501)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:349)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:254)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:271)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:134)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:164)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:319)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at com.palashsharma.SymbolResolverTest.main(SymbolResolverTest.java:21)
```

Test Case:

```java
package com.palashsharma;

import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

import java.io.FileInputStream;
import java.io.FileNotFoundException;

public class SymbolResolverTest {
    public static void main(String... args) throws FileNotFoundException {
        ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(
                new JavaSymbolSolver(new ReflectionTypeSolver())).setLanguageLevel(
                ParserConfiguration.LanguageLevel.JAVA_17);

        StaticJavaParser.setConfiguration(parserConfiguration);
        CompilationUnit cu = StaticJavaParser.parse(new FileInputStream("SampleCode.java"));
        cu.findAll(MethodCallExpr.class).forEach(MethodCallExpr::resolve);
    }
}
```

Sample Code:

```java
package com.palashsharma;

public class SampleCode {
    public static void main(String... args) {
        int o1 = Integer.parseInt(args[0]);
        int o2 = Integer.parseInt(args[1]);
        char ch = args[2].charAt(0);

        int result = switch (ch) {
            case '^' -> {
                if (o1 == 0 && o2 == 0) {
                    throw new IllegalArgumentException("Cannot evaluate expression, 0^0 is undefined.");
                }
                yield (int) Math.pow(o2, o1);
            }
            case 'x' -> o2 * o1;
            case '/' -> {
                if (o1 == 0) {
                    throw new IllegalArgumentException("Cannot evaluate expression, division by zero.");
                }
                yield o2 / o1;
            }
            case '%' -> {
                if (o1 == 0) {
                    throw new IllegalArgumentException("Cannot evaluate expression, division by zero.");
                }
                yield  o2 % o1;
            }
            case '+' ->  o2 + o1;
            case '-' -> o2 - o1;
            default -> 0;
        };

        System.out.println(result);
    }
}
```

The `Math.pow` call inside the switch causes the issue.

**Comment by PalashSharma20** [comment]
Proposed fix: https://github.com/PalashSharma20/javaparser/commit/1fa349b9ab39005a4627d397551566547362a951
