### ISSUE TITLE
IndexOutOfBoundsException when parsing Mybatis-Plus 

### ISSUE THREAD

**Issue by Fioooooooo** [javaparser/javaparser#4310]
## My Environment

javaparser 3.25.8
mybatis-plus 3.5.5

## Explain

This issue is with a third-party library, i try to reproduce the exception without the library, but i failed...... 

## Current Behavior

[Mybatis-Plus](https://github.com/baomidou/mybatis-plus) is an enhance toolkit for mybatis, it provides a way to do select with lambda expression. 

The source code i want to parse just use this toolkit library.

Here is the simplest for reproduce. And you can get `mybatis-plus-core-3.5.5.jar` [here](https://repo1.maven.org/maven2/com/baomidou/mybatis-plus-core/3.5.5/mybatis-plus-core-3.5.5.jar);

```java
@Test
public void test() throws IOException {
    CombinedTypeSolver combinedTypeSolver = new CombinedTypeSolver();
    combinedTypeSolver.add(new ReflectionTypeSolver());
    combinedTypeSolver.add(new JarTypeSolver(Path.of("/path/to/mybatis-plus-core-3.5.5.jar")));

    StaticJavaParser.getParserConfiguration()
            .setSymbolResolver(new JavaSymbolSolver(combinedTypeSolver))
            .setLanguageLevel(ParserConfiguration.LanguageLevel.BLEEDING_EDGE);

    CompilationUnit compilationUnit = StaticJavaParser.parse("""
            import com.baomidou.mybatisplus.core.toolkit.Wrappers;
                            
            import java.util.Date;
                            
            public class WrapperTest {
                            
                public void test() {
                    Wrappers.lambdaQuery(Base.class).orderByDesc(Base::getDate);
                }
                            
                public static class Base {
                    private Date date;
                            
                    public Date getDate() {
                        return date;
                    }
                }
                            
            }
            """);
    for (MethodReferenceExpr method : compilationUnit.findAll(MethodReferenceExpr.class)) {
        String signature = method.resolve().getQualifiedSignature();
        System.out.println(signature);
    }
}
```

The exception occurred when try to resolve `Base::getDate` expression. The exception stack as below
```java
java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1

	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.github.javaparser.resolution.MethodUsage.getParamType(MethodUsage.java:141)
	at com.github.javaparser.resolution.logic.MethodResolutionLogic.isMoreSpecific(MethodResolutionLogic.java:807)
	at com.github.javaparser.resolution.logic.MethodResolutionLogic.findMostApplicableUsage(MethodResolutionLogic.java:843)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.solveMethodAsUsage(JavassistUtils.java:85)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistInterfaceDeclaration.solveMethodAsUsage(JavassistInterfaceDeclaration.java:102)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.lambda$solveMethodAsUsage$1(JavassistUtils.java:81)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.solveMethodAsUsage(JavassistUtils.java:81)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.solveMethodAsUsage(JavassistClassDeclaration.java:136)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.lambda$solveMethodAsUsage$1(JavassistUtils.java:81)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.solveMethodAsUsage(JavassistUtils.java:81)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.solveMethodAsUsage(JavassistClassDeclaration.java:136)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.lambda$solveMethodAsUsage$1(JavassistUtils.java:81)
	at java.base/java.util.Optional.flatMap(Optional.java:289)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.solveMethodAsUsage(JavassistUtils.java:81)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.solveMethodAsUsage(JavassistClassDeclaration.java:136)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:181)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:566)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:122)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:656)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodReferenceExprContext.inferArgumentTypes(MethodReferenceExprContext.java:101)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodReferenceExprContext.solveMethod(MethodReferenceExprContext.java:68)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:286)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:138)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:202)
	at com.github.javaparser.ast.expr.MethodReferenceExpr.resolve(MethodReferenceExpr.java:240)
```

## My Question

Until now, i haven't find which method is specific when JP execute `isMoreSpecific(MethodUsage methodA, MethodUsage methodB)`, And i will try to find the exception method go on...

**Comment by jlerbsc** [comment]
Your problem isn't with the library but with your code, which doesn't compile "The target type of this expression must be a functional interface".

**Comment by Fioooooooo** [comment]
Thank you for your replay. I read some posts of "function interface" just now.

But i notice than the param of `orderByDesc(R column)` is generic, one of it's subclass(`LambdaQueryWrapper`) has set `R` to functional interface.

```java
public interface Func<Children, R> extends Serializable {
    default Children orderByDesc(boolean condition, R column) {
        return orderBy(condition, false, column);
    }
}
```

```java
public abstract class AbstractWrapper<T, R, Children extends AbstractWrapper<T, R, Children>> extends Wrapper<T>
    implements Compare<Children, R>, Nested<Children, Children>, Join<Children>, Func<Children, R>
```

```java
public abstract class AbstractLambdaWrapper<T, Children extends AbstractLambdaWrapper<T, Children>> extends AbstractWrapper<T, SFunction<T, ?>, Children>
```

```java
public class LambdaQueryWrapper<T> extends AbstractLambdaWrapper<T, LambdaQueryWrapper<T>>
    implements Query<LambdaQueryWrapper<T>, T, SFunction<T, ?>> {
```

```java
@FunctionalInterface
public interface SFunction<T, R> extends Function<T, R>, Serializable {
}
```

---
I'm not sure whether my thought is right or not.
If i cann't resolve `Base::getDate` from `MethodReferenceExpr`，which expression i should use? I just want to get Base.getDate() qualified signature

**Comment by jlerbsc** [comment]
Your getDate() method takes no parameters and returns a Date. It can be used as a Supplier.

    Base b = new Base();
    Supplier s = b::getDate;

But the signature of the orderByDesc method is more like a BiFunction<Boolean, R, Children>.

    default Children orderByDesc(boolean condition, R column) {
        return orderBy(condition, false, column);
    }

**Comment by jlerbsc** [comment]
I'm closing this exit because there are no more exchanges on this subject.
