### ISSUE TITLE
UnsolvedSymbolException ... cannot be resolved in context ... MethodCallExprContext

### ISSUE THREAD

**Issue by ond1** [javaparser/javaparser#4339]
Hi,

The following exception is thrown from a simple sample Java code below:

> Exception in thread "main" UnsolvedSymbolException{context='null', name='Method 'key' cannot be resolved in context key(KEYWORD_LBRA, RPAR) (line: 35) MethodCallExprContext{wrapped=key(KEYWORD_LBRA, RPAR)}. Parameter types: [PrimitiveTypeUsage{name='int'}, PrimitiveTypeUsage{name='int'}]', cause='null'}
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:651)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:324)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:118)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:493)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.lambda$getType$5(JavaParserFacade.java:380)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:379)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:640)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.LambdaExprContext.solveSymbolAsValue(LambdaExprContext.java:74)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserParameterDeclaration.getType(JavaParserParameterDeclaration.java:63)
	at com.github.javaparser.resolution.model.Value.from(Value.java:45)

```
public class Sample {

    private static final Map<Long, ExpressionMaker> patterns = new HashMap<>();

    public static final int KEYWORD_LBRA = 69;
    public static final int RPAR = 204;

    public Sample() {
    }


    private static long key(Integer... tokens) {
        long key = 0L;
        for (int token : tokens) {
            key = (key << 8) + token;
        }
        return key;
    }

    @FunctionalInterface
    private interface ExpressionMaker {
        String make(List<String> tokens, String env) ;
    }

    static {


        patterns.put(
                key(KEYWORD_LBRA, RPAR),
                (values, env) -> {
                    String kind = values.get(0);

                    return kind;
                });

    }


}
```

Run it with the following:

```
CompilationUnit cu = StaticJavaParser.parse(filename);

System.err.println("Processing " + filename);
List<NameExpr>  nes = cu.findAll(NameExpr .class);
        nes.forEach(ne -> {
            System.out.println(( ne.calculateResolvedType().describe()));
});
```

There is some type resolution problem with the argument `Integer ... token` in the `key` method

**Comment by ond1** [comment]
The problem occurs in JavaParser version 3.25.9. It works fine in version 3.17.0

**Comment by jlerbsc** [comment]
You are right. JP cannot resolve the key(Integer... tokens) method from key(KEYWORD_LBRA, RPAR) because it considers that int[] cannot be assigned to Integer[].
Probably related to https://docs.oracle.com/javase/specs/jls/se8/html/jls-5.html#jls-5.3 (Invocation Contexts#Loose invocation contexts) or 
https://docs.oracle.com/javase/specs/jls/se8/html/jls-15.html (15.12.2. Compile-Time Step 2: Determine Method Signature ) -> Second phase
