### ISSUE TITLE
Strange error when trying to find erasure of generic type where one of two type parameters is an array

### ISSUE THREAD

**Issue by FeldrinH** [javaparser/javaparser#4345]
When trying to use `.erasure()` on a resolved type with two type parameters where one is an array (for example `Map<Integer, int[]>`), an unexpected exception is thrown.

**Reproduction:**

Code:
```java
package examples;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.type.Type;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class ErasureFailure {
    public static void main(String[] args) {
        JavaParser parser = new JavaParser();
        parser.getParserConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        CompilationUnit cu = parser.parse("class A { java.util.Map<int[], Integer> test; }").getResult().orElseThrow();
        for (Type type : cu.findAll(Type.class)) {
            System.out.println(type);
            System.out.println(type.resolve().erasure());
        }
    }
}
```
Output:
```
java.util.Map<int[], Integer>
Exception in thread "main" java.lang.IllegalArgumentException: expected either zero type arguments or has many as defined in the declaration (2). Found 1
	at com.github.javaparser.resolution.types.ResolvedReferenceType.<init>(ResolvedReferenceType.java:74)
	at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.<init>(ReferenceTypeImpl.java:71)
	at com.github.javaparser.resolution.model.typesystem.ReferenceTypeImpl.create(ReferenceTypeImpl.java:58)
	at com.github.javaparser.resolution.types.ResolvedReferenceType.erasure(ResolvedReferenceType.java:575)
	at examples.ErasureFailure.main(ErasureFailure.java:17)
```

Tested with javaparser-core and javaparser-symbol-solver-core version 3.25.9.

**Comment by FeldrinH** [comment]
With a little extra testing it seems that the actual issue is that arrays in generic type parameters are not removed by erasure. For example, the erasure of `Map<int[], int[]>` is  `Map<int[], int[]>` according to JavaParser, whereas the erasure of `Map<Integer, Integer>` is `Map`.

**Comment by jlerbsc** [comment]
There is indeed an issue with the arrays.
