### ISSUE TITLE
A StackOverflowError occurred when parsing a deep string concatenation

### ISSUE THREAD

**Issue by capjiang** [javaparser/javaparser#4439]
~~~
    @Test
    fun testStackOverFlow() {
        val javaParser = JavaParser()
        val parseResult = javaParser.parse(Paths.get("DeepStringConcat.java")) // error
        if (!parseResult.result.isPresent) {
            return
        }
		...
    }
~~~

I'm using the kotlin language, but that shouldn't affect this routine! The file is https://github.com/openjdk/jdk/blob/master/test/langtools/tools/javac/DeepStringConcat.java

~~~
java.lang.StackOverflowError
	at java.util.ArrayList.addAll(ArrayList.java:583)
	at com.github.javaparser.metamodel.BaseNodeMetaModel.getAllPropertyMetaModels(BaseNodeMetaModel.java:119)
	at com.github.javaparser.ast.validator.language_level_validations.chunks.CommonValidators.lambda$new$7(CommonValidators.java:60)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:38)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	at com.github.javaparser.ast.validator.TreeVisitorValidator.accept(TreeVisitorValidator.java:40)
	Repeat this.
~~~

**Comment by jlerbsc** [comment]
This is a borderline case linked to the verification of AST nodes. Here the field declaration is initialised with a very large concatenation of character strings and the recursive traversal of the AST raises this problem.

**Comment by ethan-godden** [comment]
I am working on this

**Comment by jlerbsc** [comment]
Closed by this PR https://github.com/javaparser/javaparser/pull/5064.
