### ISSUE TITLE
Out of Memory Error with `sourceZip` API while trying to parse java's Core Library by javaparser

### ISSUE THREAD

**Issue by xuzh0u** [javaparser/javaparser#4516]
**Description:**

I've encountered an issue with the `sourceZip` API when attempting to parse the `src.zip` located in `$JAVA_HOME/lib`. The problem is that the API throws an Out of Memory error when used in this context, whereas using `sourceRoot` to parse the extracted contents of `src.zip` does not result in OOM.

**Steps to Reproduce:**

Using `sourceZip`:

```java
  public void parseZip(String path){
        Path zipPath = Paths.get(path);

        SourceZip sourceZip = new SourceZip(zipPath, new ParserConfiguration().setTabSize(4));
        List<Pair<Path, ParseResult<CompilationUnit>>> cuList = null;
        try {
            cuList = sourceZip.parse();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
```

To have a comparison, here's another piece of code using `sourceRoot` to parse the similar content:

```java
public void parseSource(String sourcePath) {
    Path path = Paths.get(sourcePath);
    SourceRoot sourceRoot = new SourceRoot(path);
    try {
        sourceRoot.tryToParse("");
        List<CompilationUnit> cus = sourceRoot.getCompilationUnits();
    } catch (IOException e) {
        System.err.println("Error parsing files in directory: " + e.getMessage());
    }
}
```

**Expected Result:**
The `sourceZip` API should successfully parse the `src.zip` without throwing an Out of Memory error.

Part of the log:
```
> Task :ExtractorRunner.main()
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.base/java.util.Optional.ofNullable(Optional.java:128)
	at com.github.javaparser.ast.Node.getParentNode(Node.java:367)
	at com.github.javaparser.HasParentNode.hasParentNode(HasParentNode.java:37)
	at com.github.javaparser.ast.body.MethodDeclaration.isImplicitlyAbstract(MethodDeclaration.java:371)
	at com.github.javaparser.ast.body.MethodDeclaration.isAbstract(MethodDeclaration.java:367)
	at com.github.javaparser.ast.validator.language_level_validations.chunks.ModifierValidator.visit(ModifierValidator.java:135)
	at com.github.javaparser.ast.validator.language_level_validations.chunks.ModifierValidator.visit(ModifierValidator.java:43)
	at com.github.javaparser.ast.body.MethodDeclaration.accept(MethodDeclaration.java:201)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$32(VoidVisitorAdapter.java:155)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$160/0x000000e0010dc818.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:155)
	at com.github.javaparser.ast.validator.language_level_validations.chunks.ModifierValidator.visit(ModifierValidator.java:76)
	at com.github.javaparser.ast.validator.language_level_validations.chunks.ModifierValidator.visit(ModifierValidator.java:43)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:158)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$44(VoidVisitorAdapter.java:176)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter$$Lambda$150/0x000000e0010db1e8.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:288)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:176)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:140)
	at com.github.javaparser.ast.validator.VisitorValidator.accept(VisitorValidator.java:35)
	at com.github.javaparser.ast.validator.Validators.lambda$accept$0(Validators.java:63)
	at com.github.javaparser.ast.validator.Validators$$Lambda$139/0x000000e0010ca000.accept(Unknown Source)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at com.github.javaparser.ast.validator.Validators.accept(Validators.java:63)
	at com.github.javaparser.ParserConfiguration$2.postProcess(ParserConfiguration.java:340)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:128)
	at com.github.javaparser.utils.SourceZip.parse(SourceZip.java:106)
	at com.github.javaparser.utils.SourceZip.parse(SourceZip.java:86)

> Task :ExtractorRunner.main() FAILED

Execution failed for task ':ExtractorRunner.main()'.
> Process 'command 'java'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
Deprecated Gradle features were used in this build, making it incompatible with Gradle 9.0.
You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.
For more on this, please refer to https://docs.gradle.org/8.7/userguide/command_line_interface.html#sec:command_line_warnings in the Gradle documentation.
BUILD FAILED in 40s
2 actionable tasks: 2 executed
```

**Actual Result:**
The `sourceZip` API throws an Out of Memory error when processing the `src.zip` located in `$JAVA_HOME/lib`, while the second code block (which uses `sourceRoot`) do not produce any OOM error and its execution ended very quickly.

**Environment:**
- Java Version: 17
- Operating System: MacOS 14.6
- API Version: Latest release 

**Additional Notes:**
- I have confirmed that using `sourceRoot` with the extracted contents of `src.zip` does not produce the Out of Memory error.
- I have attempted to increase the JVM heap size, but the issue persists.

**Comment by jlerbsc** [comment]
Have you allocated enough memory to parse the file? There may be some improvements to make.

**Comment by xuzh0u** [comment]
Thanks for your advice!

I increased the JVM memory limit from 2,304 MiB to 43,040 MiB in IDEA, but I still encounter this error.

> Edited(August 5th): maybe by your last sentence you mean the computer's memory? I did not limit the memory usage though. My computer's memory is 16GB, which should be enough to run the parsing i guess? (After all it was much bigger than the JVM heap size limit.)

The `src.zip` file of java core library, which was chosen to be the target of this parsing task is around 50MB. And when it was extracted to files, the whole folder came to be around 250MB. The JVM memory limit of 43,040 MiB seems to be more than sufficient for parsing files in a folder equivalent to 250 MB, I suppose?



BTW, if I have understood correctly, then

- Unzipping the zip file → Parsing with `sourceRoot`
- Directly parsing the zip file with `sourceZip`

These two actions should be equivalent, is that right? If there's anything wrong with my understanding, please let me know.
