### ISSUE TITLE
JavaParser cannot resolve objectCreationExpression when type argument is a record type

### ISSUE THREAD

**Issue by abdullahtellioglu** [javaparser/javaparser#4517]
The following exception is thrown when resolving the constructor of an object creation expression creates an exception that uses a record as a generic type, 

The expression that I try to parse is: `new RadioButtonGroup<LabelAndValue>("Radio group")`. `LabelAndValue` is a record

```java
java.lang.IllegalArgumentException: Cannot get a reference type declaration from com.github.javaparser.ast.body.RecordDeclaration
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toTypeDeclaration(JavaSymbolSolver.java:461) ~[javaparser-symbol-solver-core-3.26.1.jar:na]
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeDeclaration(JavaParserFacade.java:746) ~[javaparser-symbol-solver-core-3.26.1.jar:na]
```

In the code from JavaSymbolSolver below  RecordDeclaration is not handled

```java
public ResolvedReferenceTypeDeclaration toTypeDeclaration(Node node) {
        if (node instanceof ClassOrInterfaceDeclaration) {
            if (((ClassOrInterfaceDeclaration) node).isInterface()) {
                return new JavaParserInterfaceDeclaration((ClassOrInterfaceDeclaration) node, typeSolver);
            }
            return new JavaParserClassDeclaration((ClassOrInterfaceDeclaration) node, typeSolver);
        }
        if (node instanceof TypeParameter) {
            return new JavaParserTypeParameter((TypeParameter) node, typeSolver);
        }
        if (node instanceof EnumDeclaration) {
            return new JavaParserEnumDeclaration((EnumDeclaration) node, typeSolver);
        }
        if (node instanceof AnnotationDeclaration) {
            return new JavaParserAnnotationDeclaration((AnnotationDeclaration) node, typeSolver);
        }
        if (node instanceof EnumConstantDeclaration) {
            return new JavaParserEnumDeclaration((EnumDeclaration) demandParentNode(node), typeSolver);
        }
        throw new IllegalArgumentException("Cannot get a reference type declaration from "
                + node.getClass().getCanonicalName());
    }
```

**Comment by jlerbsc** [comment]
This is because record resolution will not be operational until the next version.

**Comment by jlerbsc** [comment]
I'm closing this exit, but you can reopen it if the next version doesn't meet your needs.
