### ISSUE TITLE
ResolvedMethodDeclaration.toDescription fails in the presence of type variables

### ISSUE THREAD

**Issue by johanneskloos** [javaparser/javaparser#4519]
Consider the following test case:
```
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

public class RegressionTest {
  @Test
  void testJavaparserRegression(@TempDir Path tmpdir) throws IOException {
    Files.write(tmpdir.resolve("Example.java"), Arrays.asList(
      "public class Example {",
      "  public <T> void example(T value) {}",
      "}"
    ));
    CombinedTypeSolver typeSolver = new CombinedTypeSolver();
    ParserConfiguration config = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
    typeSolver.add(new JavaParserTypeSolver(tmpdir, config));
    typeSolver.add(new ReflectionTypeSolver(true));
    typeSolver.solveType("Example").getDeclaredMethods().forEach(ResolvedMethodDeclaration::toDescriptor);
  }
}
```
Running it causes the following failure:
```
	at com.github.javaparser.resolution.types.ResolvedType.asReferenceType(ResolvedType.java:140)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.toDescriptor(ClassOrInterfaceType.java:269)
	at com.github.javaparser.ast.body.MethodDeclaration.toDescriptor(MethodDeclaration.java:337)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserMethodDeclaration.toDescriptor(JavaParserMethodDeclaration.java:177)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at com.diffblue.combiner.javaparser.CombinerTest.testJavaparserRegression(CombinerTest.java:1190)
```
The expected behaviour is that the test passes and produces a signature `(Ljava/lang/Object;)V` for `Example.example`.

**Comment by johanneskloos** [comment]
Note that the reason for the failure is a missing call to `erasure` in some `toDescriptor` methods; I'll submit a PR to fix this.
