### ISSUE TITLE
Node::getData : Possibility to check if a key is pointing at null is missing

### ISSUE THREAD

**Issue by Kimmmey** [javaparser/javaparser#4557]
Hi, 

at the following location https://github.com/javaparser/javaparser/blob/0fbc596ef0a27ff111b0663d272b1ab2ae8b110f/javaparser-core/src/main/java/com/github/javaparser/ast/Node.java#L539 is a check, if the value of a given key is `null.` If this value is `null` an `IllegalStateException` is thrown. 

The message of the thrown Exception says `"No data of this type found. Use containsData to check for this first."`
But there is no way to check if the value of the key is null. It is possible to check if the key is present with `containsData(key)`, but no way to check if the key points to `null` value.

I don't know if the implemented behavior is desired. I understand that `data.get(key)` returns null, if the key is not present, but if the key is present and the value is `null` we will get an exception.

There are two ways to mitigate this problem.
1. Check if the key is present before checking for it's value, or
2. Introduce a method, which allows to check for the value or `null` values.

Best regards,
Kim

**Comment by jlerbsc** [comment]
Hi @Kimmmey To the best of my knowledge, this API has not been introduced for use by users. Could you please specify your use case?

**Comment by Kimmmey** [comment]
Hi @jlerbsc ,

The problem that made me create this issue is that the resolution of certain types does not work. JavaParserFacade::getTypeConcrete returns null and in JavaParserFacade::getType null is stored as value for TYPE_WITH_LAMBDAS_RESOLVED.

The result is that accessing the values of the keys with Node::getData() leads to an exception.

I will provide a test case that shows when the problem occurs, but first I have to solve another issue.

best regards,
Kimmmey

**Comment by Kimmmey** [comment]
so back to this problem. I have since found out that resolving overloaded methods is a problem. The LeastUpperBoundLogic is used to determine the type of the contained expression. However, this does not work if one of the types involved is a generic type variable. Then the result is null and no type. This is also the reason why Node::getData throws the exception.

I think I have found a solution for this and will make it available in a pull request. 

Here is a test to understand the behavior. 

<details>
  <summary>Test</summary>
  
```Java
package com.github.javaparser.symbolsolver;

import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import org.junit.jupiter.api.Test;

import java.util.List;

public class ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest {

    @Test
    public void test() {
        String code = "public class Box<E> {\n" +
                      "    private E element;\n" +
                      "\n" +
                      "    public Box(E element) {\n" +
                      "        this.element = element;\n" +
                      "    }\n" +
                      "\n" +
                      "    public E getElement() {return element;}\n" +
                      "\n" +
                      "    public void setElement(E element) {this.element = element;}\n" +
                      "\n" +
                      "    @Override\n" +
                      "    public String toString() {\n" +
                      "        StringBuilder builder = new StringBuilder();\n" +
                      "        builder.append(\"Box [element=\");\n" +
                      "        builder.append(element == this ? \"(this box)\" : element);\n" +
                      "        builder.append(\"]\");\n" +
                      "        return builder.toString();\n" +
                      "    }\n" +
                      "}";
        StaticJavaParser.getParserConfiguration().setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        CompilationUnit cu = StaticJavaParser.parse(code);

        final List<MethodCallExpr> methodCallExprs = cu.findAll(MethodCallExpr.class);

        for (MethodCallExpr methodCallExpr : methodCallExprs) {
            System.err.println(methodCallExpr.toString());
            System.err.println(methodCallExpr.resolve().toString());
        }
    }
}

```
  
</details>

<details>
  <summary>Result on master (52d78c93):</summary>

```
[INFO] Running com.github.javaparser.symbolsolver.ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest
builder.append("Box [element=")
ReflectionMethodDeclaration{method=public java.lang.StringBuilder java.lang.StringBuilder.append(java.lang.String)}
builder.append(element == this ? "(this box)" : element)
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.407 s <<< FAILURE! -- in com.github.javaparser.symbolsolver.ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest
[ERROR] com.github.javaparser.symbolsolver.ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest.test -- Time elapsed: 0.375 s <<< ERROR!
java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.
        at com.github.javaparser.ast.Node.getData(Node.java:540)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:398)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:273)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:293)
        at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:133)
        at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:190)
        at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:332)
        at com.github.javaparser.symbolsolver.ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest.test(ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest.java:42)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
        at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
```
  
</details>

<details>
  <summary>expected result:</summary>

```
[INFO] Running com.github.javaparser.symbolsolver.ResolutionOfOverloadedMethodsWithTypeVariablesInvolvedTest
builder.append("Box [element=")
ReflectionMethodDeclaration{method=public java.lang.StringBuilder java.lang.StringBuilder.append(java.lang.String)}
builder.append(element == this ? "(this box)" : element)
ReflectionMethodDeclaration{method=public java.lang.StringBuilder java.lang.StringBuilder.append(java.lang.Object)}
builder.append("]")
ReflectionMethodDeclaration{method=public java.lang.StringBuilder java.lang.StringBuilder.append(java.lang.String)}
builder.toString()
ReflectionMethodDeclaration{method=public java.lang.String java.lang.StringBuilder.toString()}
```
  
</details>

**Comment by jlerbsc** [comment]
Fixed by https://github.com/javaparser/javaparser/pull/4570
