### ISSUE TITLE
Unable to parse lambda with cast inside a ternary

### ISSUE THREAD

**Issue by avik-das** [javaparser/javaparser#571]
Failing test case:

```java
public class TestTernaryFailing {
    void test() {
        IntUnaryOperator fn = true ? null : (IntUnaryOperator) i -> i * 2;
    }
}
```

It's very specific to this case. The parsing works (though I haven't checked if the AST has any issues) when there's no ternary, when the lambda is on the first branch of the ternary, or if the entire lambda is surrounded by parentheses. Here are some passing cases:

```java
public class TestTernaryPassing {
    void test() {
        IntUnaryOperator fn0 = (IntUnaryOperator) i -> i * 2;
        IntUnaryOperator fn1 = true ? null : i -> i * 2;
        IntUnaryOperator fn2 = true ? null : ((IntUnaryOperator) i -> i * 2);
        IntUnaryOperator fn3 = true ? (IntUnaryOperator) i -> i * 2 : null;
        IntUnaryOperator fn4 = true ? null : (IntUnaryOperator) (i -> i * 2);
    }
}
```

All of these, both successful and passing, go through `javac` just fine, so they're valid Java.

Here's the stack trace, starting at the call to `JavaParser.parse`:

```
com.github.javaparser.ParseException: Failed to parse lambda expression! Please create an issue at https://github.com/javaparser/javaparser/issues
        at com.github.javaparser.ASTParser.generateLambda(ASTParser.java:115)
        at com.github.javaparser.ASTParser.Expression(ASTParser.java:2273)
        at com.github.javaparser.ASTParser.VariableInitializer(ASTParser.java:1137)
        at com.github.javaparser.ASTParser.VariableDeclarator(ASTParser.java:1069)
        at com.github.javaparser.ASTParser.VariableDeclarationExpression(ASTParser.java:4005)
        at com.github.javaparser.ASTParser.BlockStatement(ASTParser.java:3944)
        at com.github.javaparser.ASTParser.Statements(ASTParser.java:1658)
        at com.github.javaparser.ASTParser.Block(ASTParser.java:3926)
        at com.github.javaparser.ASTParser.MethodDeclaration(ASTParser.java:1283)
        at com.github.javaparser.ASTParser.ClassOrInterfaceBodyDeclaration(ASTParser.java:994)
        at com.github.javaparser.ASTParser.ClassOrInterfaceBody(ASTParser.java:898)
        at com.github.javaparser.ASTParser.ClassOrInterfaceDeclaration(ASTParser.java:500)
        at com.github.javaparser.ASTParser.TypeDeclaration(ASTParser.java:421)
        at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:217)
        at com.github.javaparser.InstanceJavaParser.parse(InstanceJavaParser.java:92)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:173)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:93)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:139)
        at com.github.javaparser.JavaParser.parse(JavaParser.java:161)
```

**Comment by ptitjes** [comment]
@avik-das Hi ! I took the liberty to add your six test statements to the test suite of [JLaTo](https://github.com/ptitjes/jlato) (In commit https://github.com/ptitjes/jlato/commit/270f36 – your name is cited in the commit title). Indeed, those are passing correctly with the current version of the parser (both in the shape of the AST and the produced lexically-preserving output) but they are failing with the new (in-development) `ALL(*)` parser. As such, they are really useful to me. Tell me if this is a problem for you and I'll roll-back those test cases.

**Comment by avik-das** [comment]
@ptitjes: Thanks so much for including the test cases. I didn't realize this was fixed in the 3.0.0 alphas that are publicly available (in any case I didn't want to switch to a bleeding edge version).

**Comment by ptitjes** [comment]
@avik-das Hmmm, sorry, I was not clear... I don't know at all if it is fixed in JavaParser 3.0-alpha8. I did include your test cases in another project :) ([JLaTo](https://github.com/ptitjes/jlato))

**Comment by avik-das** [comment]
@ptitjes: Haha, I wasn't clear either. I tried out 3.0.0-alpha.9, and that fixed it. Whether or not I'm willing to upgrade to it is another matter, but the current latest alpha seems to parse this case correctly. Glad to know me running into this edge case is handy :)

**Comment by ptitjes** [comment]
@avik-das Perfect !
So either you can close this issue, or maybe you want to contribute an additional test case to ensure that it is still parsed as expected in the upcoming JavaParser versions.

**Comment by avik-das** [comment]
@ptitjes: Ah yes, good idea. I'll close this ticket as it's fixed, but if I do get time, I'll get the project set up and add a test case. Thanks for (inadvertently) prompting me to try the alpha!

**Comment by ptitjes** [comment]
Glad to be of use! Cheers.
