### ISSUE TITLE
Problem when parsing (CommentInserter related)

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#624]
This is the line which causes the problem : (CommentInserter#178)
 `if (node.getBegin().get().line == lineComment.getBegin().get().line `

And here is the SSCCE to reproduce the bug: 
```java
package z;
public class A  {

	@Override
	protected void getDataForCalcul() {

		a.b(c)//
				.success(data -> {
					// DATA STD MACHINE
					dosomething();
				})//
				.error(defaultErrorConsumer);
	}
}
```

Using `JavaParser.parse(Paths.get("failparse.java"));` to parse it yields :

```
Exception in thread "main" com.github.javaparser.ParseProblemException: No value present stack : 
java.util.Optional.get(Optional.java:135)
com.github.javaparser.CommentsInserter.attributeLineCommentToNodeOrChild(CommentsInserter.java:178)
com.github.javaparser.CommentsInserter.attributeLineCommentToNodeOrChild(CommentsInserter.java:193)
com.github.javaparser.CommentsInserter.attributeLineCommentToNodeOrChild(CommentsInserter.java:193)
com.github.javaparser.CommentsInserter.attributeLineCommentToNodeOrChild(CommentsInserter.java:193)
com.github.javaparser.CommentsInserter.lambda$5(CommentsInserter.java:167)
java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
com.github.javaparser.CommentsInserter.lambda$3(CommentsInserter.java:163)
java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
java.util.TreeMap$KeySpliterator.forEachRemaining(TreeMap.java:2742)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
com.github.javaparser.CommentsInserter.attributeLineCommentsOnSameLine(CommentsInserter.java:161)
com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:111)
com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:108)
com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:108)
com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:108)
com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:108)
com.github.javaparser.CommentsInserter.insertComments(CommentsInserter.java:108)
com.github.javaparser.JavaParser.parse(JavaParser.java:97)
com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:243)
com.github.javaparser.JavaParser.parse(JavaParser.java:191)
test.javaparser.JPBug1.main(JPBug1.java:11)


	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:247)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:191)
	at test.javaparser.JPBug1.main(JPBug1.java:11)
```

**Comment by matozoid** [comment]
Hmmm, could you check my branch? This new test for your issue doesn't seem to fail: https://github.com/matozoid/javaparser/blob/issue_624_commentsinserter/javaparser-testing/src/test/java/com/github/javaparser/CommentsInserterTest.java

**Comment by DeepSnowNeeL** [comment]
Well, when run by JUnit it doesn't fail but when I copy paste Issue624.java.txt and use my main with JavaParser.parse it throws the same error.

Using 
```java
 try {
     JavaParser.parse(Paths.get("src/test/resources/com/github/javaparser/issue_samples/Issue624.java.txt"));
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
```
in the junit test yields the error tho, so it might have something to do with JavaParser.parse()
