### ISSUE TITLE
problem in addstatement

### ISSUE THREAD

**Issue by daksunt** [javaparser/javaparser#748]
I want to be able to add many statements into a new block statement, however I cannot add the statements that have the same value. For example, add x.y() to a block twice.
 `

     public static void main(String[] args) {
        

        BlockStmt blockStmt = new BlockStmt();
        Expression exp = new NameExpr("x");
        MethodCallExpr expression = new MethodCallExpr(exp, "y");

        blockStmt.addStatement(expression);
        blockStmt.addStatement((Expression) expression.clone());
        System.out.println(blockStmt);
    }
`

This code does not work.
Cannot add the same statement even if it is a new object. Here is the error

> Exception in thread "main" java.lang.AssertionError: I am not a child of my parent.
	at com.github.javaparser.printer.PrettyPrintVisitor.printOrphanCommentsBeforeThisChildNode(PrettyPrintVisitor.java:1374)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:877)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:51)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:64)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:851)
	at com.github.javaparser.printer.PrettyPrintVisitor.visit(PrettyPrintVisitor.java:51)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:66)
	at com.github.javaparser.printer.PrettyPrinter.print(PrettyPrinter.java:42)
	at com.github.javaparser.ast.Node.toString(Node.java:249)
	at java.lang.String.valueOf(String.java:2994)
	at java.io.PrintStream.println(PrintStream.java:821)

The problem is due to addStatement.
The error is in:
addStatement
-NodeWithStatement.class, default N addStatement(Expression expr) --> expr.setParentNode(statement);
-Node.class, public Node setParentNode(Node parentNode) --> this.parentNode.childNodes.remove(this);

Throws a 
> Method threw 'java.lang.AssertionError' exception. Cannot evaluate com.github.javaparser.ast.stmt.ExpressionStmt.toString()

**Comment by matozoid** [comment]
This is indeed a bug in addStatement, something is wrong with setting parents. We'll fix it in the next release. Here is a workaround:

```java
    public static void main(String[] args) {
        BlockStmt blockStmt = new BlockStmt();
        Expression exp = new NameExpr("x");
        MethodCallExpr expression = new MethodCallExpr(exp, "y");

        blockStmt.getStatements().add(new ExpressionStmt(expression));
        blockStmt.getStatements().add(new ExpressionStmt((Expression) expression.clone()));
        System.out.println(blockStmt);
    }
```
