### ISSUE TITLE
Fix lexical preservation tests on Windows

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#832]
The build fails, and I don't know how to fix these things.

**Comment by matozoid** [comment]
@ftomassetti what does it mean when it prints a brace like this? It probably has something to do with EOL characters...

```java
}

	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:523)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$1.concreteListChange(LexicalPreservingPrinter.java:165)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementRemoved$11(NodeList.java:413)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.notifyElementRemoved(NodeList.java:413)
	at com.github.javaparser.ast.NodeList.remove(NodeList.java:143)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinterTest.printASimpleClassRemovingAField(LexicalPreservingPrinterTest.java:291)
```

**Comment by matozoid** [comment]
Here the same, but from a different JP source location:

```java

}

	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:467)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$1.concreteListChange(LexicalPreservingPrinter.java:167)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$10(NodeList.java:409)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:409)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:67)
	at com.github.javaparser.ast.body.TypeDeclaration.addMember(TypeDeclaration.java:81)
	at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.AnnotationDeclarationTransformationsTest.addingMember(AnnotationDeclarationTransformationsTest.java:84)
```

**Comment by ftomassetti** [comment]
At line 467 there should be this instruction:

`throw new UnsupportedOperationException("kept " + kept.element + " vs " + nodeTextEl);`

So it is surprising to see just a brace

**Comment by ftomassetti** [comment]
At line 523 you have similarly:

`throw new UnsupportedOperationException("removed " + removed.element + " vs " + nodeTextEl);`

Could it be that AppVeyor is not showing the error messages correctly?

**Comment by matozoid** [comment]
These are on my Windows machine while building.

I'll run it with the debugger.

**Comment by matozoid** [comment]
Hehehehe, there is a single "\r" which makes the console overwrite the current line! :-D

`java.lang.UnsupportedOperationException: removed child(FieldDeclaration) vs TokenTextElement(4) {\r}`

**Comment by ftomassetti** [comment]
eh eh eh. Ok I think we should specify that token 4 is a whitespace token in a couple of places. I realized that \n is mapped as token 3 but I thought it was representing all newlines characters while it seems that \r is mapped to 4, not 3. I would start looking at TokenConstants and where NEWLINE_TOKEN is used
