### ISSUE TITLE
LexicalPreservingPrinter with ModifierVisitor throws IllegalArgumentException

### ISSUE THREAD

**Issue by ThLeu** [javaparser/javaparser#845]
Hey thanks a lot for getting the lexical preservation going, the work you guys put into the JavaParser is greatly appreciated!

I am currently trying to play around with it and it seems to me that a lot of changes to the code are not yet supported (with Visitors but also with CompilationUnit directly).
Naturally I tried some changes with the ModifierVisitor but that seems to not work at all.
Here is the simplest example I came up with which does not work for me.

```
try (BufferedReader reader = Files.newBufferedReader(someFilePath)) {
   Pair<ParseResult<CompilationUnit>, LexicalPreservingPrinter> result = LexicalPreservingPrinter
      .setup(ParseStart.COMPILATION_UNIT, Providers.provider(reader));
   cu = result.a.getResult().get();
   cu.accept(new ModifierVisitor(), null);
} catch (IOException e) {
   e.printStackTrace();
}
```

I always end up getting the IllegalArgumentException, which I attached.
[stacktrace.txt](https://github.com/javaparser/javaparser/files/825738/stacktrace.txt)

Also, can you say in what state the Lexical Preservation currently is? Are there still a lot of open TODOs you know about or should it mainly be bugfixing? It would be nice to know what to expect and not to expect to work.

Kind regards

**Comment by matozoid** [comment]
I can answer about the state. I try to mention it in the release notes: https://github.com/javaparser/javaparser/blob/master/changelog.md

**Comment by ThLeu** [comment]
Ah yes thanks, I didnt even realise that it was mentioned as in beta but makes sense of course.
Still, from the unit tests I can see that some changes are supported already (via CompilationUnit directly) and I am not sure if I should report unsupported nodes which throw an exception or if it might be too early.

**Comment by ftomassetti** [comment]
hi @ThLeu LexicalPreservation should reasonably work, but as with all new features problems are to be expected: we figured out that the JavaParser community finds always applications that we did not think of.

For examples while using LexicalPreservation I wrote a large number of tests but it never came to me to use the ModifierVisitor. The thing is also that LexicalPreservation use a lot of metaprogramming, so it tends also to be sensible to little inconsistencies. In this case it seems to fail on the method `com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeListName` which use reflection and expect methods to have a certain name.

So I cannot really judge myself how mature it is but my guess is that a few bugs could be there, but with your help we could identify them quicker and we are committed to fix them ASAP.

**Comment by ThLeu** [comment]
Ok, thanks for that statement @ftomassetti I will look further into using the CompilationUnit directly and will report if I find issues which I can safely say are not user errors :) (I am still getting the hang of some functionality)

**Comment by ftomassetti** [comment]
I have looked a bit in this one. It is a tricky one, the more info and tests we can get the easier it will get to work on it.

**Comment by JKazma** [comment]
Hello,

I am also getting an issue with the CompilationUnit when using the LexicalPreservingPrinter. This is how I initialize my compilationUnit.

```{java}
String code = new String(Files.readAllBytes(Paths.get("/myTestingZone/src/test/java/TestLogs.java")));
Pair<ParseResult<CompilationUnit>, LexicalPreservingPrinter> result = LexicalPreservingPrinter.setup(
ParseStart.COMPILATION_UNIT, new StringProvider(code));
CompilationUnit cu = result.a.getResult().get();
cu.accept(new TypeCalculatorVisitor(), JavaParserFacade.get(combinedTypeSolver));`
```
And this is what the visitor looks like: 
```{java}
private static class TypeCalculatorVisitor extends VoidVisitorAdapter<JavaParserFacade> {

        @Override
        public void visit(MethodCallExpr n, JavaParserFacade javaParserFacade) {
                try{
                    n.addArgument("TATA");
                }catch(Exception e){
                    e.printStackTrace();
                }
                System.out.println(n);

        }

    }
```
This gives the following error:

java.lang.ClassCastException: java.util.Optional cannot be cast to com.github.javaparser.ast.NodeList

**Comment by ThLeu** [comment]
Using the ModifierVisitor with Lexical Preservation would obviously be very helpful, not only for me it seems.
It makes many "refactoring" tasks way easier than with CompilationUnit.

Since it throws an exception immediately when trying to call CompilationUnit.accept I am not sure how I could provide you with any better information yet, but if there is something specific you need just say so.

@JKazma Maybe a more complete stack trace of your problem would give some more insight into your problem. Also if you can maybe provide any non confidential parts of that TestLogs.java file that would still provoke the exception.

**Comment by JKazma** [comment]
@ThLeu Sure thing.

Here you can find the files I used.
https://gist.github.com/JKazma/89e4a7c19c5d5003d808c79c779bf1f3

You'll have to change the paths on line 40 and 122 in the LogParserTest.java file.

**This is the complete stack trace when using the lexical preservation which does not happen without it:**
/usr/lib/jvm/java-1.8.0/bin/java -Didea.launcher.port=7537 -Didea.launcher.bin.path=/opt/idea/idea-IC-145.597.3/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-1.8.0/jre/lib/charsets.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-1.8.0/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-1.8.0/jre/lib/jce.jar:/usr/lib/jvm/java-1.8.0/jre/lib/jsse.jar:/usr/lib/jvm/java-1.8.0/jre/lib/management-agent.jar:/usr/lib/jvm/java-1.8.0/jre/lib/resources.jar:/usr/lib/jvm/java-1.8.0/jre/lib/rt.jar:/myTestingZone/target/classes:/root/.m2/repository/com/github/javaparser/javaparser-core/3.1.2/javaparser-core-3.1.2.jar:/root/.m2/repository/com/github/javaparser/java-symbol-solver-core/0.5.0/java-symbol-solver-core-0.5.0.jar:/root/.m2/repository/com/google/guava/guava/18.0/guava-18.0.jar:/root/.m2/repository/io/javaslang/javaslang/2.0.3/javaslang-2.0.3.jar:/root/.m2/repository/io/javaslang/javaslang-match/2.0.3/javaslang-match-2.0.3.jar:/root/.m2/repository/org/javassist/javassist/3.19.0-GA/javassist-3.19.0-GA.jar:/root/.m2/repository/com/github/javaparser/java-symbol-solver-logic/0.5.0/java-symbol-solver-logic-0.5.0.jar:/root/.m2/repository/com/javaslang/javaslang/2.0.0-beta/javaslang-2.0.0-beta.jar:/root/.m2/repository/com/github/javaparser/java-symbol-solver-model/0.5.0/java-symbol-solver-model-0.5.0.jar:/root/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.7/slf4j-log4j12-1.7.7.jar:/root/.m2/repository/log4j/log4j/1.2.17/log4j-1.2.17.jar:/opt/idea/idea-IC-145.597.3/lib/idea_rt.jar com.intellij.rt.execution.application.AppMain LogParserTest
java.lang.ClassCastException: java.util.Optional cannot be cast to com.github.javaparser.ast.NodeList
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:157)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.lambda$calculatedSyntaxModelForNode$0(LexicalDifferenceCalculator.java:134)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:134)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:123)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatePropertyChange(LexicalDifferenceCalculator.java:114)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$1.concretePropertyChange(LexicalPreservingPrinter.java:157)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.propertyChange(PropagatingAstObserver.java:62)
	at com.github.javaparser.ast.Node.lambda$notifyPropertyChange$3(Node.java:409)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.Node.notifyPropertyChange(Node.java:409)
	at com.github.javaparser.ast.expr.MethodCallExpr.setArguments(MethodCallExpr.java:110)
	at LogParserTest$TypeCalculatorVisitor.visit(LogParserTest.java:70)
	at LogParserTest$TypeCalculatorVisitor.visit(LogParserTest.java:45)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:91)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:257)
	at com.github.javaparser.ast.stmt.ExpressionStmt.accept(ExpressionStmt.java:67)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$17(VoidVisitorAdapter.java:105)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:105)
	at com.github.javaparser.ast.stmt.BlockStmt.accept(BlockStmt.java:68)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:184)
	at com.github.javaparser.ast.body.ConstructorDeclaration.accept(ConstructorDeclaration.java:81)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$29(VoidVisitorAdapter.java:150)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:150)
	at com.github.javaparser.ast.body.ClassOrInterfaceDeclaration.accept(ClassOrInterfaceDeclaration.java:90)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.lambda$visit$40(VoidVisitorAdapter.java:170)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.forEach(NodeList.java:211)
	at com.github.javaparser.ast.visitor.VoidVisitorAdapter.visit(VoidVisitorAdapter.java:170)
	at com.github.javaparser.ast.CompilationUnit.accept(CompilationUnit.java:100)
	at LogParserTest.lambda$visitMethodCalls$1(LogParserTest.java:122)
	at DirExplorer.explore(DirExplorer.java:35)
	at DirExplorer.explore(DirExplorer.java:31)
	at DirExplorer.explore(DirExplorer.java:25)
	at LogParserTest.visitMethodCalls(LogParserTest.java:134)
	at LogParserTest.main(LogParserTest.java:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by ftomassetti** [comment]
It seems there is a problem with calculating the range of cast expressions, at least when intersection types are used

**Comment by ftomassetti** [comment]
The problem seems that we call generateLambda to hack the token range of lambdas but later we did not correct the parent range

**Comment by ftomassetti** [comment]
Also, the range of the intersection type is too wide
