### ISSUE TITLE
LexicalPreservingPrinter: Bug or request for adding Annotations to MethodDeclaration

### ISSUE THREAD

**Issue by ThLeu** [javaparser/javaparser#855]
Unfortunately I am having a hard time to get anything to work with annotations.

Using this simple File as input
```
public class TestPage extends Page {

   protected void test() {}

   @Override
   protected void initializePage() {}
}
```

and this code for the printing and changing of the CompilationUnit
```
		try (BufferedReader reader = Files.newBufferedReader(filePath)) {

			Pair<ParseResult<CompilationUnit>, LexicalPreservingPrinter> result = LexicalPreservingPrinter
					.setup(ParseStart.COMPILATION_UNIT, Providers.provider(reader));

			CompilationUnit cu = result.a.getResult().get();

			changeCU(cu);
		} catch (IOException e) {
			e.printStackTrace();
		}

	private void changeCU(CompilationUnit cu) {
		cu.getTypes().stream()
			.forEach(type -> {
				type.getMembers().stream()
					.forEach(member -> {
						if (member instanceof MethodDeclaration) {
							MethodDeclaration methodDeclaration = (MethodDeclaration) member;
							methodDeclaration.addAnnotation("Override");
						}
					});
			});
	}
```

Running this example I always get an UnsupportedOperationException.
Here is the important part of the stack trace
```
Caused by: java.lang.UnsupportedOperationException: Override
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:212)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.lambda$calculatedSyntaxModelForNode$0(LexicalDifferenceCalculator.java:134)
	at java.util.Arrays$ArrayList.forEach(Arrays.java:3880)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:134)
	at com.github.javaparser.printer.lexicalpreservation.LexicalDifferenceCalculator.calculatedSyntaxModelForNode(LexicalDifferenceCalculator.java:123)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.interpret(LexicalPreservingPrinter.java:308)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.prettyPrintingTextNode(LexicalPreservingPrinter.java:304)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.getOrCreateNodeText(LexicalPreservingPrinter.java:325)
	at com.github.javaparser.printer.lexicalpreservation.ChildTextElement.getNodeTextForWrappedNode(ChildTextElement.java:57)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.reverseIterator(TextElementIteratorsFactory.java:170)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.partialReverseIterator(TextElementIteratorsFactory.java:184)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.reverseIterator(TextElementIteratorsFactory.java:178)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.reverseIterator(TextElementIteratorsFactory.java:171)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.partialReverseIterator(TextElementIteratorsFactory.java:184)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.reverseIterator(TextElementIteratorsFactory.java:178)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.reverseIterator(TextElementIteratorsFactory.java:171)
	at com.github.javaparser.printer.lexicalpreservation.TextElementIteratorsFactory.partialReverseIterator(TextElementIteratorsFactory.java:184)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.tokensPreceeding(LexicalPreservingPrinter.java:248)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findIndentation(LexicalPreservingPrinter.java:333)
	at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:379)
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$1.concreteListChange(LexicalPreservingPrinter.java:167)
	at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
	at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:409)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:409)
	at com.github.javaparser.ast.NodeList.add(NodeList.java:67)
	at com.github.javaparser.ast.nodeTypes.NodeWithAnnotations.addAnnotation(NodeWithAnnotations.java:71)
```

Is there a reason why this is not supported? Or is it maybe a bug?

Kind regards

**Comment by matozoid** [comment]
@ftomassetti - can you give a hint here?

**Comment by ftomassetti** [comment]
Thank you for this bug report, I just submitted a PR. Not also that you should probably check if the Override annotation is already present to avoid adding it twice
