### ISSUE TITLE
Error on InitializeConstructorParametersStatementsGenerator while mvn install

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#906]
In InitializeConstructorParametersStatementsGenerator#findFieldInClass

I get :
```
[INFO] --- exec-maven-plugin:1.6.0:java (generate-javaparser-metamodel) @ javaparser-metamodel-generator ---
New source root at "K:\workspace\Javaparser\javaparser-core\src\main\java"
Parsing K:\workspace\Javaparser\javaparser-core\src\main\java\com\github\javaparser\metamodel\JavaParserMetaModel.java
Adding new file com.github.javaparser.metamodel.NodeMetaModel.java
Adding new file com.github.javaparser.metamodel.BodyDeclarationMetaModel.java
[WARNING] 
java.lang.NullPointerException
	at com.github.javaparser.generator.metamodel.InitializeConstructorParametersStatementsGenerator.findFieldInClass(InitializeConstructorParametersStatementsGenerator.java:44)
	at com.github.javaparser.generator.metamodel.InitializeConstructorParametersStatementsGenerator.generate(InitializeConstructorParametersStatementsGenerator.java:24)
```

Since nodeClass can only be null at this position.

**Comment by matozoid** [comment]
Hi, nice to see you active again :)

I don't understand how you're getting this one - it's part of the build and that works fine here. Windows issue again?

**Comment by DeepSnowNeeL** [comment]
Yep windows

**Comment by matozoid** [comment]
Did everything work after recompiling core?
