### ISSUE TITLE
Parse error. Found "/" 

### ISSUE THREAD

**Issue by lodart** [javaparser/javaparser#958]
I've got an error when parsing this file : [https://github.com/SilenceIM/Silence/blob/master/src/org/smssecure/smssecure/attachments/AttachmentServer.java](url)
The error says :

	Exception in thread "main" com.github.javaparser.ParseProblemException: (line 0,col 0) Parse error. Found "/", expected one of  ";" "@" "\u001a" "abstract" "class" "default" "enum" "final" "import" "interface" "module" "native" "open" "private" "protected" "public" "static" "strictfp" "synchronized" "transient" "transitive" "volatile" <EOF>
	Problem stacktrace : 
	com.github.javaparser.GeneratedJavaParser.generateParseException(GeneratedJavaParser.java:10018)
	com.github.javaparser.GeneratedJavaParser.jj_consume_token(GeneratedJavaParser.java:9874)
	com.github.javaparser.GeneratedJavaParser.CompilationUnit(GeneratedJavaParser.java:379)
	com.github.javaparser.JavaParser.parse(JavaParser.java:123)
	com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:386)
	com.github.javaparser.JavaParser.parse(JavaParser.java:358)
	mainPackage.TestMardi13.main(TestMardi13.java:43)
	at com.github.javaparser.JavaParser.simplifiedParse(JavaParser.java:390)
	at com.github.javaparser.JavaParser.parse(JavaParser.java:358)
	at mainPackage.TestMardi13.main(TestMardi13.java:43)

While the file seems okay ...

**Comment by lodart** [comment]
Ok, my bad, I did 
`CompilationUnit cu = JavaParser.parse(new File("AttachmentServer.java"));`
and not 
`CompilationUnit cu = JavaParser.parse(new FileInputStream("AttachmentServer.java"));`

**Comment by ftomassetti** [comment]
It happens even to the best ones. Feel free to report all the errors you are running to: we are here to help
